### ISSUE TITLE
Issue on mac safari 8/ safari 9

### ISSUE THREAD

**Issue by FEDuser** [verlok/lazyload#102]
(1) I am using latest version of lazyload js.
(2) on safari 8/ 9, It is showing following error-
SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode
line -   const isBot = !("onscroll" in window) || /glebot/.test(navigator.userAgent);

**Comment by verlok** [comment]
Hi, 
Sorry about that. Those versions of Safari are not supported by my script.
You could try replacing `const` with `var` to solve this specific issue.

**Comment by verlok** [comment]
Wait there @FEDuser,
are you using the non transpiled version of LazyLoad?
You should be using the file `lazyload.transpiled.min.js`!
I'm gonna update the readme file about this, since I didn't make that clear.
Thanks for letting me know.

**Comment by verlok** [comment]
Hi @FEDuser,
I recently released version 8. If you use this version, just include `lazyload.min.js` as you're probably already doing.
Thanks

**Comment by verlok** [comment]
Psst: have you already starred this repo? All you need to do is to press the Star ★ button on the top right corner of the website. ;)

**Comment by FEDuser** [comment]
Thank you. But I need to support very old browser. I am not using this library for now.

**Comment by verlok** [comment]
Then you can use an older version of the script. Like 3.x, [find it here](https://github.com/verlok/lazyload/releases/tag/v3.0.0)
Same functionality, more or less, legacy browsers supported.
