### ISSUE TITLE
Please publish v7.2.2 on NPM - data_srcset problem

### ISSUE THREAD

**Issue by aggreggator** [verlok/lazyload#104]
Hi Verlok,

first thanks for this great plugin. :)

Could you publish https://github.com/verlok/lazyload/releases/tag/7.2.2 on NPM?
Only v7.2.1  is published on NPM: https://www.npmjs.com/package/vanilla-lazyload

i've installed your plugin with:
```
npm install --save vanilla-lazyload
```
I thought the newest version 7.2.2 was installed...
Had the problem that only the data-original was transformed to src attribute.
data-orignal-set was not transformed.
After a longer debugging session, i've found the discrepancy and added:
`data_srcset: 'originalSet'` to the options object as fix.

As this bug is already fixed in 7.2.2, it would be great if it becomes usable in node universe.

Thanks in advance

agg

**Comment by verlok** [comment]
Done!
Thanks for letting me know

**Comment by verlok** [comment]
@aggreggator please note that I've just released version 8.0.0. Version 8.0.0 is the same as 7.2.2 but with renamed dist files. The main transpiled file to include is now `dist/lazyload.min.js` as you would expect, and no longer `dist/lazyload.transpiled.min.js`.

**Comment by verlok** [comment]
Psst: have you already starred this repo? All you need to do is to press the Star ★ button on the top right corner of the website. ;)

**Comment by aggreggator** [comment]
★ed!

**Comment by aggreggator** [comment]
★ed!

**Comment by verlok** [comment]
Thanks! It's 1001 stars now! :)
