### ISSUE TITLE
packery with lazyload

### ISSUE THREAD

**Issue by regenrek** [verlok/lazyload#106]
Do anyone has a working example with [packery](http://packery.metafizzy.co) ? 

Thank you in advance

**Comment by verlok** [comment]
I don't, but if you tell me what you'd like to achieve, maybe I can help.

**Comment by regenrek** [comment]
hi

i try to achieve something like rearrange after images are loaded. i implemented it here with lazy load but its kinda buggy http://www.wexltrails.at/trails/

**Comment by verlok** [comment]
Thanks. Uhm, the link didn't help, I only see a 3x2 grid with 6 images in it.
Anyway, the first thing that comes in my mind, if you move around the grid elements like in the _packery_ demo, you'll need to call LazyLoad's `update` method after, or during, the rearrangement. See the [API](https://github.com/verlok/lazyload#api) section in the README.

**Comment by verlok** [comment]
Psst: have you already starred this repo? All you need to do is to press the star button on the top right corner of the website. ;)

**Comment by verlok** [comment]
★

**Comment by verlok** [comment]
I'm closing this issue now, if you still have questions do not hesitate to open it again. I hope you solved it! Let me know in the case.
