### ISSUE TITLE
Manually set the scroll value

### ISSUE THREAD

**Issue by quentinneyraud** [verlok/lazyload#107]
Hi,

I quickly read your code and it seems that it's not possible to manually set the scroll value. I'm using a smooth scrolling library which listen `mouse wheel` event to set CSS transform on `body` element. So `scroll` event is never fired and images not loaded.

Is someone have a workaround ?

**Comment by verlok** [comment]
No, my code works only on the native scroll events, even if you could set the scroll value manually, the methods always read the position properties from the elements themselves, so it wouldn't work. 

I think you should develop your own lazy load, maybe you can reuse some of the code in my project to do that.
