### ISSUE TITLE
webkitURL is deprecated

### ISSUE THREAD

**Issue by omarzion** [verlok/lazyload#108]
Not a bug
`[Deprecation] 'webkitURL' is deprecated. Please use 'URL' instead.`

Also,  I am loving your project, it was so simple to get running

**Comment by verlok** [comment]
Hello, thank you for reporting this.

Anyway I can't find the word webkiturl in the code of my project, neither in the transpired files nor in the es2015 ones. What did you get this notification?

By the way if you like my project, please star it if you didn't already;)
