### ISSUE TITLE
container:document.body doesn't work

### ISSUE THREAD

**Issue by hdon** [verlok/lazyload#110]
I was mocking up a thumbnail search tool:

https://gist.github.com/hdon/e58f13b0eda76421b806d404f055f469

When I Control+Shift+R reload in Chromium 58.0.3029.110 every single image on the page is loaded.

I was able to fix it by changing my instantiation of `LazyLoad` to have no arguments, but it was not expected that passing `{container:document.body}` as its first argument would break it.

Maybe this is a documentation bug?

**Comment by verlok** [comment]
Hi there, the "container" option must be a scrolling container, like `window` or any other DOM element with `overflow: scroll`. 

But wait a minute, what do you mean with "break it"? Does it throw some error? Or it just doesn't load the images?

Thank you

**Comment by verlok** [comment]
@hdon do you still have an issue?

**Comment by verlok** [comment]
Closing. If you still have this issue, please re-open.
