### ISSUE TITLE
What if user doesn't have JavaScript enabled?

### ISSUE THREAD

**Issue by darbymanning** [verlok/lazyload#111]
Just wondered if it's possible to retain the `src` attribute on the `<img>` tags, so if a user doesn't have JS enabled it renders the image normally.... or would this prevent LazyLoad operating as the browser would render the images?

Any other ideas for making this work for users without JavaScript enabled?

**Comment by verlok** [comment]
You could use a `noscript` tag containing the `img` as you would use it if you didn't have JavaScript. That's the only way to support JavaScript disabled browsers and not impacting performance for the vast majority that have JavaScript enabled
