### ISSUE TITLE
Image types webp/jpeg

### ISSUE THREAD

**Issue by dalvaradotey** [verlok/lazyload#112]
Hello!
Congrats for the scripts, it's awesome.

I have both image versions (jpeg and webp).  According to each browser support, I need to load one of them:

```
<picture>
  <source data-original-set="path/to/image" type="image/webp">
  <source data-original-set="path/to/image" type="image/jpeg">
  <img data-original="path/to/image">
</picture>
```

But I can only load the jpeg version, how can I load the webp type version?

**Comment by verlok** [comment]
Interesting question, nobody asked about webp before. 

First of all, sorry but I have to ask, are you testing this in Chrome, right? :)

Secondly, did you know that there are services that makes you free from generating more images versions per dimensions and formats? One of these is Cloudinary.com - take a look! 

Finally, I have to test this on my own Chrome to unterstand what is happening. And this must wait until Monday, sorry!

**Comment by dalvaradotey** [comment]
@verlok, yep ... testing in Chrome with original code and work fine.
```
<picture>
  <source srcset="path/to/image.webp" type="image/webp">
  <source srcset="path/to/image.jpg" type="image/jpeg">
  <img src="path/to/image.jpg">
</picture>
```
I know about cloudinary... and tried google pagespeed module with nginx, but i think i can make some optimizations by my own.

Thanks for checking

**Comment by verlok** [comment]
I'm checking now. I'll let you know soon.

**Comment by verlok** [comment]
Hi @dalvaradotey,
I created [this pen](https://codepen.io/verlok/pen/mMyLdJ) in order to reproduce the bug, but I couldn't reproduce it.
Chrome is downloading the webp both on the _eagerly loaded image_ and on the _lazily loaded image_, whereas Firefox is downloading the jpg in both images.
If you could please fork my codepen and put there your html and js (and css?) code maybe I can help you understand what's going on.
Thanks

**Comment by dalvaradotey** [comment]
@verlok,
Ok, I'm testing the pen file making some modifications, the problem was on 7.2.0 version. I'm upgrading to 8.0.1 and now work fine :) Sorry, I used cdn script in the README example .

Thanks again for this great script.
