### ISSUE TITLE
Images are not loaded in chrome before scroll stops

### ISSUE THREAD

**Issue by brokleen** [verlok/lazyload#113]
In chrome if you don't stop scrolling, the lazy elements are not loaded.
Has anyone found a solution to fix that ?

**Comment by verlok** [comment]
Have you tried playing with the `throttle` option?
Its default is `150` and it means "if another scroll event is fired within 150 milliseconds, wait another 150 milliseconds".
Try diminish the value to 50 and see what happens.
Let me know if you solved or not.

**Comment by brokleen** [comment]
Same with throttle set at 50.
I have this issue on chrome for mac os, on windows everything works well

**Comment by verlok** [comment]
Sorry, I just figured out a bug on the throttling function, and released version 8.0.2 which fixes it.
Can you update to 8.0.2 and check again?

**Comment by verlok** [comment]
Otherwise, can you put your HTML, CSS and JS code on a [Pen](https://codepen.io/) and send me the link, so I can check?

**Comment by brokleen** [comment]
I found the issue.
I have a conflict between lazyload and [Pikaday](https://github.com/dbushell/Pikaday)
When Pickadate is active and when I don't stop scrolling the images keep the pending states in the network inspector.
