### ISSUE TITLE
Dist file doesn't work with module bundlers

### ISSUE THREAD

**Issue by matthew-dean** [verlok/lazyload#123]
I'm getting this error in the dist file when using in Rollup (ES6 module bundler):
`Uncaught TypeError: Cannot set property '_settings' of undefined`

It looks like this library relies on a `this` object which doesn't exist. A global object? Not sure if the issues are with the build from src to dist. This can also be solved by adding a "module" key to package.json that points to the module source.

**Comment by matthew-dean** [comment]
Oh never mind, this is because I missed the "new" keyword. You could do a factory pattern that allows the lib to work with or without `new`.

**Comment by verlok** [comment]
Yes I could do that, but I like to enforce  the `new` keyword because it makes explicit that the result is an object, an actual instance you can use.
