### ISSUE TITLE
Too many container and images

### ISSUE THREAD

**Issue by WeAreUnique** [verlok/lazyload#124]
Hello,
I have multiple container (generator from wordpress).
My code:
```
 new LazyLoad({
    elements_selector: "div, img",
    data_src: "src",
    skip_invisible: true,
    data_srcset: "srcset",
});
```
Demo page: https://bbland.net
Please help.
Thank you so much.

**Comment by verlok** [comment]
Hi @WeAreUnique,
you didn't explain your problem properly. 

In the link you provided me, you have only one scrolling container, the page / document.
All images are displaying correctly.

So what issue are you having?

**Comment by verlok** [comment]
Please note that selecting all images and divs on the page leads to very bad performance...  can't you select only the images with some class?

**Comment by WeAreUnique** [comment]
@verlok I added "lazy" class in every div, img. But still not work.

**Comment by verlok** [comment]
What exactly is not working? 
Can you post the HTML code top please? 
The ideal would be to create a new pen on codepen.io so I can see what's wrong with your code
