### ISSUE TITLE
Safari 10.1.2 - Issues with LazyLoading over 128 images 

### ISSUE THREAD

**Issue by anastasialanz** [verlok/lazyload#128]
Are you reporting a bug or requesting a feature?
Bug report

If it's a bug, it would be very useful to me if you answered the following questions.
Your answers will help me understand what's happening and enable me to reproduce the bug.

* What is happening?
When I look at a page that is lazyloading over 100 images, sometimes the images do not show up and also do not fade it. After many reloads of the page, I see different sets of images not appear because the `loaded` class is not being applied.
* What is the expected behaviour?
I expected to see all of the images appear and fade in when scrolling. This works fine on the latest version of Chrome. 
* Which version of LazyLoad are you using?
The latest, 10.0.1
* In which browser(s) and browser version(s) are you experiencing the problem?
Safari 10.1.2
* Could you provide the HTML, CSS and JS code you use for your images?
I am using this snippet of JS
```
(function () {
  var ll = new LazyLoad({
    threshold: -100
  });
}());
```

Here is the snippet of HTML:
```
<div class="work-item">
  <a href="http://localhost:8000/booksmagazines/span/" class="img-link">
     <img src="http://localhost:8000/wp-content/uploads/2017/01/65.jpg" data-src="http://localhost:8000/wp-content/uploads/2017/01/65.jpg" width="750" height="549" class="loaded" data-was-processed="true">
      <h3>Span</h3>
   </a>
</div>
```
* What are the steps to reproduce the problem?
1. Go to the Safari browser
2. Refresh the page a few times to see different results.

Thank you.

**Comment by verlok** [comment]
Thank you for reporting this.
The problem is that version 10 uses Intersection Observer, which is not yet supported in Safari.
As a fallback, LazyLoad version 10 loads all the images at once, which is not nice when you have a lot of images to deal with.
You can solve this easily using the latest version less than 9 of my script, which is version 8.1.0.
Let me know if this can be closed.
Thanks!

**Comment by verlok** [comment]
I'm considering this closed. If it isn't, feel free to open it again.
