### ISSUE TITLE
Clarify license?

### ISSUE THREAD

**Issue by frankrausch** [verlok/lazyload#13]
Awesome tool!

The license info is slightly hidden in the package.json.
Would you mind adding a LICENSE.md text file with a filled-in ISC license template so you can be properly credited?

Thanks for your great work.

**Comment by verlok** [comment]
I definitely should to that. 
Where can I get information of that license to choose and why, and where can I copy a template of the file you're suggesting to add?

**Comment by frankrausch** [comment]
I’m no expert, but you specified the ISC license in package.json. If you did not specify it by accident, here’s a template:
https://en.wikipedia.org/wiki/ISC_license

Many people on GitHub seem to use the MIT license:
https://en.wikipedia.org/wiki/MIT_License

jQuery uses MIT, for example:
https://github.com/jquery/jquery/blob/master/LICENSE.txt

**Comment by frankrausch** [comment]
👍
