### ISSUE TITLE
Development of v8

### ISSUE THREAD

**Issue by SassNinja** [verlok/lazyload#131]
@verlok as you might remember I'm needing an option to pass an element to `elements_selector` instead of a string.
I've just made a PR for this https://github.com/verlok/lazyload/pull/130

But unfortunately I can't use the latest version of lazyload because I can't stop supporting the IE completely plus iOS!
https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver#Browser_compatibility

Thus I must stay with version 8 and need the option adjustment for this one, too.

Any chance that version can still be extended or is it completely closed?

**Comment by verlok** [comment]
Absolutely yes, I'm maintaining both versions: 10 and 8 for the reason you mentioned. I'll evaluate and eventually merge this PR as soon as possible.

**Comment by verlok** [comment]
Closing this, as I'm maintaining v 8.x as well
