### ISSUE TITLE
Not work in Mobile Chrome 54.0

### ISSUE THREAD

**Issue by VSpoint** [verlok/lazyload#133]
The plugin not work on my mobile Chrome 54.0,
but if I comment this code 
http://clip2net.com/s/3NJZi2r
it works amesome.

**Comment by verlok** [comment]
If you need to support older versions of Chrome, I recommend to use version 8.2.0 of LazyLoad which doesn't use the Intersection Observer API, which is quite new.
You can read more about it in the [readme](README.md) file.

PS: Removing that line of code would make the images load all at once, so it's like not having any lazy load at all.

**Comment by jrtderonde** [comment]
> The plugin not work on my mobile Chrome 54.0,
> but if I comment this code
> http://clip2net.com/s/3NJZi2r
> it works amesome.

URL is missing
