### ISSUE TITLE
callback_load on background image

### ISSUE THREAD

**Issue by dooker** [verlok/lazyload#136]
callback_load seems not to work on background images. I can see, when it's set with callback_set, but I have never seen the 'loaded' class to appear for the element

**Comment by verlok** [comment]
That’s because it’s not possible to implement, since background images don’t fire a loaded event.

**Comment by verlok** [comment]
Hey @dooker,
that wasn't THAT impossible to implement, and things changed on version 15. 

I found a way to manage background images's load/error event, so now background images are now getting the `loaded` or `error` class and calling `callback_loaded` and `callback_error`.

Take a look at the [changelog](https://github.com/verlok/lazyload/blob/master/CHANGELOG.md) and to the [upgrading guide](https://github.com/verlok/lazyload/blob/master/UPGRADE.md) if you're interested.

Have a nice day.

**Comment by dooker** [comment]
Awesome, thanks, will give it a try
