### ISSUE TITLE
Usage with Ionic 1 / AngularJS. Support of ng-src ?

### ISSUE THREAD

**Issue by alkahtani** [verlok/lazyload#137]
I would like to know if ng-src is supported , I have difficulties to use data-src as it seems this attr is not working in ionic , is their any possible resolution , I am stuck with my app huge number of images

**Comment by verlok** [comment]
Hello. The lazy source must be in a data- attribute, but you’re not forced to use data-src, you can use anything else, for example data-whatever and pass it to the options of LazyLoad with `data_src`. See the docs on the readme file.

**Comment by alkahtani** [comment]
Thank you verlok for your reply , here is what i have done so far but before i would like to give you quick brief about what i want to do , i am developing an app using ionic 1 , this app is to downloading 100 of stored images in firebase storage , i came into performance issue , now , i have stored lazyload.js from your repo , add it to my index page , initialize lzyloadoptions in my controller , i haven't add it  to any event  , i got the below error  "ncaught TypeError: Cannot read property 'classList' of null" specifically at line 106 ,6 and 7 
(typeof exports === 'undefined' ? 'undefined' : _typeof(exports)) === 'object' && typeof module !== 'undefined' ? module.exports = factory() : typeof define === 'function' && define.amd ? define(factory) : global.LazyLoad = factory();
})(this, function () {

var supportsClassList = !!document.body.classList; 

i would appreciate if you can direct me or helping me to solve this issue , i have been stuck for a couple of days looking to solve this performance issue using lazy load technique

**Comment by alkahtani** [comment]
update ...
i have moved lazyload.js file from the index page to the page having issue with and it seems the ncaught error disappeared  now , i want to pass the lazy load options i have don the following : 
1.added my tag as below 
<img  data-hire="{{assetCollection[$index].URL}}"  class="photo_library"  /> 
2. window.lazyLoadOptions = {
              threshold: 50,
              data_src: data-hire
          };
, i dont know of this is the right way , please help how to do it , appreciate your patience

**Comment by alkahtani** [comment]
UPDATE #2
here is my console and snapshot of my app grid ,the images shown like white boxes ,  please note i haven't added any css 

![image](https://user-images.githubusercontent.com/13502824/30777890-428bbe8e-a0ce-11e7-9048-b8bde06ecd0c.png)

![image](https://user-images.githubusercontent.com/13502824/30777891-497970e2-a0ce-11e7-8ca8-bf8f52a81a46.png)

**Comment by verlok** [comment]
Hey there, I appreciate that you solved some of the issues by yourself. 
The issue you’re having now is due to a wrong option you’re passing. To read data from the `data-hire` attribute you need to pass only `hire` to the `data_src` option.

**Comment by verlok** [comment]
In other words, you need to do:

```js
window.lazyLoadOptions = {
    data_src: "hire"
};
```

**Comment by alkahtani** [comment]
I have changed the as per recommended above but i got the same result , here is my code to give more insight 
`<div class="row" ng-repeat="brick in assetCollection | limitTo:numberOfImagesToDisplay 
               track by $index " ng-if="$index % 3 === 0">
                <div class="col col-33" ng-if="$index < assetCollection.length"  ng-click=PassSelectedimg({{$index}}) >
                    <img  data-hire="{{assetCollection[$index].URL}}"  class="photo_library"  />
                </div>
                <div class="col col-33 " ng-if="$index + 1 < assetCollection.length" ng-click="PassSelectedimg({{$index+1}})">
                    <img  data-hire="{{assetCollection[$index + 1].URL}}"  class="photo_library"   />
                </div>
                <div class="col col-33  " ng-if="$index + 2 < assetCollection.length" ng-click="PassSelectedimg({{$index+2}})">
                    <img  data-hire="{{assetCollection[$index + 2].URL}} " class="photo_library"   />
                </div>
          </div>
          <ion-infinite-scroll on-infinite="addMoreItem()" ng-if="assetCollection.length > numberOfImagesToDisplay"></ion-infinite-scroll>
          
          <script>
            window.lazyLoadOptions = {
              threshold: 50,
              data_src:"hire"
            };
            window.addEventListener('LazyLoad::Initialized', function (e) {
              console.log(e.detail.instance);
              console.log("Hello Lazy")
            }, false);
          </script>
          <script type="text/javascript " src="js/lazyload.js"> </script>

, i know i am not following ionic best practices by adding the js file to my index page but i thought adding it here will solve the issue, what do you think?
`

**Comment by verlok** [comment]
Thanks for sharing. 
I’m not an expert in Ionic nor Angular so you will need to do some debugging to see what’s going wrong there. 

Here’s some advices:
- include the unminified version of LazyLoad 
- open Chrome web inspector, go to the scripts panel, locate the LazyLoad file and set a debug breakpoint in the `update` method

There, you can see how many images got selected and stored in the `_elements` property. If they are zero, you can check the options you passed, how many you have in the DOM at that time, etc. 

Let me know how it goes!

**Comment by verlok** [comment]
@alkahtani I updated my latest message with more information

**Comment by alkahtani** [comment]
many thanks @verlok , sorry for being late to reply, i have been out of time last days , i will do a test and update you soon .

**Comment by alkahtani** [comment]
I will update you ... so sorry it is out of my hand

**Comment by verlok** [comment]
@alkahtani can we close this?

**Comment by alkahtani** [comment]
@verlok i couldn't get it work , i tried my best with no luck , if you feel you need to close this issue and re-open it again when both of us have time to do more work it is fine . i would like to appreciate every time you spend to reply and check or followup this issue. i promise to do more test on clean project if it is working i  will email you . this is my email "al-kahtani@hotmail.com"

**Comment by verlok** [comment]
Yes @alkahtani please try this on a clean project and let me know.
Closing the issue in the meantime.
Thanks
