### ISSUE TITLE
Empty src attributes

### ISSUE THREAD

**Issue by SimonSteinberger** [verlok/lazyload#14]
Great plugin, we've featured it on https://plainjs.com/javascript/plugins/lazyload-95/ :+1: 

Yet, you may want to recommend using blank pixel images instead of empty img `src` attributes. The empty attributes can have an extremely negative impact on the server. Some sources to back this up:

https://www.nczonline.net/blog/2009/11/30/empty-image-src-can-destroy-your-site/
http://stackoverflow.com/questions/19126185/setting-an-image-src-to-empty
http://stackoverflow.com/questions/5775469/whats-the-valid-way-to-include-an-image-with-no-src/28077004

Although blank pixels appear somewhat 'outdated', they are in fact not. There doesn't seem to exist any other solution for safely overcoming the downsides of an empty src attribute.

Cheers

**Comment by verlok** [comment]
Great! Thanks for featuring my work. 
The reason why I'm not recommending using a pixel gif is that when you use LazyLoad with the progressive JPEG image format - to allow users see the images while loading using the `show_while_loading` option - if a pixel image is in the `src` attribute, when LazyLoad replaces its value with the proper one, the browser will just wait the full load event of the image without showing the progressive rendering. 
What do you think?

**Comment by SimonSteinberger** [comment]
I see. I guess it would be best to just mention the potential pitfall and leave the decision up to the developer. As main developer of Pixabay.com, a site for free images an videos, I wouldn't implement an empty src attribute, because I'd worry too much about the unnecessary server requests. I'd prefer this over progressive JPEG loading.

**Comment by verlok** [comment]
Cool,
I'll do this. 
Thank you for the hint. 
Are you going to implement it on pixabay?

--
Andrea Verlicchi
www.andreaverlicchi.eu

**Comment by SimonSteinberger** [comment]
Possibly in the future, yes. Although we'd probably strip down the code to the minimum what we actually would use to keep file size small and the plugin as efficient as possible. Or maybe we'd base parts of our code on your plugin :)

**Comment by verlok** [comment]
Great! :)

--
Andrea Verlicchi
www.andreaverlicchi.eu

**Comment by SimonSteinberger** [comment]
Just to let you know: In the meantime, we do make use of your code base in Pixabay  :+1: Although, we included the blank pixel solution and added srcset support. Just minor changes - but they were necessary for our needs. Thanks a lot for your great and simple solution!
