### ISSUE TITLE
Cached Images

### ISSUE THREAD

**Issue by nunoguerra** [verlok/lazyload#140]
Should not it display as images if they have already been cached?

**Comment by verlok** [comment]
Hi there. I didn’t understand your question. Can you be clearer? Thanks

**Comment by verlok** [comment]
PS: eu falo português, se quiser pode escrever no seu idioma :)

**Comment by nunoguerra** [comment]
:)

Refiro-me às imagens que ficam na cache do browser ou seja depois de carregarmos uma página essas imagens ficam em cache internamente no browser, se fizermos um soft refresh ou se voltarmos a visitar a mesma página o browser vai usar a cache para oferecer um carregamento mais rápido e neste caso o layzload plugin deveria apresentar logo as imagens sem ter de as carregar novamente.

**Comment by verlok** [comment]
Muito obrigado pela explicação. 
Tudo funciona como você descreveu. Quando o LazyLoad vai carregar as imagens porque entraram no viewport, o browser vai carregar as imagens dá cache invez que dá internet

**Comment by nunoguerra** [comment]
Eu entendo que o LazyLoad faz isso. A minha questão é se será possível o LazyLaod apresentar directamente as imagens da cache no browser independentemente delas estarem no viewport ou não. Eu estou usando um placeholder para as imagens que ainda não estão carregadas e quando visito uma página que já visitei anteriormente essa página já tem as imagens na cache e em vez de aparecer o placeholder deveriam aparecer as imagens e não só quando elas entram no viewport.

Não sei se me estou a fazer entender, isto é apenas um pequeno detalhe de melhoria, contudo agradeço o ótimo plugin que desenvolveste.

**Comment by verlok** [comment]
Agora entendi melhor o que você queria fazer. 
Infelizmente não é possivel fazer isso porque a cache do browser não é exposta por nenhuma API.
