### ISSUE TITLE
Having console errors getting this implemented in a bootstrap website

### ISSUE THREAD

**Issue by donsue** [verlok/lazyload#141]
Are you reporting a bug or requesting a feature?

If it's a bug, it would be very useful to me if you answered the following questions.
Your answers will help me understand what's happening and enable me to reproduce the bug.

* What is happening?
* What is the expected behaviour?
* Which version of LazyLoad are you using?
* In which browser(s) and browser version(s) are you experiencing the problem?
* Could you provide the HTML, CSS and JS code you use for your images?
* What are the steps to reproduce the problem?

script load call in html head
<script src="https://cdnjs.cloudflare.com/ajax/libs/vanilla-lazyload/8.2.0/lazyload.min.js"></script>

Responsive section containing images.  Trying to add lazyload to second element (and then would add it to all elements following (could be hundreds)):

<div class="portfolio_block columns3" data-animated="fadeIn" id="results1" class="results">
								<div class="element col-sm-4 category1 project padbot30">
									<div class="hover_img">
										<img src="../images/prom/2018blush/top_pink_5661.jpg" alt="Pink 5661" />
										<a class="zoom" href="../images/prom/2018blush/top_pink_5661.jpg" rel="prettyPhoto[portfolio1]"></a>
									</div>
									<div class="project_descr center">
										<h4>Pink 5661</h4>
										
									</div>
								</div>
								
								<div class="element col-sm-4 category2 project padbot30">
									<div class="hover_img">
										
										<img data-src="../images/prom/2018blush/top_blush_11558.jpg" width="420" height="580" alt="Blush 11558">
										<a class="zoom" href="../images/prom/2018blush/top_blush_11558.jpg" rel="prettyPhoto[portfolio1]"></a>
									</div>
									<div class="project_descr center">
										<h4>Blush 11558</a></h4>
									</div>
								</div>

This is the image that is not showing up due to the call data-src (works with just src):

![top_blush_11558](https://user-images.githubusercontent.com/32394125/31021630-66291e56-a504-11e7-93fe-2ca8fdc769b1.jpg)

This is the javascript at the bottom of the page:

        <script>
		new LazyLoad();
	</script>

I also tried it with:

<script>
var myLazyLoad = new LazyLoad({
    container: document.getElementById('results1')
});
</script>

and I tried it with:

<script>
	(function () {
		function logElementEvent(eventName, element) {
			console.log(new Date().getTime(), eventName, element.getAttribute('data-src'));
		}
		function logEvent(eventName, elementsLeft) {
			console.log(new Date().getTime(), eventName, elementsLeft + " images left");
		}
		/* Uncomment the callbacks in LazyLoad options to see the callbacks logs in your browser's console */
		new LazyLoad({
			container: document.getElementById('results1')
			
			/*callback_load: function (element) {
				logElementEvent("LOADED", element);
			},
			callback_set: function (element) {
				logElementEvent("SET", element);
			},
			callback_processed: function(elementsLeft) {
				logEvent("PROCESSED", elementsLeft);
			} */
		});
	}());
</script>

But with all I get the following console errors (either local or online):

Uncaught TypeError: Cannot read property 'classList' of null
    at lazyload.min.js:1
    at lazyload.min.js:1
    at lazyload.min.js:1
(anonymous) @ lazyload.min.js:1
(anonymous) @ lazyload.min.js:1
(anonymous) @ lazyload.min.js:1
index.html:556 Uncaught ReferenceError: LazyLoad is not defined
    at index.html:556

**Comment by jr-cologne** [comment]
Since you are using version 8.2, you have to use `data-original` instead of `data-src` for the source of the image that should be loaded.

Furthermore, you need to use this JS code:

```js
var myLazyLoad = new LazyLoad();
```

In case you want to use `data-src`, you can use this:

```js
var myLazyLoad = new LazyLoad({
    data_src: "src"
});
```

If you need more information, you can [read through the documentation of version 8 here](https://github.com/verlok/lazyload/blob/master/README_v8.md).

**Comment by verlok** [comment]
Thank you @jr-cologne, well done explanation! :)

**Comment by donsue** [comment]
Hi JR,

**Comment by verlok** [comment]
Hi @donsue,
thank you for getting back to us. 

> They suggested that you might want to add a few lines of code to your script that tells the script to not start until everything else is loaded.  They said that would prevent other goofus's like me from having issues.

I didn’t do that because I want to give the script users the freedom to decide when and how to execute the script. 
The only thing that I changed upon a user’s request was to add the ability to execute the script asynchronously. 

I took a look to your page and I noticed that the images can be shown overlapped sometimes. I think this must be because the images don’t have a size until loaded, and some js could use the size to position the images. I suggest to set a size in CSS even before the images load (at least set a min-height, which also avoids all images to load at once), or to execute any eventual graphically arranging JavaScript after the images were loaded. You can use the `callback_loaded` option

**Comment by donsue** [comment]
I was hoping to add your responsive option but hadn’t got to it yet.  Is that the callback loaded option?

Susan Donohue
202-256-6121

**Comment by verlok** [comment]
Hi there, not exactly. You can use the `callback_loaded` option  to execute some JavaScript code (a callback function) whenever an image finishes loading, in case you’re using some JavaScript to rearrange the images in the layout. 

To use LazyLoad with responsive images  you just need to use the `src` and the `srcset` options as described in the README file, along with the `sizes` attribute or the `picture` tag depending on the result you’re looking for.  And of course you should already know how responsive images work in advance.
