### ISSUE TITLE
Chrome 54.0

### ISSUE THREAD

**Issue by davthu** [verlok/lazyload#142]
This library does not run in Chrome 54.0 (Both windows and Mac). Same code runs flawless in latest version of Chrome and IE. Using latest version of vanilla-lazyload version 10.3.1.

**Comment by verlok** [comment]
Current version of chrome is 61, so Chrome 54 is quite old. Version 10 of LazyLoad is made only for modern browsers. 
Have you tried version 8 of LazyLoad, which is the recommended version?

**Comment by davthu** [comment]
Seems to work with version 8.2.0 👍

**Comment by verlok** [comment]
Good to know!
Thanks
