### ISSUE TITLE
Not work in Samsung Internet Browser (Not Chrome)

### ISSUE THREAD

**Issue by yekowele** [verlok/lazyload#143]
The plugin not work on Samsung Note 5 - Android 7.0 -  Samsung Internet Browser (5.4)

Is there way any fallback action?

**Comment by verlok** [comment]
Please repoet the error that you are getting or the unexpected behavior and more importantly the version of LazyLoad that you are using. The recommended version is 8.2.x

**Comment by yekowele** [comment]
@verlok I apologize for not specifying the version. It's my fault. Any way solved using version 8.2.x

Thank you for helping.

**Comment by warudin** [comment]
I'm having this problem as well, but in my case after updating to 8.2.x the problem wasn't solved. 

I don't know how to get error messages or debug the Internet-browser on Android. I'm seeing no image, while a fallback in the <img> tag is provided. The site where this happens can be viewed here: [agro-chemie.nl](http://www.agro-chemie.nl)

Here's a screenshot of what happens:
![](https://performis.zendesk.com/attachments/token/ev33PGcDOF899m2yxbGPLdAwk/?name=inline-477919145.png)

**Comment by yekowele** [comment]
@warudin i think the cause of the problem another js error.
You can read the android remote device error messages using the method specified this link : https://developers.google.com/web/tools/chrome-devtools/remote-debugging/

**Comment by verlok** [comment]
@warudin, please let me know if the comment from @yekowele helped

**Comment by warudin** [comment]
Thank you very much for the tip, @yekowele! I've found out the problem was related to a lack of height and width in a parent div.
