### ISSUE TITLE
 lazy load doesn't work in safari 

### ISSUE THREAD

**Issue by maksimize** [verlok/lazyload#144]
* What is happening?
All pictures are not lazy loaded in safari 
* What is the expected behaviour?
picture supposed to be lazy loaded 
* Which version of LazyLoad are you using?
just downloaded the demos from master and testsed with it  
* In which browser(s) and browser version(s) are you experiencing the problem?
Safari desktop and I guess on mobile 
* Could you provide the HTML, CSS and JS code you use for your images?
demos/simple.html
* What are the steps to reproduce the problem?
1. open safari
2. open developer tools -> network tab  
3. refresh the page 
Actual
all images are loaded 
Expected 
Images should be loaded on scroll 

Thank you.

**Comment by maksimize** [comment]
Ignore that , I just read the md file

**Comment by verlok** [comment]
LOL. Yes, switch back to version 8.2 to make it work correctly on Safari. Until Safari won’t update and support IntersectionObserver
