### ISSUE TITLE
Add body class if class ".loading" active

### ISSUE THREAD

**Issue by jquimera** [verlok/lazyload#147]
First, this plugin is wonderful. Congratulations on your great work!

I would like to know if it is possible to add a class in the body, when the class "loading" is active. Or add a class in the div that comes before the image, also based on the captivity of the class "loading"

Example:

`	<div class="post-thumbnail">
		<a href="#" title="My lazy IMG">
			<img data-src="https://hdwallpapersbuzz.com/wp-content/uploads/2017/03/wallpaper-4k-images-1.jpg">
		</a>
	</div>`

`if ($('img').hasClass('loading')) {
    $("body").addClass("image-is-loading");
    $(".post-thumbnail").addClass("post-image-is-loading");
}`

Can someone help me? Thank you.

**Comment by verlok** [comment]
Hi @jquimera,
you could use the `callback_load` callback provided by the LazyLoad script in the options so you could execute code every time an image is fully loaded. 
For example, you could check if there are still images with the loading class in the container, then add or remove classes in the container itself accordingly.

**Comment by jquimera** [comment]
@verlok Was it something like this? I tested it here but it did not work.

```
callback_load: function (element) {
	logElementEvent("LOADED", element);
    $("body").addClass("images-is-loading");
    $(".post-thumbnail").addClass("post-images-is-loading");
},
```

**Comment by verlok** [comment]
Yes, that is the `callback_load`.
Probably the code you’re writing inside the callback function is wrong :)

**Comment by jquimera** [comment]
@verlok thanks
