### ISSUE TITLE
Readme for v8 has examples to new version

### ISSUE THREAD

**Issue by KrzychuJedi** [verlok/lazyload#148]
New and old read me have same links to examples and sources which is misleading and confusing.

**Comment by verlok** [comment]
Yeah, you’re right. I need to organize it better. Maybe I should keep only one readme with all the examples and the demos for both versions. It would be clearer, wouldn’t it?

**Comment by KrzychuJedi** [comment]
I think keeping it separately is good option (if links would be fixed ;) Putting this in one readme may be better but I don't know the API much.  It there possibility that describing differents for each version would make it hard for read?

**Comment by verlok** [comment]
Released 8.5.0 with the same API as version 10. Solved 😄
