### ISSUE TITLE
Images are not loaded in scrollable container

### ISSUE THREAD

**Issue by peritpatrio** [verlok/lazyload#15]
If you have a container on a page that has fixed size and `overflow: scrolling;`, images inside this container are not lazy loaded when you scroll just the container it self. If you first scroll the container and then the whole page => images are loaded.

**Comment by verlok** [comment]
Hi @peritpatrio, I must have lost this issue notification. Sorry about that.
To lazy load images inside a scrollable container, you must pass the scrollable container element in the `container` option of lazyload.
See the demos and the code [here](http://verlok.github.io/lazyload/#user-content-demos).

**Comment by peritpatrio** [comment]
Thanks for the clarification!

**Comment by cnanders** [comment]
First off: great work on this.  I just swapped out from Tuupola version and you are right - noticeable performance boost.

Is there a way to do lazyloading in two dimensions?  For example on this page, http://verlok.github.io/lazyload/demos/multiple_container.html the second "scrollable container" is below the fold, so it would be great to not have to load the images in the viewable part of this container until the y scroll pixel reaches it.  And then only load the images in the x dimension when the user scrolls horizontally to them.

For my application, I'm building a Netflix / iTunes style browse page where I have horizontally scrollable lists of images (that have overflow-x: scroll) but then there are many of these as you scroll down the main page.  I'd like to have the lazyload work in both dimensions.  How much effort would this be?

**Comment by verlok** [comment]
Thank you for the compliments, much appreciated. 

But wait there, to do something like Netflix or iTunes, if you have many horizontally scrollable containers, in each container it should just work like in the demo you linked above, doesn't it? 

Oh I see what you want to do. Doing that the user would download "only" the first 3 images for each horizontal container, but if you have many, you still load many images. 

So you want lazyload to act horizontally in each horizontal scrollable container, and the ability to "activate" lazyload... lazily, so when they enter the viewport. 

I'm pretty sure you can to this using my script without too many modifications, but I have to do some tests (and now I'm on holidays until Monday 25th July). The idea would be to use lazyload on each scrolling container and listening to some event it launches to activate a new Lazyload on the container itself.

**Comment by verlok** [comment]
Could you open a new issue titled "lazily load lazyload" with what you described here?

**Comment by cnanders** [comment]
Thank you, @verlok! I posted the the [new issue](https://github.com/verlok/lazyload/issues/29) as you requested.
