### ISSUE TITLE
Show images on demand?

### ISSUE THREAD

**Issue by lukehatfield** [verlok/lazyload#150]
Is there a way to load all images in a container when a user triggers an event? I have some hidden slideshows that don't always get activated if they appear on screen and the user does not continue to scroll.

**Comment by paambaati** [comment]
@lukehatfield Did you try initializing the library (`new LazyLoad();`) on your event trigger? That should do the trick.

**Comment by lukehatfield** [comment]
@paambaati There are other lazy images on the page I don't want to load though. And unfortunately I've been taken off this task as the client is using a work-around. Thanks for your help anyway!

**Comment by verlok** [comment]
Yes, if new images are added dynamically, you can use the `update` method in order to make LazyLoad consider them. 
There’s a demo for this feature inside the `demos` folder.  
Let me know if this solves.
