### ISSUE TITLE
Microsoft Edge

### ISSUE THREAD

**Issue by leon** [verlok/lazyload#152]
Just spent an hour trying to get lazy loading working in microsoft edge.

What I realized is that for edge to fire the observer for an img element it must have a size.
Since img tags are inline as standard edge doesn't pick them up.
And since we don't have a src for the lazy loaded images the don't exist yet.

By setting
```
img[data-src],img[data-srcset] {
  display: block;
  min-height: 1px;
}
```

edge is able to see the images and they get loaded.

Could you please add a section to your readme about this, so other people don't have to do the same debugging as me :)

**Comment by mercuryyy** [comment]
leon thanks for this. 

Are you able to find a work around for safari browsers?

**Comment by verlok** [comment]
@leon: sure, will do. Thank you! I didn’t know that. Also, having a min-height in your images will prevent LazyLoad to detect ALL images inside the viewport at page landing, so I’d recommend to use a min-width that is really the minimum height of an image, not only just 1 pixel. 

@mercuryyy: this is not possible, Safari still doesn’t support IntersectionObserver. Please hold on and stick with the recommended version which is 8.2.1. They will update Safari, one day.

**Comment by mercuryyy** [comment]
@verlok yes thats what i did but why not add to the 10.3.3 a safari fallback something like 

`var isSafari = /^((?!chrome|android).)*safari/i.test(navigator.userAgent);`

So run the IntersectionObserver on chrome/ie/ff and fallback to 8.2.1 on safari ?

**Comment by verlok** [comment]
Because the two versions of LazyLoad  are very different one from each other, 8.x has code that listens to the scroll and resize events, whereas 10.x used IO and has totally different code. 
Implementing any internal switch would result in a much heavier script with both versions’ code, and we all want our scripts to be lightweight, don’t we?

Instead, you could do a check on whether `IntersectionObserver` is supported or not, then load 8.x or 10.x conditionally. The script has the ability to initialize one or more LazyLoad automatically so it would be even easier to make this happen.

**Comment by verlok** [comment]
Hey @mercuryyy,
thank you for the inspiration!

Here's the code you could use to download LazyLoad 8.x or 10.x conditionally, and auto-instantiate it on the page. So you would have a modern script where IntersectionObserver is supported, and a fallback for where it isn't.

```js
(function(){
	var head = document.getElementsByTagName('body')[0];
	var lazyLoadScript = document.createElement("script");
	var lazyLoadVersion = !("IntersectionObserver" in window) ? "8.2.1" : "10.3.3";
	lazyLoadScript.src = "https://cdnjs.cloudflare.com/ajax/libs/vanilla-lazyload/" + lazyLoadVersion + "/lazyload.min.js";
	window.lazyLoadOptions = {data_src: "src", data_srcset: "srcset"};
	head.appendChild(lazyLoadScript);
}());
```

This code was tested and it works. I've created a new demo in the demos folder, named conditional_load.html, check it out if you want to try it or play around with it.

Cheers!

**Comment by mercuryyy** [comment]
Thank you!

**Comment by mercuryyy** [comment]
@verlok  solution is working but in 8.2.1 when running is safari some of the same images are being downloaded 3-5 times for no reason, cant seem to figure out why.

**Comment by verlok** [comment]
@mercuryyy we're gone way off topic here, anyway I just tested it on Safari and it behaves correctly. Can you open another issue and be more specific? Thanks

**Comment by verlok** [comment]
@leon done! Could you specify the version of MS Edge you encountered the problem on?

**Comment by verlok** [comment]
> Has this issue changed since 2017?

You tell us. What happens if you don't set a min-height on MS Edge?
Did you need to use the "css hack"?

From the demos you can find in the [demos](demos) folder, everything seems to work perfectly.

**Comment by martijnimhoff** [comment]
I'm on v12.2.0 and it not working in Edge (with and without the css hack)
