### ISSUE TITLE
Issue on mobile

### ISSUE THREAD

**Issue by phuongleduy** [verlok/lazyload#154]
Hi, all.
 I have a issues on device mobile. please help me.

**Comment by verlok** [comment]
Hi,
in order to get help please describe the issue, the code you are using (html and js) and the version of LazyLoad you’re getting the issue on.

**Comment by phuongleduy** [comment]
This is version and my script
<script src="https://cdnjs.cloudflare.com/ajax/libs/vanilla-lazyload/8.2.0/lazyload.min.js"></script>
<script>
	new LazyLoad({threshold: 50,elements_selector: 'img.lazyLoad'});
</script>
Thanks a lot.

**Comment by verlok** [comment]
Thanks. 
Everything should be working fine. 

Are the script placed AFTER your HTML (so to be sure the DOM is ready when the JS is executed)?

What is the issue you are having?

**Comment by verlok** [comment]
By the way, I see you didn’t use the `img` tag, but I took it for a copy/paste error, or markdown trying to use it as an image. But you did use the tag, right?

**Comment by phuongleduy** [comment]
@verlok thanks you, i solved the issue, but image load on mobile so slow.

**Comment by verlok** [comment]
You should really use responsive images in order to make mobile phones use a smaller version of the image. 
Google “responsive images” to find out more. 
My LazyLoad script supports responsive images so you will have best results on mobile too.
