### ISSUE TITLE
Is simple defer of image loading supported?

### ISSUE THREAD

**Issue by AndrewCraswell** [verlok/lazyload#157]
I can't find this mentioned in the docs, but is it possible to use this library to defer image loading until the page loads? I already use lazyload to load in a bunch of images way at the bottom of the page where most users don't scroll to, but there are some images nearer the top of the page that I'd like to load regardless of whether it's in the viewport, I'd just prefer them to be deferred until the page loads. I could write a simple block of vanilla JavaScript to handle this, but since I'm already initializing a LazyLoad() instance, I'd prefer to rely on it if it has this functionality...

Here's an example of what I'm thinking:
```
function init() {
  var imgDefer = document.getElementsByTagName('img[data-defer-src]');
  for (var i=0; i < imgDefer.length; i++) {
    if(imgDefer[i].getAttribute('data-defer-src')) {
      imgDefer[i].setAttribute('src', imgDefer[i].getAttribute('data-defer-src'));
    }
  }
}

window.onload = init;
```

Thanks!

**Comment by verlok** [comment]
Sure, if you already use LazyLoad to load your images, you could instantiate a second LazyLoad and make it load only those images. For example, if you already do:

```js
var yourMainLazyLoad = new LazyLoad { elements_selector: 'img.lazy' };
```

You could instantiate ANOTHER lazyload for the deferred images only at window.onload. So:

```javascript
function init() {
  var yourOtherLazyLoad = new LazyLoad { elements_selector: 'img.defer' };
}

window.onload = init;
```

This would load the `img.defer` images (that are inside the viewport), at the window load time.

The markup for the deferred images could be the same as the lazy images, with the only difference that the first ones have the `lazy` class, and the second ones have the `defer` class.

You could also use any other kind of CSS selectors for the `elements_selector` option, but I think the class is easier to read, and you could use `data-src` and `data-srcset` in both the lazy and the deferred images.

Also please note that loading images after the window load event could determine a browser reflow and repaint, which is a slow operation, unless you reserve space for the images before they load.

Cheers!

**Comment by verlok** [comment]
PS: I saw you starred a lot of lazyload scripts, but not mine. I'm a little bit jealous now. ;) Will you star mine too?

**Comment by AndrewCraswell** [comment]
Done, and done! Thanks so much! :)

**Comment by verlok** [comment]
Awesome. Thanks! :)
