### ISSUE TITLE
Possibility to apply lazyload to any element

### ISSUE THREAD

**Issue by alvarotrigo** [verlok/lazyload#159]
I'm not quite sure if this is already possible or not, but as far as I was able to test, it is not.

I would like to make use of lazyload in elements that has no image or `src` attribute at all. For example, to `<div class="test"></div>` 

[Reproduction online](https://jsfiddle.net/hmqg7hxb/) where you can see the image loads and fires the callback but not the `div` element. 

The reason for it is simple. Defer the loading of non-critical files / code to improve pageload performance.
Some scenarios are:

- Include [disqus comments](https://disqus.com/) snippet when about to reach its container
- Include codepen JS file when reaching the codepen.
- Include [vimeo player JS file](https://github.com/vimeo/player.js) when reaching the video.
- Include non-critical CSS stylesheets when about to reach the elements using it (newsletters, comments, footer...)
- Fire Google Analytics tracking call when reaching certain element. 

This could all be done through the `callback_load` call and using this library to detect if they are in viewport or they are about to be, would be ideal. 

At the moment I have to create the `inViewPort` function myself and it seems a bit like duplicating code and probably not as good in terms of performance.

**Comment by verlok** [comment]
Hi @alvarotrigo,
thank you for the suggestion, this is a very good idea and a very small code change is required.
I'd introduce a new callback called `callback_enter` that would be called when the element enters the viewport (considering "threshold").
What do you think?

**Comment by verlok** [comment]
I did it. And released it under the version tag 10.4.0.
When it will be on CDNJS, this fork of your fiddle shoud work https://jsfiddle.net/cqwjL3ku/

Let me know if we're good :)

**Comment by alvarotrigo** [comment]
Awesome! 
I'm not quite sure what's inside the `dist` folder. Is it version 8 or version 10? Should I assume its 8?
Didn't see any comment credits or property within the lazyLoad object with its version.

Using npm install it seems I get version 8.5.2, but then the latest release is 10.4.x.
How does this work? 
Did you update it in version 8 too?

**Comment by verlok** [comment]
You’re right, I did it all in a hurry yesterday night and I forgot to update the `dist` folder, and to run `npm publish`. Will fix it soon. 
Version 8.x is still not updated. I wanted to be sure that this was working as you expected on version 10 beforehand. 
I’ll let you know. 
Thanks for your patience.

**Comment by verlok** [comment]
Just released the fix as 10.4.1. Also on npm.
You can use it like that:

```js
ll = new LazyLoad({
	callback_enter: function (element) {
		logElementEvent("ENTERED", element);
	}
});
```

Let me know!

**Comment by alvarotrigo** [comment]
Yeap! Thanks for that! Working as expected!
Let me know when it's available in version 8. 

By the way, how can I install both version with npm to make use of [the conditional loading](https://github.com/verlok/lazyload#advanced-and-best-option-conditionally-load-version-8-or-10)? (without using the CDN :) )

**Comment by verlok** [comment]
Hi @alvarotrigo,
the fix is now available in both versions 10.4.1 and in 8.6.0.

\o/ yay! I'm closing the issue now.

> By the way, how can I install both version with npm to make use of the conditional loading? (without using the CDN)

We were figuring out today and I think that you can't, meaning you must use the CDN.
If you figure something out to do that, please let me know.

**Comment by alvarotrigo** [comment]
Thanks for that!! ;)

**Comment by alvarotrigo** [comment]
Regarding this issue, I just realised it works with only certain elements but now with others. 
For example, you get the callback triggered on a `<div>` but not on a `<script>` file.

This prevents us from using lazyload to load scripts in our site.

Reproduction online:
https://jsfiddle.net/alvarotrigo/1zrkqx37/2/

Notice how the script won't lazy load.
