### ISSUE TITLE
Infinite scroll support

### ISSUE THREAD

**Issue by Tabrisrp** [verlok/lazyload#160]
Hi,

More a question than a bug report. On a website with infinite scrolling, so new elements are added to the DOM asynchronously, the script is currently not able to detect them automatically right?

If correct, is this something that would be possible in the future? Also, in that case, the current way to load new images added to the DOM is through the update() method?

**Comment by verlok** [comment]
Hi @Tabrisrp,
all that you wrote is correct: the script is currently unable to detect new elements, so you'll have to call `update()` on the LazyLoad instance when new content gets added to the page. 

We have a couple of demos for using LazyLoad with dynamic content, [here](https://github.com/verlok/lazyload/blob/master/demos/dynamic_content.html) passing a selector and [here](https://github.com/verlok/lazyload/blob/master/demos/dynamic_content_nodeset.html), passing a NodeSet object to it.

**Comment by verlok** [comment]
Ah, if you add LazyLoad asynchronously, you can still assign the automatically created instance of LazyLoad to a variable. The code for this is [here](https://github.com/verlok/lazyload/blob/master/demos/async.html) and there's also a "recipe" in the [readme](README.md) file, under the heading "Auto init + store the instance in a variable"

**Comment by verlok** [comment]
There's a way, though, to make LazyLoad auto-update when new content gets added to the page. 

It can be done using the MutationObserver API ([see here](https://developer.mozilla.org/it/docs/Web/API/MutationObserver)) either in the hosting website's script or in the LazyLoad script itself. 

The only constraint is that MutationObserver only works starting from IE11, and some LazyLoad users want to use support older browsers too. Anyway the support would be quite widespread already.

**Comment by Tabrisrp** [comment]
Thank you very much for your answers, I was able to make the auto-update with MutationObserver, seems to be working perfectly!

Support of old browsers is not really an issue for me, so it's all good!

**Comment by verlok** [comment]
Great! Just yesterday I was playing around with MutationObserver too. I’d like to integrate it in the script, but I need to better understand how it works in the depths of the DOM chain. 

Could you please copy and paste the MutationObserver-related part of your code here?

That would help.

**Comment by Tabrisrp** [comment]
It's pretty straight-forward, I'm not that much versed in JS so there might be a better way to do this

```
// Listen to the Initialized event
window.addEventListener(\'LazyLoad::Initialized\', function (e) {
    // Get the instance and puts it in the lazyLoadInstance variable
	var lazyLoadInstance = e.detail.instance;

	var observer = new MutationObserver(function(mutations) {
		mutations.forEach(function(mutation) {
			lazyLoadInstance.update();
		} );
	} );
	
	var b      = document.getElementsByTagName("body")[0];
	var config = { childList: true, subtree: true };
	
	observer.observe(b, config);
}, false);
```

**Comment by verlok** [comment]
Hey @Tabrisrp,
I think that it has to be an external script to call LazyLoad's `update()` method when the DOM is updated. 
One way to do it is right the way you implemented it. Another one would be to call `update()` after injecting new DOM.
I don't think this DOM change management should be in charge of LazyLoad.
