### ISSUE TITLE
Occasionally, IntersectionObserver reports a 0 IntersectionRatio, stopping a reveal

### ISSUE THREAD

**Issue by broguinn** [verlok/lazyload#165]
* What is happening?

Certain horizontal rows never load their images because IntersectionObserver occasionally reports an IntersectionRatio of 0. In my local dist I've moved to `>=` for the check on L195, but maybe that should be removed altogether? I'm not seeing over-firing of events or prematurely-loaded images as-is.

* What is the expected behaviour?

The row loads on intersection

* Which version of LazyLoad are you using?

10.4.x 

* In which browser(s) and browser version(s) are you experiencing the problem?

Chromium 64

* Could you provide the HTML, CSS and JS code you use for your images?

I can't share the source, but I'm using something nearly identical to the basic example in the README.

* What are the steps to reproduce the problem?

1. Have multiple rows of images.
2. Set a breakpoint at https://github.com/verlok/lazyload/blob/master/dist/lazyload.js#L195
3. Occasionally IntersectionObserver reports all entries have an IntersectionRatio of 0, and won't fire another intersection event for these items unless you scroll back up
4. Be frustrated

* Thank you

Thank *you* for the very well-maintained lib!

**Comment by broguinn** [comment]
Unfortunately, modifying the ratio check means that all images are loaded immediately on the initialization of the IntersectionObserver instance -- I'm still trying to figure out how to get it to not activate initially.

**Comment by broguinn** [comment]
This is gross and probably not ideal, but I got it working by adding state to the constructor so that the first time the InteractionObserver calls onIntersection (when it ends up called for all target entries) it breaks:

https://gist.github.com/broguinn/b77e3d89456894ef7a719ef3bcbb47f1

**Comment by broguinn** [comment]
One more update: to get entries to load their images that are initially visible on page load, I changed the check line to:
`if (entry.intersectionRatio > 0 || _this._initialized) {`

**Comment by verlok** [comment]
Hi @broguinn,
thanks for submitting the issue and for the analysis. I’ll check everything and fix it as soon as possible.

**Comment by verlok** [comment]
Released 10.4.2 which fixes this.

**Comment by broguinn** [comment]
Thanks so much!!
