### ISSUE TITLE
Loads all images

### ISSUE THREAD

**Issue by anteksiler** [verlok/lazyload#17]
I am using this plugin on this staging site, which is a WordPress site: http://ftgoodlife.staging.wpengine.com/

By default, it loads all the images inside the container. Using the following options:

````
threshold: 100,
					container: document.getElementById('content-container'),
					elements_selector: ".post-gallery img",
					throttle: 30,
					class_loading: 'image-loading',
					class_loaded: 'image-loaded',
					data_src: "original",
					show_while_loading: false,
					callback_set: function() { /* ... */ }
````

**Comment by anteksiler** [comment]
@verlok Hi Andrea, I would appreciate you input on this.

**Comment by anteksiler** [comment]
I removed the "container" attribute and this was fixed.

**Comment by verlok** [comment]
Yes, the "container" should be used only if the scrolling container is different than the main document. For example, if you have 2 scrolling regions in your page. Sorry for the delay.
