### ISSUE TITLE
Lazyload safari

### ISSUE THREAD

**Issue by marcantons** [verlok/lazyload#171]
..

**Comment by marcantons** [comment]
Where to download lazyload vers 8.1 to solve problems with safari

**Comment by verlok** [comment]
Hi @marcantons,
to which problems with Safari are your referring to?

The latest version which is compatible with ALL the browsers, including Safari, is 8.6.0.
You can find it here: https://cdnjs.cloudflare.com/ajax/libs/vanilla-lazyload/8.6.0/lazyload.min.js
