### ISSUE TITLE
skitzo behaviour

### ISSUE THREAD

**Issue by 0dp** [verlok/lazyload#174]
* What is happening?
All images load, but only some images gets the `.loaded` class applied, sometimes; seamlessly at random.

* What is the expected behaviour?
All images load, and all images should be visible by having `.loaded` applied to them.

* Which version of LazyLoad are you using?
I use the recommended conditional loading method.

* In which browser(s) and browser version(s) are you experiencing the problem?
FF57, Chrome63

* Could you provide the HTML, CSS and JS code you use for your images?
```
<img class="fl-photo-img" src="//images.jpg" alt="image" itemprop="image" srcset="//image.jpg 819w, //image.jpg 240w, //image.jpg 768w, //image.jpg 600w" sizes="(max-width: 640px) 100vw, 640px" data-was-processed="true" width="640" height="800">
```

```
            .fl-photo-img {
                display: block;
                border: 0;
                opacity: 0;
            }
            .fl-photo-img:not(.initial) {
                transition: opacity 1s;
            }
            .fl-photo-img.initial,
            .fl-photo-img.loaded,
            .fl-photo-img.error {
                opacity: 1;
            }
            .fl-photo-img:not([src]) {
                visibility: hidden;
            }    
```

```
            (function(w, d){
                var b = d.getElementsByTagName('body')[0];
                var s = d.createElement("script"); s.async = true;
                var v = !("IntersectionObserver" in w) ? "8.6.0" : "10.4.1";
                s.src = "https://cdnjs.cloudflare.com/ajax/libs/vanilla-lazyload/" + v + "/lazyload.min.js";
                w.lazyLoadOptions = {elements_selector: ".fl-photo-img"}; // Your options here. See "recipes" for more information about async.
                b.appendChild(s);
            }(window, document));
```

* What are the steps to reproduce the problem?
The page has a grid of images all with the class `.fl-photo-img`, above code is loaded. Below is a screenshot of the result.

https://screenshots.firefox.com/2wpmP9B0AHpM3R4c/localhost

Thank you.

**Comment by aggreggator** [comment]
You don't use use any data attributes in your img-tag. 
Nothing gets lazyloaded and is proccessed through lazyload. 
It's just an standard image tag.

**Comment by verlok** [comment]
Hi @0dp,
Thank you for the very detailed report. 
What @aggreggator replied is correct, if that is really the HTML code you’re using. 
Can you confirm it is so? If not, can you put the real HTML you’re using?

**Comment by 0dp** [comment]
Hi Guys,

Ahh I see, I've added data-src and it seems to work correctly.

Funny how it still attempts, and partially succeed lazyloading.
