### ISSUE TITLE
Fallback for users that disable javascript? How about Opera Mini?

### ISSUE THREAD

**Issue by zom243** [verlok/lazyload#179]
How to make the images loading normally for browser that have javascript disabled? Is there any way to do this? And also, is this lazy load work on Opera Mini? Or at least, will the image load normally on Opera Mini?

**Comment by verlok** [comment]
Hi there. The only way to do that is to place an `img` tag with the correct `src` value inside a `noscript` tag. All of this in addition to the lazy image tag.
