### ISSUE TITLE
Chrom on iPad Mini crashes

### ISSUE THREAD

**Issue by artursudnik** [verlok/lazyload#18]
I have serious issue while testing on iPad Mini. Page with over 100 images scrolls non smoothly. Over time it gets worse and worse, finally web browser crashes. Very basic use case with default options.

**Comment by artursudnik** [comment]
Just tested that this is not related to the plugin but to the number of images on page. Chrome crashes also after removing lazyload script and initialization code.

**Comment by verlok** [comment]
Can you give me more information about this? Does Safari for iOS have the same issue? What about Chrome *without* lazy load?

--
Andrea Verlicchi
www.andreaverlicchi.eu

**Comment by verlok** [comment]
That's what I was trying to understand with my previous questions. How big are the images in size and weight? I suggest you to optimize them and if they already are, unload them as they exit the viewport. If the pagination of your images is not applicable 

--
Andrea Verlicchi
www.andreaverlicchi.eu

**Comment by artursudnik** [comment]
I've exactly figured out what you suggest - there are too many nonresponsive images on this page that is too big for this small device. It crashes even with no lazyload solution.

**Comment by verlok** [comment]
Try making them responsive then. You can use the `srcset` and `sizes` attributes and still lazy load the images with my (awesome) script. 

[Here's a repo](https://github.com/verlok/img_srcset_lazyload/blob/master/readme.md) of mine which explains exactly how to do it. Yay! ^_^

Happy coding. 
Andrea

**Comment by verlok** [comment]
Try making them responsive then. You can use the `srcset` and `sizes` attributes and still lazy load the images with my (awesome) script.

[Here's a repo](https://github.com/verlok/img_srcset_lazyload/blob/master/readme.md) of mine which explains exactly how to do it. Yay! ^_^

Happy coding.
Andrea
