### ISSUE TITLE
Documentation points to 10.4.1

### ISSUE THREAD

**Issue by justindamer** [verlok/lazyload#183]
The conditional loading example in the documentation points specifically to 10.4.1.

I only figured out there was a newer version when I encountered the IntersectionObserver issue in Chrome which is resolved in 10.4.2.

Is there a way to point to a less precise version number? Like "newest"?

Great work on this, it was a life saver! Thanks.

**Comment by verlok** [comment]
Hi there. 
You’re welcome :)

No, unfortunately there’s no way to always point to the latest version, and I kinda would not advise to do so, especially in production, because you wouldn’t have a stable environment. 

Will update the version in the readme, though. Thanks

**Comment by verlok** [comment]
Done :) Thanks
