### ISSUE TITLE
lazyload loads all images (even outside viewport) on iOS / PhoneGap

### ISSUE THREAD

**Issue by spinninghamster** [verlok/lazyload#186]
I am using this lazyload on an iOS PhoneGap application. On Android it works perfectly fine, but in iOS it instantly loads all images, even those outside the viewport.

I was wondering if there's any CSS tag or attribute that would cause this? I've begun stripping everything away but can't seem to track it down.

**Comment by verlok** [comment]
You’re probably using version 10. Use version 8 to make it work correctly on iOS safari, or loading the versions conditionally using require.js. 
Read the readme for more information.

**Comment by spinninghamster** [comment]
Nope, I tried both version 8 and 10. Strangely even testing the PhoneGap application in the browser it doesn't work until I resize the browser window just 1 pixel. Then the images load.

**Comment by verlok** [comment]
Here's what happens at the browser window's resize event:

- version 8 of LazyLoad calls the `_loopThroughElements()` method which loops over all the lazy images to check whether or not they are inside the viewport, then if the answer is yes it calls the `_ _reveal()` method.
- version 10 of LazyLoad does nothing, but the browser resize impacts on the `IntersectionObserver`, which triggers the `revealIntersectingElements()` and eventually calls the `revealElement()` function.

I hope this helps you understand what's going wrong with your usage of this script.

**Comment by verlok** [comment]
@spinninghamster did you have any luck solving this issue?

**Comment by adrianxadamn** [comment]
Confirming that using <script src="https://cdnjs.cloudflare.com/ajax/libs/vanilla-lazyload/8.7.1/lazyload.min.js"></script> still doesn't reveal images inside viewport on Safari

**Comment by adrianxadamn** [comment]
Nevermind. It does work. I had to use lazyload options. I guess it's picky for Safari but Chrome doesn't need it. 

new LazyLoad({
      elements_selector: ".lazy",
      threshold: 0,
      callback_enter: function(element){
          $(element).addClass('loaded');
      }});

**Comment by verlok** [comment]
Good to know. Thank you.

**Comment by spinninghamster** [comment]
Sorry for re-opening this old issue. I dropped this for another option but now am in need of a lazyload option again and still facing the same issue.

I tried the above 8.7.1 version and it doesn't work when I use:

> var lazyLoadInstance = new LazyLoad({
>    	    elements_selector: ".lazy"
> });

This code however works when using 12.x

What's the correct code to use for 8.x? I can't find the documentation anywhere.

**Comment by verlok** [comment]
Hey @spinninghamster 
to find the doc you can go to the releases section of this GitHub project, find the version you want, check out and read the readme. 

But when that was the final and more recent version, it didn’t have the problem you’re having now. 

Why don’t you open a new issue with all the details?
