### ISSUE TITLE
Could lazyload support IFRAME?

### ISSUE THREAD

**Issue by yanni4night** [verlok/lazyload#19]
IFRAME is another type of resource should be lazy-loaded.

**Comment by verlok** [comment]
Are you talking about images inside and iframe? Or about making iframes to gain their source attributes as they enter the viewport?

**Comment by yanni4night** [comment]
Just think about https://vvo.github.io/lazyload/ ,which supports iframe lazyloading but with obscure API

**Comment by verlok** [comment]
Thank you for the suggestion. 
I'll take a look at the code to see if supporting iframes is easy enough to keep the code as fast and simple as it's now. I'll let you know.

**Comment by verlok** [comment]
Hi @yanni4night,
I did some test and I found out that my script actually already supports iframe loading :)

To do so, you have to initialize an instance of LazyLoad using the following code.

In the HTML:

```html
<iframe data-original="iframes/i01.html" frameborder="0"></iframe>
<iframe data-original="iframes/i02.html" frameborder="0"></iframe>
<iframe data-original="iframes/i03.html" frameborder="0"></iframe>
`

And in Javascript:

```javascript
new LazyLoad({
	elements_selector: "iframe",
	show_while_loading: true
});
```

I just committed [a demo](/demos/iframes.html) inside this repo.

**Comment by yanni4night** [comment]
I see that I have to set `show_while_loading` to `true`,or it will not work,thanks.

**Comment by verlok** [comment]
Now supported natively in [version 2.0.0](https://github.com/verlok/lazyload/releases/tag/v2.0.0)

**Comment by yanni4night** [comment]
Wonderful！

**Comment by verlok** [comment]
And now the `show_while_loading` option defaults to `true`. Check out the demo files in the demos folder or read the readme.md

**Comment by botako** [comment]
Hey @verlok  how about images inside an iframe, how can you do that?

**Comment by verlok** [comment]
Hello @botako,

If you have little (a few) images inside the frame, you can just lazy load the whole iframe.

If you have many images inside the iframe, and you have control for the iframe’s code, you can try instantiating a lazy load inside the iframe, but I never tried that.

**Comment by verlok** [comment]
By the way this issue is closed already, please open a new one.
