### ISSUE TITLE
How to install it in Vue-Cli?

### ISSUE THREAD

**Issue by nnagewad** [verlok/lazyload#191]
Are you reporting a bug or requesting a feature?
- Bug / Question

What is happening?
- I'm trying to install your plugin using npm.
- Unsure the proper process in installation...

What is the expected behaviour?
- No errors
- I thought it was simple???

Which version of LazyLoad are you using?
- Latest version

In which browser(s) and browser version(s) are you experiencing the problem?
- Latest Chrome

Thank you.

**Comment by verlok** [comment]
Sorry @nnagewad, I'm failing to understand what you're asking here.
Maybe you can ask a more specific question?

**Comment by verlok** [comment]
@nnagewad, I'm assuming you solved after months of inactivity. Feel free to reopen the issue if you still need help.
