### ISSUE TITLE
Safari 11 only loads images in viewport. LazyLoad 8.7.1

### ISSUE THREAD

**Issue by addedlovely** [verlok/lazyload#192]
Are you reporting a bug or requesting a feature?
Bug.

* What is happening?
In Safari 11.0.3 / 10.1 images that are visible in the viewport load, ones off screen do not. Resizing the browser or scrolling doesn't invoke loading.

* What is the expected behaviour?
Images lazy load.

* Which version of LazyLoad are you using?
8.7.1 

* In which browser(s) and browser version(s) are you experiencing the problem?
Safari 11.0.3 / 10.1

* Could you provide the HTML, CSS and JS code you use for your images?
Please see reduced test case here:
https://codepen.io/addedlovely/full/WzLPgQ/

Thought CSS grid might be at fault, but disabling that makes no difference:
https://codepen.io/addedlovely/full/XEoOOe/

Also tried disabling using CSS padding top to make a placeholder bounding box:
https://codepen.io/addedlovely/pen/pLqGYN

* What are the steps to reproduce the problem?
Load the pen, make sure some of the images are off the viewport, scroll down - see the 2 images on the bottom row don't load.

Thank you.

**Comment by addedlovely** [comment]
Ah, I had missed the data- from srcset, e.g. data-srcset

**Comment by verlok** [comment]
I was just about to take a look on your issue. Good to know you’ve solved it yourself. :)
