### ISSUE TITLE
Force download all images on click event

### ISSUE THREAD

**Issue by umesh-velir** [verlok/lazyload#193]
Are you reporting a bug or requesting a feature?
Requesting a feature

Is there a way to force download all images on click event?

Thanks!

**Comment by verlok** [comment]
Hi @umesh-velir,
thank you for this request. Could you clearify two of your sentences?

> I could not use aspect ratio approach

Are you referring to the tip&trick I wrote in the tips and tricks section, about [occupying vertical space](https://github.com/verlok/lazyload#occupy-vertical-space-and-maintain-ratio)? If yes, can I ask you why can't you use that?

The "load all images" feature shouldn't be hard to implement in the script, it's just a loop and a function call, but I fail to imagine a case where this could be useful to anybody. In other words... you need to convince me :)

**Comment by gyoungbe** [comment]
Hi @verlok! What if you're trying to force download all images in a carousel. Lazy load the initial image and then when the user triggers the carousel (using keyboard or a carousel nav button) it loads the rest of the images within the carousel?

**Comment by verlok** [comment]
Hi @gyoungbe,
LazyLoad shouldn’t be used in carousels,  since carousels don’t use scroll events but they move the elements in their own way. 
If you want to lazy load images in a carousel,  you should find a carousel with the lazy load feature included

**Comment by rmngrc** [comment]
In my case I would like to load them all for our visual diff test suite. Would there by any way to do that programmatically @verlok ?

**Comment by verlok** [comment]
Yes, you can just select all lazy loaded images via jQuery or `document.querySelectorAll`, cycle them in a loop and copy the attribute from the `data-src` to the `src`, and to the same with the `srcset`. Do you know how to do that or you need a hint?

**Comment by verlok** [comment]
Of course I can develop a public method on LazyLoad which immediately loads all the images. It would be simpler to you, wouldn’t it.

**Comment by rmngrc** [comment]
That would be great! Massive thanks!

**Comment by verlok** [comment]
@umesh-velir, you're served.

**Comment by verlok** [comment]
You now have a method called `loadAll` which you can use to force download all the images.
Please find the code and the demo in the `demos/load_all.html` demo.

**Comment by rmngrc** [comment]
Thanks @verlok!! 👏

**Comment by verlok** [comment]
You got them!
