### ISSUE TITLE
Implementing LazyLoad for 'the_post_thumbnail()' php function

### ISSUE THREAD

**Issue by james-ig-phillips** [verlok/lazyload#195]
I apologise in advance if this is the wrong place to post this request as it's not a bug/issue.

I'm having trouble trying to implement the lazy loading script by replacing the_post_thumbnail() PHP WordPress function.

The code I'm trying to replace is:
`<?php if (has_post_thumbnail()) { the_post_thumbnail(); } else { ?>`

My approach has been:
```
<?php if (has_post_thumbnail()) { ?>

	<?php
	$thumb_id = get_post_thumbnail_id(get_the_ID());
	$alt = get_post_meta($thumb_id, '_wp_attachment_image_alt', true);
	?>
	<noscript><img src="<?php echo get_the_post_thumbnail_url();?>" alt="<?php echo $alt; ?>" class="bg"></noscript>
	<img data-src="<?php echo get_the_post_thumbnail_url();?>" alt="<?php echo $alt; ?>" class"bg lazy">

<?php } else { ?>
```

The image just returns as a broken image.

Any kind of response would be awesome. If you need any further details please let me know and I'll gladly provide them.

**Comment by verlok** [comment]
Hi @james-ig-phillips, I'm assuming you solved in the past inactive months. If you didn't, feel free to reopen the issue. Thanks
