### ISSUE TITLE
verlok lazyload not add loaded class for background images

### ISSUE THREAD

**Issue by a7medm7med** [verlok/lazyload#198]
By default, the plugin is added `loaded` class for images after it's loaded, But that's not happening for background images. (The same issue on the plugin demo page).

So my question is how can added class `loaded ` for background images?

**Comment by verlok** [comment]
Hey @a7medm7med,
things changed on version 15. 

I found a way to manage background images's load/error event, so now background images are now getting the `loaded` or `error` class and calling `callback_loaded` and `callback_error`.

Take a look at the [changelog](https://github.com/verlok/lazyload/blob/master/CHANGELOG.md) and to the [upgrading guide](https://github.com/verlok/lazyload/blob/master/UPGRADE.md) if you're interested.

Have a nice day.
