### ISSUE TITLE
Changing the Intersection Observer Threshold after Initialization

### ISSUE THREAD

**Issue by cbieser** [verlok/lazyload#200]
feature request

I want to be able to change the threshold value of the Intersection Observer. When loading for the first time, I want to avoid off-screen images and use a lower threshold. When the page is fully loaded (and a few seconds have passed), I want to raise the threshold.

Do you think that's possible?

**Comment by verlok** [comment]
Hey,
that’s actually a good idea!
The IntersectionObserver is an instance variable named `_observer` so it’s accessible through your variable name. 

For example:

```js
var myLazyLoad = new LazyLoad();
myLazyLoad._observer // do whatever you want with it
```

**Comment by verlok** [comment]
Now that I checked, you can’t do it that way, because the IntersectionObserver’s RootMargin property is Read Only. 

What you would need to do is create a first LazyLoad, `.destroy()` it after the page landing, then create another LazyLoad with a smaller `threshold`. 

That would make it.
