### ISSUE TITLE
lazyload not affecting marked images

### ISSUE THREAD

**Issue by johlym** [verlok/lazyload#205]
* What is happening?

In production, `lazyload.js` does not "lazy load" images. 

* What is the expected behaviour?

Images are loaded as needed during scroll events.

* Which version of LazyLoad are you using?

v8 latest

* In which browser(s) and browser version(s) are you experiencing the problem?

Safari, Firefox, Chrome

* Could you provide the HTML, CSS and JS code you use for your images?

This is one of them:

```
<img src="/assets/images/2018/05/07/circleci-sm.jpg" alt="" data-lightbox="image-1" srcset="/assets/images/2018/05/07/circleci-sm@2x.jpg 2x" data-src="/assets/images/2018/05/07/circleci-sm.jpg 2x" data-srcset="/assets/images/2018/05/07/circleci-sm@2x.jpg 2x">
```

* What are the steps to reproduce the problem?

Load production site.
See images that were not supposed to load yet load via browser Network tab.
Verify scroll position is at 0 using `document.body.scrollTop`.

<img width="709" alt="screen shot 2018-05-14 at 8 50 32 pm" src="https://user-images.githubusercontent.com/5686227/40035839-95ea0ab2-57b8-11e8-9d6b-fdc9018edead.png">

Scratch head.

Let me know if I can provide anything else. 

(PS: It's worth noting I'm also using `lightbox.js` for these images but removing it doesn't have an effect)

UPDATE:

I can't believe I missed this. Having `src=""` and `srcset=""` filled was what was causing my problems. I feel 🐑 ish for not noticing that sooner.

**Comment by verlok** [comment]
Sometimes, explaining your problem to someone else (ore something else, see Rubber Duck Debugging on Wikipedia) helps to find the cause of the problem. 

Thanks for opening and closing this.
