### ISSUE TITLE
All images are being loaded

### ISSUE THREAD

**Issue by gvenm** [verlok/lazyload#207]
* What is happening?

All images are being loaded even outside the viewport.

* What is the expected behaviour?

Images outside of viewport not to be loaded until user scrolls.

* Which version of LazyLoad are you using?

10.5.2

* In which browser(s) and browser version(s) are you experiencing the problem?

Currently Google Chrome

* Could you provide the HTML, CSS and JS code you use for your images?

`<picture>
    <source ng-srcset="{{@root.rootPath}}assets/images/{{name}}.jpg" media="(min-width: 1024px)" data-srcset="{{@root.rootPath}}assets/images/{{name}}.jpg">
    <source ng-srcset="{{@root.rootPath}}assets/images/{{name}}-tablet.jpg, {{@root.rootPath}}assets/images/{{name}}-tablet.jpg" media="(min-width: 768px)" data-srcset="{{@root.rootPath}}assets/images/{{name}}-tablet.jpg, {{@root.rootPath}}assets/images/{{name}}-tablet.jpg">
    <img class="r-image {{name}}" data-src="{{@root.rootPath}}assets/images/{{name}}.jpg" ng-srcset="{{@root.rootPath}}assets/images/{{name}}.jpg, {{@root.rootPath}}assets/images/{{name}}.jpg" alt="default office" data-srcset="{{@root.rootPath}}assets/images/{{name}}.jpg ,{{@root.rootPath}}assets/images/{{name}}.jpg">
</picture>`

On init:

`new LazyLoad();`

Thank you.

**Comment by gvenm** [comment]
So if I scroll all the way down on the page, this works perfectly when scrolling up it works the way it should however not working from the top

**Comment by verlok** [comment]
Hi @gvenm,
are you able to replicate the problem in a Pen on [CodePen](https://codepen.io/)?

**Comment by gvenm** [comment]
Hi @verlok 

Thank you for your response.

I managed to get this working, it seemed to be an issue with Handlebars and its #each statement in the HTML.

Quick question while I'm here, is there support for video by any chance?

**Comment by verlok** [comment]
Hey there. Thanks for your reply. Could you open another issue for the video support?

**Comment by verlok** [comment]
@gvenm I mean, please add a new issue as a request. The lazy loading of `video` is not currently supported, but I think it would be possible to support it with a very few lines of code.
