### ISSUE TITLE
8.x multiple error events on same failed resource (causes occasional call stack exceeded error)

### ISSUE THREAD

**Issue by webkitstudio** [verlok/lazyload#208]
On branch support/8.x, there is an issue where an image is being set, even though it was already processed.

I noticed this when scrolling, and an image 404's, what happens is the library keeps trying to set the src attribute, which causes the error handler to fire multiple times.

Its more noticeable on slower devices.

I would recommend add this to line 81 in /src/lazyload.js

`if (isBot || isInsideViewport(element, settings.container, settings.threshold) && !getData(element, "was-processed")) {`

**Comment by verlok** [comment]
Hi @webkitstudio,
thank you for opening this.

I'm not sure I understood what you're trying to explain here. Can you demonstrate this on a Codepen, or record a quick video of the incident you're encountering?

Secondly, why don't you fork the repo and fix it yourself, then open a pull request to integrate the fix in the official version of the script?

Many thanks

**Comment by verlok** [comment]
I understood what you mean now, sorry I wasn't reading thoroughly.
I'll take a closer look to this issue in the next hours.

**Comment by verlok** [comment]
I tried to replicate the issue you're reporting in this codepen https://codepen.io/verlok/pen/dKvZNv?editors=1010 but I wasn't able to replicate the error handler to fire multiple times. Could you please check?

**Comment by verlok** [comment]
@webkitstudio any updates? Can I close this?

**Comment by verlok** [comment]
Closed. Feel free to open anytime if you encounter this problem again.
