### ISSUE TITLE
Video Support

### ISSUE THREAD

**Issue by gvenm** [verlok/lazyload#209]
Hi @verlok 

Just wanted to find out if there is video support?

Thank you.

**Comment by verlok** [comment]
That shouldn't be a big deal to implement. Will check.

**Comment by gvenm** [comment]
Awesome, thank you! 😀

**Comment by verlok** [comment]
@gvenm I started working on it today, I confirm it should be quite easy to do. I'll keep you updated.

**Comment by verlok** [comment]
@gvenm you can see the few changes I did in [this commit](https://github.com/verlok/lazyload/commit/03d0e90f4e5002f6752f9e3c2a02a8e0cfa99911). It's still on a feature branch, need to add some tests on it, then merge it to master.

**Comment by gvenm** [comment]
This is brilliant! Appreciate this @verlok

**Comment by verlok** [comment]
Done and released 10.7.0.
Not yet released in 8.x version.

**Comment by verlok** [comment]
Done! https://twitter.com/vanillaLazyload/status/1010404143662497793
