### ISSUE TITLE
Background-image support

### ISSUE THREAD

**Issue by stalinkay** [verlok/lazyload#21]
@verlok, thank you for this plugin. I believe it can even be better if you add support for background-images both in inline CSS  and in a linked stylesheet. Thank you in advance.

**Comment by verlok** [comment]
Thank you. It's not what this script is meant for, but I'm open to pull requests. 
If you don't feel like coding, please note that I read in other "issues" that some users were able to tweak the usage of this plugin to add support to background images without changing it.

**Comment by stalinkay** [comment]
Ok. Cool.

**Comment by verlok** [comment]
Also, you can use lazyload's events to determine when an image enters the viewport and use the callback to do pretty much what you want.

**Comment by stalinkay** [comment]
Understood.

**Comment by verlok** [comment]
Now supported natively in [version 2.0.0](https://github.com/verlok/lazyload/releases/tag/v2.0.0)
