### ISSUE TITLE
src error in html validator

### ISSUE THREAD

**Issue by imarks-saisudhakar** [verlok/lazyload#211]
When i check html validation it shows error **Element img is missing required attribute src.**

WE Expecting no errors at the time of html validation.  

we are used latest version from cdn 

<script src="https://cdnjs.cloudflare.com/ajax/libs/vanilla-lazyload/10.5.2/lazyload.min.js"></script>

![lazyloaderror](https://user-images.githubusercontent.com/22255836/41402021-df144f2a-6fde-11e8-99fb-be303c08d13d.jpg)

please resolve issue ASAP.

Regards,
Saisudhakar.
Thank you.

**Comment by verlok** [comment]
Hello!

This is not an issue I can solve in my script, if you want W3C valid HTML markup _before_ JavaScript is executes, you can place a placeholder `src` in your HTML markup. 

Anyway if you don’t do that, you'll still have W3C valid HTML after JavaScript is executed.

**Comment by verlok** [comment]
Please read the new section of the README, [Do NOT use placeholder images](https://github.com/verlok/lazyload#do-not-use-placeholder-images) until the end of the section.

**Comment by imarks-saisudhakar** [comment]
Got it,Thank you for your Quick response.
