### ISSUE TITLE
SEO: Fetch as Bingbot does not `show` real image but placeholder / empty src

### ISSUE THREAD

**Issue by gerdneuman** [verlok/lazyload#215]
1. Go to https://www.bing.com/webmaster/diagnostics/fetch/bingbot (must register your demo site first I guess)
2. Search for lazy loaded image

What happens:
Looks like the image placeholder or empty `src` does not get replaced by LazyLoad for the Bingbot.

What should happen:
Same as for Googlebot. Replace for Bingbot too.

I know Bing has by far not the same market share like Google, but still a few million users use it :) Also DuckDuckGo or Yahoo search is based on Bingbot results afaik

**Comment by gerdneuman** [comment]
Uh, sorry, just noticed that `Fetch as Google` also shows the un-lazy-loaded source: https://www.google.com/webmasters/tools/googlebot-fetch 

Could should you maybe shed some light on how the SEO-friendliness of LazyLoad works? Could not find much about it in the README.

**Comment by verlok** [comment]
Uhm, interesting. Investigating right now. I'll let you know. Thanks for opening this. And sorry for the delay.

**Comment by verlok** [comment]
Hey @gerdneuman,
I discovered that version 10 had an issue with SEO. The bit of code that recognized a bot and loaded all the images right away wasn't there anymore, but it was still present on version 8.
I released version 10.11.0 with the fix.

**Comment by verlok** [comment]
Hey @gerdneuman,
I'm closing this, this issue should be fixed now on version 10.11.0.
Feel free to re-open it if you still notice the problem.

**Comment by gerdneuman** [comment]
@verlok Thanks ❤️ 

One question though: The test is `/glebot/.test(navigator.userAgent)` as far as I see in 
https://github.com/verlok/lazyload/blob/010dbf7248f77f0388ee4f0a664c55696861a36e/src/lazyload.environment.js#L2

However, this will only match Google Bot, but not other bots like the Bing Bot (hence the title of this bug): See https://www.bing.com/webmaster/help/which-crawlers-does-bing-use-8c184ec0 for the bingbot user agents.

As said Bing has by far not the same market share like Google, but still a few million users. Also in other regions other search engines are also popular (e.g. Yandex in Russia).

PS https://www.keycdn.com/blog/web-crawlers/ has a pretty good guide on the most common bots (Yandex, Yahoo, DuckDuckGo), all these sites also have documentation on their crawlers user agent.

Would be nice if these could be added so it works for all of them and not only Googlebot.

**Comment by verlok** [comment]
Ok I’ll take a look into that.

**Comment by verlok** [comment]
Just released versions 10.12.0 and 8.12.0 with the fix. See [changelog](CHANGELOG.md).
