### ISSUE TITLE
Images are not shown outside the viewport / ios / v8.8.0

### ISSUE THREAD

**Issue by dijkermans** [verlok/lazyload#216]
Hi, images are not shown outside the viewport with iphone using v8.8.0. 

**It works fine with v10.7.0**

I'm using it for background images.

`<div class="ww"><a class="xx lazy" href="yy" data-src="zz"></a></div>`

iphone 5s / iOS 11.4

Regards, Jeroen

**Comment by verlok** [comment]
Hi @dijkermans,
thank you for reporting this, but I’m afraid I don’t understand why would the images be shown outside the viewport, given that the viewport is the only visible portion of the page. 
Could you please explain?
Thanks

**Comment by dijkermans** [comment]
Hi,

In mean "below the fold". So when I visit the page I see images, but when I'm scrolling I don't see the "new" images. It's a blank gap.

Regards.

**Comment by verlok** [comment]
Thanks for the clarification.
Did the problem come with v. 8.8.0 or was it present also in 8.7.1?

**Comment by verlok** [comment]
Hey @dijkermans,
I've created [this test](https://codepen.io/verlok/pen/WyyzwJ) on Codepen, which uses background images and runs on LazyLoad v.8.8.0.
I tested it both on my Mac and on iOS 11.4 on my iPhone 5s, and I didn't found any issues.
Please post your HTML, CSS and JS code here if you need any more help.
