### ISSUE TITLE
NPM out of date

### ISSUE THREAD

**Issue by jdconley** [verlok/lazyload#218]
Can you update NPM with the latest 8.x and 10.x versions? Looks like it is quite out of date.

**Comment by rmngrc** [comment]
👍

**Comment by tmsf** [comment]
👍

**Comment by verlok** [comment]
You’re right guys, I forgot to `npm publish` a couple of times. Will do as soon as I come back from holidays.

**Comment by jdconley** [comment]
Thanks! Using the git url pointing to a release tag in my package.json just feels wrong. 👍

**Comment by verlok** [comment]
Done!
