### ISSUE TITLE
Video and iframe (others maybe) don't lazyload, need to create a new instance with a added class

### ISSUE THREAD

**Issue by giventofly** [verlok/lazyload#219]
Tested on chrome and firefox (latest versions).

i have img, video and iframe with data-src.
latest version of lazyloadjs.

after dom is loaded:
```
//lazyload
var myLazyLoad = new LazyLoad();
//videos and iframe
var myLazyLoad2 = new LazyLoad({
  elements_selector: ".lazy"
});
```
all images load fine but for videos and iframe i need to add the class .lazy and create a instance catching the .lazy class, otherwise then won't load.

images work if i add the lazy class. but would expect it would work without the class added.

**Comment by verlok** [comment]
That is the expected behavior since the default value for the `elements_selector` is `img` as you can read in the API section of the documentation (readme file). 

You can have a single LazyLoad instance passing `.lazy` as value and using the `lazy` class on the images too.

**Comment by giventofly** [comment]
i understood that later, i keep the impression that it would parse all the data-src, and change accordingly to the element wrapper.

But you are right, using the class is the better option. thanks for the feedback.
