### ISSUE TITLE
callback_load not called for background-images

### ISSUE THREAD

**Issue by crtl** [verlok/lazyload#221]
Hello,
I am using the versions 8.8.0/10.9.0 and it took me a while since Ive noticed that the `callback_load` is not called for background-images. Also `class_loaded` is not added.

I dont know if this is a feature or a bug but this should be noted in the documentation.

I am now using the following code:

```js
window.lazyLoader = new LazyLoad({
    elements_selector: ".lazyload",
    class_loading: "lazyload-loading",
    class_loaded: "lazyloaded",
    callback_set: function(element) {
        var $p = $(element).parents(".lazyload-parent");

        if ($p.length) {
            //class_loaded was not added automatically for backgroundImage
            element.classList.add("lazyloaded");
            $p.addClass("lazyloaded-parent");
        }
    },
});
```

My markup is:

```html
<div class="lazyload-parent">
  <a href="...">
    <div class="lazyload" data-src="http://example.tld/image.png"></div>
   </a>
</div>
```

**Comment by verlok** [comment]
Hello. This has been reported by others but it’s not a bug. 

You can find your answer reading on the closed issues reporting the same problem.

**Comment by verlok** [comment]
Hey @crtl,
things changed on version 15. 

I found a way to manage background images's load/error event, so now background images are now getting the `loaded` or `error` class and calling `callback_loaded` and `callback_error`, but multiple background images should now be loaded via the `data-bg-multi` attribute.

Take a look at the [changelog](https://github.com/verlok/lazyload/blob/master/CHANGELOG.md) and to the [upgrading guide](https://github.com/verlok/lazyload/blob/master/UPGRADE.md) if you're interested.

Have a nice day.
