### ISSUE TITLE
All images loaded on page load with version 10.11

### ISSUE THREAD

**Issue by Tabrisrp** [verlok/lazyload#225]
On the latest version 10.11, all images are loaded directly on page load instead of being lazyloaded as you scroll down.

I tested on Chrome and Firefox, all with the same behaviour.

I did the tests using the demos provided in this repository directly, and also on my local WordPress installation where I'm including the script using the conditionally load method.

The version 8.11 works correctly, loading the images sequentially during scroll.

**Comment by verlok** [comment]
Thanks @Tabrisrp,
I must have been very tired when releasing that version.

I'm already on it.

**Comment by verlok** [comment]
Solved this. 

The boolean condition assigned to `isBot` was completely reversed. I must have pressed a keyboard combo in VS Code which inverted the condition, then I didn't double check before releasing it.

Thanks again for letting me know.
