### ISSUE TITLE
Uncaught ReferenceError: LazyLoad is not defined

### ISSUE THREAD

**Issue by ankurdhamija83** [verlok/lazyload#226]
Are you reporting a bug or requesting a feature?

If it's a bug, it would be very useful to me if you answered the following questions.
Your answers will help me understand what's happening and enable me to reproduce the bug.

* What is happening? - I am getting an error in the browser console - "Uncaught ReferenceError: LazyLoad is not defined"
* What is the expected behaviour? - I guess, this error should not occur.
* Which version of LazyLoad are you using? - Using the following setup code from the website

```html
	<script type="text/javascript">
		(function(w, d){
		var b = d.getElementsByTagName('body')[0];
		var s = d.createElement("script"); 
		// s.async = true;
		var v = !("IntersectionObserver" in w) ? "8.12.0" : "10.12.0";
		s.src = "https://cdnjs.cloudflare.com/ajax/libs/vanilla-lazyload/" + v + "/lazyload.min.js";
		w.lazyLoadOptions = {}; // Your options here. See "recipes" for more information about async.
		b.appendChild(s);
		}(window, document));
	</script>

<script type="text/javascript">
			var myLazyLoad = new LazyLoad({
	    		elements_selector: ".lazy"
			});
	</script>
```

* In which browser(s) and browser version(s) are you experiencing the problem? - Chrome
* Could you provide the HTML, CSS and JS code you use for your images? - `<img width="300" height="300" alt="Best phones under 15000 price in India" title="Best seller phones under 15000 price in India" class="lazy" data-src="https://res.cloudinary.com/hello-vinci/image/upload/v1533011927/15-min.png">`
* What are the steps to reproduce the problem?

Thank you.

Surprisingly, the image loads correctly but I get the above mentioned error in the browser console.

Regards,
Ankur

**Comment by verlok** [comment]
Hi Ankur,
you are mixing the asynchronous loading and execution of LazyLoad and the synchronous one. 
You can remove your `new LazyLoad()` and pass the option literal object where you see the comment “your options here”.

**Comment by ankurdhamija83** [comment]
Thanks a lot Andrea!!
Lazyload.js is one of the best lazy loading JS library I have used.

**Comment by verlok** [comment]
We open source developers? All we need is love!
Thank you
