### ISSUE TITLE
Webp support

### ISSUE THREAD

**Issue by jakubkaderavek** [verlok/lazyload#227]
Hi,
works this script with webp format - is there a check, when I have two sources webp and jpeg, then script select right format depend on browser support?
Thanks you

**Comment by massic80** [comment]
I don't get the point: shouldn't the browser choose the `type` of the `source` element, regardless to the script being used? https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture#The_media_attribute

**Comment by verlok** [comment]
Ciao @massic80,
yes you’re right, if you use the `picture` element. But using it implies having a lot more code than using the `img` element.

**Comment by jakubkaderavek** [comment]
@verlok I think, that there is a next solution with srcset - first source as webp (if is supported) a second in jpg - srcset="small_600.webp 600w, small_600.jpg 600w,  medium_1024.webp 1024w,  medium_1024.jpg 1024w" what do you thing?

**Comment by verlok** [comment]
I think it’s too verbose markup. 
You could just specify the jpg source and LazyLoad could change it to Webb if supported.

**Comment by jakubkaderavek** [comment]
@verlok maybe, but what in case if some images not have webp format - only jpg. I think we can use attr data-format="webp" or something like this, what do you thing?

**Comment by verlok** [comment]
Guys, 
**you don’t need to put the `lazy` class on `source` tags. It’s bad for performance. Source tags inside the picture tags are already managed by the lazy image inside it.

**Comment by verlok** [comment]
> maybe, but what in case if some images not have webp format - only jpg

@jakubkaderavek you’re right, even if I think that most people use a service like Cloudinary to convert images to webp so it should be on every image. 

Well you could use a class “has-webp” on the images that have the webp alternative, then you can:

```js
var lazyLoadForWebp = new LazyLoad({
    elements_selector = "img.has-webp",
    switch_to_webp = true
});

var lazyLoadRegUlar = new LazyLoad({
    elements_selector = "img"
})
```

**Comment by verlok** [comment]
@jakubkaderavek you have it in version 10.14 released today. You also have 2 brand new demos, `webp_all` and `webp_some`. The latter is the one that covers your case, I guess. 

Coming soon in version 8.14 too. :)

**Comment by shoesforindustry** [comment]
As an aside: When we did some test compressing with mozjpeg at q60 (just about good enough for us), which produces ordinary jpgs, they were sometimes smaller or within a few bytes of webp, so we went with that. Maybe worth investigating?

**Comment by verlok** [comment]
Thanks @shoesforindustry for pointing that out.

I've been working for at least 3 years with images and image resizing, both on premise (in-house made algorithms) and with cloud-based SAAS such as [Cloudinary](https://cloudinary.com), Akamai Image Manager (//https://www.akamai.com/uk/en/products/web-performance/image-manager.jsp) and others. 

From my experience I can tell you that the quality and the weight of the images depends very much on the image content, other than the algorithms and the settings. 

To do the comparison, I created a tool to left-right compare the images, and to switch their positions so you can focus on a particular detail without moving your eye. Me and our photography team used this tool to test the image quality.

It's very important to take quality into consideration if you're doing e-commerce or working with high-end clients. We found that webp might have some quality issues at medium-high quality levels in very specific cases, noticeable only with particular screens (that regular users don't own so they wouldn't ever notice), so we've stopped automatic webp conversion on some of the websites we manage, on the client request. 

Considered that, I think that for most cases WebP is very good and efficient, but everyone should consider it and test it on a mixed set of their own images.

**Comment by jakubkaderavek** [comment]
@verlok thanks a lot, i thing, tak this is great solution :-)

**Comment by verlok** [comment]
You're [welcome](http://paypal.me/verlok) 😇

**Comment by verlok** [comment]
All done in versions 8.14 and 10.14.
