### ISSUE TITLE
Failed parsing 'srcset' attribute value since it has an unknown descriptor.

### ISSUE THREAD

**Issue by elliottmangham** [verlok/lazyload#229]
Are you reporting a bug or requesting a feature?
Bug.

* What is happening?
I am getting many console errors, reading:
- Failed parsing 'srcset' attribute value since it has an unknown descriptor. (lazyload.js:91)
- Dropped srcset candidate "<URL>" (lazyload.js:91)

<img width="995" alt="screen shot 2018-08-04 at 06 26 43" src="https://user-images.githubusercontent.com/12933804/43676779-8716fbe0-97ef-11e8-8b5d-978efd6c5b17.png">

Note the functionality is working fine, but the console is causing problems with code audits.

* What is the expected behaviour?
No console errors.

* Which version of LazyLoad are you using?
[Version 10.13 ](https://github.com/verlok/lazyload/tree/10.13.0).

* In which browser(s) and browser version(s) are you experiencing the problem?
Just seems to be Chrome. I am using version 67.0.3396.99 (Official Build). I had a quick look on Safari and Firefox and didn't notice any errors.

* Could you provide the HTML, CSS and JS code you use for your images?

**Standard format:**
```
<img class="lazy-img" data-src="..." alt="...">
```

**WebP format:** (which doesn't actually work)
```
<picture>
        <source class="lazy-img" data-srcset="..." type="image/webp" alt="..." />
        <img class="lazy-img" data-src="..." alt="..." />
</picture>
```

**CSS Code:**
```
img.lazy-img {
        display: block;
	border: 0;
	opacity: 0;

	&:not(.initial) {
		transition: opacity 1s cubic-bezier(.7,0,.3,1) .45s;
	}

	&.initial,
	&.loaded,
	&.error {
		opacity: 1;
	}

	&:not([src]) {
		visibility: hidden;
	}
}

.lazy-img:not(img) {
	opacity: 0;
	transition: opacity 1s cubic-bezier(.7,0,.3,1) .45s;

	&[data-was-processed="true"] {
		opacity: 1;
	}
}
```

**JS Code:**
```
var myLazyLoad = new LazyLoad({
        elements_selector: ".lazy-img"
});
```

* What are the steps to reproduce the problem?
No specific steps. I am also running jQuery@3.3.1, Owl Carousel@2.2.1, Google Maps, Particles.js@2.2.2 & Cookie Consent. Though I doubt any of these are conflicting.

If you message me on Twitter (@elliottmangham) I can share with you a demo link.

Thank you. Help is very much appreciated!

**Comment by verlok** [comment]
Try without the lazy-img class on the source tags. If it doesn’t solve, please share a link to the website or a Codepen so I can take a look

**Comment by verlok** [comment]
Hey @elliottmangham,
I just copy-pasted your code in a new codepen, and:

- I don't get any console error
- It works, and it loads the webp version on Chrome and Opera

https://codepen.io/verlok/pen/VBBqjq

Please tell me if I can be of any other help.

**Comment by elliottmangham** [comment]
Hi @verlok, thank you. I have shared a demo link with you via email.

I will go through my site and remove the lazy class from `source` tags as you recommend.

**Comment by elliottmangham** [comment]
@verlok I've found it is related to `data-srcset`.

Still investigating but I noticed my CMS was outputting the same values for srcset 1x and 2x, which might be tripping lazyload up.

```
<img
class="image lazy-img"
data-src="..."
data-srcset="... 1x, ... 2x"
alt="">
```

**Comment by verlok** [comment]
@elliottmangham what LazyLoad does is to simply copy the value of `data-srcset` into `srcset`, and `data-src` into `src`. LazyLoad doesn't parse or elaborate the values of the attributes, so if your CMS writes it wrong it cannot trip lazyload up, it can just produce wrong HTML.

**Comment by verlok** [comment]
PS: It seems you are serving the exact same image both to retina displays and non retina displays. The image descripted by `2x` should be twice the height and twice the width of the `1x`. If you can't have two dimensions, just take away the `srcset` and leave the `src`.

**Comment by verlok** [comment]
You're [welcome](https://www.paypal.me/verlok)! 😄

**Comment by DimaGashko** [comment]
I hope it can help someone. This is wrong srcset too (two spaces)
`.../images (1)_mid_x3_1080X810.jpeg 1080w`
(Of course, you may use function encodeURIComponent)
