### ISSUE TITLE
the 8.13.0 version will report a error

### ISSUE THREAD

**Issue by fakership** [verlok/lazyload#230]
![image](https://user-images.githubusercontent.com/16553183/43714306-1efd5dda-99af-11e8-84b6-334cca718a20.png)

It seems that the export object is not a function

**Comment by fakership** [comment]
when i take it back to 8.7.0, it will work!

**Comment by verlok** [comment]
Hey guys, thank you for reporting this.
I'm afraid I need more information to help you. 
Please tell me how you include LazyLoad (`npm install`? CDN script?) and how you use it. 
Show me the code and I will be able to understand what happens.

**Comment by fakership** [comment]
I include LazyLoad by (npm install):
import Lazyload from 'vanilla-lazyload';

**This is the usage:**
new LayLoad({})

the lazyload.min.js will report a error;

**Comment by verlok** [comment]
Hey @fakership,
thanks for reporting it. I'll definitely check and get back to you.

**Comment by verlok** [comment]
Hey @fakership,

I've created [this GitHub test repo](https://github.com/verlok/lazyload-es2015-test) in which I call LazyLoad as an ES2015 module, and everything works as expected.

So I think the problem might be related to something else you are using to bundle or minify your code.

What are you using? WebPack 4? Rollup.js? Babel is included in the mix?

Please share more information so I can investigate more.
Thanks

**Comment by verlok** [comment]
I was able to reproduce the bug using WebPack to bundle LazyLoad in this test repo.
https://github.com/verlok/lazyload-es2015-webpack-test
Now I'm going to fix it. I'm sure it's just a matter of webpack configuration.

**Comment by fakership** [comment]
yes, I bundle LazyLoad by webpack4.

**Comment by verlok** [comment]
I found the issue. It was a mistake in my package.json

**Comment by verlok** [comment]
Just released 8.15.0 and 10.15.0 on npm.
The issue should be fixed now. Let me know!

**Comment by verlok** [comment]
I've tested it in [this repo](https://github.com/verlok/lazyload-es2015-webpack-test) and checked that now it works correctly.

Thank you @fakership and @massic80 and @l3aconator for reporting your issues!
