### ISSUE TITLE
lazyload.es.js is missing

### ISSUE THREAD

**Issue by gaetan-puleo** [verlok/lazyload#231]
The `lazyload.es.js` file is not present in `node_modules/vanilla-lazyload/dist/`.

I use the 8.13.0 version .

The workaround is to load the `lazyload.es2015.js` until a fix is published.

**Comment by verlok** [comment]
Hey @gaetan-puleo, thank you for pointing that out.

You're totally right, I changed my mind during the publication process so the documentation wasn't updated.

This is the correct table of filenames and versions, which I fixed also in the changelog and in the release notes on GitHub. 

| Filename               | Module Type                                    | Advantages                                                         |
| ---------------------- | ---------------------------------------------- | ------------------------------------------------------------------ |
| `lazyload.min.js`      | UMD (Universal Module Definition)              | Works pretty much everywhere, even in common-js contexts           |
| `lazyload.iife.min.js` | IIFE (Immediately Invoked Function Expression) | Works as in-page `<script src="">`, ~0.5kb smaller minified        |
| `lazyload.amd.min.js`  | AMD (Asynchronous Module Definition)           | Works with the *require.js* module loader, ~0.5kb smaller minified |
| `lazyload.es2015.js`   | ES Module type                                 | Exports `LazyLoad` so you can import it in your project            |
