### ISSUE TITLE
How do I use this in Angular 6?

### ISSUE THREAD

**Issue by bezysoftware** [verlok/lazyload#234]
I tried to use the sample for Iframes, paste that code in my component.ts, but it doesn't seem to work, nothing gets loaded

**Comment by verlok** [comment]
Hi @bezysoftware,
Thank you for asking. 

In my opinion didn’t provide enough  information to help us help you. 

Can you report a portion of your html and JS code so the community can understand and help?

Thanks

**Comment by verlok** [comment]
I consider this solved since you didn’t reply in the latest months. Feel free to reopen if you still need help.
