### ISSUE TITLE
Class "loaded" not applied to a loaded video

### ISSUE THREAD

**Issue by maeligg** [verlok/lazyload#239]
Hello,

I am using V10.15.0 of lazyload, testing on the latest version of Chrome.
Lazy loading a `<video>` seems to work fine except that the "loaded" class is never applied to it ("loading" is correctly applied).
Before entering the viewport : 
`
<video width="100%" autoplay="" loop="" muted="" data-src="my-video" class="js-lazyload"</video>
`
After entering the viewport : 
`
<video width="100%" autoplay="" loop="" muted="" data-src="assets/my-video.mp4" class="js-lazyload loading" src="my-video.mp4" data-was-processed="true"></video>
`

**Comment by verlok** [comment]
Need to listen to the [`loadeddata` event](https://www.w3schools.com/tags/av_event_loadeddata.asp).

**Comment by verlok** [comment]
Note to self: possibly add `audio` to the lazy-loadable HTML elements.

**Comment by verlok** [comment]
Must release the fix on version 8.x too.

**Comment by verlok** [comment]
Solved in both versions 8.15.2 and 10.16.2
