### ISSUE TITLE
Autoplaying video not loaded correctly after entering the viewport

### ISSUE THREAD

**Issue by maeligg** [verlok/lazyload#240]
Hello,

Testing on V10.15.0 + Chrome latest.
I think this is a separate issue from https://github.com/verlok/lazyload/issues/239 so I'm opening a new one. It looks like when you are using 'data-src' on `<source>` instead of `<video>`, the autoplayed video is not loaded correctly. Looking at https://developers.google.com/web/fundamentals/performance/lazy-loading-guidance/images-and-video/#for_video_acting_as_an_animated_gif_replacement it seems that you need to manually call the element's load() method after updating the src.

**Comment by verlok** [comment]
Fixed in v.10, not yet in v.8

**Comment by verlok** [comment]
Fixed in v.8 too
