### ISSUE TITLE
lazyload the inline style="background-image:url('file.jpg')"

### ISSUE THREAD

**Issue by Uniquesquare** [verlok/lazyload#243]
Dear,

I was wondering if the plugin can lazyload the inline background images added directly to the html markup (style="background-image:url('file.jpg')")!

I am using a bespoke platform that I can not change the HTML markup and BFG image is added as an inline style tag!

Thank @verlok

**Comment by verlok** [comment]
Sorry for the delay, I thought I answered 2 days ago but my message wasn't actually sent.
If you really can't change the HTML markup, there's nothing you can do.
