### ISSUE TITLE
Uncaught TypeError: Assignment to constant variable (Chrome)

### ISSUE THREAD

**Issue by Somethingideally** [verlok/lazyload#247]
Can`t build for production mode with 10.17 version (dev version is well), got error:
Uncaught TypeError: Assignment to constant variable.
Using Laravel mix with Webpack (Laravel mix using  "webpack": "^3.11.0")

**Comment by Somethingideally** [comment]
8.15 version is well in production and dev mode

**Comment by verlok** [comment]
Hi @somethingideally,
could you please copy and paste the error details so that I can know on which const it throws the error?
I’m on vacation now and I can’t check myself. 
Thanks in advance

**Comment by Somethingideally** [comment]
lazyload.es2015.js:238 Uncaught TypeError: Assignment to constant variable.
    at B (lazyload.es2015.js:238)
    at H (lazyload.es2015.js:307)
    at q (lazyload.es2015.js:275)
    at W._manageIntersection (lazyload.es2015.js:339)
    at Array.forEach (<anonymous>)
    at W._onIntersection (lazyload.es2015.js:351)

there are logs of error

**Comment by verlok** [comment]
Thank you. 
I’m afraid those logs won’t be of much help though, since it seems your code has been minified. 
Do you have the chance to execute unminified code and get the logs from there?

**Comment by verlok** [comment]
It looks like it’s webpack configuration fault. 

To avoid any, could you check if the error occurs also in this very simple repo which leverages webpack to bundle LazyLoad?
https://github.com/verlok/lazyload-es2015-webpack-test

Let me know what happens. 
Thanks

**Comment by verlok** [comment]
@Somethingideally could you answer my question? Thanks

**Comment by verlok** [comment]
I've just tried the es2015 version loaded as is in the browser, using [this repo](https://github.com/verlok/lazyload-es2015-test) which has LazyLoad 8.15.2 as a dependency, and it doesn't throw any errors.

So I really need your help @Somethingideally and @wuxiuran to know what goes wrong in your cases.

**Comment by verlok** [comment]
@wuxiuran, @Somethingideally, 

I've just check if the error occurs in the [repo which leverages webpack](https://github.com/verlok/lazyload-es2015-webpack-test) to bundle LazyLoad.

I've tried:
* LazyLoad version 8.15.2 build in *development* mode
* LazyLoad version 8.15.2 build in *production* mode
* LazyLoad version 10.18.0 build in *development* mode
* LazyLoad version 10.18.0 build in *production* mode

And I wasn't able to replicate the error.

Maybe you can find the solution to your specific problem in that repo?

* If not, I need your help to know what goes wrong in your cases.
* If yes, please share the solution here to others which might have the same problem.

Thanks

**Comment by grund3g** [comment]
I have the same error with the production build (v. 10.19.0):

<img width="492" alt="bildschirmfoto 2018-10-05 um 10 55 11" src="https://user-images.githubusercontent.com/6507335/46526008-5e218880-c88d-11e8-92ef-9d44601ace65.png">
<img width="771" alt="bildschirmfoto 2018-10-05 um 10 55 28" src="https://user-images.githubusercontent.com/6507335/46526015-624da600-c88d-11e8-9fab-f5d88ae5145c.png">

**Comment by adriandmitroca** [comment]
If that helps, this issue is not present on 10.4.2. I've just discovered it after making an upgrade.

**Comment by verlok** [comment]
I'm still waiting for an answer to this question I've asked before.

I've just checked if the error occurs in the [repo which leverages webpack](https://github.com/verlok/lazyload-es2015-webpack-test) to bundle LazyLoad.

I've tried the following:

* LazyLoad version 8.15.2 build in *development* mode
* LazyLoad version 8.15.2 build in *production* mode
* LazyLoad version 10.18.0 build in *development* mode
* LazyLoad version 10.18.0 build in *production* mode

But I wasn't able to reproduce the error.

**Why do you think that WebPack build works?**

Thanks

@adriandmitroca, @grund3g, @wuxiuran, @Somethingideally

**Comment by verlok** [comment]
Also could you post the version of WebPack and Babel you're using, and your babel and webpack configuration file? Thanks

@adriandmitroca, @grund3g, @wuxiuran, @Somethingideally

**Comment by nowyTR** [comment]
Same problem here:
-  vanilla-lazyload@10.19.0
- "webpack": "3.10.0",
- "babel-loader": "8.0.0-beta.0",
- "@babel/core": "7.0.0-beta.34"

ugflifyjs config:
`new UglifyJsPlugin({
      parallel: 4,
      sourceMap: true,
      uglifyOptions: {
        ie8: false,
        safari10: true,
        compress: {
          drop_console: false
        }
      }
    }),`

**Comment by verlok** [comment]
The problem seems to reside inside UglifyJS in my opinion, given that with WebPack 4 everything works fine (see [this repo](https://github.com/verlok/lazyload-es2015-webpack-test)). 

Anyone is having the same problem on WebPack 4?

**Comment by cympak01** [comment]
Adding those lines resolved my issue:

mix.options({
    uglify: {
        uglifyOptions: {
            compress: { inline: false }
        }
    }
});
