### ISSUE TITLE
Multiple Background Images for a Single Element

### ISSUE THREAD

**Issue by vigoren** [verlok/lazyload#249]
Is there a way to support the lazy loading of multiple background images for a single element. 
EG: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Backgrounds_and_Borders/Using_multiple_backgrounds

Not critical but wondering if it is possible or too compicated

**Comment by verlok** [comment]
Hi @vigoren,
thank you for your kind request. 

That wouldn’t be possible at the moment. 
What would you need this feature for?

**Comment by verlok** [comment]
Yeah this is interesting. 
The `data-srcdet` attribute is currently unused for background images, maybe we can do something with it. Let me think.

**Comment by verlok** [comment]
What do you think about this solution:

- You put whatever you’d put in the `background-image` CSS property inside the `data-srcset` HTML attribute, like this: 

```html
<div class=“lazyBg” data-srcset="url(https://images.com/bg1), url(https://images.com/bg2), url(https://images.com/bg3)">
```

The script then copies whatever it finds in the `data-srcset` inside the element’s `style` using `background-Image`.

It’s different from what the `data-src` does. The script doesn’t just copy the  `data-src`  content to the style background, it also wraps the image url inside a `url()` CSS directive. The `data-srcset` would be copied as is. 

I like it because:

- The script wouldn’t have to parse the `data-srcset`
- You could also use a gradient background image together with the real images
- We would use a pre-existing option

I don’t like it because

- You would have to put CSS code in the HTML attribute which should be mapped to the `srcset` attribute. Not this mapping wouldn’t be strict anymore. 

Probably this “dislike“ could be solved creating a new `data-bg` option.

**Comment by vigoren** [comment]
That sounds like a good solution to me. I share your dislike with putting CSS in the attribute but like you said could be solved with a custom attribute.  Though that does take away the like of using a pre existing option. 

I think to start using data-srcset would be great. Then can always look at transitioning to a different attribute later. 

Thanks again

**Comment by verlok** [comment]
Actually it can’t. When the users start to use it, you can’t change the API without changing the version by a major. 

It’s better to start directly using `data-bg`. It’s no big deal to have a new option. 

Thank you for your reply and your issue. 
I’m vacationing now, as soon as I get my hands on a computer again, I’ll develop it. 
Or if you prefer, you can fork and pull request this :)

**Comment by verlok** [comment]
In case you want to fork and PR, you just need to edit the files:

- `lazyload.defaults.js` to add the new `data_bg` option,
- `lazyload.setSources.js` limited to the `setSourcesBg` function. 

Once you’re done, you can build the minified files using `gulp` and test it using the files in the `demos` folder.  

When everything is working, open a Pull Request towards the `development` branch. 

Thanks!

**Comment by vigoren** [comment]
Sounds good, I have something put together just need to test it a bit more then I will make the pull request.

**Comment by verlok** [comment]
Great! Thank you very much

**Comment by ligne13** [comment]
Hey guys,  

I'm also interested in this new feature !
Hope you will find something soon.

Good work !

**Comment by salespageshark** [comment]
Looking forward for this feature also! LazyLoad is great! :)

**Comment by verlok** [comment]
Thank you very much.
The feature is in under the final checks in the `development` branch, waiting to be released!

**Comment by verlok** [comment]
Now released also in version 8.16.0.
Closing this.

**Comment by verlok** [comment]
Hey @vigoren,
things changed on version 15. 

I found a way to manage background images's load/error event, so now background images are now getting the `loaded` or `error` class and calling `callback_loaded` and `callback_error`, but multiple background images should now be loaded via the `data-bg-multi` attribute.

Take a look at the [changelog](https://github.com/verlok/lazyload/blob/master/CHANGELOG.md) and to the [upgrading guide](https://github.com/verlok/lazyload/blob/master/UPGRADE.md) if you're interested.

Have a nice day.

**Comment by KirstyMarks-Roar** [comment]
> Hey @vigoren,
> things changed on version 15.
> 
> I found a way to manage background images's load/error event, so now background images are now getting the `loaded` or `error` class and calling `callback_loaded` and `callback_error`, but multiple background images should now be loaded via the `data-bg-multi` attribute.
> 
> Take a look at the [changelog](https://github.com/verlok/lazyload/blob/master/CHANGELOG.md) and to the [upgrading guide](https://github.com/verlok/lazyload/blob/master/UPGRADE.md) if you're interested.
> 
> Have a nice day.

HI Verlok, I have tried using multi background, and it isnt working. I have passed the following to the div.
`<div class="lazy background" data-bg-multi="url({{view url='/images/test/testbackground.png'}}), linear-gradient(#fff, #ccc)">`

Advice is appreciated.

**Comment by verlok** [comment]
Hey @KirstyMarks-Roar ,

could you post the rendered `div` with the final `data-bg-multi` attribute?
And the JS code you used to initialize LazyLoad?

Also please check the related [demo](https://www.andreaverlicchi.eu/lazyload/demos/background_images_multi.html) and the related [code](https://github.com/verlok/lazyload/blob/master/demos/background_images_multi.html).

**Comment by verlok** [comment]
PS: This is a closed issue, if you still need support please open a new one as a question. Thanks

**Comment by KirstyMarks-Roar** [comment]
> PS: This is a closed issue, if you still need support please open a new one as a question. Thanks

Hi, apologies. I thought it was open as i could reply to it, and it was relevant to the question :) I managed to get it working with the data-bg option instead. However should you still need me to, Im happy to open a new Question. 

Thanks
Kirsty

**Comment by verlok** [comment]
@KirstyMarks-Roar you mean you used `data-bg` instead of `data-bg-multi`?

**Comment by KirstyMarks-Roar** [comment]
> @KirstyMarks-Roar you mean you used `data-bg` instead of `data-bg-multi`?

Hi Verlok, yes. When I used the `data-bg-multi` option, it didnt seem to pick up multiple backgrounds (I am passing an image, and a gradient). However when I used `data-bg` and passed the background image and linear gradient, it seemed to render :)

**Comment by verlok** [comment]
Wait, which version of the script you're using?
I totally forgot to ask.

**Comment by verlok** [comment]
The documentation you can find here on GitHub are valid only for the latest version.

**Comment by verlok** [comment]
@KirstyMarks-Roar , in addition, note that the `data-bg` option will cease working if you update the version of lazyload to a newer one. In the latest version, `data-bg-multi` should be used to set multiple backgrounds.
