### ISSUE TITLE
Does not work when container was hidden

### ISSUE THREAD

**Issue by magglomag** [verlok/lazyload#25]
Hi,

Many thanks for the great plugin.

I ran into the issue when using it in a container which is by default hidden with `aria-hidden="true"` and gets visible on click (it’s an overlay) the images are not getting loaded. If I remove the `aria-hidden="true"` it works just fine.

**Comment by magglomag** [comment]
Ah, I think I solved it by calling the function again when clicking on the link that changes the `aria-hidden` attribute from `true` to `false`.

**Comment by verlok** [comment]
Great! I knew you could sort it out yourself! :)
