### ISSUE TITLE
I use react demo,  page search function, show page images data-src and data-srcset will not the same

### ISSUE THREAD

**Issue by zhilianghuang** [verlok/lazyload#253]
![image](https://user-images.githubusercontent.com/17289763/45746737-85921780-bc36-11e8-9fa9-c6a89136c713.png)

**Comment by verlok** [comment]
Interesting issue. I think this might be a browser bug. On what browsers are you getting this issue?

**Comment by verlok** [comment]
Also, @zhilianghuang if you could please copy-paste some JSX code or HTML code here, I could do some tests around your HTML. Unfortunately I'm not able to type those characters. Thanks

**Comment by zhilianghuang** [comment]
I have solved it. reactjs render data list , Use the key to use the duplicate question. 
Solution：
I take the loop key and get the data back to the primary key. 
Thanks
