### ISSUE TITLE
Don't work for picture images 

### ISSUE THREAD

**Issue by weslley-campos** [verlok/lazyload#254]
Are you reporting a bug or requesting a feature? bug

* What is happening? 

Hi, I just found a problem in demonstrating the example of responsive images, when I add the .lazy class to the first images, it simply loads all, does not expect to scroll the page to load the images.

* Which version of LazyLoad are you using? lasted
* In which browser(s) and browser version(s) are you experiencing the problem? chrome
* Could you provide the HTML, CSS and JS code you use for your images? no
* What are the steps to reproduce the problem? Describe before.

Thank you.

`<!DOCTYPE html>
<html>

<head lang="en">
	<meta charset="UTF-8">
	<title>
		Lazyload tests
	</title>
	<style>
		/* img:not([src]):not([srcset]) {
			visibility: hidden;
		} */
	</style>
</head>

<body>
	<div id="results1" class="results">
		<ul>
			<li>

**### //this is the problem. Add lazy class for firts images.**

				<picture> 
					<source media="(min-width: 1024px)" srcset="https://placehold.it/220x280?text=01_220w 1x, https://placehold.it/440x560?text=01_440w 2x"
					/>
					<source media="(min-width: 500px)" srcset="https://placehold.it/330x420?text=01_330w 1x, https://placehold.it/660x840?text=01_660w 2x"
					/>
					<img alt="Stivaletti" class="lazy" src="https://placehold.it/220x280?text=01_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" srcset="https://placehold.it/220x280?text=02_220w 1x, https://placehold.it/440x560?text=02_440w 2x"
					/>
					<source media="(min-width: 500px)" srcset="https://placehold.it/330x420?text=02_330w 1x, https://placehold.it/660x840?text=02_660w 2x"
					/>
					<img alt="Open toe" class="lazy" src="https://placehold.it/220x280?text=02_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" srcset="https://placehold.it/220x280?text=03_220w 1x, https://placehold.it/440x560?text=03_440w 2x"
					/>
					<source media="(min-width: 500px)" srcset="https://placehold.it/330x420?text=03_330w 1x, https://placehold.it/660x840?text=03_660w 2x"
					/>
					<img alt="Sneakers class="lazy" &amp; Tennis" src="https://placehold.it/220x280?text=03_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" srcset="https://placehold.it/220x280?text=04_220w 1x, https://placehold.it/440x560?text=04_440w 2x"
					/>
					<source media="(min-width: 500px)" srcset="https://placehold.it/330x420?text=04_330w 1x, https://placehold.it/660x840?text=04_660w 2x"
					/>
					<img class="lazy" alt="Sneakers &amp; Tennis shoes basse" src="https://placehold.it/220x280?text=04_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=05_220w 1x, https://placehold.it/440x560?text=05_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=05_330w 1x, https://placehold.it/660x840?text=05_660w 2x"
					/>
					<img class="lazy" alt="Sneakers &amp; Tennis shoes alte" data-src="https://placehold.it/220x280?text=05_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=06_220w 1x, https://placehold.it/440x560?text=06_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=06_330w 1x, https://placehold.it/660x840?text=06_660w 2x"
					/>
					<img class="lazy" alt="Sneakers &amp; Tennis shoes alte" data-src="https://placehold.it/220x280?text=06_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=07_220w 1x, https://placehold.it/440x560?text=07_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=07_330w 1x, https://placehold.it/660x840?text=07_660w 2x"
					/>
					<img class="lazy" alt="Sneakers &amp; Tennis shoes basse" data-src="https://placehold.it/220x280?text=07_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=08_220w 1x, https://placehold.it/440x560?text=08_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=08_330w 1x, https://placehold.it/660x840?text=08_660w 2x"
					/>
					<img class="lazy" alt="Sneakers &amp; Tennis shoes basse" data-src="https://placehold.it/220x280?text=08_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=09_220w 1x, https://placehold.it/440x560?text=09_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=09_330w 1x, https://placehold.it/660x840?text=09_660w 2x"
					/>
					<img class="lazy" alt="Stivali" data-src="https://placehold.it/220x280?text=09_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=10_220w 1x, https://placehold.it/440x560?text=10_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=10_330w 1x, https://placehold.it/660x840?text=10_660w 2x"
					/>
					<img class="lazy" alt="Stivali" data-src="https://placehold.it/220x280?text=10_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=11_220w 1x, https://placehold.it/440x560?text=11_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=11_330w 1x, https://placehold.it/660x840?text=11_660w 2x"
					/>
					<img class="lazy" alt="Stivaletti" data-src="https://placehold.it/220x280?text=11_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=12_220w 1x, https://placehold.it/440x560?text=12_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=12_330w 1x, https://placehold.it/660x840?text=12_660w 2x"
					/>
					<img class="lazy" alt="Stivaletti" data-src="https://placehold.it/220x280?text=12_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=13_220w 1x, https://placehold.it/440x560?text=13_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=13_330w 1x, https://placehold.it/660x840?text=13_660w 2x"
					/>
					<img class="lazy" alt="Stivali" data-src="https://placehold.it/220x280?text=13_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=14_220w 1x, https://placehold.it/440x560?text=14_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=14_330w 1x, https://placehold.it/660x840?text=14_660w 2x"
					/>
					<img class="lazy" alt="Stivaletti" data-src="https://placehold.it/220x280?text=14_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=15_220w 1x, https://placehold.it/440x560?text=15_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=15_330w 1x, https://placehold.it/660x840?text=15_660w 2x"
					/>
					<img class="lazy" alt="Décolleté" data-src="https://placehold.it/220x280?text=15_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=16_220w 1x, https://placehold.it/440x560?text=16_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=16_330w 1x, https://placehold.it/660x840?text=16_660w 2x"
					/>
					<img class="lazy" alt="Mocassini" data-src="https://placehold.it/220x280?text=16_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=17_220w 1x, https://placehold.it/440x560?text=17_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=17_330w 1x, https://placehold.it/660x840?text=17_660w 2x"
					/>
					<img class="lazy" alt="Stivaletti" data-src="https://placehold.it/220x280?text=17_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=18_220w 1x, https://placehold.it/440x560?text=18_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=18_330w 1x, https://placehold.it/660x840?text=18_660w 2x"
					/>
					<img class="lazy" alt="Décolleté" data-src="https://placehold.it/220x280?text=18_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=19_220w 1x, https://placehold.it/440x560?text=19_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=19_330w 1x, https://placehold.it/660x840?text=19_660w 2x"
					/>
					<img class="lazy" alt="Décolleté" data-src="https://placehold.it/220x280?text=19_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=20_220w 1x, https://placehold.it/440x560?text=20_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=20_330w 1x, https://placehold.it/660x840?text=20_660w 2x"
					/>
					<img class="lazy" alt="Francesine" data-src="https://placehold.it/220x280?text=20_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=21_220w 1x, https://placehold.it/440x560?text=21_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=21_330w 1x, https://placehold.it/660x840?text=21_660w 2x"
					/>
					<img class="lazy" alt="Stivaletti" data-src="https://placehold.it/220x280?text=21_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=22_220w 1x, https://placehold.it/440x560?text=22_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=22_330w 1x, https://placehold.it/660x840?text=22_660w 2x"
					/>
					<img class="lazy" alt="Décolleté" data-src="https://placehold.it/220x280?text=22_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=23_220w 1x, https://placehold.it/440x560?text=23_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=23_330w 1x, https://placehold.it/660x840?text=23_660w 2x"
					/>
					<img class="lazy" alt="Mocassini" data-src="https://placehold.it/220x280?text=23_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=24_220w 1x, https://placehold.it/440x560?text=24_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=24_330w 1x, https://placehold.it/660x840?text=24_660w 2x"
					/>
					<img class="lazy" alt="Mocassini" data-src="https://placehold.it/220x280?text=24_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=25_220w 1x, https://placehold.it/440x560?text=25_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=25_330w 1x, https://placehold.it/660x840?text=25_660w 2x"
					/>
					<img class="lazy" alt="Stivali" data-src="https://placehold.it/220x280?text=25_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=26_220w 1x, https://placehold.it/440x560?text=26_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=26_330w 1x, https://placehold.it/660x840?text=26_660w 2x"
					/>
					<img class="lazy" alt="Stivaletti" data-src="https://placehold.it/220x280?text=26_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=27_220w 1x, https://placehold.it/440x560?text=27_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=27_330w 1x, https://placehold.it/660x840?text=27_660w 2x"
					/>
					<img class="lazy" alt="Stivaletti" data-src="https://placehold.it/220x280?text=27_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=28_220w 1x, https://placehold.it/440x560?text=28_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=28_330w 1x, https://placehold.it/660x840?text=28_660w 2x"
					/>
					<img class="lazy" alt="Mocassini" data-src="https://placehold.it/220x280?text=28_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=29_220w 1x, https://placehold.it/440x560?text=29_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=29_330w 1x, https://placehold.it/660x840?text=29_660w 2x"
					/>
					<img class="lazy" alt="Stivaletti" data-src="https://placehold.it/220x280?text=29_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=30_220w 1x, https://placehold.it/440x560?text=30_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=30_330w 1x, https://placehold.it/660x840?text=30_660w 2x"
					/>
					<img class="lazy" alt="Stivaletti" data-src="https://placehold.it/220x280?text=30_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=31_220w 1x, https://placehold.it/440x560?text=31_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=31_330w 1x, https://placehold.it/660x840?text=31_660w 2x"
					/>
					<img class="lazy" alt="Stivaletti" data-src="https://placehold.it/220x280?text=31_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=32_220w 1x, https://placehold.it/440x560?text=32_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=32_330w 1x, https://placehold.it/660x840?text=32_660w 2x"
					/>
					<img class="lazy" alt="Stivaletti" data-src="https://placehold.it/220x280?text=32_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=33_220w 1x, https://placehold.it/440x560?text=33_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=33_330w 1x, https://placehold.it/660x840?text=33_660w 2x"
					/>
					<img class="lazy" alt="Cuissardes" data-src="https://placehold.it/220x280?text=33_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=34_220w 1x, https://placehold.it/440x560?text=34_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=34_330w 1x, https://placehold.it/660x840?text=34_660w 2x"
					/>
					<img class="lazy" alt="Décolleté" data-src="https://placehold.it/220x280?text=34_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=35_220w 1x, https://placehold.it/440x560?text=35_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=35_330w 1x, https://placehold.it/660x840?text=35_660w 2x"
					/>
					<img class="lazy" alt="Stivaletti" data-src="https://placehold.it/220x280?text=35_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=36_220w 1x, https://placehold.it/440x560?text=36_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=36_330w 1x, https://placehold.it/660x840?text=36_660w 2x"
					/>
					<img class="lazy" alt="Sneakers &amp; Tennis shoes basse" data-src="https://placehold.it/220x280?text=36_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=37_220w 1x, https://placehold.it/440x560?text=37_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=37_330w 1x, https://placehold.it/660x840?text=37_660w 2x"
					/>
					<img class="lazy" alt="Mocassini" data-src="https://placehold.it/220x280?text=37_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=38_220w 1x, https://placehold.it/440x560?text=38_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=38_330w 1x, https://placehold.it/660x840?text=38_660w 2x"
					/>
					<img class="lazy" alt="Sneakers &amp; Tennis shoes basse" data-src="https://placehold.it/220x280?text=38_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=39_220w 1x, https://placehold.it/440x560?text=39_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=39_330w 1x, https://placehold.it/660x840?text=39_660w 2x"
					/>
					<img class="lazy" alt="Mocassini" data-src="https://placehold.it/220x280?text=39_220w">
				</picture>
			</li>
			<li>
				<picture>
					<source media="(min-width: 1024px)" data-srcset="https://placehold.it/220x280?text=40_220w 1x, https://placehold.it/440x560?text=40_440w 2x"
					/>
					<source media="(min-width: 500px)" data-srcset="https://placehold.it/330x420?text=40_330w 1x, https://placehold.it/660x840?text=40_660w 2x"
					/>
					<img class="lazy" alt="Mocassini" data-src="https://placehold.it/220x280?text=40_220w">
				</picture>
			</li>
		</ul>
	</div>
	<script src="/lazyload/dist/lazyload.min.js"></script>
	<script>
		(function () {
			new LazyLoad({
				elements_selector: ".lazy"
			});
		}());
	</script>
</body>

</html>`

**Comment by verlok** [comment]
Hi @weslley-campos,
that might be because in the HTML code you posted, I didn't use the `data-src` nor `data-srcset` attributes in the first images.
This is not a bug, this is a feature. It's to make browsers load the first N images faster, see [this repo readme](https://github.com/verlok/productListingPageBestPractices) for more information.

**Comment by verlok** [comment]
I’m sorry, but I fail to understand what you’re trying to explain here. 
Could you please create a new pen on Codepen so I can see what the problem is?
Thanks

**Comment by verlok** [comment]
@weslley-campos ?

**Comment by weslley-campos** [comment]
![2018-09-24](https://user-images.githubusercontent.com/29134909/45967365-28b2aa80-c004-11e8-8434-458d887e2ad5.png)


using lazy in all elements happens this, all the images were downloaded, but there was no scrolling on the screen, I tried to simulate it on the code pen, however, I got it because I do not have this monitoring to see if the images were downloaded, it could be a browsing behavior or of the vscode extension I'm using.

https://codepen.io/weslley-campos/pen/rZgYJQ


however it is working on the site I am working on, I was only bothered by this behavior. Thanks for listening.

**Comment by verlok** [comment]
Hey @weslley-campos,
I can see the problem in your fiddle. 
You didn't put any CSS code to give your images or list items a `min-height`, so when you create the lazyload instance all the images are inside the viewport.
That's why they are all loaded simultaneously.
Read more about this in the documentation (README.md file), tips & tricks section, "occupy vertical space and maintain ratio" ([here](https://github.com/verlok/lazyload/#occupy-vertical-space-and-maintain-ratio))

**Comment by weslley-campos** [comment]
Thanks!
