### ISSUE TITLE
Free tickets for WebSummit Lisbon

### ISSUE THREAD

**Issue by verlok** [verlok/lazyload#255]
Hi all,
thanks to the **Open Source initiative**, to which I submitted this repo, I've won 2 tickets for [WebSummit](https://websummit.com) which is taking place in Lisbon on November 5-8, 2018.

Well, guess what? I just need one ticket (maybe 0, not sure if I'm going), and I thought it would be the best idea to share them with you followers and contributors!

If you are interested in getting the other ticket, please comment below.

All [contributors](https://github.com/verlok/lazyload/graphs/contributors) like @klarstrup, @g100g, @greenie, @Spone, @ricardobrandao, @ignatiusreza, @brunoscopelliti, @vigoren and others get the precedence over others, but if you're reading this, you can probably get one!

**Comment by ricardobrandao** [comment]
Wow, that's great! I hope you can come and enjoy the city! I'm interested in that second ticket and I'll happily buy you a big lunch :)

**Comment by klarstrup** [comment]
Cool initiative @verlok! I'm good tho

**Comment by verlok** [comment]
@ricardobrandao I get you're interested in the ticket! I need your name, surname and e-mail, the rest of the information can be inserted by yourself.

**Comment by G100g** [comment]
Unfortunately I can't! Thx @verlok

**Comment by ignatiusreza** [comment]
Wow! Thanks for the offer @verlok! Very nice of you, unfortunately I can't make the trip..

**Comment by verlok** [comment]
@ricardobrandao are you still interested?

**Comment by ricardobrandao** [comment]
Sorry for the late reply but I have been busy the last few days. I've sent you an email with my personal details. Once again, thank you for your offer!

**Comment by verlok** [comment]
@ricardobrandao I didn’t get your email though. Sure you’ve sent it to the correct email address? It’s name.surname@gmail.com

**Comment by juceliohv** [comment]
I am.
