### ISSUE TITLE
No alt atribute = no image in Firefox browser

### ISSUE THREAD

**Issue by bodanus7** [verlok/lazyload#256]
Hey,
I've got a strange issue.  
Lazyload works great if a picture has an alt attribute, but when it is empty script does not work - the picture is not visible. 
It happens only on Firefox.

This is my code snipet: 

```
<img
     data-src="{{url}}"
     data-srcset="{{srcset}}"
      data-sizes="{{sizes}}"
     height="{{height}}"
     width="{{width}}"
     alt="{{alt}}">
```

Thank you for any help.

**Comment by verlok** [comment]
So @bodanus7 if an image doesn't have an `alt` attribute, it doesn't load, not even lazily?

What happens in your code when the alt is empty? Does it render an empty `alt` attribute (`alt=""`) or the alt attribute is not rendered at all? Just asking because the `alt` attribute is required.

**Comment by bodanus7** [comment]
Thank you for your reply.

It is happening when there is a lack of `alt` attribute or `alt` attribute is empty. 
When I'm adding `&nbsp; ` into `alt` (`alt="&nbsp;"`)all works out.

Alt attribute is required but  not everyone knows about it.

**Comment by verlok** [comment]
Could you please create a Pen on Codepen.io so that I can check with my Firefox?

**Comment by verlok** [comment]
@bodanus7 Could you please create a Pen on Codepen.io so that I can check with my Firefox and initiate a debug session?

**Comment by verlok** [comment]
@bodanus7 is this still an issue?
