### ISSUE TITLE
LazyLoad and printing

### ISSUE THREAD

**Issue by markusweb** [verlok/lazyload#257]
i used the conditional loading, so in firefox/chrome it uses 10.x and in safari 8.x

lazyloading of the images works in all browsers. when scrolling down the images are being loaded.

when i print the page, only the already loaded images will be printed. i tried to use

```js
wLazyLoad = new LazyLoad({ elements_selector: '.lazy', });
window.onbeforeprint = function () {
   wLazyLoad.loadAll();
};
```

but without luck. it should load alle the images, right? 

* safari it will only display the already loaded images. 
* chrome i only see my placeholders no images. in the console and in my server logs i see the loading of the images.
* firefox will load the remaining images and then prints them (checked also in the console)

**Comment by verlok** [comment]
Hey @markusweb, this is a very interesting issue.
What you did using `loadAll()` is correct, I'd probably add some more Javascript to wait for all the images to be loaded.
Do do this, you should wait for a number of `loaded` events equals to the number of images yet to be loaded.
The number of images yet to be loaded can be found inside `wLazyLoad._elements.length`, and you could listen to the `loaded` event in your images container, e.g. the page `body` tag.

**Comment by markusweb** [comment]
good to hear. i will have a look on it too.
one question for understanding: when i call loadAll() will it return immediatly and then load the images in background? this would explain the behaviour. my webserver will log the loading of the images but maybe the browser has not yet changed all the images-tags?

**Comment by verlok** [comment]
Yes of course, the loading is asynchronous

**Comment by verlok** [comment]
We could modify the LazyLoad script so that it notifies when all the images we’re loaded. But it is not something that I can do in a short time.

**Comment by markusweb** [comment]
would it be possible to have an option for loadAll to disable the asynchronous call? so that it waits until all the images are loaded, somehing like `loadAll(deferr)`

**Comment by verlok** [comment]
> would it be possible to have an option for loadAll to disable the asynchronous call?
@markusweb I don't think so, because the loaded event emitted by the images is not a Promise.

**Comment by verlok** [comment]
I've just added a new `demos/print.html` file that show you how to do that.


/cc @markusweb

**Comment by verlok** [comment]
Turns out that the code above doesn't work on Safari because Safari [doesn't support](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeprint) `onbeforeprint`.  

So the full code we'd need to add to our page would be:

```js
// We have our global instance of LazyLoad in wLazyLoad
var wLazyLoad = new LazyLoad({ elements_selector: '.lazy' });
var isSafari = /^((?!chrome|android).)*safari/i.test(navigator.userAgent);

/* We need to create a function that returns a Promise
	* that executes the loadAll() method and resolves only when 
	* there are no more images managed by LazyLoad,
	* which means it already loaded them all */
var loadAllImages = () => new Promise(function (resolve, reject) {
	wLazyLoad.loadAll();
	var intervalId = setInterval(() => {
		if (!wLazyLoad._elements.length) {
			clearInterval(intervalId);
			resolve();
		}
	}, 500);
});

loadAllAsync = async () => {
	// NOTE: Maybe it's a best practice to show HERE a message to the user
	// telling him that the print is being prepared...
	await loadAllImages();
	// ...then hide the above shown message HERE
};

if (isSafari) {
	/* The following code allows us to solve this on Safari too
		* since Safari doesn't support the onbeforeprint event */
	var mediaQueryList = window.matchMedia('print');
	mediaQueryList.addListener(function (mql) {
		if (mql.matches) {
			loadAllAsync();
		}
	});
}
else {
	/* The onbeforeprint function must then be defined as async
		* to allow await-ing for loadAllImages()'s promise to be resolved */
	window.onbeforeprint = loadAllAsync;
}
```

Messy, isn't it. 
So probably is a good idea to have a LazyLoad `loadAllAsync` method to `await` for.
I'm on it.

/cc @markusweb

**Comment by verlok** [comment]
The idea would be not to use the native `onbeforeprint` but to provide a *print button* on your page which first download all the images, then launches the print.

This would be the full code. I'm working on it in the `feature/loadAllAsync` branch, `demos/print.html` file.

```js
var isSafari = /^((?!chrome|android).)*safari/i.test(navigator.userAgent);

// We have our global instance of LazyLoad in wLazyLoad
var wLazyLoad = new LazyLoad({
	elements_selector: '.lazy',
	callback_load: (el) => {
		console.log("Loaded", el.src);
	}
});

if (isSafari) {
	/* The following code allows us to solve this on Safari too
	   since Safari doesn't support the onbeforeprint event */
	var mediaQueryList = window.matchMedia('print');
	mediaQueryList.addListener(async function (mql) {
		if (mql.matches) {
			await wLazyLoad.loadAllPromise();
		}
	});
}
else {
	/* The onbeforeprint function must then be defined as async
	   to allow await-ing for loadAllImages()'s promise to be resolved */
	window.onbeforeprint = async function () {
		await wLazyLoad.loadAllPromise();
	};
}

/* The best way to print it is to provide a custom button which 
   first download all the remaining images, then open the print dialog */
document.querySelector(".print").addEventListener("click", async (ev) => {
	var button = ev.target;
	const oldContent = button.innerHTML;
	button.innerHTML = "Preparing...";
	button.disabled = true;
	await wLazyLoad.loadAllPromise();
	button.innerHTML = oldContent;
	button.disabled = false;
	window.print();
});

**Comment by verlok** [comment]
Now merged into development branch.

**Comment by verlok** [comment]
Suddenly I realized that Promises are not supported in Internet Explorer, and given that `window.onbeforeprint` can't be async anyway, it's better to rollback the code based on Promises to a callback system like everywhere else.

**Comment by verlok** [comment]
So now in the `master` branch you have a working `demos/print.html` file, which works in all browsers including IE11. 

What it does is using callbacks to **keep track** of how many images are **currently loading**. It then provides a **print button** which runs the `loadAll()` method and waits until the number of loading images is `0` before opening the print dialog.

Here's the code for your convenience.

```js
var isSafari = /^((?!chrome|android).)*safari/i.test(navigator.userAgent);
var loadingImages = 0;

// We have our global instance of LazyLoad in wLazyLoad
var wLazyLoad = new LazyLoad({
	elements_selector: '.lazy',
	callback_load: (el) => {
		loadingImages -= 1;
		console.log("Finished loading. Currently loading " + loadingImages);
	},
	callback_set: (el) => {
		loadingImages += 1;
		console.log("Started loading. Currently loading " + loadingImages);
	}
});

function disableButtonAndGetContent(button) {
	var oldContent = button.innerHTML;
	button.innerHTML = "Preparing...";
	button.disabled = true;
	return oldContent;
};

function enableButtonAndSetContent(button, content) {
	button.innerHTML = content;
	button.disabled = false;
};

function printButtonHandler(event) {
	var button = event.target;
	var oldContent = disableButtonAndGetContent(button);
	// Start counting how many images were loaded from now
	wLazyLoad.loadAll();
	var intervalId = setInterval(function () {
		// WAITING FOR ALL THE IMAGES TO BE LOADED
		console.log("::Check:: Currently loading " + loadingImages);
		if (loadingImages <= 0) {
			clearInterval(intervalId);
			enableButtonAndSetContent(button, oldContent);
			window.print();
		}
	}, 500);
}

/* The best way to print it is to provide a custom button which 
	first download all the remaining images, then open the print dialog */
document.querySelector(".print").addEventListener("click", printButtonHandler);

/* The following code tries to patch the user printing using the browser's
	print command, but it works only partially. */
if (isSafari) {
	/* The following code allows us to solve this on Safari too
		since Safari doesn't support the onbeforeprint event */
	var mediaQueryList = window.matchMedia('print');
	mediaQueryList.addListener(function (mql) {
		if (mql.matches) {
			wLazyLoad.loadAll();
		}
	});
}
/* Tries to dowload all images before printing, but even using async/await 
	this can't block some browsers' print dialog */
else {
	window.onbeforeprint = function () {
		wLazyLoad.loadAll();
	};
}
```

I tried to put the code to keep track of how many images are loading inside the LazyLoad script, but it would require quite a refactoring. But I'll keep thinking about it.

**Comment by verlok** [comment]
Hey @markusweb,

I've moved the count of number of elements still to be loaded inside the script, in version 10.19.0 (still didn't do it on v. 8.x).

Now you have a new `callback_finish` options so you no longer need to fiddle with `setInterval`.

Here's the final code of `demos/print.html`:

```js
/*
CUSTOM PRINT BUTTON MANAGEMENT 
------------------------------
The best way to print it is to provide a custom button which 
first download all the remaining images, then open the print dialog */

var printRequested = false;
var allLoaded = false;

function printButtonHandler(event) {
	printButton.innerHTML = "Preparing...";
	printButton.disabled = true;
	if (allLoaded) {
		openPrintDialog();
	}
	else {
		printRequested = true;
		wLazyLoad.loadAll();
	}
}

function openPrintDialog() {
	printButton.innerHTML = printButtonContent;
	printButton.disabled = false;
	window.print();
}

function finishLoadHandler() {
	allLoaded = true;
	if (printRequested) {
		openPrintDialog();
	}
}

var printButton = document.querySelector(".print");
printButtonContent = printButton.innerHTML;
printButton.addEventListener("click", printButtonHandler);

/*
LAZYLOAD DEFINITION
-------------------
Global instance of LazyLoad in wLazyLoad,
used to call the loadAll method in different points	*/

var wLazyLoad = new LazyLoad({
	elements_selector: '.lazy',
	callback_finish: finishLoadHandler
});

/* 
BROWSER'S NATIVE PRINT EVENTS LISTENERS
--------------------------------------- 
In order to make browsers load all the images before printing
even if the user doesn't press the custom print button. 
NOTE that this works only partially in some browsers! */

var isSafari = /^((?!chrome|android).)*safari/i.test(navigator.userAgent);
if (!isSafari) {
	window.onbeforeprint = function () {
		wLazyLoad.loadAll();
	};
}
else {
	// Safari doesn't support the onbeforeprint event
	var mediaQueryList = window.matchMedia('print');
	mediaQueryList.addListener(function (mql) {
		if (mql.matches) {
			wLazyLoad.loadAll();
		}
	});
}
```

Let me know what you think!

**Comment by markusweb** [comment]
hi,
yes, having a dedicated print button will make things much easier. with the print button it will work in firefox. without the print button and just using the browsers print function it will not work.

- firefox will not work
- chrome will work
- safari will load all images on page display, as the branch 10.x will not work with safari. when doing print it will hang saying "preparing print..." 

i just googled a bit. the print subject is a problem to all of the lazyload scripts out there... 
seems no one is printing any webpage (ok, it will not always be useful to print a long page but....)

**Comment by markusweb** [comment]
yesterday we have decided that the layzload function for screen and browsing is more important and helpful than the print function. so we will life with the print problem (although it would be cool if there is a solution)

markus

**Comment by verlok** [comment]
I still need to replicate the feature on version 8.x, which is the recommended version for Safari and IE. This will make it work with Safari with the print button.

**Comment by verlok** [comment]
Also released in 8.17.0 (for Safari and IE)
https://github.com/verlok/lazyload/releases/tag/8.17.0

@markusweb

**Comment by verlok** [comment]
Reopened for: in-depth cross-browser testing

**Comment by markusweb** [comment]
OK, i just googled a bit and found: [https://stackoverflow.com/questions/43707762/how-to-lazy-load-images-and-make-them-available-for-print#4376846]  so it seems that image loading is asynchron and you cannot wait or stall the printing of the browser. the print will also "come up" before the page is finished. so i think lazyloading and printing is something which will not work. so we have to live with a flaw that not all images are shown while printing. maybe we can tweak it with some CSS and show some nicer placeholder...

Markus

**Comment by verlok** [comment]
That’s right Markus. 
Did you try implementing the custom print page button?

**Comment by verlok** [comment]
Tested cross browser using [this repo](https://github.com/verlok/lazyload-print-test) and [live demo](https://www.andreaverlicchi.eu/lazyload-print-test/). I think this can be closed now. 👍
