### ISSUE TITLE
v10.18.0 of lazyload doesn't exist on CDNJS

### ISSUE THREAD

**Issue by bridgeport** [verlok/lazyload#260]
As you can see, it doesn't exist on the CDN page here:
https://cdnjs.com/libraries/vanilla-lazyload

The CDN link you reference in the read me leads to a 404 not found:
https://cdnjs.cloudflare.com/ajax/libs/vanilla-lazyload/10.18.0/lazyload.min.js

Thanks for this great script.

**Comment by verlok** [comment]
Hey @bridgeport,
thanks for reporting this issue.

I've reported [the issue](https://github.com/cdnjs/cdnjs/issues/13011) to the CDNJS GitHub repo.
It seems that they're having [some problems](https://github.com/cdnjs/cdnjs/issues/) at this moment.

I'll change the version reported in my readme.md for now.
Thanks

**Comment by verlok** [comment]
You can temporarily download any version of LazyLoad from the JSDELIVR CDN:

* With github as origin
  https://cdn.jsdelivr.net/gh/verlok/lazyload@10.18.0/dist/lazyload.min.js
* With npm as origin
  https://cdn.jsdelivr.net/npm/vanilla-lazyload@10.18.0/lazyload.min.js

The two ways are almost equal, but sometimes I can't publish on npm right away so they are available on the github url first.

/cc @bridgeport

**Comment by verlok** [comment]
cdnjs still doesn't respond and doesn't answer via GitHub nor Twitter. 
I'm opening another issue to myself to remember switching cdnjs to jsdelivr in the docs.

**Comment by verlok** [comment]
@bridgeport fixed doc in README.md file. Thanks!

**Comment by bridgeport** [comment]
@verlok I know you switched to jsdelivr in the docs a while ago, but thought it worth mentioning that cdnjs.com has been stuck on v12.0.3 for a long while now:
https://cdnjs.com/libraries/vanilla-lazyload

**Comment by verlok** [comment]
Thank you.
That’s why I switched.
Cdnjs has become unresponsive and they have no support.

> --
—
Andrea Verlicchi
www.andreaverlicchi.eu
