### ISSUE TITLE
Requesting Detail: What is the Best Threshold value?

### ISSUE THREAD

**Issue by Niresh12495** [verlok/lazyload#265]
What is the best threshold value, Please explain the answer if possible with research?

**Comment by verlok** [comment]
Hey! Good question. 
The answer is there isn’t one. It depends on many factors, for example: what devices are you developing for? How big/heavy are the images? How fast are your users likely to scroll. Etc.
If you’re developing for smartphones you’d probably go for something like the average viewport height.

**Comment by Niresh12495** [comment]
Im using the following JS to set threshold value, do you have any better suggestion?

`Math.max(document.documentElement.clientHeight*3/4, window.innerHeight*3/4 || 0);`

**Comment by verlok** [comment]
That could do the trick!
