### ISSUE TITLE
Stuck with "loading" on Safari

### ISSUE THREAD

**Issue by ChrisButterworth** [verlok/lazyload#266]
Using this with a slider in safari and updating when the slide changes to load the next one. Unfortunately when doing this it seems to be stuck with the "loading" class that won't update even after it's left to load.

Using 8.16.0 in Safari

Using: 
```
   const update = () => {
        if (typeof window.lazy !== 'undefined'){
            window.lazy.update();    
        }
    };
```
and calling it when the slide changes along with the conditional load as specified in the readme file amended to:
```
    (function(w, d){
        var b = d.getElementsByTagName('body')[0];
        var s = d.createElement("script"); 
        var v = !("IntersectionObserver" in w) ? "8.16.0" : "10.19.0";
        s.src = "https://cdn.jsdelivr.net/npm/vanilla-lazyload@" + v + "/dist/lazyload.min.js";
        b.appendChild(s); 
        s.onload = function(){
            w.lazy = new LazyLoad({
                elements_selector: ".lazy"
            });
        }
    }(window, document)); 
```
and:
```
<picture>
    <source media="(min-width:1441px)" data-srcset="/app/uploads/2018/09/FTB_Crop_1-2560x1440.jpg" type="image/jpeg">
    <source media="(min-width:480px)" data-srcset="/app/uploads/2018/09/FTB_Crop_1-1440x810.jpg" type="image/jpeg">
    <source data-srcset="/app/uploads/2018/09/FTB_Crop_2-483x859.jpg" type="image/jpeg">
    <img class="lazy" src="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=" data-src="/app/uploads/2018/09/FTB_Crop_2-483x859.jpg" alt="FTB_Crop_1">
</picture>
```

Even after I've refreshed the page and cleared cache it still hangs.

**Comment by verlok** [comment]
Hey 👋🏼 
LazyLoad is not meant to work along with sliders. 
Many sliders already have the feature to lazy load their elements. See your slider library docs. 
Also see other closed issues on this repo. 
Thanks

**Comment by ChrisButterworth** [comment]
it's one I built myself hoping to utilise LazyLoad to handle loading images when the slide changes.

**Comment by ChrisButterworth** [comment]
The slider doesn't use transform, its a simple fade effect using `update` to show the image after the slide has changed; it's that function that is causing erratic behaviour (i can understand it hasn't been designed to be used with sliders but surely it could)

Yes it uses v8.16.0

Not trying to be annoying but that last statement is like saying "why use a scalpel when you can use a meat cleaver" not using jQuery elsewhere on the website so loading a huge library and slider for something I can do myself and can concentrate on performance with it too.

**Comment by verlok** [comment]
LazyLoad‘s `update` method just updates the elements watched by the instance of LazyLoad when you add new ones. 

If you want to force re-check if the elements are inside the viewport you must use `handleScroll` which is a throttled function so you can call it every time your slider moves by 1 tick, or you can call

**Comment by verlok** [comment]
`_loopThroughElements` is the function that checks each single watched image for its visibility.
