### ISSUE TITLE
LazyLoad not loading images with specified absolute position <500px screen width and 1024px screen width safari

### ISSUE THREAD

**Issue by salespageshark** [verlok/lazyload#267]
For some reason images don't load at all when loading them on Safari with width <500px or width equal to 1024px. I use Safari Responsive Design Mode, Safari 12.0 - MacOS - Mac.

https://salespageshark.com/assets/portfolio/sales-pages/ebiz-wordpress-theme/
http://prntscr.com/l6fzgn

I found out that when I remove "data-" from the img tag, without lazyload, the images load correctly.

Also, if I remove 
`top: -47px;
left: -32px;`

in `.avatar-wrapper-absolute`
the problem disappears. Only when I specify specific position problem persists for these screen widths.

It's strange that the problem repeats for the 1024px screen width the images don't load too.

here just the ones on the left? These are the same images on the right or left
http://prntscr.com/l6g0wp

For 1058px width screen size it loads fine
http://prntscr.com/l6g284

This image loads fine outside Responsive Design Mode, but not inside it for 1024px screen width
http://prntscr.com/l6g0kd

Loads fine in 1089px screen width
http://prntscr.com/l6g2pi

I'd appreciate any help. Thank you!

**Comment by verlok** [comment]
Hi,
If you want help, please provide your HTML, CSS and JS code, here or on a Codepen or JsBin. 
Otherwise is very hard to understand what’s happening.

**Comment by verlok** [comment]
Hi @salespageshark,
I just saw it online and I was able to replicate it on my Safari, but I still need your help. Can you post here the javascript code used to initialize LazyLoad on that page?

**Comment by salespageshark** [comment]
I don't think it's an issue of these position relative/absolute combined together. Opacity 0 can be due using of AOS that makes the image invisible at first before initializing the animation on scroll.

Maybe this image example would be easier, it just uses position absolute

http://prntscr.com/l6mljm
screen width 559px not showing up

http://prntscr.com/l6mm9d
660px screen width showing up

I use this code to initialize LazyLoad:
`(function(w, d){
  var b = d.getElementsByTagName('body')[0];
  var s = d.createElement("script");
  var v = !("IntersectionObserver" in w) ? "8.17.0" : "10.19.0";
  s.async = true; // This includes the script as async. See the "recipes" section for more information about async loading of LazyLoad.
  s.src = "https://cdnjs.cloudflare.com/ajax/libs/vanilla-lazyload/" + v + "/lazyload.min.js";
  w.lazyLoadOptions = {
    elements_selector: "img, iframe",
    threshold: "400"
  };
  b.appendChild(s);
}(window, document));
`

The problem still persists when I add `skip_invisible: false`

**Comment by verlok** [comment]
Hi @salespageshark,

I see an issue with the code you're using to initialize LazyLoad: you're passing a string (`"400"`) instead of an integer (`400`) in the `threshold` option. 

You should pass an integer, like that:

```js
w.lazyLoadOptions = { elements_selector: "img, iframe", threshold: "400" };
```

So the full code would be:

```js
(function(w, d) {
	var b = d.getElementsByTagName("body")[0];
	var s = d.createElement("script");
	var v = !("IntersectionObserver" in w) ? "8.17.0" : "10.19.0";
	s.async = true;
	// This includes the script as async. See the "recipes" section for more information about async loading of LazyLoad.
	s.src =
		"https://cdnjs.cloudflare.com/ajax/libs/vanilla-lazyload/" +
		v +
		"/lazyload.min.js";
	w.lazyLoadOptions = {
		elements_selector: "img, iframe",
		threshold: 400,
		thresholds: "50% 400px"
	};
	b.appendChild(s);
})(window, document);
```

I think this could solve your problem. 
Let me know!

**Comment by verlok** [comment]
I've just tried instantiating a `new LazyLoad()` on your website passing the correct options (the ones I wrote posted before), and it immediately loaded the images. 

So it was just a problem of type, as you passed a string to the `threshold` option which expects a number, the value couldn't be used and probably broke the calculations inside the script.

**Comment by devolkpl** [comment]
I just figured out that the issue occuring when cointainer element has _overflow: hidden_ ​​property. I have an image that is absolute positioned that goes out of left edge of viewport and it's not loading. Once I remove overflow: hidden it is working again. In my opinion it is a bug.

**Comment by verlok** [comment]
If you think so, please open a new issue

**Comment by allaire** [comment]
@verlok I just experienced this `overflow: hidden` issue on parent container , with an image (lazyloaded) with a negative margin that goes out a bit of the container. In that scenario, the image never load. Removing the negative margin or the `overflow: hidden` fix it.

**Comment by anephew** [comment]
Same here, 2021, on Mozilla
