### ISSUE TITLE
Feature Suggestion - Create Wordpress Plugin

### ISSUE THREAD

**Issue by MartyD23** [verlok/lazyload#268]
Hi, I think it would be good to have a wordpress version of this plugin.

Not everyone has the technical skill required to manually get this working by themselves.

Having a plugin would make it a lot easier for more people to benefit from this.

**Comment by Tabrisrp** [comment]
You can check this plugin that is using this very script for the lazyload: https://wordpress.org/plugins/rocket-lazy-load/

**Comment by verlok** [comment]
Thank you @Tabrisrp!
I think this settles it.

**Comment by MartyD23** [comment]
Thanks guys, i'm testing out that plugin and so far so good!
