### ISSUE TITLE
<noscript> element

### ISSUE THREAD

**Issue by AlgyTaylor** [verlok/lazyload#27]
Heya,

Nice work! :+1:  I wrote something similar back in 2011 - http://algytaylor.blogspot.co.uk/2011/11/tgvjs-javascript-to-reduce-page-loading.html

One of the good suggestions I'd had from that was that you should add a noscript tag with the actual image, so that it works for people with JavaScript disabled (or otherwise non-working), ie:

```
<img data-original="/path/to/file" alt="alt text" />
<noscript><img src="/path/to/file" alt="alt text" /></noscript>
```

Cheers,
Algy

**Comment by verlok** [comment]
Great. Would you like to update the readme file with a pull request?

**Comment by AlgyTaylor** [comment]
Done :)
