### ISSUE TITLE
option class_loading issue

### ISSUE THREAD

**Issue by nick2017** [verlok/lazyload#270]
Hi,
found a bug, when I'm trying to set the custom class_loading class it doesn't work. Actually even default loading class doesn't work :(
However class_loaded works like a charm. Doesn't work I mean loading class was not added at all while we are waiting when images will be loaded. I set a huge delay like 10-15sec to test. I used the latest lazyload version https://cdn.jsdelivr.net/npm/vanilla-lazyload@10.19.0/dist/lazyload.min.js

Firstly I thought that there is an error with other JS plugins I have, but after analyzing I came up with the idea to take one of your codepen examples and change it and test class_loading option there, and I found that it doesn't work there either.

I forked one of your examples and changed it a little, please have a look

https://codepen.io/webmnstr/pen/MPMraa

For the .image.lazy_l element should be added a .lazy_loading_test_lass class while loading, however we see that nothing is happening.

Thank you.

**Comment by nick2017** [comment]
some screenshots
https://screenpresso.com/=K1Lcf  -> lazy loaded class added
https://screenpresso.com/=2ciKe  -> lazy loading class during the loading was not added

**Comment by verlok** [comment]
I verified this. The minified version is missing the `managedTags` const for some reason. I'll fix it ASAP. Thanks for reporting.

**Comment by verlok** [comment]
Solved this in later versions.
