### ISSUE TITLE
Latest 8.x version not working in IE11

### ISSUE THREAD

**Issue by MAHolzbach** [verlok/lazyload#271]
1. Loading lazyload via npm package as "vanilla-lazyload": "^8.7.1" is throwing a syntax error on IE11.
2. Full functionality on IE11.
3. 8.17.0
4. IE11
5. - 
6. Open a page on IE11 using the above version of lazyload.

The syntax error appears to be caused by the latest 8.x version loading the ES2015 version. Hard coding version 8.7.1 fixes the issue.

**Comment by arjenblokzijl** [comment]
I can confirm the hard coding of 8.7.1 works for me as wel.

**Comment by verlok** [comment]
What are you doing to include the file on your project after installing it via NPM? Are you creating a bundle using webpack or gulp or grunt, and if yes, are you using a subtool using rollup or any other?

Or are you including the file directly using a script tag?

**Comment by MAHolzbach** [comment]
After NPM install (it was in the package.json as `"vanilla-lazyload": "^8.7.1",`) I am importing it into our Webpack entry point file as `import myLazyLoad from "vanilla-lazyload";`, then instantiating it as `new myLazyLoad();`.

**Comment by Kurzdor** [comment]
I have got the same problem with IE11.
Got this issue with import LazyLoad from 'vanilla-lazyload';
At first IE11 dropped an issue with arrow functions.
I solved this with 
``` 
exclude: /node_modules\/(?!(some-modules|vanilla-lazyload)\/).*/
```
but after that IE started throwing another issue with Object.assign.

The solution was that i need to import lazyload umd version like this: 
``` import LazyLoad from 'vanilla-lazyload/dist/lazyload.js';```

**Comment by VasekPurchart** [comment]
I am experiencing this as well, using Webpack (but we do not run any loaders on code from node_modules, so only modules and minification can come into play probably).

I tracked the syntax error to version [8.15](https://github.com/verlok/lazyload/blob/master/CHANGELOG.md#10150), but it throws a different error (`Object doesn't support this action`) already in [8.13](https://github.com/verlok/lazyload/blob/master/CHANGELOG.md#8130) where the different distribution files appeared for the first time. So maybe there is something wrong in the build process (producing code IE11 is not able to parse?).

I am not able to pinpoint precisely where IE stops understanding the code, but it's highlighting gets messed up here:

```
e.style.backgroundImage=`url("${t}")`}if(s){let t=h(s,n);e.style.backgroundImage=t}})(e,n)},
                                  ^
```

Anyway I think the last vorking version for IE for now is `8.12`.

**Comment by unchai** [comment]
I workarounded with webpack alias config.

```js
module.exports = {
  ...
  alias: {
    'vanilla-lazyload': require.resolve('vanilla-lazyload/dist/lazyload.js'),
  },
  ...
};
```

**Comment by verlok** [comment]
Hi guys,
since version 8.x will soon cease to be supported in favor of v.11 + the IntersectionObserver polyfill, could you try if version 11 works as expected with you webpack configuration?
Thanks

**Comment by 128keaton** [comment]
@verlok  I cannot get 11.x working on IE11 sadly, even with the polyfill.

**Comment by verlok** [comment]
@128keaton I’ve tested it on IE and it worked perfectly with and without polyfill. I invite you to open a new issue and add a few details. It’s hard to understand what’s happening if you don’t add any. Thank you.
