### ISSUE TITLE
LazyLoading ads delivered by JavaScript?

### ISSUE THREAD

**Issue by jonathanstegall** [verlok/lazyload#272]
Are you reporting a bug or requesting a feature? Feature

I'm trying to understand if this library can be used to lazyload ads when it's not clear what exactly will be returning from the ad server (that is, it could be an image, an iframe, or other HTML).

For example, we have a network that delivers this kind of code:

```
<div class="appnexus-ad ad-x100">
	<script>
	<!--
		var OAS_pos = "Top,Right1,x02,x03,x04,x05,x07,Middle,TopRight,x100,x101!x100";
		var OAS_query = "";document.write('<scr' + 'ipt src="' + OAS_url + 'adstream_jx.ads/' + OAS_sitepage + '/1' + OAS_RNS + '@' + OAS_pos + '?' + OAS_query + '">' + '<\/script>');
	// --
	</script>
	<script src="https://[server-url]/@Top,Right1,x02,x03,x04,x05,x07,Middle,TopRight,x100,x101!x100?"></script>
	<noscript>
	    <a href="https://[server-url]/@Top,Right1,x02,x03,x04,x05,x07,Middle,TopRight,x100,x101!x100">
	    	<img src="https://[server-url]/@Top,Right1,x02,x03,x04,x05,x07,Middle,TopRight,x100,x101!x100" border="0">
	    </a>
	</noscript>
</div>
```

I can't tell from the documentation if this is possible, but what I'd like to do is call that script - `<script src="https://[server-url]/@Top,Right1,x02,x03,x04,x05,x07,Middle,TopRight,x100,x101!x100?"></script>` - when the user reaches the threshold where the page would load a lazy loaded image.

Does this make sense? Is it feasible with this library?

**Comment by verlok** [comment]
Hey @jonathanstegall, what you can do is to place some DOM element in the page, for example the future container of the ad, create a custom instance of LazyLoad, then inject che script/dom element using one of LazyLoad's callbacks.

```html
<div id="some_ad"><!-- your add will appear here --></div>
```

```css
#some_ad {
  min-height: 1px;
}
```

```js
function load_ad() {
  // put here the code to load your ads
}

new LazyLoad({
  elements_selector: "#some_ad",
  callback_enter: load_ad
});
```

**Comment by UisgeBeatha436** [comment]
Anyone?

**Comment by verlok** [comment]
Hi @UisgeBeatha436 ,
it the error is:

> uncaught exception: TagError: adsbygoogle.push() error: Only one 'enable_page_level_ads' allowed per page.

then you should call the callback just once. Like this:

```html
<script>
  var pushedGoogleAds = false;
  var myLazyLoad = new LazyLoad({
      elements_selector: ".lazy"
  });

  // lazyload used in the Bootstrap carousel
  $(function() {
    return $(".carousel.lazy").on("slide.bs.carousel", function(ev) {
      var lazy;
      lazy = $(ev.relatedTarget).find("img[data-src]");
      lazy.attr("src", lazy.data('src'));
      lazy.removeAttr("data-src");
    });
  });

  function load_ad() {
    if (pushedGoogleAds) return;
    (adsbygoogle = window.adsbygoogle || []).push({
        google_ad_client: "ca-pub-3514636835854223",
        enable_page_level_ads: true
    });
    pushedGoogleAds = true;
  }

  new LazyLoad({
    elements_selector: "#google_ad",
    callback_enter: load_ad
  });
</script>
```

**Comment by UisgeBeatha436** [comment]
@verlok  Thank you for explaining. This did do the track :)

**Comment by verlok** [comment]
Happy to help, as always.

**Comment by Niresh12495** [comment]
@jonathanstegall  & @UisgeBeatha436 
I have created a javascript library to Lazy load Ads, You might try this
https://github.com/Niresh12495/LazyHTML

@verlok This might help you too, Thanks.
