### ISSUE TITLE
Unknown async GET Error

### ISSUE THREAD

**Issue by MrUltimate** [verlok/lazyload#274]
Are you reporting a bug or requesting a feature? Bug

If it's a bug, it would be very useful to me if you answered the following questions.
Your answers will help me understand what's happening and enable me to reproduce the bug.

* What is happening? Known Error in Chrome console, trying to get images from img.secureserver.net Images also appear while loading.
* What is the expected behaviour? No error in console + images do not appear before fully loading
* Which version of LazyLoad are you using? v8.x.x
* In which browser(s) and browser version(s) are you experiencing the problem? Google Chrome
* Could you provide the HTML, CSS and JS code you use for your images? Please look at: helloshivam.com/
* What are the steps to reproduce the problem? Load page.

Thank you.

<img width="551" alt="screen shot 2018-11-14 at 2 03 12 pm" src="https://user-images.githubusercontent.com/7812204/48505921-391e1f00-e816-11e8-9ca9-08016ed33ad9.png">

EDIT: This is an unknown AdBlocker error. Bad on my part. Please close this request.

**Comment by verlok** [comment]
Hi @MrUltimate,
I'm sorry that I'm so late in replying but I've been very busy in the latest days.

Glad you solved it, ultimately.
I'm closing this.
