### ISSUE TITLE
How to update in case of automatic instances creation

### ISSUE THREAD

**Issue by waqasy** [verlok/lazyload#278]
I'm using following method. How to update it after loading more dynamic images?

```
w.lazyLoadOptions = {
    	data_src: 'src',
	data_srcset: 'srcset'
};
```

**Comment by verlok** [comment]
Hey @waqasy,
good question! The answer was in the readme.md file, find it here
https://github.com/verlok/lazyload#auto-init--store-the-instance-in-a-variable
Thanks!
