### ISSUE TITLE
Suddenly stopped working.

### ISSUE THREAD

**Issue by kylescousin** [verlok/lazyload#279]
On here: https://leesmee.com

All of a sudden, the images are not lazy loading anymore. They don't load at all (most of them, scroll down)
Notice the loading icons on the thumbnails (blue circles) which are the placeholders. data-src is set on all the images.

I'm using this piece of code for the images that have a class 'lazy':

```js
<script>
		(function(w, d){
			var b = d.getElementsByTagName('body')[0];
			var s = d.createElement("script");
			var v = !("IntersectionObserver" in w) ? "8.17.0" : "10.19.0";
			s.async = true; // This includes the script as async. See the "recipes" section for more information about async loading of LazyLoad.
			s.src = "https://cdn.jsdelivr.net/npm/vanilla-lazyload@" + v + "/dist/lazyload.min.js";
			w.lazyLoadOptions = {elements_selector: ".lazy"};
			b.appendChild(s);
		}(window, document));

		var myLazyLoad = new LazyLoad({
			elements_selector: ".lazy"
		});
	</script>
```

Anyone knows what is going on here? Can it have anything to do with Cloudflare?

**Comment by waqasy** [comment]
Your images are loading. 
You don't have to use `elements_selector: ".lazy"` twice.

**Comment by kylescousin** [comment]
They are not. Just a few are, when you scroll down most of them are stuck
with the loading icon.

Op di 4 dec. 2018 08:59 schreef waqas <notifications@github.com:

**Comment by kylescousin** [comment]
Found the problem, it's this: https://blog.cloudflare.com/we-have-lift-off-rocket-loader-ga-is-mobile/

When turning off 'rocket loader' on Cloudflare, it works.
Is this something that can be solved on your part?

**Comment by verlok** [comment]
Apparently, rocket loader interferes with the javascript code on your website. If you know what you're doing, just turn it off.

A suggestion, don't instantiate a `new LazyLoad()` because using `w.lazyLoadOptions` automatically instantiates one.

```js
(function(w, d){
	var b = d.getElementsByTagName('body')[0];
	var s = d.createElement("script");
	var v = !("IntersectionObserver" in w) ? "8.17.0" : "10.19.0";
	s.async = true; 
	s.src = "https://cdn.jsdelivr.net/npm/vanilla-lazyload@" + v + "/dist/lazyload.min.js";
	w.lazyLoadOptions = {elements_selector: ".lazy"}; // <= This global variable makes LazyLoad to self-create an instance of itself when loaded
	b.appendChild(s);
}(window, document));

var myLazyLoad = new LazyLoad({
	elements_selector: ".lazy" // <= This creates ANOTHER instance of LazyLoad, but it will initially throw an error since there won't be any global LazyLoad when these lines of code are executed (since the script is injected before and it takes some time to arrive)
});
```

Is that clear?
