### ISSUE TITLE
to_webp with option to change other part of image url than extension

### ISSUE THREAD

**Issue by michalrusina** [verlok/lazyload#280]
There's a nice option to automatically file extension to WEBP, but this does not cover situation where the image format is set in query parameters. For instance using http://glide.thephpleague.com like this:

`<img src="kayaks.jpg?w=500&fm=jpg">` original (jpg)
`<img src="kayaks.jpg?w=500&fm=webp">` changed format to WEBP

Solution would be to accept  search and replace strings as array for this option:

`to_webp: ["&fm=jpg","&fm=webp"]`

Then the extension would be unchanged and `&fm=jpg` replaced with `&fm=webp`.

**Comment by verlok** [comment]
That makes perfectly sense’
Would you please open a pull request to implement this feature?

**Comment by ipernet** [comment]
Thas is maybe not sufficient to provide an option the regexp pattern to use for replacement of "jpg" to "webp" somewhere in the URL.

It would not solve the use caseof [safe urls](https://thumbor.readthedocs.io/en/latest/security.html?highlight=security) where a server-side token is generated specific to the URL parameters used.

Best would be to use a `data-webp-src` attribute when `to_webp` is set to true that will be used as the webp url source.

Or go with the more verbose `<picture>`

**Comment by verlok** [comment]
@ipernet thanks for your suggestion, but if we go for the `data-srcset-webp` solution the markup of the image would almost double in size.

Think about this image:

```html
<img
	alt="Sneakers &amp; Tennis shoes basse"
	data-src="../img/44738717AM_15_a.jpg"
	data-srcset="../img/44738717AM_15_a.jpg 220w, ../img/44738717AM_11_a.jpg 330w"
	data-sizes="220px"
/>
```

It would become 

```html
```

**Comment by verlok** [comment]
I like @michalrusina's solution best. Will try and implement it as soon as possible.

**Comment by ipernet** [comment]
@verlok indeed, but it's a choice of not supporting safe urls or URLs that can only be generated server-side, due to possible heavy html markup on the client side. However I have the feeling that repeated things (like parts of same URLs here) in the markup tends to compress quite good, because most of the time html is served with gzip. 
Is it more about possible DOM performances issue?

**Comment by verlok** [comment]
You’re right that developers should worry about safe urls, but this discussion goes beyond this issue and it’s OOT here. But hey, the `picture` tag would still be usable with LazyLoad if I did this change, I don’t want to force anyone using the `img` tag. 

That said, there are many differences between the two: one of them is that`picture` is much more declarative and imperative on the browser, whereas `img` with `srcset` and `sizes` is just a strong hint to the browser. You can can find more googling around.

The only missing feature of the `img` is the possibility to use WebP conditionally, and given that here JavaScript is already used to LazyLoad the images, replacing the URL before assigning it to the image seems a good solution to me.

**Comment by schellenbergk** [comment]
`data-srcset-webp` would solve my issue too where my build process versions my files eg:
```
img/imageA-01b1d17269.webp
img/imageA-ef29f43990.png
```
just swapping the file extension does not help here.

**Comment by verlok** [comment]
Hello everyone,
I’m closing this issue because of #288. Read the discussion there please. 

@schellenbergk @michalrusina the solution to your specific problem is here https://github.com/verlok/lazyload/issues/288#issuecomment-465239290
