### ISSUE TITLE
Not working with SharePoint online display template code.

### ISSUE THREAD

**Issue by vaibhavgg** [verlok/lazyload#281]
Are you reporting a bug or requesting a feature? - Not getting it worked. May be I am doing something wrong or might be bug.

If it's a bug, it would be very useful to me if you answered the following questions.
Your answers will help me understand what's happening and enable me to reproduce the bug.

* What is happening? - I am trying to use image lazyload with simple method as given in link: https://github.com/verlok/lazyload/blob/master/demos/simple.html. I am trying to use it in SharePoint online search result's display template. 
* What is the expected behaviour? - There are images that should get lazy-loaded.
* Which version of LazyLoad are you using? - 8.17.0
* In which browser(s) and browser version(s) are you experiencing the problem? - Chrome, IE 11.
* Could you provide the HTML, CSS and JS code you use for your images? - 

HTML: 
```html
<img border="0" data-src="_#= $urlHtmlEncodeString(ctx.CurrentItem.csr_Icon) =#_" >
```

JS:
```js
<script type="text/javascript" src="Portal/lazyload.min.js</script>
<script type="text/javascript">
    	//new LazyLoad();
</script>
```

* What are the steps to reproduce the problem?
With the above code, the HTML markup that finally gets loaded in browser is as below:

```html
<img alt="Alt-Text" class="PictureUrlImage" style="align:center;width:63px;height:78.2px;" id="imgDummy" data-src="valid-image-url">
```

Please note that the 'src' and also 'data-was-processed=true' are not generated in final markup. Hence, the images actually do not appear on screen.

Am I doing something wrong? Please help with this.

Thank you

**Comment by verlok** [comment]
In the Javascript code you posted I see some errors: the "new lazyload()" instruction is commented out, and the "src" attribute of the first script is not closed. Maybe that was the problem?
