### ISSUE TITLE
How to use lazyload in <a>-tag

### ISSUE THREAD

**Issue by UisgeBeatha436** [verlok/lazyload#282]
I'm using version 8 of lazyload. On my site I'm using floatbox for showing images. To show the images i a box, one has to put the link to the image in the <a>-tag, for example:

```html
<a id="{$alt_id}-{$x}" data-rel="fotoalbum" class="lazy" title="{$alt}" href="{CGSmartImage src={$file} alt="{$alt}" title="{$alt}" noresponsive=1 notag=1 noembed=0}"></a>
```

Note: CGSmartImage creates a Base64 image.

Adding the class 'lazy' as shown above, doesn't work out. Is there a way to make use of lazyload in respect to the <a>-tag?

To add an example of how I implemented lazy load so far (html ran from PHP) in combination with Floatbox, but I don't think that matters.

```php
echo("<div id=\"a_$fotofile\" class=\"floatbox_$side floatbox\" data-fb-options=\"group:group-$group_id caption:$title type:image\">");
     echo("<a id=\"a_$photofile\" data-rel=\"photo_group\" class=\"floatbox lazy\" data-src=\"$photo\" href=\"$photo\"> $thumb</a>");
     echo()
     if ($title) {
          echo("<span class=\"group_image_title\">$title</span>");
     }
     echo("<span class=\"group_image_c2e\">(klik voor grote foto)</span>");
```

Thank you.

**Comment by verlok** [comment]
Sorry I can't help you out here because I didn't understand the question. Could you clearify what floatbox is and why do you need to put all the image attributes inside the `a` tag?

**Comment by equinusocio** [comment]
@verlok Floatbox is a lightbox legacy effect: https://floatboxjs.com/ I think they are just not compatible..

**Comment by UisgeBeatha436** [comment]
Thanks for your replies. 
By changing the a-element and split it into a separate img-tag and a a-tag I managed to get lazyload to work.
