### ISSUE TITLE
callback_finish is sometimes not fired

### ISSUE THREAD

**Issue by luxwan13** [verlok/lazyload#285]
Lazyload version: 10.19.0
When Chrome dev tool is opened with "Disable Cache" option ticked, the `callback_finish` callback function sometimes does not get triggered, even though all images are downloaded and has a `loaded` class.
I am using the `callback_finish` function to trigger carousel script after all images are loaded. My code below:

```js
var lazyLazy = new LazyLoad({
        elements_selector: ".section-carousel",
        callback_set: function (el) { // this fires on every page refresh...
            var carousel = new LazyLoad({
                container: el,
                callback_finish: function () { // this sometimes fires, but sometimes not, very annoy...
                    initCarousel('#' + el.id + ' .our-story-carousel');
                    $(el).removeClass('section-loading');
                },
                callback_error: function () { // this never happens!
                    console.log('error');
                }
            });
        }
    });
```

**Comment by dverbovyi** [comment]
same for me

**Comment by verlok** [comment]
The `callback_finish` should be called when all the images managed by LazyLoad were loaded, so that LazyLoad doesn't need to watch for images entering the viewport anymore. Was this clear before this reply? If it was, I'm confused. In order to have the `callback_finish` fired, all your images in the carousel should be loaded. Are you sure this is something you want?

**Comment by verlok** [comment]
You can easily check what’s going wrong inspecting the elements still in the LazyLoad’s observer, something like this in the console of your browser’s dev tools. 

```js
lazyLoadInstance._elements
```

What are the elements still there?

**Comment by verlok** [comment]
I’ve made some changes in version 11.x that might have solved this issue. Feel free to reopen if you still need help.
