### ISSUE TITLE
Failed to construct IntersectionObserver: member root is not of type Element

### ISSUE THREAD

**Issue by vcoppolecchia** [verlok/lazyload#286]
Hello, similar (if not identical) problem as #273 here, but I still can't figure this out.

### My context
I inserted lazyload script the async way and [with this recipe](https://www.andreaverlicchi.eu/lazyload/#conditional-load) (spoiler: "_conditional load_").

### What is happening
I get the same error as @DMCK96. Essentially my page loads lazy images the right way, but in the console I get this:
![verlok-lazyload-issue](https://user-images.githubusercontent.com/900011/49229351-99ec5080-f3ed-11e8-9104-2a0d06bc38a7.jpg)

### Which version of LazyLoad I'm using
I'm conditionally loading based on browser capabilities, just like is suggested in the recipe "_conditional load_".

### HTML, CSS and JS code I'm using
The recipe has only a single difference from the standard one in the documentation: I'm passing to window object an array of `lazyLoadOptions` options. The only reason I'm doing so is because I am lazy loading also other images in the page (other than those in the HTML markup below).

Script and options
```html
<script>
  (function(w, d) {
    var b = d.getElementsByTagName('body')[0];
    var s = d.createElement('script'); 
    var v = !('IntersectionObserver' in w) ? '8.17.0' : '10.19.0';
    s.async = true;
    s.src = 'https://cdn.jsdelivr.net/npm/vanilla-lazyload@' + v + '/dist/lazyload.min.js';
    w.lazyLoadOptions = [{
      elements_selector: '.lazy-img'
    }, {
      elements_selector: '.lazy-img',
      container: document.querySelectorAll('.scrollable-small-only')
    }];
    b.appendChild(s);
  }(window, document));
</script>
```

The HTML
```html
<ul class="scrollable-small-only">
...
<img class="lazy-img" data-src="path/to/the/image.jpg" alt="..." />
...
</ul>

```
@verlok sorry for opening a new issue with content from #273, but I still can't figure this out after almost a month. As stated in the issue mentioned before any help will be greatly appreciated, thanks.

**Comment by verlok** [comment]
@vcoppolecchia did @dverbovyi's answer solve the issue for you?

**Comment by vcoppolecchia** [comment]
Yes, this solved my issue. Thank you guys! 😉
