### ISSUE TITLE
Is it possible to lazily load lazyload?

### ISSUE THREAD

**Issue by cnanders** [verlok/lazyload#29]
I'm trying to build a Netflix / iTunes style browse page where there are horizontally scrollable lists of images (that have overflow-x: scroll) but then there are many  of these lists stacked vertically as you scroll down the main page (say 20 or 30)

Right now I'm triggering each overflow-x container list one as a LazyLoad instance (as you suggest here http://verlok.github.io/lazyload/demos/multiple_container.html ), they each work great horizontally, but on load, the page loads all of the visible images of each overflow-x container, even ones vertically below the fold.  In my case, with 20 of these horizontal rows, that may be 80 images below the fold that are loaded on initial page load. 

Ideally, there would be a way to have some nesting of the Lazyload so it would watch when new overflow-x containers vertically come into view and then keep watching each overfow-x container for horizontal moves.  I tried to articulate this in the attached images. 

<img width="832" alt="screen shot 2016-07-15 at 2 39 40 pm" src="https://cloud.githubusercontent.com/assets/414996/16889262/ff9fb8a4-4a99-11e6-97ec-27c482f17691.png">

<img width="854" alt="screen shot 2016-07-15 at 2 40 07 pm" src="https://cloud.githubusercontent.com/assets/414996/16889272/0be7e6e0-4a9a-11e6-8237-5f7777566e79.png">

**Comment by cnanders** [comment]
fwiw, [lazy-load-xt](https://github.com/ressio/lazy-load-xt) does this out of the box.  It uses jQuery, however, so I'm not sure it will have the same performance as this codebase.  I'm testing now.

**Comment by verlok** [comment]
@cnanders any updates?

**Comment by cnanders** [comment]
Never did any actual testing, however I'm using it in [production](http://www.hooktheory.com/theorytab) and it works beautifully.  You'll see on that linked page that it works in the x direction (overflow-x divs) as well as in the vertical direction (divs below the fold)

**Comment by verlok** [comment]
Beautiful. I'm gonna leave this issue open because I want to do this test one day.

**Comment by lopugit** [comment]
@verlok How'd it go?

**Comment by verlok** [comment]
@lopugit still haven't try... :(

**Comment by verlok** [comment]
I've started to work on this [here](https://github.com/verlok/lazyload/tree/support/lazilyLoadLazyLoad)
I'll let you know where it goes

**Comment by lopugit** [comment]
@verlok I use this little hack to make sure lazy images load when doing things like removing hidden classes when filtering products that have lazy load images which don't load because the window isn't scrolled.

`window.scrollTo(window.scrollX, window.scrollY-1);
window.scrollTo(window.scrollX, window.scrollY+1);`

I'm very curious to see what you come up with to listen to images coming into the viewport from your end, I guess it is up to you to support that functionality? I'll keep an eye on it :P

**Comment by verlok** [comment]
Interesting. I don't see why you don't use the `update` method on the LazyLoad instances, but maybe working on it I'll find out.

**Comment by lopugit** [comment]
@verlok oh are you serious. That would be because I'm retarded. So to get this straight you're working on a way to detect if the image is in the viewport? Not just activated by scrolling but just, what, are you gonna poll or somehow detect all image elements coordinates?

**Comment by verlok** [comment]
I think you misunderstood what I wrote. 
What I was suggesting is to use the `update` method like that:

```js
var myLazyLoad = new LazyLoad(/* options */);
// after you did things like removing hidden classes after filtering
myLazyLoad.update();
```

Does it make sense?
This is what I do in the "dynamic content" demo. See the demo folder. Or the readme file where there's just your case explained.

**Comment by lopugit** [comment]
I know I know but I'm not talking about how you're going to implement lazyloading for images that come from outside the viewport horizontally like in the OP's question?

**Comment by verlok** [comment]
That already works in the demo. The problem that @cnanders has is that the first images on the left in each horizontally scrolling container are loaded even if the container is outside the viewport. 
I replicated the issue and I'll solve it in the future making sure that LazyLoad consider them outside of the viewport. 
To close this issue, though, I have a fix in mind, which is to lazily load lazy load. That's what I'm doing in the branch. I'll notify you when I'm done.

**Comment by verlok** [comment]
The demo I'm working on is [this](https://github.com/verlok/lazyload/blob/support/lazilyLoadLazyLoad/demos/lazily_load_lazyLoad.html)

**Comment by verlok** [comment]
Solved. 
[That demo](https://github.com/verlok/lazyload/blob/support/lazilyLoadLazyLoad/demos/lazily_load_lazyLoad.html) now works and it's very elegant.
F**k yeah.

Still... it should not be that complicated to use LazyLoad. I'll see if there's a better to check whether the image is visible or not, unregarding the multiple scrolling containers that might exist.

**Comment by verlok** [comment]
Merged into master. Demo is now in the demo folder. Specifically [here](https://github.com/verlok/lazyload/blob/master/demos/lazily_load_lazyLoad.html).

**Comment by lopugit** [comment]
When does the callback fire?
