### ISSUE TITLE
too much recursion when loading an es6 module into a common js enviornment

### ISSUE THREAD

**Issue by jstoebel** [verlok/lazyload#290]
Are you reporting a bug or requesting a feature?
reporting a bug

If it's a bug, it would be very useful to me if you answered the following questions.
Your answers will help me understand what's happening and enable me to reproduce the bug.

* What is happening?
I have an ES6 component that wraps vanilla-lazyload, and is then loaded using require.js

```
// the component
import LazyLoad from 'vanilla-lazyload';

class LazyLoadWrapper {
  constructor() {
    // do some stuff...
    this.lazyLoadHandler = new LazyLoad({
      elements_selector: '.lazy-load-img'
    })
  }

  // ...
}

export default LazyLoadWrapper
```

here is the js file which is included in my page

```
// main.js

require(['bundle/vanilla-lazyload.bundle'], function (LazyLoadWrapper) {
  new LazyLoadWrapper.default()
})
```

When `main.js` is run on a page on my site I get the error `too much recursion`.

* What is the expected behaviour?
any images with the class `.lazy-load.img` should be lazy loaded

* Which version of LazyLoad are you using?
8.17.0

* In which browser(s) and browser version(s) are you experiencing the problem?
Firefox for OSX and Chrome for OSX

* Could you provide the HTML, CSS and JS code you use for your images?

heres an image tag in my html. JS shown above.

`<img alt="my-img" data-src="/ext/resources/images/my-img.png" class="lazy-load-img">`

* What are the steps to reproduce the problem?
Attempt to load the page :) unfortunately, I can't provide the entire code base because its proprietary, but let me know if there are any other bits of my code I can provide.

Thank you for a great library!

**Comment by verlok** [comment]
Hi @jstoebel,
The "too much recursion" error is possibly a require.js loop of dependencies.
Did you manage to solve this since 9 January? (sorry for being late, very busy month!)

**Comment by jstoebel** [comment]
@verlok Thanks for getting back to me! I switched to a different library that seems to work with our setup.

**Comment by verlok** [comment]
Ok then. 

Did you notice that LazyLoad is also exporter as AMD in the `dist` folder?

You can make it work requiring the AMD LazyLoad from a CDN as a dependency of your AMD module, instead of importing the standard module version of LazyLoad.

I know that for sure because we do that in our setup. 

I hope this make you reconsider using my (very lean and lightweight and fast and flexible) script.
