### ISSUE TITLE
Not working on Nexus theme by Elegant Themes

### ISSUE THREAD

**Issue by absentio** [verlok/lazyload#296]
I can't get it to work on recent videos widget by Elegant Themes which is included in my theme.
The theme was using $wp_embed and it didn't work. Then i tried to switch it to Youtube Embed plugin shortcode (https://en.wordpress.org/plugins/youtube-embed/), but it didn't work anyway.
When I click on play button, the fancybox appears, but the iframe inside it has src set as "about:blank".
Is there any way to get it working? Having 5 iframes loading on my page in background is really heavy and makes my page size bigger.

I am using LazyLoad last version avaiable in wordpress repository, Wordpress 5.0.3 and PHP Version 7.1
Here is a link to theme demo https://www.elegantthemes.com/demo/?theme=Nexus , the widget i am referring to is the one with "Recent videos" written above.
Sorry for my english, but this is not my native language.
Thank you.

**Comment by verlok** [comment]
Sorry, I should see some HTML, CSS and JS code in order to help you.

**Comment by verlok** [comment]
After not receiving feedback for 2 weeks, I'm assuming the problem was solved.
