### ISSUE TITLE
Enter/Set/Load won't trigger on img in Chrome 52

### ISSUE THREAD

**Issue by 01011010** [verlok/lazyload#297]
I have this rather peculiar issue on my phone running Chrome 52. Script use is async and single instance autoinit with options. (All other browsers seem to behave fine, including Chrome 61, and 7x) 
```javascript
var v = !("IntersectionObserver" in w) ? "8.7.1" : "10.19.0";`
```
Debugging it via my phone tells me the following:
Background elements with the selector (lazy) work, but <img> tags using data-src and data-srcset won't load until I manually trigger it with .loadAll() 

This is the number of images to begin with, nicely loaded into the array...
```javascript
window.lazyLoadInstance
U {_settings: Object, _observer: IntersectionObserver, _loadingCount: 0, _elements: Array[27]}
```

Background elements "pop-in" as I scroll past them, but the images won't, and is confirmed by the callback at the time...
```javascript
entered
set 1548367168967
load 1548367170423
```

Manually calling .loadAll() does the trick on the images and the styles etc., but I can't work out why I need to call that function to make it the images appear...
```javascript
...loadAll()
set 1548367802411
undefined
load 1548367803647
...
```

This is the config if it matters:
```javascript
const lazyClass = ".lazy";
// Set the lazyload options for async usage
window.lazyLoadOptions = {
    //container: wrapper,
    elements_selector: lazyClass,
    data_src: 'src',
    data_srcset: 'srcset',
    threshold: 0,
    //callback_enter: function() { console.log('entered'); },
    //callback_set: function() { console.log('set', Date.now()); },
    //callback_load: function() { console.log('load', Date.now()); },
};
```
Any help would be appreciated.

**Comment by 01011010** [comment]
Hi Verlok, 

Thanks for the response.

Sure, here is the raw balde template file section for the image:
```html
<img 
  data-src="{{$image->generate()->url()}}"
  data-srcset="{{low.jpg}} 320w,
               {{medium.jpg}} 480w,
               {{high.jpg}} 800w"
  sizes="(max-width: 480px) 100vw,
         (max-width: 900px) 33vw,
          233px"
  alt="" class="img-responsive lazy" itemprop="image">
```

This is the rendered page, and the CSS code to go with that section, plus the divs it sits in:

```html
<div class="container">
  <div class="row">
    <div itemscope="itemscope" itemtype="http://schema.org/Product" class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-heading">
          <a aria-label="View product" itemprop="url" href="https://" alt="" data-gtm-product="{}" data-gtm-click="">
            <img data-src="https://domain/image.jpg" data-srcset="https://domain/image_low.jpg 320w,
              https://domain/image_medium.jpg 480w,
              https://domain/image_high.jpg 800w" sizes="(max-width: 480px) 100vw,
                   (max-width: 900px) 33vw,
                  233px" alt="" itemprop="image" class="img-responsive lazy loaded" 
              srcset="https://domain/image_low.jpg 320w,
              https://domain/image_medium.jpg 480w,
              https://domain/image_high.jpg 800w" 
              src="https://domain/image.jpg" data-was-processed="true">
          </a>
        </div>
        <div class="panel-body">
          <a itemprop="url" aria-labelledby="" href="https://domain"><h3 id="" itemprop="name" class="panel-title">Title</h3></a>
        </div> 
        <div class="panel-footer"></div>
      </div>
    </div>
    ...
  </div>
</div>
```
```css
/* Prevents img without src to appear */
img:not([src]) {
    visibility: hidden;
}
/* For the image itself */
.img-responsive{
	display: block;
	margin-left: auto;
	margin-right: auto;
	max-width: 100%;
	height: auto;
	vertical-align: middle;
	border: 0;
}
...
```
Do let me know if you need any other info. Many thanks in advance (and btw, great script!)

**Comment by verlok** [comment]
Everythings looks good to me, I can't tell why this shouldn't work on Chrome 52. It's maybe a bug related to that specific version of Chrome.

My instinct says that you could try a couple of things:

- transform that `sizes` attribute to a `data-sizes` attribute
- remove the `img:not([src])` part from the CSS

Just to test if it works on Chrome 52.
Let me know!

**Comment by verlok** [comment]
@01011010 any feedback?

**Comment by 01011010** [comment]
Have tested it tonight, and unfortunately none of those changes (alone or combined) made a difference. 
I still had to call lazyLoadInstance.loadAll() in order to make the images appear.
```javascript
lazyLoadInstance.loadAll() <-- all images appear
undefined
```

**Comment by 01011010** [comment]
Started digging into it, and here are my findings using various versions of Chrome.
60 doesn't care about data-sizes or css. It just works as per the initial setup in my first comment.
58 works if you change sizes to data-sizes (css doesn't matter)
57 works if you change sizes to data-sizes (css doesn't matter)
56 works if you change sizes to data-sizes (css doesn't matter)

Doesn't matter if you make the changes, it just doesn't work (without loadAll()) in the following versions:
55
54
53
52

Will see if I can find anything in the change logs in the coming days...

**Comment by verlok** [comment]
@01011010 I’m going to close this issue. It looks like it’s about very old versions of Chrome, and Chrome is an auto-updating browser. If you still need help, feel free to reopen it.
