### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by akroii** [verlok/lazyload#30]
I'am using

**jQuery 2.1.4**
* Swipe 2.0
* jQuery FocusPoint; version: 1.1.1
*  jQuery mmenu v4.7.5
+ jQuery mmenu offCanvas addon
* respimage polyfill

```
new LazyLoad({
		container: "imageContainer",
			data_src: "src",
			data_srcset: "srcset",
			show_while_loading: true

		});
```

--> `_supportsClassList = !!document.body.classList;`

**Comment by akroii** [comment]
you need add the options in the footer

**Comment by akroii** [comment]
hmm Cannot read property 'querySelectorAll' of null
in line: `this._elements = _convertToArray(this._queryOriginNode.querySelectorAll(this._settings.elements_selector));`

**Comment by verlok** [comment]
Can you detail what is your HTML and JS code like? If you don't, I can't debug my script. 

--
Andrea Verlicchi
www.andreaverlicchi.eu

**Comment by verlok** [comment]
Great!
