### ISSUE TITLE
Update() doesn't refresh background images.

### ISSUE THREAD

**Issue by bmargevicius** [verlok/lazyload#300]
Using version 10.19.
It appears the update() doesn't refresh background images? 
Also the 'loaded' class is not being appended to lazy loaded background images. 

My patch around this (using jquery)
 $('.lazy:not(.loaded)[data-bg]').each(function(i, el){
                            var $el = $(el);
                            var background = $el.data('bg');
                            $el.css("backgroundImage", background).addClass("loaded");
                        });

**Comment by verlok** [comment]
> It appears the update() doesn't refresh background images?

No, it doesn't, and it isn't supposed to. If you read the API docs, it says the `update` method only checks if new images arrived in the scrolling container.

> Also the 'loaded' class is not being appended to lazy loaded background images.

No, it doesn't, and it isn't supposed to. There's no way to check if a background image is loaded in javascript. The real question is: if it really is a background image, why do you need to be notified for its loading? If it is a content image, you should use real images with the `img` tag.

There are tons of closes issues about this topic. Please check the [closed issues containing the "background" word](https://github.com/verlok/lazyload/issues?utf8=✓&q=is%3Aissue+is%3Aclosed+background).

**Comment by bmargevicius** [comment]
1) Fair.. 
2a) I wouldn't expect it to check if it actually loaded. In my mind if the swap from data-src to src happened the loaded class would apply. It's 50/50 here. 
2b) If there is a background image loading in an infinite scrolling loading scenario. The background image was used on a svg, where background-position: contain. Applying the loaded class here (as in the code above) prevents reloading.
