### ISSUE TITLE
Internet Explorer 11 – no image at all – arrow functions in lazyload js

### ISSUE THREAD

**Issue by Jones-S** [verlok/lazyload#301]
Not sure if it is a bug, maybe I also don't quite understand the internet explorer part.

## What is happening?
I use the plugin with `srcset` and in IE11 I don't see any image at all.
There is the DOM element, with a srcset but no src attribute:

```
<img class="Hero__image Hero__lazy" alt="" 
  data-src="https://cms.domain.ch/content/uploads/2019/02/beer2000x1500-720x540.jpg" 
  data-srcset="https://cms.domain.ch/content/uploads/2019/02/beer2000x1500-2000x1500.jpg 2000w, https://cms.domain.ch/content/uploads/2019/02/beer2000x1500-1440x1080.jpg 1440w, https://cms.domain.ch/content/uploads/2019/02/beer2000x1500-1280x960.jpg 1280w, https://cms.domain.ch/content/uploads/2019/02/beer2000x1500-720x540.jpg 720w" 
  data-sizes="(min-width: 1440px) 50vw, (min-width: 768px) 50vw, 100vw"
>
```
So IE 11 is not capable of interpreting srcset, but without a normal `src` there is nothing to fallback.

## Which version of LazyLoad are you using?
`"vanilla-lazyload": "^10.20.0",`
## In which browser(s) and browser version(s) are you experiencing the problem?
Internet Explorer 11
## What are the steps to reproduce the problem?
Probably just use some code like:
```
<img class="lazy" data-src="/your/image1.jpg"
    data-srcset="/your/image1.jpg 200w, /your/image1@2x.jpg 400w"
    data-sizes="(min-width: 20em) 35vw, 100vw"
>
``` 
And then open up IE11.

I am aware of the _Note about Internet Explorer_ part in your readme. But first if I log 

`    console.log('typeof window.CustomEvent: ', (typeof window.CustomEvent));`
I get: `typeof window.CustomEvent:  function`. 
So in IE11 it seems to be a function. Maybe this is related to some polyfills I am using anyway. Or some setup in my nuxt project.

The only error I get my console (using browserstack, IE11): 
```
Script1002: Syntax error
File: vendors.app.js, Line: 6305, Column: 46
```
Which leads me to this:
<img width="616" alt="image" src="https://user-images.githubusercontent.com/7059580/52487201-5f591e00-2bbd-11e9-940b-7918abac7d1b.png">

`const replaceExtToWebp = (value, condition) =>`
Seems that arrow functions could be a problem?
So I guess your plugin is not IE compatible if relying on arrow functions?
Is there something I am overseeing?

Thank you.

_____ 
Edit:
I saw that you recommend using version 8.17.0.
So I installed that package and now everything seems to be broken:
`navigator is not defined`
<img width="962" alt="image" src="https://user-images.githubusercontent.com/7059580/52487909-fa062c80-2bbe-11e9-91c3-c41097c301f2.png">

_____
Edit 2:
I just keep posting some updates, maybe someone goes through the same process once.
I realized there are demos that I can just ran by calling al ink. For example
https://www.andreaverlicchi.eu/lazyload/demos/with_srcset_sizes.html

I realize that your images indeed have a `src` set. And you don't have a console error.
So I guess it has to do with the usage of the new version installed as npm package, which ships code that is not IE11 ready...

**Comment by Jones-S** [comment]
Solution:
Well I found a solution: I transpile the node_module in my webpack config from ES6 to something readable by IE11.
I now get an image.
I hope this is all good for now.

**Comment by vcoppolecchia** [comment]
Hi @Jones-S, maybe I can be of some help here because I've got a [live example](https://www.fotoregali.com/stampe) which is 99% similar to what you need and, most importantly of all, is working (we recently brought it on the live servers). 

Here's the code:
```javascript
(function(w, d) {
    var b = d.getElementsByTagName('body')[0];
    var s = d.createElement('script'); 
    var v = !('IntersectionObserver' in w) ? '8.17.0' : '10.19.0';
    s.async = true;
    s.src = 'https://cdn.jsdelivr.net/npm/vanilla-lazyload@' + v + '/dist/lazyload.min.js';
    w.lazyLoadOptions = {
        elements_selector: '.lazy-img',
        callback_load: function(lazyImage) {
        lazyImage.parentElement.className += ' bgc-transparent';
        }
    };
    b.appendChild(s);
}(window, document));
```
Let me break it down for you (the way I would've liked someone to explain me at the beginning 😂): following the recipes you alredy know I loaded a different version based on the value of the `v` variable inside the IIFE function (meaning based on `IntersectionObserver` support). I've also mixed this recipe with another one listed on the plugin page to be able to lazy load the images again and have an instance with a callback available so I can fire the plugin again after the load event (we have products filters on the site linked above that load additional content via ajax).

Hope this clarifies and helps you and anybody coming across this. Bye. 😉

**Comment by verlok** [comment]
Guess this is solved by now. 
Thank you @Jones-S for the updates and @vcoppolecchia 

Or do I still need to fix anything?

**Comment by Jones-S** [comment]
No I think it's all good. For my case I like to not load the script in separately but rather include it into my minified js to have only one request. 
Maybe it would be nice to mention that the npm package is not IE ready and it needs to go through some conversion to make it browser compatible in your readme, but other than that no fixes required. Thank you
