### ISSUE TITLE
Version 8 would benefit from optional elements parameter in constructor to maintain API with version 10

### ISSUE THREAD

**Issue by cfx1** [verlok/lazyload#304]
Current version 10 constructor:
`var LazyLoad = function LazyLoad(customSettings, elements) {`
and passes `elements` to `update`:
`this.update(elements);`

Would be great if it could be implemented in version 8 as well.
As of 8.17.0, version 8's constructor is
`var LazyLoad = function LazyLoad(instanceSettings) {`
and its `update` is called without any parameters:
`this.update();`

**Comment by verlok** [comment]
Hi @cfx1,
thanks for reporting this.

I'm planning to dismiss the development of version 8.x in favor of maintaining only version 10.x which could work with the [`IntersectionObserver` polyfill by w3c](https://github.com/w3c/IntersectionObserver/). 

The reason of this is that 
- the `IntersectionObserver` is [soon to be supported in Safari](https://caniuse.com/intersectionobserver), which was the only modern browser missing this support, 
- [Microsoft stated users should stop using IE to browse the web](https://www.zdnet.com/article/microsoft-security-chief-ie-is-not-a-browser-so-stop-using-it-as-your-default/), so IE users would be the ones using and downloading the polyfill

What do you think?

**Comment by verlok** [comment]
Referenced in #306
