### ISSUE TITLE
NOTICE: Version 8.x of LazyLoad soon to be deprecated

### ISSUE THREAD

**Issue by verlok** [verlok/lazyload#306]
I'm planning to dismiss the development of version 8.x and deprecate it in favor of maintaining only version 10.x which could work with the [`IntersectionObserver` polyfill by w3c](https://github.com/w3c/IntersectionObserver/). 

The reason of this is that:

- the `IntersectionObserver` is [soon to be supported in Safari](https://caniuse.com/intersectionobserver), which was the only modern browser missing this support, 
- [Microsoft stated users should stop using IE to browse the web](https://www.zdnet.com/article/microsoft-security-chief-ie-is-not-a-browser-so-stop-using-it-as-your-default/), so IE users would be the ones using and downloading the polyfill

The [official w3c polyfill](https://github.com/w3c/IntersectionObserver/tree/master/polyfill) could be loaded _conditionally_ on less recent versions of Safari and Internet Explorer, using [Polyfill.io](https://cdn.polyfill.io/v3/).

**Comment by Erulezz** [comment]
+1

Dropping support and updates is a good idea when Safari 12.1 has been released (coming somewhere in March probably with iOS 12.2 and macOS 10.14.4). Keeping the docs online for v8 (as it is now, but with a deprecation warning) until the majority of users are on Safari 12.1 is also a good idea. It always take a while before the majority of users are upgraded.

**Comment by shoesforindustry** [comment]
+1 With Erulezz comments. All in favour of this move, but it has to be after Safari 12.1 has been out for some time, it just makes sense?

**Comment by verlok** [comment]
Hi all,
thanks for taking the time to comment. 

In my opinion, the deprecation of version 8.x could start the exact day Safari will start supporting `IntersectionObserver`, because:

- The suggested solution would be to use the `IntersectionObserver` polyfill, which will grant compatibility with older Safari versions still around. 
- Version 8.x would continue to be available forever, only it won’t be maintained anymore.

**Comment by verlok** [comment]
It's done already. The README file no longer mentions conditional loading and version differences.
