### ISSUE TITLE
ios safari overflow-x container, modal container

### ISSUE THREAD

**Issue by kelenakamura** [verlok/lazyload#308]
* What is happening?
On iPhone Safari - for modal windows (https://micromodal.now.sh/) absolute position window, and overflow-x containers, it seems that the images or bg images don't load in. BUT they do load in if the modal or overflowed images are in viewport and then you scroll up or down in the actual window.
Is this the correct behavior? Is it something that we have configured wrong?

* What is the expected behaviour?
That when the modal is opened, or when the container is scrolled horizontally the image appears.
If we test just on desktop chrome via toggling to device viewport it works as expected.

* Which version of LazyLoad are you using?
Using conditional load so 8.17 on Safari

* In which browser(s) and browser version(s) are you experiencing the problem?
Safari on iPhone

* Could you provide the HTML, CSS and JS code you use for your images?

```html
<script type='text/javascript'>
  (function(w, d){
    var b = d.getElementsByTagName('body')[0];
    var s = d.createElement("script");
    var v = !("IntersectionObserver" in w) ? "8.17.0" : "10.20.0";
    s.async = true; // This includes the script as async. See the "recipes" section for more information about async loading of LazyLoad.
    s.src = "https://cdn.jsdelivr.net/npm/vanilla-lazyload@" + v + "/dist/lazyload.min.js";
    w.lazyLoadOptions = {elements_selector: ".lazy"};
    b.appendChild(s);
}(window, document));
  </script>
```

* What are the steps to reproduce the problem?
Explained in What is happening.

**Comment by verlok** [comment]
Hello @kelenakamura,
did you pass in the `container` option to LazyLoad? 

If the scrolling container is not the main document but an `overflow: scroll` element, that element must be passed to LazyLoad in the `container` option so version 8.x can understand what to watch.

Let me know if this solves.

**Comment by kelenakamura** [comment]
with the conditional approach above how do we handle multiple different scrollable containers on a page?

**Comment by kelenakamura** [comment]
oh actually i see you can send multiple config objects to lazyLoadOptions (so can we send 1 for main body, and 1 each for any specific containers that may exist on the page?) so we need a custom config object for each type of page on our site?

window.lazyLoadOptions = [{
    /* your instance 1 options */
}, {
    /* your instance 2 options */
}];

**Comment by verlok** [comment]
Well, the script injection like you did can be useful if you have a very simple website. If your website is more complex, you probably need to go for a different approach.

**Comment by verlok** [comment]
Probably, the best way to go is to conditionally load the IntersectionObserver polyfill and subsequently always load LazyLoad version 10.x. 

Since version 10 doesn’t need to watch on the `scroll` event of the scrolling container (like version 8.x does), this solution would spare you the need of specifying a `container` to make it work on other scrolling containers. 

Note that this will soon be the recommended solution on the README, see #306.

**Comment by kelenakamura** [comment]
ah okay maybe that does make more sense, we'll try that method.

**Comment by kelenakamura** [comment]
okay that worked for the scrollable containers but seems for an off canvas modal, it still only loads in when you have the modal visible and you scroll the main window.

**Comment by verlok** [comment]
I didn’t understand what’s happening exactly in your latest message. 
Could you replicate this in a [codepen](https://codepen.io) so that I can take a look?

**Comment by kelenakamura** [comment]
yes i think we're going to look into how we're loading in the modal on mobile. so i think its fine, the polyfill method is much better than the conditional method for sure. thanks!

**Comment by verlok** [comment]
I totally redesigned the README file of this repo. Maybe you can find there something that didn’t catch your eye before.
