### ISSUE TITLE
Using lazyload with Salvattore

### ISSUE THREAD

**Issue by RChrisE** [verlok/lazyload#309]
I use Salvattore to create a gallery dynamically. As the gallery is quite large, I'd like to use lazyload. But with Salvattore all the images are loaded, not only the ones above the fold.

I'm using lazyload 10.20 in a JTL Shop backend.
The php(smarty)/html:

```php
<div id="grid" data-columns>
{foreach name=Links from=$linkgroups->inspirationen->Links|@array_reverse item=Links}
	{assign var=imgNo value=$Links->nSort}
		<a href="/{$Links->URL}" class="img-box">
			<img class="lazy" src="" data-src="/mediafiles/Bilder/Inspirationen/{$imgNo}.jpg">
			<img class="hidden zaehler-container" src="/bilder/Testbilder/ecke.svg" />
			<span class="hidden zaehler">{$imgNo}</span>
		</a>
{/foreach}
</div>
```

Thanks

**Comment by verlok** [comment]
Hi @RChrisE ,
I've never tried Salvattore, but I guess that with your code, just adding the script to your page like documented in the README.md, and instantiating a new LazyLoad on the page should work. 

```js
new LazyLoad();
```

Why the question? Did you have any problems?

Just pay attention that you didn't put the `alt` attributes on the main content image. This is required and it's for accessibility.

**Comment by RChrisE** [comment]
Hi Andrea,
I followed your advice, but the problems persists. I thinks this is due to Salvattore's way of loading pictures. They are all above the fold while loading as they don't have a height yet.

**Comment by verlok** [comment]
I need your help in order to help you out here.

Could you please create a new Pen on codepen.io and replicate the issue there?

In this way I could see what’s going wrong, and if the error is in Salvattore’s code, in LazyLoad’s code, or in your specific implementation.

**Comment by verlok** [comment]
@RChrisE do you still need help or did you solve?

**Comment by RChrisE** [comment]
Sorry I couldn't solve it and I had no time to post a Pen. We are quite busy with an update of our shop.

**Comment by verlok** [comment]
I’m closing it then, since I don’t have enough information to help you. Feel free to reopen if you can add information. Cheers!
