### ISSUE TITLE
Use with Unslider

### ISSUE THREAD

**Issue by rafalolszewskii** [verlok/lazyload#31]
How can i use this with unslider or any other slider ?

simple code like this doesn't work well with it.

```
  var myLazyLoad = new LazyLoad({
    elements_selector: ".lazyload",
    data_src: "original"
  });
```

**Comment by verlok** [comment]
Please detail what your case is and what are you trying to do

**Comment by rafalolszewskii** [comment]
Sorry, it seems to work now, maybe my cache was not refreshed :smile:
