### ISSUE TITLE
Babel 7.0 doesn't compile with lazy-load 10.20.1

### ISSUE THREAD

**Issue by 0000marcell** [verlok/lazyload#315]
The build doesn't output any error but the final file is not compiled correctly
when removing lazy-load everything works fine
any idea of what could be causing this problem is appreciated

babel: 7
babel-core: 7
webpack: 3.5.6

**Comment by verlok** [comment]
Hey @0000marcell, have you tried version 11.0.2?

**Comment by verlok** [comment]
Also, if you could specify better what is happening, what are you trying to achieve, how you configured your files, it would very helpful.

**Comment by 0000marcell** [comment]
hi @verlok i'm gonna try version 11.0.2 if it doesn't work i'm gonna try to make a build as simple as possible that has the problem

**Comment by 0000marcell** [comment]
version 11.0.2 worked great, thanks verlok, i dont know why version 10 was installed instead

**Comment by verlok** [comment]
I’m glad that worked. 

Version 10 was instale because I released version 11 one week ago, I guess. 

Closing this.
