### ISSUE TITLE
Avoid hidden images loading

### ISSUE THREAD

**Issue by VincenzoMartino** [verlok/lazyload#321]
I was wondering if the plugin has a function that avoids hidden images loading

**Comment by VincenzoMartino** [comment]
Hi verlok,
Yes, I mean all cases when the images are in the html but not visible (display none, visibility hidden, opacity 0 exc.).

> Have you tried and checked what actually happens before asking here?
 
Yes with standard plugin hidden images are loaded (loaded images are listed in the debugger network tab) and obviously not displayed.

There is a method to avoid this?

**Comment by verlok** [comment]
I've just created a demo under the `demos` folder, named `image_hidden.html`.
You can see it live here: https://www.andreaverlicchi.eu/lazyload/demos/image_hidden.html

I created it to make sure of how the `IntersectionObserver` works, since it's at the base of the LazyLoad script.

The images are not revealed and loaded if they are, or its parents are `display: none`.
In all other cases, `visibility: hidden` or `opacity: 0`, in the image or its parent nodes, the images are revealed.

**Comment by verlok** [comment]
So @VincenzoMartino I guess that if you use `display: none` to hide your images that you don't want to load solves it. Or do you need to use `opacity` or `visibility` for specific reasons?

**Comment by verlok** [comment]
Maybe, if you're trying to do something like "load the images only ad mouse over" or "when a specific event happens", you can load the `load()` method.

Checkout the `load.html` demo in the `demos` folder. [Live here](https://www.andreaverlicchi.eu/lazyload/demos/load.html).

**Comment by verlok** [comment]
Does this satisfy your requirement?

**Comment by verlok** [comment]
So to recap, you have two options to avoid LazyLoad loading hidden images:

1. Hide your images using `display: none` on the image or its parents 
2. Hide your images using `opacity` or `visibility`, but initialize LazyLoad selectively only on the images that are supposed to be loaded (as they enter the viewport), using `elements_selector`, then load the hidden images using the `load()` method. 

Does this make sense?

**Comment by VincenzoMartino** [comment]
Hi Verlok,
thanks so much for your accurate answer, and sorry if I write only now.

> In all other cases, visibility: hidden or opacity: 0, in the image or its parent nodes, the images are revealed.

My problem was exactly this!

Now I'm operating on css rules updating on `display: none` and where isn't possible I'll operate with `elements_selector`.
Thanks so much for hint.
Vincenzo

**Comment by verlok** [comment]
I’m glad we solved it. 
Cheers 🍻

**Comment by thewebartisan7** [comment]
Seem that method load() is not working anymore, it's possible?
I am getting `Lazyload.load is not a function`
