### ISSUE TITLE
Error: Cannot find module 'vanilla-lazyload'

### ISSUE THREAD

**Issue by ctowler157** [verlok/lazyload#322]
`Error: Cannot find module 'vanilla-lazyload'`

1. Go to [npm runkit](https://npm.runkit.com/vanilla-lazyload)
2. Click on "Run"
3. See error in stack trace

Expected behavior is the requiring/importing the module works

version 11.0.3

![image](https://user-images.githubusercontent.com/16481282/54152624-05de4c00-4414-11e9-84d2-7d0d80edb30e.png)

**Comment by verlok** [comment]
Hey there,
thanks for reporting. The error is in my `package.json`, specifically in the `main` property. It's pointing to `"dist/lazyload.cjs.min.js"` which not exists, instead of pointing to `"dist/lazyload.min.js"`.
Will fix ASAP.
Thanks

**Comment by ctowler157** [comment]
Thanks! I was looking at a bunch of different lazy load libraries and this one looked like the best for my use case, so I was bummed when it didn't work. Thanks for hopping on it so quick, looking forward to using this!!

**Comment by verlok** [comment]
Fixed in 11.0.4

**Comment by verlok** [comment]
You’re welcome!

I hope you find this useful like many others did.

If you have any doubt I hope you can find this useful. 

&rarr;
http://www.andreaverlicchi.eu/lazy-load-responsive-images-in-2019-srcset-sizes-more/

I wrote it just a couple of days ago. 

Cheers!

**Comment by ctowler157** [comment]
Yeah, I actually picked this library specifically because we're already using srcSet and `<picture>` pretty heavily and this seemed to be the only lazyload with support for those out of the box

**Comment by verlok** [comment]
I’m glad to hear that. 

Thanks for choosing vanilla-lazyload  out of many alternatives! 

I’m curious about the heavy usage of srcset and picture you’ll do. Can you reveal the website(s) you’re gonna use it on?

And if you like it, please share the love on Twitter :)
