### ISSUE TITLE
package.json module pointing to wrong file

### ISSUE THREAD

**Issue by MarciD** [verlok/lazyload#323]
**Describe the bug**
package.json:8 "module" is pointing to "dist/lazyload.esm.min.js" -> which does not exist.
A non minified version exists but not the lazyload.esm.min.js.
This breaks compiling (production), when importing with e.g. `import LazyLoad from "vanilla-lazyload";`

Saw that minification of esm-version was disabled, with this one:
https://github.com/verlok/lazyload/commit/44e1403#diff-b9e12334e9eafd8341a6107dd98510c9

If you want, I could create a PR for pointing to non-min-version or enable minifying again?! :)

**LazyLoad version**
- Version 11.0.4

**Comment by verlok** [comment]
Yes please open a pull request to point to the non minified version. 

Just remember to bump the version number to 11.0.5. 

Thanks

**Comment by verlok** [comment]
Hey @MarciD,
I found 5 minutes to do that on the train and I fixed it.

Thank you for reporting!
verlok
