### ISSUE TITLE
Support for network failure

### ISSUE THREAD

**Issue by khalyomede** [verlok/lazyload#324]
**Is your feature request related to a problem? Please describe.**
I tried the demo at [https://www.andreaverlicchi.eu/lazyload/demos/image_simple.html](https://www.andreaverlicchi.eu/lazyload/demos/image_simple.html). I scrolled a bit until the 10th image. Then I enabled the "offline" mode on Chrome DevTools, and kept scrolling until the 20th. Images failed to load. I disabled the "offline" mode and scrolled until the 30th image, loading with success. And finally I scrolled back to the 10-20th but the images were not loaded.

**Describe the solution you'd like**
To be able to tell lazyload to re-run (if the "viewport conditions" satisfies) the image loading process in case the network comes back. Maybe an opt-in attribute on the options of lazyload to make this non breaking the existing setup.

**Describe alternatives you've considered**
Manually listening to the online/offline events like:

```html
<img onerror="this.setAttribute('data-failed', 'true');" data-src="..." />
```

```javascript
window.addEventListener('online', () => {
  const failedImages = document.querySelectorAll('img[data-src][data-failed]');

  // if viewport screen conditions satisfies, trigger lazyload on this particular image
});
```

(all the code above is pure illustration)

**Additional context**
None.

**Comment by verlok** [comment]
Hey @khalyomede ,
thank you for asking. I think you can already do something like that.

When the connection comes back:

- select all the images with the `error` class set
- cycle them and remove their `data-processed` attribute and the `error` class
- call `.update()` on the LazyLoad instance

This will make LazyLoad re-consider all the images should do already.

**Comment by khalyomede** [comment]
Thank you @verlok for the quick answer, I will try it out. I let you manage whether you should close this issue as you provided a workaround or if you think it could be worth keeping this as a feature request. Cheers.

**Comment by verlok** [comment]
I'm verifying that on a new demo. Not easy as I said, apparently.

**Comment by verlok** [comment]
Here's the code you need:

```js
/* Retry error-ed images when the connection come back */
window.addEventListener("online", function() {
	var errorElements = document.querySelectorAll(".lazy.error");
	errorElements.forEach(el => {
		el.classList.remove("error");
		el.removeAttribute("data-was-processed");
	});
	ll.update();
});
```

I'm putting a demo online right ASAP.

**Comment by verlok** [comment]
Actually I think I will integrate this feature in LazyLoad, so I won't add a new demo for that.

But here's a Gist for you:
https://gist.github.com/verlok/8d8a454bc40cadd3dc62de3b5d8e78d3

**Comment by khalyomede** [comment]
You sir are really kind with me! Such fast answer with ready-to-use code, just what I needed to make my PWA perfect! Thank you so much for the time spent. Looking forward for this feature to come!!

**Comment by verlok** [comment]
Did that on the branch "feature/retryWhenOnline"
https://github.com/verlok/lazyload/tree/feature/retryWhenOnline

If you want to try it, it just works.
Just make sure to run gulp to generate the dist files before you try.

Cheers

**Comment by verlok** [comment]
🎉 Added in version 12.2.0!
