### ISSUE TITLE
opt out webp support

### ISSUE THREAD

**Issue by aaarichter** [verlok/lazyload#325]
**Describe the solution you'd like**

The webp feature detection is not necessary on our page. It would be great to opt out of that functionality

**Comment by aaarichter** [comment]
closing . I just discovered that this functionality exists only in the 2015 bundle.

**Comment by verlok** [comment]
It’s only in version 10. Version 11 has removed that functionality. 

So to opt out, just update to version 11. 

Cheers!

**Comment by aaarichter** [comment]
👍 

maybe the 2015 bundle should be removed from the dist folder to avoid having two versions available at the same time

**Comment by verlok** [comment]
Oh jeez. 
Didn’t notice it was still in the `dist` folder. 
I didn’t cleaned it up and it was still there from version 10. 
I’ve deleted it now. 
Thank you for pointing out.
