### ISSUE TITLE
src set to svg content and image do not show

### ISSUE THREAD

**Issue by db-conception** [verlok/lazyload#326]
Hello,

Since one of the last update, I get  :

```html
<img width="200" height="200" src="**data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox=**'0%200%201%201'%3E%3C/svg%3E" data-lazy-src="https://mysite.fr/wp-content/uploads/20..." data-lazy-sizes="(max-width: 200px) 100vw, 200px">
```

And my picture is not visible.

When I disable image lazy loading I get : 

```html
<img width="200" height="200" src="**https://mysite.fr/wp-content/uploads**/2018/08/avis-lea..."... sizes="(max-width: 200px) 100vw, 200px">
```

If I am not mistaken, In any previous version, I get not "**data:image/svg+xml,**" but the good path of my picture and it worked.

Thank you.

**Comment by peterdarthur** [comment]
If it makes any difference, it's loading SVG files for me, with domain-relative paths ("/path/to/image.svg"). I haven't tried full paths.

**Comment by verlok** [comment]
Hello,
you need to provide some more context if you need help. 
Can you put your sample code on Codepen or JsFiddle?

**Comment by verlok** [comment]
https://codepen.io/verlok/pen/WmzBob?editors=1000

**Comment by verlok** [comment]
The codepen above works, but I've put the default data attributes, which are `data-src` and `data-sizes`.

Since you used `data-lazy-src` and `data-lazy-sizes` you should create your instance of LazyLoad like that.

```js
var myLazyLoad = new LazyLoad({ data-sizes: "lazy-sizes", data-src: "lazy-src" });
```

Hope this helps!

**Comment by verlok** [comment]
@db-conception here's the Pen for your HTML case, eventually. 
https://codepen.io/verlok/pen/eXMayR?editors=1000

**Comment by db-conception** [comment]
Ok thank's. I resolved my problem.
