### ISSUE TITLE
Threshold reversed when scrolling up

### ISSUE THREAD

**Issue by peterdarthur** [verlok/lazyload#327]
**Is your support request related to a problem? Please describe.**
Let's say I visit a page with lazyload, scroll to the bottom, and reload the page. When scrolling **up** on a page with lazyload on and a threshold set to 300, images that enter at the top of the viewport appear only after they are **300px below the top** of the viewport, effectively a -300 threshold when scrolling up.

**To Reproduce**
1. Initialize Lazyload with a noticeable threshold (300+)
2. Scroll to bottom
3. Reload the page
4. Scroll up and see images load in, 300px below viewport top.

**Expected behavior**
I would expect the threshold to be the amount of pixels 
- below the bottom of the viewport
- **above the top of the viewport**

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version 11.0.3

**Desktop (please complete the following information):**
 - OS: Mac 10.13.4
 - Browser: Chrome
 - Version: Chrome 73.0.3683.75

**Comment by verlok** [comment]
Hi again @peterdarthur,
I can't reproduce this issue

I'm testing this on the demos in the demos folder. [Live demo here](https://www.andreaverlicchi.eu/lazyload/demos/image_simple.html).

What I did:
* Scrolled down until image 7
* Reloaded the page

Result: images 7, 8, 9 and also 6 were loaded.

Screenshot:

![image](https://user-images.githubusercontent.com/1127721/54665016-1f535800-4ae6-11e9-8464-3459de2e6bab.png)

**Comment by verlok** [comment]
PS: `300` is the default value of the `threshold` option, so it already does that without passing any option. Did you pass any different option?

**Comment by verlok** [comment]
Also find all the demos with their description, code and live example here:
https://github.com/verlok/lazyload#-demos

**Comment by peterdarthur** [comment]
Thanks, @verlok , I tried doing a codepen, but upon reloading a pen, it always starts from the top of the document.  The stakeholders in my project deemed the issue not worth working out, since visitors (almost) never reload at the bottom of a page, so I will just mark this as closed. 

For what it's worth, I used a custom threshold of 200, but I see in your demos (https://www.andreaverlicchi.eu/lazyload/demos/thresholds.html) that it works scrolling up as well. If you can't reproduce the issue, then it must have been something specific to my site. Thanks so much for your prompt responses!
