### ISSUE TITLE
Images displayed on Firefox but not Chrome

### ISSUE THREAD

**Issue by Tabrisrp** [verlok/lazyload#329]
**Describe the bug**
On the following page, the 2 images for the main events are correctly lazyloaded and displayed when the page is viewed on Firefox, but they are ignored on Chrome. The others images on the page are working correctly on both browsers.

**To Reproduce**
1. Go to https://www.healingroomssmv.com/events/ with Chrome
3. Scroll down to the main events section
4. Images for the events are not loaded

**Expected behavior**
Those images should be loaded when using Chrome

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version 11.0.3

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Chrome
 - Version 73

**Comment by verlok** [comment]
Hey @tabrisp,

I’ll have a look into that page tomorrow morning. 

In the meantime, could you provide some indications that might help me find the differences of behavior?

Are the main event images different in some way? CSS wise? JS wise? HTML wise?

**Comment by verlok** [comment]
I took a look and I was able to replicate the issue on Chrome.
(surprisingly, it doesn't happen on Opera which is a Chromium-based browsers)
Will dig dive.
Any details you might have missed here is precious.

**Comment by Tabrisrp** [comment]
Thank you for looking into this.

Part of the HTML around the images that are not processed is as follow:
```
<div class="et_pb_column et_pb_column_1_2 et_pb_column_1    et_pb_css_mix_blend_mode_passthrough">
	<div class="et_pb_module et_pb_image et_pb_image_0 et_animated et-waypoint et_always_center_on_mobile">
	<a href="https://www.healingroomssmv.com/new-believers/">
            <span class="et_pb_image_wrap has-box-shadow-overlay">
                <div class="box-shadow-overlay"></div>
                <img data-lazy-src="https://www.healingroomssmv.com/wp-content/uploads/2019/03/InHouse_NewBelievers_web_events.jpg" alt="" />
           </span>
       </a>
	</div>
</div>
```

There is also a `position: relative;` CSS attribute for the image. The `box-shadow-overlay` div has the following properties:
```
position: absolute;
z-index: 10;
top: 0;
left: 0;
width: 100%;
height: 100%;
pointer-events: none;
```

Example of an image processed:
```
<div class="et_pb_main_blurb_image">
        <a href="http://www.healingroomssmv.com/2017/10/bridge/">
            <span class="et_pb_image_wrap">
               <img data-lazy-src="https://www.marlevvll.com/wp-content/uploads/2017/10/bridge_healing_rooms_event.jpg" alt="Bridge logo overlaying the Golden Gate bridge." class="et-waypoint et_pb_animation_off" />
           </span>
        </a>
</div>
```

I don't know if the CSS could be the factor here. I'm not in control of it as it's generated by the Divi Builder on WordPress.

**Comment by alexandrecruz** [comment]
Same issue. I have noticed that using smaller screen size works for me but regular 1920x1280 doesn't.
Also, when I 'resize' by at least 1px the window size, the images are loaded.

Our code do no magic:
```
new LazyLoad({
    elements_selector: 'img[data-src],iframe[data-src]',
    thresholds: '30% 300px',
});
```

**Comment by Tabrisrp** [comment]
If it can help, this was not an issue with version 10.17 of the script.

**Comment by verlok** [comment]
@alexandrecruz and you use which version of the script?

**Comment by verlok** [comment]
If it can help, this was not an issue with version 10.17 of the script.

@Tabrisrp this is a useful information. Thanks. I'm trying and debugging it now with both versions.

**Comment by verlok** [comment]
@Tabrisrp I opened Chrome and enabled local overrides, changed the script you're using with 10.17.0, and the problem still remains. So it's not script-related, it's Chrome related, unfortunately. I'm investigating to find out if it's a bug on `IntersectionObserver` which happens in some corner case.

**Comment by verlok** [comment]
Well well,

after debugging for 1 hour I found out that those 2 images are correctly managed by LazyLoad and passed on to the `IntersectionObserver`, but Chrome's observer never calls the callback on those two.

So yes, it looks like a bug on `IntersectionObserver` which happens in some corner case. I will open a bug to Chrome about this.

I noticed that if you removed the `position: relative` from your `.et_pb_image img` selector, it works as it should and does on other browsers.

```css
.et_pb_image img {
    /* position: relative; */
}
```

I hope this solves for you.

**Comment by verlok** [comment]
Also please check that you're calling LazyLoad's `update` method `62` times, because of the MutationObserver you added in the page, which is watching on every single DOM tree modification. 

The `update` method should be called only when new DOM elements responding to the `elements_selector` option are added to the page, so you can probably remove the whole MutationObserver part from your page. I did, and everything still works.

**Comment by Tabrisrp** [comment]
Thank you for all your time and investigation. Hopefully this will be fixed in a future version of Chrome.

And also thank you for your recommendation about the MutationObserver part. This is unneeded for that page, but I took the time to investigate and wrote some code that will reduce the calls to the `update` method to only when the elements corresponding to the `elements_selector` are in a new node.

I'll close the issue now!

**Comment by verlok** [comment]
Good play. 
I’m glad you solved.

**Comment by omarshamali** [comment]
i tried all solutions above did not work, all browsers are showing the images yet not chrome:
var myLazyLoad = new LazyLoad({
    elements_selector: ".lazy",
			    to_webp: true
});
	
			
example html output:
<picture>
 					 <source data-srcset="XXXXXX95Q100W100H1556142620171597536.webp" type="image/webp">
  					 <source data-srcset="XXXXXX95Q100W100H1556142620171597536.png" type="image/*"> 
  					 <img class="lazy" data-src="XXXX95Q100W100H1556142620171597536.png" alt="">

				</picture>

**Comment by verlok** [comment]
@omarshamali you don’t need the `to_webp` option since you’re already using the picture tag to do the image selection job. 

Also you can remove the second `source` tag, the one with `image/*`, since the `srcset` in the regular `img` tag will work in all other images formats.

**Comment by verlok** [comment]
This should work:

```js 
var myLazyLoad = new LazyLoad({
    elements_selector: ".lazy"
});
```

example html output:

```html
<picture>
    <source data-srcset="XXXXXX95Q100W100H1556142620171597536.webp" type="image/webp">
    <img class="lazy" data-src="XXXX95Q100W100H1556142620171597536.png" alt="Image description goes here">
</picture>
```

Remember to add an image description in the `alt` attribute. It’s good for SEO and for accessibility.

**Comment by Irritated851** [comment]
@verlok https://csser.space/questions/firefox-presents-a-compact-box-positioned-between-the-images
