### ISSUE TITLE
Missing - fadein effect like in lazyload.jquery

### ISSUE THREAD

**Issue by eladcandroid** [verlok/lazyload#33]
Demo:
http://www.appelsiini.net/projects/lazyload/enabled_fadein.html

**Comment by verlok** [comment]
You can do it either in JS only or JS + CSS for the transition, passing a function to the `callback_load` setting.

**Comment by verlok** [comment]
Let me know if we can close this issue.

**Comment by eladcandroid** [comment]
Great. Thanks! :+1:  I'll close it.. :)

**Comment by verlok** [comment]
@eladcandroid I've added a fade-in demo without using callbacks, which only uses the CSS classes set by default by LazyLoad. [View source](https://github.com/verlok/lazyload/blob/master/demos/fade-in.html) || [See it in action](http://verlok.github.io/lazyload/demos/fade-in.html)

**Comment by verlok** [comment]
(I've update the links above, I had them misspelled)
