### ISSUE TITLE
Code Sandbox Demo Code Bug

### ISSUE THREAD

**Issue by ctowler157** [verlok/lazyload#330]
I don't really know how to report this other than through a github issue, so my apologies if this isn't the best way.

I was recently adding Iframe support to my application and was confused why it didn't JustWork until I eventually tracked down an issue with my initialization: I was passing the selector as `element_selector` instead of `elements_selector`. This was a silent bug, as the default param of `img` allowed it to work seamlessly in my application, but was problematic when I tried adding lazy Iframes. Anyways, long story short is I copied a lot of the initial setup from the react demo codepen, which has the following in the configuration:
![image](https://user-images.githubusercontent.com/16481282/55429426-7a129800-5559-11e9-9b88-3dd8cda9b64c.png)

I'm hoping you can fix this so any other lazy developers who copy initialization code doesn't have to deal with this.

**Comment by verlok** [comment]
Hey Chris,
what exactly you would expect LazyLoad to do in this case?

**Comment by ctowler157** [comment]
Nothing! Just update the codepen so that the config doesn't have the typo
(It reads `element_selector` instead of `elements_selector`)

**Comment by verlok** [comment]
This one 
https://codesandbox.io/s/20306yk96p

Will do. Thanks

**Comment by verlok** [comment]
Done
