### ISSUE TITLE
Can't defer background images according to Google PSI

### ISSUE THREAD

**Issue by o-nkar** [verlok/lazyload#333]
Hi

I am using the lazyload script on Wordpress website and works well on a normal image and background images on the website. But when I have tested the same page on Goole PSI then Google suggest me Defer offscreen images.
When checking the images then those images that are in the background using style tag are not deferred.

Please help.

**Comment by verlok** [comment]
Hey, thank you for reaching out. Would you mind share some of your HTML, CSS and JS code so that I can understand what’s happening?

**Comment by o-nkar** [comment]
Hi @verlok 

Thanks for the getting back to me, currently  I am using it on the Wordpress website and make lazyload of background images. 

and I think I am able to fix the issue on my end.

Thanks
