### ISSUE TITLE
LazyLoading not working correctly on firefox mobile

### ISSUE THREAD

**Issue by invisor** [verlok/lazyload#335]
Images not loading on mobile Firefox browser. It works fine on mobile Chrome and Safari instead of mobile Firefox.
Android 9
Firefox 66.0.2

Link to reproduce: https://www.emeralds.com/
Just scroll down. If you will scroll to the bottom, some images from above will be loaded

**Comment by verlok** [comment]
Hey @invisor,

I've tested it on Firefox mobile on a Samsung Galaxy 9 using BrowserStack. It seems to work perfectly to me.

![image](https://user-images.githubusercontent.com/1127721/56814288-2553fb80-683f-11e9-94a4-a162e0676d04.png)

Can you give me more detail?

**Comment by verlok** [comment]
Same on Android 7.1 

![image](https://user-images.githubusercontent.com/1127721/56814443-8380de80-683f-11e9-9304-3215c2138827.png)

**Comment by verlok** [comment]
And Android 9 on the Google Pixel 3

![image](https://user-images.githubusercontent.com/1127721/56814599-d5c1ff80-683f-11e9-9f21-f94df7e0c90d.png)

**Comment by invisor** [comment]
@verlok thank you for your help. I hope that this is my local problem. That's how the site looks at my mobile:
![photo_2019-04-26_21-36-19](https://user-images.githubusercontent.com/10770118/56815489-b04aeb00-686b-11e9-8ea2-cc7df0e73da9.jpg)

I have not idea what is going wrong

**Comment by verlok** [comment]
Yeah I guess. Have you tried with a different device? Maybe you turned off something on your local Firefox? Did it throw any error in the developer tools?
