### ISSUE TITLE
Lazy Loading not working for some hover images

### ISSUE THREAD

**Issue by graphicmist** [verlok/lazyload#336]
I am facing a problem where for some images on hover it is not loading the images. The issue is varying for different browsers and for different resolutions. For example, the hover image is not displaying for last two images in my chrome and same behaviour is being replicated for first and last image in a row in another system with higher resolution in chrome. For firefox it is working fine.

**Steps to replicate**
Goto website www.vegnonveg.com and hover on images, some of the images are getting displayed and some are not.

**LazyLoad version** version 11.06
Browser - Chrome [Version 73.0.3683.75]
Medium - Desktop

**Comment by verlok** [comment]
Hey @graphicmist ,
thank you for opening this.

This is your current html code for the images.

```html
<div class="img-switch img-box">
    <img class="placeholder" src="https://d423t6satclt9.cloudfront.net/resized/60X/640/reebok-atmos-x-fly-mobius-5cbdf935c0293.jpeg">
    <img class="img-normal lazy" data-src="https://d423t6satclt9.cloudfront.net/resized/400X328/640/reebok-atmos-x-fly-mobius-5cbdf935c0293.jpeg" alt="ATMOS X FLY MOBIUS">
    <img class="img-hover placeholder" src="https://d423t6satclt9.cloudfront.net/resized/60X/640/reebok-atmos-x-fly-mobius-5cbdf93662ba8.jpeg">
    <img class="img-hover lazy" data-src="https://d423t6satclt9.cloudfront.net/resized/400X328/640/reebok-atmos-x-fly-mobius-5cbdf93662ba8.jpeg">
</div>
```

I also saw that you're using the following to init LazyLoad:

```js
var lazyLoadInstance = new LazyLoad({
    elements_selector: ".lazy",
    callback_loaded: function(element) {
        $(element).prev('.placeholder').addClass('hidden');
    },
});
```

Doing so, you're targeting ALSO for the `.img-hover.lazy` images, and you're letting the IntersectionObserver (managed by LazyLoad) decide when an image is visible or not.

You could do something better. You could trigger yourself the `load()` method on the hover images. See the code in the `demos/load.html` demo. 

Let me know if this helps!

**Comment by graphicmist** [comment]
Thanks for the prompt reply. Let me test this out and get back to you.

**Comment by graphicmist** [comment]
Many thanks, the approach worked for me. Awesome library and awesome work!

**Comment by graphicmist** [comment]
Hi, I have one more issue in that. In chrome browser, if you check put throttling on browser as slow 3g and try hovering over image the library changes src without downloading the image.  This creates experience in which image placeholder goes blank. Moreover, the small image used in hover src is not loaded in chrome instantly. But it works well in firefox.

**Comment by verlok** [comment]
Hi there,
I’m glad it worked. 

The library now should download the images when you tell it to load them using `load()`, but it’s not the library that shows the image while it’s still blank. That should be you showing it at mouseover. The things I did in the demo linked above is to show the hover image only when it has the `loaded` class. 

Check the demo’s CSS code. You should do something like

```css
.img-hover.loaded { display: block }
```
