### ISSUE TITLE
Querystrings sometimes getting removed from src urls when revealed

### ISSUE THREAD

**Issue by PeteDuncanson** [verlok/lazyload#337]
**Describe the bug**
Have set the data-src attribute to a url which has a query string. When lazyload has finished processing the images src is set to the url minus the querystring:
![image](https://user-images.githubusercontent.com/1674590/57026902-ca514880-6c32-11e9-8114-347a0115b501.png)

**To Reproduce**
Difficult to do, I've been struggling to consistently get it however I think it happens when the image is already in the viewport (ie do a page reload when the image is already in view). I've got useNative set to true btw, tried without and same issue.

**Expected behavior**
The images url is set to the full url including querystring

**LazyLoad version**
v12.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 74.0.3729.108

** Context **
We use the querystring for resizing the images and have a cache buster on it.

**Comment by verlok** [comment]
Hey @peteduncanson,
thank you for opening this. 

The code inside LazyLoad only does a full copy of the URL in the data attribute to the src one, so I figure it’s hardly a problem cause a script itself. 

If you could possibly copy and paste the HTML code of one of your images (from the browser's “view source” command) and the JavaScript code you use to instantiate LazyLoad, options included, I can try to reproduce the issue.

**Comment by verlok** [comment]
Did you manage to solve this on your side?

**Comment by verlok** [comment]
I'm assuming you solved this. If you still need help, please reply. Feel free to reopen.
