### ISSUE TITLE
Lazy loading 3rd party widgets / scripts

### ISSUE THREAD

**Issue by dreamyguy** [verlok/lazyload#34]
As it is well known in the _lazy-loading_ community, **Lazy Load XT** helped many get the job done back in the days. Unfortunately it hasn't seen an update for over 2 years now...

It had a great feature, which was enabling one to lazy-load 3rd-party widgets like Google Ads, Facebook Buttons and other social widgets, that consist of both markup and script.

It would be great if **LazyLoad** had that baked in, but I'm unsure on how the approach would be on LazyLoad's context.

Below is a reference to the feature, with its documentation and source:

https://github.com/ressio/lazy-load-xt#widgets
https://github.com/ressio/lazy-load-xt/blob/master/src/jquery.lazyloadxt.widget.js

Cheers,
Wallace

**Comment by verlok** [comment]
Hello @dreamyguy, I decided not to add any extension to LazyLoad, because it's good as is its. Further development will imply support to the `picture` tag and eventually a conversion to ES2015.

The good news it that you can already lazy load iframes if you need to (like embedded codepens, vimeos, etc.)

**Comment by dreamyguy** [comment]
No worries @verlok, we ended up using your script anyway, and have noticed a significant improvement on performance. The `throttle` feature is a must and improved the experience on mobile browsers dramatically, especially on Android, where the "jumpy lag" was so obvious.

Just that one improvement over **Lazy Load XT** was enough for us to stick to **LazyLoad** for good. 👍

**Comment by verlok** [comment]
#perfmatters 👍🏼

**Comment by verlok** [comment]
Psst: have you already starred this repo? All you need to do is to press the Star ★ button on the top right corner of the website. ;)
