### ISSUE TITLE
it is support to add a placeholder in background-image?

### ISSUE THREAD

**Issue by jerryc127** [verlok/lazyload#340]

**Comment by verlok** [comment]
Hi @jerryc127,
yes. 

You can put your placeholder as background image, then load the real one when entering the viewport using `data-bg`. 

Does it make sense to you?

**Comment by jerryc127** [comment]
i use this to test , but i found a problem.
when the first time to visit the website, the background-image will show the placeholder and then the background-color, then the background-image.the background-image is showed from top to the bottom,
how to solve this problem?
![1222](https://user-images.githubusercontent.com/16351105/57996391-bd20ce80-7af9-11e9-9d8f-21ca741e5f4e.gif)

**Comment by verlok** [comment]
You can solve that effect using a real `img` tag instead of a background image.

**Comment by verlok** [comment]
Or, you can use a single image for the placeholder and the final one, if you convert it in the progressive JPEG image format.
