### ISSUE TITLE
Lazy load not working in specific conditions

### ISSUE THREAD

**Issue by piotrbak** [verlok/lazyload#341]
Hello!

First of all, thank you for your awesome work. Lately, we faced a problem when the placeholder is not being changed even if the markup is correct.

This problem happens only when using the specific (and popular) WordPress theme. When copying the markup into another theme, everything seems to work correctly. You can find the markup here:
http://snippi.com/s/q8clr8p

**To reproduce:**

- Please visit http://mega.wp-rocket.me/enfold/
- You can find the image here:
https://jmp.sh/W4FmuS3

**Observations:**

- When removing <a> link completely, lazy load works just fine. You can check it by scrolling down on the same page. I added this image in the same way but haven't included the link.
- It happens only on the Enfold theme, I copied the same markup with <a> link to another theme and it worked just fine
- Removing all JavaScript related to this theme didn't resolve this problem.

**LazyLoad version**
- Version [11.0.6]

Thank you for looking into this.

Have a great day!
Piotr

**Comment by verlok** [comment]
Hey there,
Thank you for opening this. 

Could you copy and paste the JavaScript code you use to create the instance of LazyLoad? I’d like to see the options passed. 

Also, have you tried this with version 12 of LazyLoad?

Third, if you copy and paste the HTML, CSS and JS code in a codepen, are you able to replicate the issue? It would be easier to debug there.

**Comment by verlok** [comment]
I took a closer look, I also wonder if the `noscript` tag is admitted inside the `a` tag. 
Give it a try without the `noscript` tag and let me know what happens.

**Comment by verlok** [comment]
And to finish, I can correctly see the image in the link you provided. 
Did you already manage to fix it?

![image](https://user-images.githubusercontent.com/1127721/58283848-adc7ac80-7da9-11e9-8dfa-a35da7ff7ef9.png)

**Comment by piotrbak** [comment]
Thanks for getting back to me so quickly.

The issue is still present for me. However, I can see that src is being replaced when changing the viewport of the browser. Please see attached:
https://www.loom.com/share/c940c1678fde4fccacf425d09bde070e

**Comment by verlok** [comment]
Hey there. Did you also read my previous comments ?

**Comment by piotrbak** [comment]
Hello!

My apologies, I wasn't able to check how it works on version 12 of the script nor the <noscript> case. I'll do my best to check it during the weekend.

When it comes to the code that is used to create the instance of LazyLoad, please find it attached here:
http://snippi.com/s/xc4unvq

I believe that everything will work just fine on Codepen, as we are not able to reproduce this issue even when using another WP theme. I can add it there though, please let me know if you want me to, I'll go for it during other mentioned checks.

**Comment by piotrbak** [comment]
I've just tested it with 12.0 version of the script and also without the `noscript` tag.
Unfortunately, it didn't help.

**Comment by verlok** [comment]
Hi there,

the code you copied and pasted makes sense to me, I think it’s correct. 

Given that I can’t reproduce the problem on the link you provided, I don’t know how to help you here. 

Are you sure it’s not a browser extension or setting that’s preventing the image to load on your side?

If you are, the only way I can help you is ask you to try and reproduce the issue on a Codepen. If the problem is in LazyLoad, it will happen there too.

**Comment by verlok** [comment]
I’m assuming you solved here. If you still need help and you can help me help you, feel free to reopen.

**Comment by piotrbak** [comment]
Hello!

My apologies for not reaching you before. I was waiting for the results of our tests to make sure it's resolved. This issue was fixed by changing default placeholder dimensions from 1 to 0.

The change can be found here:
https://github.com/wp-media/rocket-lazyload-common/pull/40/commits/412c1e69a186c4d151e1d49cd27526a3b36a0556

Thank you for your time, I really appreciate it.
Have a great day!
