### ISSUE TITLE
Images not loaded in Firefox - in new tab

### ISSUE THREAD

**Issue by PhocaCz** [verlok/lazyload#343]
Hi, not sure if this issue is caused by some common problem or it is somehow related to wrong use of the lazy load library.

**To Reproduce**
1. Open Firefox
2. Click on link to lazy load images website with CTRL Key pressed (to open the site in new tab). **Let the inactive tab completely load** and then see the site. The images are not loaded. This does not happen in Chrome.

Example: https://www.phoca.cz/stockphoto/ - click on this link with pressed CTRL in Firefox - when the site is completely loaded in new tab, visit it - the images are not loaded there.

**Expected behavior**
Expected is the behavior like in Chrome - the images will be loaded when the tab is active (visited)

**LazyLoad version**
- 12.0.0

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: **Firefox**
 - Version: 67.0 64 bit

**Screenshots GIF**
![Error](https://i.imgur.com/gOmDCaS.gif)

**Screenshots**
![Error](https://i.imgur.com/o9h9ElS.png)

vs:
![OK](https://i.imgur.com/mKonoma.png)

**Additional context**
**Be sure, the inactive tab is completely loaded. Visit it after the site is completely loaded!**

**Comment by verlok** [comment]
Hey @PhocaCz
thank you for opening this.

Unfortunately, Google says the link you provided is not safe to open.

![image](https://user-images.githubusercontent.com/1127721/58424234-49516980-8097-11e9-8ba1-78a2b63c7e93.png)

Could you please provide a Codepen or host your code somewhere else?

**Comment by PhocaCz** [comment]
Hi, hmmm, no idea why google marks it as not save. It is just a https link with standard certificate.

But it seems like I found the problem. I load the lazy load library in head with:

`<script async src=".../lazyload.min.js"></script>`

The async rule is Ok for Chrome but not for Firefox - in Firefox the library just needs to be uploaded at the bottom of the page. Then it works.

**Comment by verlok** [comment]
That might be the problem, or it might not be.

When you load the library as `async`, and you have the `window.lazyLoadOptions` set, the script will be initialized as soon as it's downloaded.

If Firefox runs the script before the DOM is ready, LazyLoad might not find anything to watch.

If you put the script in the bottom, it's all good!
