### ISSUE TITLE
Autodetect/Autocorrect missing "url()" function on data-bg attribute

### ISSUE THREAD

**Issue by juanmardefago** [verlok/lazyload#346]
**Is your feature request related to a problem? Please describe.**
This feature is not related to a problem per se, but rather to a major inconvenience while using this library on certain edge cases.

To keep it short, I'm working on a project where we replaced lazysizes with this library, because of performance problems. Lazysizes was used for a long time in this project, and since the API is quite similar, it wasn't much of a problem to migrate to this library, except for one super edge case: Because of reasons that I'm not aware of, we have an admin panel where you can edit html content of some pages, and then have them stored for serving the modified versions of those html pages. Some of these pages have lazyloaded images.

This html editor is extremely messy and convoluted, and for some reason it's really difficult to modify how it behaves, and it was made with the lazysizes API in mind.

Almost every lazyloaded element works perfectly, and most of the problems we had were trivial to solve, except for this one: to change all usages of data-bg from the lazysizes API to the lazyload API you would need to run a major storage migration.

**Describe the solution you'd like**
I've looked around in the codebase, and it seems that adding an autodetect/autocorrect feature in this library would be trivial, and would make it quite easier for anyone migrating from lazysizes to do it. I also don't think it would actually impact performance, since we could manage to do it by checking that the data-bg string begins with url(, and if it doesn't, we just add the missing bits of string.

I have no problem in doing the desired modifications and publish a PR, but I wanted to ask you first, since there might be a reason why this is not being done in the first place.

**Describe alternatives you've considered**
I considered just taking it on the chin and write myself all those ugly migrations, but this seems far trivial and it seems that it would be useful for some people, while not negatively affecting anyone.

I look forwards to your reply!

**Comment by verlok** [comment]
Hi @juanmardefago,

the reason why I didn’t put the `url()` is that the `data-bg` attribute can be used for _multiple background_ images, and in that case the code could be:

```html
<img data-bg="url(image1.jpg), url(image2.jpg), linear-gradient(to bottom, yellow, blue)"> 
```

Or it could be

```html
<img data-bg="linear-gradient(to bottom, yellow, blue), url(image.jpg)"> 
```

So you see that adding the `url()` there would break things. 

But if you want to use a single image and you want to avoid the `url()` part, you could just use the `data-src` attribute on any div or other tags. 

```html
<div class="lazyBg" data-src="image.jpg">
...
</div>
```

Then in js

```js
new LazyLoad({ elements_selector: ".lazyBg" })
```

This lazyload script decides where to put the `data-src` based on the type of tag. If it’s an image or an iframe, they become a `src` attribute. Otherwise, it will be placed in the background-image and **it would be automatically wrapped by a `url()`**.

You can also use a single lazyload instance for all your images and background images, just include all them in the `elements_selector` option. 

Does this work for you?

**Comment by verlok** [comment]
PS: I’m very glad to hear that you migrated to from lazySizes vanilla-lazyload because it’s best for performance. Could you please detail more? Thank you

**Comment by juanmardefago** [comment]
Hi @verlok, sorry for the delay!

Just after I opened the PR and tried to implement it I found out the same thing you just described, since it allows for multiple urls, and other background image properties (like linear gradient), it becomes quite more difficult to autodetect and autocorrect missing url fuctions.

Unfortunately, using data-src (which is awesome that you can do it, by the way) won't be really possible to solve this issue, since it means having to modify the html contents (replace data-bg in favour of data-src) and will unfortunately require to do some database migrations (since, again, we are storing modified html content in a database to allow for admin panel modification of html templates).

Nonetheless I think I found a way to add this functionality to single backgrounds, without affecting multiple backgrounds performance. If you want I can PR it as soon as it's done, so you can take a look and decide whether it's worth it or not.

Oh and also, really grateful for your time, and this awesome library!

**Comment by verlok** [comment]
Thank you, let’s switch the conversation to the PR then.

**Comment by verlok** [comment]
Hey @juanmardefago,
things changed on version 15. 

I found a way to manage background images's load/error event, so now background images are now getting the `loaded` or `error` class and calling `callback_loaded` and `callback_error`.

Take a look at the [changelog](https://github.com/verlok/lazyload/blob/master/CHANGELOG.md) and to the [upgrading guide](https://github.com/verlok/lazyload/blob/master/UPGRADE.md) if you're interested.

Have a nice day.
