### ISSUE TITLE
Webp Support

### ISSUE THREAD

**Issue by BadgersNadgers** [verlok/lazyload#349]
Ok, I can see that webp_to has been dropped but how do you auto webp on background images? 

The case for the webp_to being dropped seems mostly about the picture tag which doesnt help with background images 

https://github.com/verlok/lazyload/issues/288

Is there a way to webp_to for back ground images ...
I know comments said its now Meh -- but not only does picture now need a polyfill but have we lost webp_to on background images also?

Such as shame to lose it and now have to add in polyfills

**Comment by verlok** [comment]
The picture does not require a polyfill, because if the browser doesn’t understand the picture tag it will simply ignore it. And it’s OK if ignores it because browsers that don’t  understand the picture tag also don’t  read the WebP image format.

**Comment by verlok** [comment]
Secondly, why do you need lazy load for background images? Most of the times that people ask me about lazy loading background images they were supposed to use content imaged for both accessibility and SEO.

**Comment by verlok** [comment]
Third point: I don’t remember if older version of lazy load supported the switch to WebP in the background images. Did you check this?

**Comment by verlok** [comment]
To give you the full context,

- to universally detect whether or not your browser supports webs is very complex to do in javascript and it will add too many lines of code to this lazyload script
- to manipulate the URL of your images to transform your JPG URL to WebP URL is not easy to do, and it would add more lines of code to this LazyLoad script 

Ultimately, I don’t think it’s LazyLoad’s job to check if your browser supports WebP or not, and to manipulate the URL of your images consequently.

**Comment by BadgersNadgers** [comment]
interesting, my assumption was previous versions did webp background images
because everything passed the lighthouse test at pagespeed insights
Maybe there is an issue there with lighthouse?? i.e if webp isnt being
changed on the back ground images it is being passed as using webp by
lighthouse, but not when web_p switch is switched off!

Im wanting to lazy load back images because its an image heavy website and
more of a visual sale than an SEO concern as SEO is not so important in
this market, traffic comes from paid routes and other marketing.

**Comment by BadgersNadgers** [comment]
Am going to follow your suggestions re picture tag and webp and use
modernizr to switch to webp on background images (hopefully in sync with
lazy load)
