### ISSUE TITLE
Can the save-data client hint request header be supported in your script?

### ISSUE THREAD

**Issue by dklinzing** [verlok/lazyload#351]
**Is your feature request related to a problem? Please describe.**

Browsers are starting to support the save-data client hint request, where a browser is specifically asking a web experience to prioritize low data usage when serving content.  Currently, there is no way to define specific images to users with this preference turned on using this lazy loading library.  

See https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/save-data/ for more information on the save-data client hint.

**Describe the solution you'd like**

Would it be possible, or make sense, to include this in your library so as a user I can specify images that should lazily load to those w/ save-data turned on?

**Describe alternatives you've considered**

We could handle this on our own by passing different, lower resolution, srcs into the lazy loader before initializing it.

**Additional context**

**Comment by verlok** [comment]
Hey there. You can already use responsive images with the `srcset` attribute, so that browsers will choose the best format to satisfy the users request to save data. This should be a browsers implementation and work also on regular images and native lazy images, so I wouldn't implement it here.
