### ISSUE TITLE
Why don't my images show up with lazy load plugin?

### ISSUE THREAD

**Issue by DevinDkCreative** [verlok/lazyload#352]
Hi guys, I've been having troubles getting my featured images to show up across my whole Wordpress website. On my home pages, all my posts, etc. I know it's the Lazy Load plugin because when I deactivate it, the featured images go back. The problem is when I deactivate it my page speed skyrockets down to the red.

I'm wondering if there is a setting in Lazy Load I am missing or anything I can do to fix this problem. Thank you very much for your help and my website being affected is [Airbnb Universe](https://www.airbnbuniverse.com).

**Comment by verlok** [comment]
Would you please provide some of your HTML and JS code and how you load the portions of the DOM containing the images?

**Comment by verlok** [comment]
I'm assuming you solved. Feel free to reopen if you still need help.
