### ISSUE TITLE
Request: Provide typings with npm package

### ISSUE THREAD

**Issue by hustlahusky** [verlok/lazyload#356]
**Is your feature request related to a problem? Please describe.**
Hello. I'm mostly using Typescript in my projects and it would be nice if you can provide Typescript typings alongside with npm package. It will be very useful for me and other developers who using Typescript. And I'll can use cool imports, like this:

```ts
import LazyLoad from 'vanilla-lazyload';
```

instead of doing this:

```ts
// tslint:disable-next-line:variable-name
const LazyLoad = require('vanilla-lazyload/dist/lazyload.esm').default;
```

**Describe the solution you'd like**
The only changes you need to make are add `typings` directory to `files` property in `package.json` and specify path to `./typings/lazyload.d.ts` in `type` property of `package.json`.

**Comment by verlok** [comment]
Hey there, thank you for opening this. Since you already know how to do it, why don’t you open a pull request?

**Comment by hustlahusky** [comment]
I started using your library today and I had no time to open PR yet. I think I can try to do it later

**Comment by hustlahusky** [comment]
@verlok hi. I opened pull request #357 to resolve this issue. Can you review it?
