### ISSUE TITLE
when componentDidUpdate data-src is different from src

### ISSUE THREAD

**Issue by rainydayDY** [verlok/lazyload#358]
**Describe the bug**
The presentation is correct usually, but when I update the parent component,and the props is correct,so the data-src is correct, but I find the src is not updated。

here is :
```
export class LazyImage extends React.Component {

    static propTypes = {
        alt: PropTypes.string,
        srcset: PropTypes.string,
    }
    componentDidMount() {
        document.lazyLoadInstance.update();
    }

    componentDidUpdate() {
        document.lazyLoadInstance.update();
    }

    render() {
        const { alt, srcset } = this.props;
        return (
            <picture>
                <source type='image/webp' data-srcset={srcset}/>
                <img data-src={srcset} className="lazy" alt={alt} url={srcset}/>
            </picture>
        );
    }
}

export default LazyImage;

```
**To Reproduce**

**Expected behavior**

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version [12.0.0]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Screenshots**

**Additional context**

**Comment by verlok** [comment]
Yes that's because, to save memory and CPU time, once an image has been loaded it gets "unwatched" by LazyLoad. If you change the `data-src` value again, make sure to call LazyLoad's `load(element, true)` (the second parameter is `force`) to load it again, as @RaZeR-RBI was suggesting in #361.
