### ISSUE TITLE
Migrating to ES6

### ISSUE THREAD

**Issue by dientuki** [verlok/lazyload#36]
Hi, i take a look to your code and it's great. I'm working in a big proyect for a medium and we have all the js in es6, transpiling it with babel. Are you planning to migrate to ES6?

Thanks

**Comment by verlok** [comment]
Hi @dientuki,

I thought about doing it, but I'm afraid that the ES5 code written by Babel could be heavier than the one I can write directly.
Anyway I should think migrating to ES6, as browsers are starting to support it natively.

Thank you for asking.
If you want to help me doing this, I'm open to pull requests :+1:

**Comment by verlok** [comment]
I'm working on this on the branch `feature/es2015`.
Any help / pull request is welcome.

/cc @dientuki @ricardobrandao @benago

**Comment by ricardobrandao** [comment]
Hi @verlok

Hi have some work on that branch. I'll create a PR tomorrow. However I am using static properties - [stage 2](https://github.com/tc39/proposal-class-public-fields) - which are not supported by the uglifier and therefore we can't uglify the original source code. Should we move the default settings to a variable inside the constructor (i.e. not accessible outside)?

**Comment by verlok** [comment]
Oi @ricardobrandao,
obrigado por estar trabalhando com meu script :)

I was thinking about using very simple ES6/ES2015 features, so to the script wouldn't need to be transpiled to ES5 for the most recent browsers (Chrome, Opera), but I'm ready to change my mind if you can convince me.

To answer your final question, imho it's not a problem if the default settings are not accessible from outside.

**Comment by verlok** [comment]
@ricardobrandao veeery good job! I think we can merge the branch `feature/es2015` in the `development` branch now. Then I'll get everything ready to release it to the world soon (including to cdnjs.com)

**Comment by verlok** [comment]
Merged in.

**Comment by ricardobrandao** [comment]
Great. On a related note, we might want to take a look at [this](https://www.youtube.com/watch?v=ncYQkOrKTaI&feature=youtu.be) (source [here](https://github.com/GoogleChrome/sample-media-pwa/blob/master/src/client/scripts/helpers/lazy-load-images.js)) example from Paul Irish as soon as [intersection observers are in a stable state](https://wicg.github.io/IntersectionObserver).

**Comment by verlok** [comment]
Psst: have you already starred this repo? All you need to do is to press the Star ★ button on the top right corner of the website. ;)
