### ISSUE TITLE
add arguments in callbacks

### ISSUE THREAD

**Issue by ar53n** [verlok/lazyload#360]
**Is your feature request related to a problem? Please describe.**
I want do custom operations for items and some calculations.
And also we can add method **_lazyLoadInstance.markAsLoaded()_**

**Describe the solution you'd like**
I suggest pass to callbacks 3 arguments. It will look like this.

```js
callback_enter: (el: HTMLElement, entry: IntersectionObserverEntry, lazyloadInstance) => {
    // console.log('Loading', el);
},
```

**Comment by verlok** [comment]
I guess this is not a big deal to implement, I can see why you could take advantage of the IntersectionObserverEntry, but why would you need the lazyloadInstance in the third parameter?

**Comment by verlok** [comment]
Ok now I get it.
I've made the edit in a branch called `feature/callbacksMoreArguments`.

Callbacks have now more arguments:

- callback_load(el, instance)`
- callback_error(el, instance)`
- callback_finish(instance)`
- callback_reveal(el, instance)`
- callback_enter(el, intersectionObserverEntry, instance)`
- callback_exit(el, intersectionObserverEntry, instance)`

Would you be satisfied with this solution?

**Comment by ar53n** [comment]
@verlok its look good, but i think better for `callback_enter` and `callback_exit` change parameters positions
from `(el, intersectionObserverEntry, instance)` to `(el, instance, intersectionObserverEntry)` for better user experience.
or we can put the "instance" in callbacks as the first parameter

**Comment by verlok** [comment]
I can’t change the current first argument because I need to be backward compatible. 

The reason I’ve ordered the items this way is that I think that the instance argument would be the lesser used, so I’ve put it in the 3rd place.

**Comment by ar53n** [comment]
@verlok but wait in `callback_enter` `callback_exit` now have only one param its element. And i suggest swap last 2 params `intersectionObserverEntry` and `instance`

**Comment by verlok** [comment]
Ok I will swap them. 

I didn’t understand the following sentence:
> in callback_enter callback_exit now have only one param its element

Could you please clarify?

**Comment by ar53n** [comment]
> Could you please clarify?

i mean in current version we have only one params in that callbacks and this change does not break backward compatibility

**Comment by verlok** [comment]
In `callback_enter` and `callback_exit` the reason I’ve ordered the items this way is I think that the `IntersectionObserverEntry` would be more (by a wider user basis) used than the LazyLoad instance. 

Furthermore, leaving them this way:

```
callback_enter(el, intersectionObserverEntry, instance)
callback_exit(el, intersectionObserverEntry, instance)
```

they are ordered by specificity. The more specific is the element, the intersectionObserverEntry is related to the element, and the instance is on top of all. 

I'll leave it like this.

**Comment by verlok** [comment]
There you go! Version 12.3.0 is out with its brand new callbacks arguments.
