### ISSUE TITLE
callback_enter is not firing on IOS 12.1.4

### ISSUE THREAD

**Issue by anthonygelinas** [verlok/lazyload#363]
Images does not load on safari in ios 12.1.4 for this demo :
https://www.andreaverlicchi.eu/lazyload/demos/lazily_load_lazyLoad.html

**Comment by verlok** [comment]
Could you please upload / link a video that can demonstrate this?

**Comment by faradaytrs** [comment]
I confirm the problem doesn't work on iPhone 8 iOS 12.4.1

**Comment by verlok** [comment]
No additional information arrived. Closing this. 
Feel free to reopen if you can report more information
