### ISSUE TITLE
Lazy loading a video poster image

### ISSUE THREAD

**Issue by smrubin** [verlok/lazyload#365]
Didn't see it mentioned in the docs, but was wondering about support for lazy loading the poster image for a video element.

I've seen it implemented in a similar lazy loading lib: https://github.com/malchata/yall.js/issues/32

Thanks!

**Comment by verlok** [comment]
So the thing you’re asking is to make the poster images lazy as video. Right?

**Comment by smrubin** [comment]
I think we are talking about the same thing.

To clarify, asking for lazy loading of the poster image (via the poster attribute) for video elements.

**Comment by verlok** [comment]
So something like that would be fine for you?

```html
<video class="lazy" controls width="620"
    data-src="lazy.mp4" data-poster="lazy.jpg">
    <source type="video/mp4" data-src="lazy.mp4">
    <source type="video/ogg" data-src="lazy.ogg">
    <source type="video/avi" data-src="lazy.avi">
</video>
```

**Comment by verlok** [comment]
Just released in version 12.4

**Comment by smrubin** [comment]
@verlok Yeah that looks great, thanks for implementing!

**Comment by verlok** [comment]
You're welcome.

**Comment by skreutzberger** [comment]
Hi, super interesting for me, too. How would I do it using Videojs under React? Just add another property to the `videoJsOptions` as described here https://videojs.com/guides/react/?

Lighthouse tells me `Defer offscreen images` for my video poster images when they are still not visible. It seems they are identified with `div.vjs-poster`. 


I tried adding  the properties `className: "lazy"` and `class:"lazy"`  but still the poster image is not lazily loaded. 

Thanks for the help!
