### ISSUE TITLE
LazyLoad v12.0.0 does not load all images

### ISSUE THREAD

**Issue by baszero** [verlok/lazyload#366]
**Describe the bug**
I just upgraded to Version 12. Now images do sometimes NOT appear. When I reload the page, they appear sometimes.
The HTML looks ok, like:

`<img data-src="/img/blabla.jpg">`

**To Reproduce**
I run the default installation and I just load my webpage.
It can not be reproduced, as it might be related to the order and number of images that have to be loaded.

**Expected behavior**
it should load ALL images ALWAYS, without exception. This way v12 is not production-ready yet!

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version 12.0.0

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G87)
 - Browser Chrome
 - Version 76.0.3809.100 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
not tested

**Comment by baszero** [comment]
This bug is most probably related to #350 , and I think I could fix it with the following workaround:

I only added this to my CSS:

```
img[data-src], img[data-srcset] {
	min-height: 1px; min-width: 1px; 
}
```

Now the problematic images, that sometimes got loaded or not, do now load all the time. 

Thanks to user @sevenflip

**Comment by verlok** [comment]
Thank you @baszero,
when you say that v12 is not production ready, you mean that the previous versions, v11.x isn’t affected by the Chrome 75.x bug?

**Comment by baszero** [comment]
Hi @verlok , no, I was just saying that version 12 is not production-ready (i'm not saying that lazyload has the bug, maybe the bug is in Chrome, but for me as an application provider, I can't use this version yet in a live system).

I upgraded from v5.5.0, that worked fine as expected.

**Comment by verlok** [comment]
Yes, if your tied to a specific version of Chrome and the issue was resolved by the Chrome team in later versions, you should definitely switch back to a previous version of LazyLoad. Version 8.x is the latest that doesn't use IntersectionObserver.

**Comment by baszero** [comment]
Ok, so you're saying that I should switch back to https://github.com/verlok/lazyload/releases/tag/8.17.0 for production environments?
