### ISSUE TITLE
v12.0.0 has issues with Firefox 68.0.2

### ISSUE THREAD

**Issue by baszero** [verlok/lazyload#368]
**Describe the bug**
I have situations where an image does not load in Firefox 68.0.2 but it loads in the latest Google Chrome or Safari.
I don't know what the root cause is but maybe someone else is also experiencing problems with v12 and Firefox?

**LazyLoad version**
v12.0.0

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G87)
 - Browser Firefox 68.0.2

**Comment by baszero** [comment]
Just to mention: the version https://github.com/verlok/lazyload/releases/tag/8.17.0 works fine with Firefox 68.

I would recommend to add a disclaimer at the v12 documentation page that there might be still issues with some browser.

**Comment by verlok** [comment]
@baszero could you provide some code, a codepen or a link to replicate the issue? Otherwise it would be impossible to investigate on it.

**Comment by baszero** [comment]
Well, there is nothing special about it. It is just a normal HTML IMG tag, nested inside many DIVs (page layout).

**Comment by mikey242** [comment]
Interestingly for me all images on the page load immediately in Firefox (i.e immediately on page load) but in Chrome it works as expected.

**Comment by verlok** [comment]
> Interestingly for me all images, both background an img tag, load immediately in Firefox (i.e immediately on page load) but in Chrome it works as expected by loading on scroll.

This behaviour is triggered by the `loadAll` method, which on versions that rely on `IntersectionObserver` is called immediately is the `IntersectionObserver` is not detected in the browser, and you didn't load a polyfill before.

**Comment by verlok** [comment]
Hello @baszero 
I've tried to reproduce the issue on Firefox 68 using Browserstack, but I couldn't.
Closing this, but if this is still an issue for you, feel free to reopen it and comment.
