### ISSUE TITLE
Webp data-src for backgrounds

### ISSUE THREAD

**Issue by mihail-minkov** [verlok/lazyload#370]
The situation I am having is that I often use transparent PNG placeholders to maintain the aspect ratio of a container. Then I add a lazy-loaded background to the parent container of the PNG thus making something similar to a clipping mask in Photoshop.

The structure I use is similar to this. The PNG is a 3x2 pixels extended to `width: 100%; height: auto` transparent image, thus always maintaining a 3:2 proportion.

```
<div class="prop-img lazy" data-src="./images/image.jpg">
  <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAACCAQAAAA3fa6RAAAADklEQVR42mNkAANGCAUAACMAA2w/AMgAAAAASUVORK5CYII=" alt="3:2 transparent PNG">
  <span class="prop-op">For Sale</span>
</div>
```

Recently I've started using a lot of WebP images, so if it's a `<picture>` tag I have no problem I just assign the respective sources and it's done. If it's a CSS defined rule with an ID or a class, I just use the `.no-webp`, `.webp` classes that Modernizr gives me, but the one case where I don't have any option (that I'm aware of) is when it's an inline background.

So basically the idea is to add something like a `data-webp-src` and maybe when both are available and usable to use the webp version.

In the case of the above code, I imagine something like this:

```
<div class="prop-img lazy" data-src="./images/image.jpg" data-webp-src="./images/image.webp">
```
Another option could be something like:

```
<div class="prop-img lazy" data-srcset="[./images/image.jpg, image/jpeg], [./images/image.webp, image/webp]">
```

Zurb Foundation uses this approach for their data-interchange function, but in that case the second parameter is the breakpoint, in this case it would be mimicking the picture srcset.

**Comment by verlok** [comment]
Hi @mihail-minkov,

> I often use transparent PNG placeholders to maintain the aspect ratio of a container. Then I add a lazy-loaded background to the parent container of the PNG thus making something similar to a clipping mask in Photoshop.

Your solution is very creative, but it's not good for the websites you develop, because background images are totally ignored by search engines and assistive technologies.

There are better ways to reserve space for your images before they load. One is [right here](https://github.com/verlok/lazyload#occupy-vertical-space-and-maintain-ratio), in the README file of this project. Another good one uses SVGs and it's explained [here on CSS tricks](https://css-tricks.com/preventing-content-reflow-from-lazy-loaded-images/#article-header-id-2).

I advice you for one of those, then use a `picture` tag like described in the README if you want to make your browser to automatically load webp files.

Another way could be to use a cloud-based image manager like Akamai Image Manager or Cloudinary, which also automatically serve the more modern Jpeg2000 image format to Safari, which doesn't support WebP.

**Comment by mihail-minkov** [comment]
Thanks @verlok . In many cases the images are actually used as backgrounds but since I want to keep the same aspect well I use the transparent png technique. In the examples you showed me the end result would be the original image because the `data-src` would eventually substitute the 3:2 transparent placeholder. I actually wasn't aware of that svg trick, but it's basically the same thing, just in my case I require a different end result.

As for the search engine as I mentioned in most cases the images are used more as a background rather than content, so I don't think it should affect so much.

The other option would be to create a helper that resizes and crops the images to the proportion I require, but it would be too heavy compared to this option.

As for the webp thing Akamai could be an option, but what if the project doesn't contemplate the cost of using a CDN? I already have processes in my site that convert images to webp, I just don't have an easy way to load the formats.

I use Modernizr to set the `.webp` and `.no-webp` class, but I am not aware if there's a way to use this class when lazy loading the images.

**Comment by mihail-minkov** [comment]
Also, I got curious, which would be better in terms of performance.

The png:
`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAACCAQAAAA3fa6RAAAADklEQVR42mNkAANGCAUAACMAA2w/AMgAAAAASUVORK5CYII=`

or

The svg:
`data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 3 2'%3E%3C/svg%3E`

**Comment by verlok** [comment]
> which would be better in terms of performance?

The SVG is shorter: only 91 bytes vs the 120 bytes of the PNG. Plus, the SVG doesn't grow much if you want to achieve different ratios e.g. 16:9, but the PNG would consistently grow in size.

**Comment by verlok** [comment]
As for your request, LazyLoad already had a WebP detection and feature and specific options in previous versions (10.14.0 introduced it), but:

- detection was very tricky and expensive;
- we discussed for long about use cases and then I decided to drop it. [Read the discussion](https://github.com/verlok/lazyload/issues/288)

The support was then dropped in version 11.0.0.

**Comment by mihail-minkov** [comment]
Well yes but from what I see that discussion was still related to images rather than backgrounds.

What happens if I already have the webp images and I only need the switch, I also use Modernizr to detect this so it could be a mix with the classes added by Modernizr.

**Comment by verlok** [comment]
Hey @mihail-minkov ,
you might find inspiration on this page http://www.stucox.com/blog/using-webp-with-modernizr/

```js
Modernizr.on('webp', function (result) {
  // `result == Modernizr.webp`
  console.log(result);  // either `true` or `false`
  if (result) {
    // Has WebP support
  }
  else {
    // No WebP support
  }
});
```

For example, you could use the detection to replace all the URLs pointing to JPG to WEBP files in the `data-src` before lazyload is instantiated.

**Comment by verlok** [comment]
I'm assuming you solved. Feel free to reopen if you still need help.

**Comment by mihail-minkov** [comment]
Hello @verlok ,

Sorry for taking so long to answer. In the end I followed your Modernizr recommendation and I did this:

```
Modernizr.on('webp', function (result) {
    if (result) {
        var lazyBg = document.querySelectorAll("[data-bg]");
        lazyBg.forEach(function(element, index) {
            var bg = element.dataset.bg;
            bg = bg.replace(new RegExp("\\jpg|jpeg|png"), "webp");
            element.setAttribute("data-bg", bg);
        });

        var lazyBgHD = document.querySelectorAll("[data-bg-hidpi]");
        lazyBgHD.forEach(function(element, index) {
            var bg = element.dataset.bgHidpi;
            bg = bg.replace(new RegExp("\\jpg|jpeg|png"), "webp");
            element.setAttribute("data-bg-hidpi", bg);
        });
        var lazyMultiBg = document.querySelectorAll("[data-bg-multi]");
        lazyMultiBg.forEach(function(element, index) {
            var bg = element.dataset.bgMulti;
            bg = bg.replace(new RegExp("\\jpg|jpeg|png"), "webp");
            element.setAttribute("data-bg-multi", bg);
        });

        var lazyMultiBgHD = document.querySelectorAll("[data-bg-multi-hidpi]");
        lazyMultiBgHD.forEach(function(element, index) {
            var bg = element.dataset.bgMultiHidpi;
            bg = bg.replace(new RegExp("\\jpg|jpeg|png"), "webp");
            element.setAttribute("data-bg-multi-hidpi", bg);
        });
    }
});
```

I tried doing it inside my script file using jQuery before the lazyLoad instance, but it only worked for images that were not visible. I ended up putting it inline in my `head` element, right after the Modernizr initialization and it worked. I suppose this snippet could be useful to someone.
