### ISSUE TITLE
Hello, tried to load YouTube video inside an iframe and did not work

### ISSUE THREAD

**Issue by inglesuniversal** [verlok/lazyload#371]
Does your script support YouTube videos?

Tried this code with no luck (just got a gray screen as blocked content)

`<iframe class="lazy" data-src="https://www.youtube.com/watch?v=8Kv_bW0OF1k;autoplay=0&amp;rel=0&amp;controls=0&amp;showinfo=0" poster="https://img.youtube.com/vi/8Kv_bW0OF1k/mqdefault.jpg" style="width:100%;height:100%;"></iframe> `

**Comment by verlok** [comment]
Hey there, 
you're trying to include a full youtube page in an iframe.
Probably there'a youtube restriction performing this operation.
Sorry I can't help you here, this is out of scope.
