### ISSUE TITLE
Release notes missing info about callback renamed

### ISSUE THREAD

**Issue by zipper** [verlok/lazyload#372]
When updating from 10 to 12, I find out, that the callback `callback_load` has been renamed to `callback_loaded`, but there is no mention in release notes. The change happened in release 11 with other "callbacks renewed". Could you please add that for others?

**Comment by verlok** [comment]
You can find that information in the CHANGELOG.md file. 
Where would you want to find it?

**Comment by zipper** [comment]
I can't find any mention of that. There are other changes to callbacks described, but not this changed. I searched the release notes, but can't find it in changelog either. I believe it has been forgotten to mention.

Still I consider this library priceless, so thank you!

**Comment by verlok** [comment]
Fixed that in 12.0.1
