### ISSUE TITLE
couldnt load image using cdn

### ISSUE THREAD

**Issue by truongson0909** [verlok/lazyload#373]
tried use lazyload but i dont know why image cannot load and display.
for example picture
https://imgur.com/4TAzZ43
but the link image existed.
https://imgur.com/4ZwhE1K
can you help?

**Comment by verlok** [comment]
Hey @truongson0909 ,
from what I see in the screenshots, the image has been loaded because the `lazyloaded` class was applied.
Are you sure it's not hidden for some reason?

**Comment by verlok** [comment]
I’m closing this. Reopen if you still need help.
