### ISSUE TITLE
<standing ovation>

### ISSUE THREAD

**Issue by Blake-LeBlanc** [verlok/lazyload#374]
Hello Andrea! 

Your lazyload plugin is awesome and the documentation you provide for it has been a lifesaver! Thank you for all the time and effort you've put into it, it shows!

All the best from a happy lazyload user,
Blake

**Comment by verlok** [comment]
Thank you, @Blake-LeBlanc, 
we open source developers take compliments as fuel to go.

Thanks for filling up on it.
Cheers! 🥂
