### ISSUE TITLE
callback_enter is not fired on Chrome 37

### ISSUE THREAD

**Issue by crystalbit** [verlok/lazyload#375]
Hi!

**Describe the bug**
callback_enter is not fired on Chrome 37

**To Reproduce**
ua: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.94 Safari/537.36
```
    lazyLoadInstance = new LazyLoad({
        elements_selector: ".image",
        threshold: 200,
        callback_enter: function(el) {
            console.log("callback_enter")
        }
    });
```
.image are divs

**Expected behavior**
console-log appears in modern browsers, but not in chrome 37 on mac

**LazyLoad version**
- Version: 12.0.2

**Desktop (please complete the following information):**
 - OS: mac os
 - Browser Chrome 37

also seems to be related to https://github.com/verlok/lazyload/issues/363

**Comment by verlok** [comment]
Hey @crystalbit ,

I've tested Chrome 37 using BrowserStack and I've noticed it doesn't support IntersectionObserver (see screenshot below), so all images are loaded immediately (see same screenshot). This is not a bug at all, it's a way to avoid breaking the web page.

What you need to do is to use the IntersectionObserver polyfill. The ways to do that are documented in the README file.

Cheers!

![image](https://user-images.githubusercontent.com/1127721/65910640-6a222680-e3cb-11e9-9d87-212774788491.png)
