### ISSUE TITLE
LazyLoad not working on Safari 13 (OSX)

### ISSUE THREAD

**Issue by joalsan** [verlok/lazyload#377]
**Is your support request related to a problem? Please describe.**
I'm using vanilla-lazyload script with Safari 13.0.1 (14608.2.11.1.11, OSX version) and it is not working properly (images are loaded immediately). It seems to work OK on Chrome, Firefox and Safari (IOS version).

**To Reproduce**

HTML

```html
<img class="lazyload" data-src=...>

<script src="https://cdn.jsdelivr.net/npm/intersection-observer@0.5.1/intersection-observer.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vanilla-lazyload@12.0.2/dist/lazyload.min.js"></script>
```

JS 

```js
var lazyLoadInstance = new LazyLoad({
  elements_selector: ".lazyload"
});
```

You can test on my website (joalsan.pythonanywhere.com).

**LazyLoad version**
- Version 12.0.2

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Safari
 - Version: 13.0.1 (14608.2.11.1.11)

**Comment by verlok** [comment]
Hey @joalsan,
first of all, congratulations for the micro machines collection!

I've just tested the website on my Mac with Safari 13.0.1 and I cannot reproduce the issue. I you open the network panel, you can see the images are actually loaded as the user scrolls down.

What's the problem then?

**Comment by verlok** [comment]
![image](https://user-images.githubusercontent.com/1127721/65912837-24fff380-e3cf-11e9-9a74-62d1145d83de.png)

Then, scrolling down...

![image](https://user-images.githubusercontent.com/1127721/65912876-35b06980-e3cf-11e9-83a0-0e8b4e4d5562.png)

**Comment by joalsan** [comment]
Ciao Andrea!

Thanks for your support!

In your case it seems to work perfectly, so there would be any
difference... When I do the same, Safari downloads all the images (I see 21
MB where you see only 3,28MB...).

I will continue the research, thanks anyway!

**Comment by verlok** [comment]
No problem. 
If you find out what was causing the issue on your machine, please share!

**Comment by hummal** [comment]
Got the same problem. It is happening over all Apple devices. I guess it depends on Apples Safari Webkit version which is requirement for ALL browsers on iOS/iPadOS or MacOS to be the Safari Webkit version.

Means this behaviour is directly related to Apple Webkit and can not be reproduced with Chrome on any other OS then Mac/iPad/i-OS

In my case the images are loading correctly even in Safari as can seen in DOM Explorer. Also the CSS is correct as it should be. But it is not drawn to the page. If I scroll a bit it starts drawing those images. Im my case I can play around with the opacity (set to 0 then set to 1) and it starts working without scrolling. 

I will search further in the opacity direction. But I guess it is not an lazyload issue.
