### ISSUE TITLE
Question: Passing objects along images for callbacks?

### ISSUE THREAD

**Issue by thurfir** [verlok/lazyload#378]
Hello, 

I would like to pass some (complex) data by-image to be used inside the callbacks events, is it possible?

Thank you.

**Comment by verlok** [comment]
Please explain what you mean by “pass some complex data” and what do you need to do inside the callback.

**Comment by thurfir** [comment]
Hello @verlok , my requirement is to send some analytics when an image is loaded: the type of image viewed, its classification, some metadata..

For now I'm considering adding a data-x attribute key to my images and storing the image's data in a global array, but a configuration like:

`var aLazyLoad = new LazyLoad(options, [{ element: myImage, data: myData}, { ... }]);`

would be helpful.

**Comment by verlok** [comment]
Hey @thurfir,
you could store data in a data element of the images HTML, then read it upon loaded using the `callback_loaded` callback.

I've created an example here: https://codepen.io/verlok/pen/GRRJPwG
Here I store a number and a string, but you could store only the ID and keep the data in your data layer or whatever you have.

Please let me know WhatsApp

**Comment by thurfir** [comment]
Yes this (id + data array) is the solution I was talking about, I was wondering if there were a better way than attaching ids to my images and storing a global array in my pages. This will do for now ;-)
