### ISSUE TITLE
reduce npm node_modules filesize

### ISSUE THREAD

**Issue by staabm** [verlok/lazyload#379]
installing the module via npm creates a huge amount of files in the node_modules directory.

it would be great if the package, installable via npm would only contain everything required for production usage.
I guess this would mean the `dist/` folder and the `README.md` for very fundamental docs purposes.

looking at e.g. https://github.com/aframevr/aframe/pull/1586 it seems npm does support a `export-ignore` with `.gitattribute`.

In case we can agree an what shoule be included, I can provide a pull request

**Comment by verlok** [comment]
I agree. Please do it.

**Comment by verlok** [comment]
I've reopened the issue becuse I've moved @staabm fixes to [a branch](https://github.com/verlok/lazyload/tree/feature/excludeUnrequiredGitIgnore) while waiting for a reply to #380

**Comment by verlok** [comment]
> installing the module via npm creates a huge amount of files in the node_modules directory.
@staabm are you sure? I've tried it and it only installs a few files from the `dist` folder.

**Comment by staabm** [comment]
@verlok thx for the feedback. we just updated the lazyload lib to the most recent version and the problem no longer appears.

I guess my actual report was only affecting the 9.x series or similar.

sorry for the noise.
