### ISSUE TITLE
use lazyload.load in callback_error

### ISSUE THREAD

**Issue by Mater1996** [verlok/lazyload#381]
**Describe the bug**
when i use lazyload.load in callback_error
this will get error and loaded class both

**Expected behavior**
remove error class and add loaded class when img loaded

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version lastest 12.1

**Desktop (please complete the following information):**
 - OS: window
 - Browser chrome
 - Version lastest

**Screenshots**
![image](https://user-images.githubusercontent.com/26322213/66558064-840af880-eb85-11e9-86b3-3c4f91322238.png)

**Additional context**

**Comment by verlok** [comment]
Please specify why you are doing lazyload.load on callback_error and what you are trying to load if the original  image failed to load.

**Comment by Mater1996** [comment]
i want to listen img error  and reload this img use lazyload.load

**Comment by verlok** [comment]
@Mater1996 I've just released 12.2.0 with the new feature "retry when back online". Now if your users lose the internet connection causing errors on images loading, this script tries and loads those images again when the connection is restored.

Does this solve your problem?

**Comment by verlok** [comment]
(sorry closes by mistake)

**Comment by verlok** [comment]
> i want to listen img error and reload this img use lazyload.load

For this purpose I would advice to remove the error class before trying to load the image again with the `load()` method, because it would take care of applying the `loading` class while loading, and a `loaded` or `error` class at the end.

**Comment by verlok** [comment]
I really think that the `load()` method shouldn't remove any `error` classes, because it could potentially generate bugs on how people already use the script today. So I hope my 12.2.0 solves what you were trying to do.
