### ISSUE TITLE
Background image lazy load and callbacks

### ISSUE THREAD

**Issue by isuke01** [verlok/lazyload#384]
Hello, 
I saw in docs, `callback_finish` wont be fired and load class will not ba added into bg images.
I also tried other hooks like `callback_finish` with no luck. Is there a way to add class or some callback after BG image is loaded? 

I'd like to make transition between placeholder and new loaded BG.

Thanks :)

By now Im using just stying with attribute `&[data-was-processed="true"] {` since this is added after image is loaded, but if it is added, maybe there is way to add something else with some callbacks?

**Comment by wamk9** [comment]
> Is there a way to add class or some callback after BG image is loaded?

You can try using `callback_reveal`, it fires when div or img appears on screen, the `callback_finish` fires when all images is loaded.

**Comment by isuke01** [comment]
Ok, thanks

**Comment by verlok** [comment]
Hey @isuke01, @wamk9,
things changed on version 15. 

I found a way to manage background images's load/error event, so now background images are now getting the `loaded` or `error` class and calling `callback_loaded` and `callback_error`.

Take a look at the [changelog](https://github.com/verlok/lazyload/blob/master/CHANGELOG.md) and to the [upgrading guide](https://github.com/verlok/lazyload/blob/master/UPGRADE.md) if you're interested.

Have a nice day.
