### ISSUE TITLE
clone a div containing image using lazyload

### ISSUE THREAD

**Issue by xpeyman** [verlok/lazyload#386]
In page loading i clone a div and change its attributes also the images of the div but the lazy load does not work on cloned images 
Could you help me solve the problem ?!

**Comment by verlok** [comment]
Yes I can, if you clearify. 
What do you mean by “cloning during page load”? It’s hard to tell what happens first. 
So you have the HTML with lazy images inside a div, at which point in time you clone the div? Before or after LazyLoad is launched? If you clone the div before, everything should work. If you clone the div after, you probably need to use the `update()` method on the lazyload instance to make it look for new images that you created.

**Comment by verlok** [comment]
@xpeyman have you solved?

**Comment by xpeyman** [comment]
Hey body
Thanx alot
It was very useful
It is solved
Greatttttt !!!!

**Comment by verlok** [comment]
Glad to hear that. 
Enjoy my script!
(and make sure to star ⭐️ it)
Cheers 🍻
