### ISSUE TITLE
Some images won't load in Edge

### ISSUE THREAD

**Issue by Dennise89** [verlok/lazyload#387]
**Describe the bug**
Some images won't show on Window Edge.

**To Reproduce**
1. Go to 'https://www.cewe.nl/persoonlijke-adventskalender.html'
2. Scroll down
4. See that images next to the texts are not loaded

**Expected behavior**
When I scroll down, I expect the images to show up.

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version 12.1.0

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Windows Edge
 - Version: 44.17763.771.0

**Screenshots**
![image](https://user-images.githubusercontent.com/11348419/67288449-48edbb00-f4dd-11e9-86bf-3ef8f7244e0e.png)

**Comment by verlok** [comment]
Hey there. 
Thank you for opening this. 
Could you please report here the most meaningful  HTML and JS code that you use on that website?
Thanks

**Comment by verlok** [comment]
I've taken a look at your webpage. 

Using MS Edge, it seems that your images are hidden by your CSS, since I can't even find them inspecting the page with the browser inspector.

Also beware that you are using both native lazy loading and JS based lazy loading on the same images. I've found this in your DOM:

```html
<img class="lazy hide_on_mobile loaded" data-src="https://www.cewe.nl//images/nl_NL/landingpage/advent/advent-calendar-ferrero-2.jpg" alt="" title="" loading="lazy" src="https://www.cewe.nl//images/nl_NL/landingpage/advent/advent-calendar-ferrero-2.jpg" data-was-processed="true">
```

The `data-was-processed` means that that element was processed by this script, but the `loading=lazy` means that image should be lazy loaded by the browser lazy images are supported.

I suggest you to read this article I've written in may about how to do hybrid lazyloading, hybrid meaning both native and js-driven lazyload, using this script.

➡ [Hybrid Lazy Loading: A Progressive Migration To Native Lazy Loading](https://www.smashingmagazine.com/2019/05/hybrid-lazy-loading-progressive-migration-native/)

**Comment by verlok** [comment]
I've tested [this demo](https://www.andreaverlicchi.eu/lazyload/demos/image_basic.html) and others on MS Edge and this script is working correctly, so I'm switching the "bug" label to "question".

**Comment by verlok** [comment]
If you want more help, please report here the most meaningful HTML and JS code that you use on that website. The best way to help you would be if you could isolate the problem on a new pen on [Codepen](https://codepen.io).

**Comment by Dennise89** [comment]
@verlok This is what I have in my website. Now if you load this [codepen](https://codepen.io/dennise89/pen/ExxWXYM) in Edge, it will load every image straight away.

**Comment by Dennise89** [comment]
> I've taken a look at your webpage.
> 
> Using MS Edge, it seems that your images are hidden by your CSS, since I can't even find them inspecting the page with the browser inspector.
> 
> Also beware that you are using both native lazy loading and JS based lazy loading on the same images. I've found this in your DOM:
> 
> ```
> <img class="lazy hide_on_mobile loaded" 
>   data-src="https://www.cewe.nl//images/nl_NL/landingpage/advent/advent-calendar-ferrero-2.jpg" 
>   alt="" 
>   title="" 
>   loading="lazy" 
>   src="https://www.cewe.nl//images/nl_NL/landingpage/advent/advent-calendar-ferrero-2.jpg" 
>   data-was-processed="true">
> ```
> 
> The `data-was-processed` means that that element was processed by this script, but the `loading=lazy` means that image should be lazy loaded by the browser lazy images are supported.
> 
> I suggest you to read this article I've written in may about how to do hybrid lazyloading, hybrid meaning both native and js-driven lazyload, using this script.
> 
> ➡ [Hybrid Lazy Loading: A Progressive Migration To Native Lazy Loading](https://www.smashingmagazine.com/2019/05/hybrid-lazy-loading-progressive-migration-native/)

Also, I do not see the `loading="lazy"` attribute in Edge. I see this:
![image](https://user-images.githubusercontent.com/11348419/67370238-9bc98000-f57a-11e9-8cd8-93b067da072f.png)

**Comment by verlok** [comment]
If the images are loaded inside the Codepen, it's not a problem of this LazyLoad script.
I think this must depend on the CSS you used on that page, as I wrote before.
What do you think?

**Comment by verlok** [comment]
I'm assuming you solved. Feel free to reopen if you still need help.
