### ISSUE TITLE
Hello there! I'm not sure but it seems like there is an issue with Lazyload pluggin on Google Chrome. Images on website dont load how they should

### ISSUE THREAD

**Issue by arthurp93** [verlok/lazyload#388]
**Is your support request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**To Reproduce**

**Expected behavior**

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version [12, latest]

**Desktop (please complete the following information):**
 - OS: [Windows 10 Pro]
 - Browser [Chrome]

**Comment by verlok** [comment]
I'm gonna need more information to debug on that.
Please add some code snippet you're using and a codepen in which you isolate the problem.
Please open a new issue with all the information required.
