### ISSUE TITLE
Question: I do not understand data-srcset and data-size

### ISSUE THREAD

**Issue by nitipot** [verlok/lazyload#390]
```
<img alt="A lazy image" class="lazy" 
    data-src="lazy.jpg" 
    data-srcset="lazy_400.jpg 400w, lazy_800.jpg 800w" 
    data-sizes="100w">
```

From my understanding the number behind each data source is size in pixel use for choosing image to display and it compare with data-sizes.
1. Am I understanding it correctly?
2. What does "100w" mean in `data-sizes="100w"` is it equals to 100px?
3. I want it to choose image based on screen width is it possible to do with only this <img> tag?

**Comment by verlok** [comment]
Hi @nitipot,
1. What you wrote before the questions is right, but what you wrote in the questions made me think again 
2. I don’t understand the question, but please note that the value of the sizes attribute must be one or more CSS lengths expressed in CSS pixels or in viewport width (vw), so `sizes="100w"` is not a valid attribute. 
3. You could also use the `picture` tag

I think this script’s repo is not the right place to explain this technique. But the thing you’re looking for (images that adapt to the browser width) is called “responsive images”, so just Google this keyword!

Particularly, to understand `srcset` and `sizes` I found particularly useful this article: https://ericportis.com/posts/2014/srcset-sizes/

Happy learning!

**Comment by davemccrea** [comment]
I think possibly the confusion comes from the docs [here](https://github.com/verlok/vanilla-lazyload#lazy-responsive-image-with-srcset-and-sizes) and [here](https://github.com/verlok/vanilla-lazyload#lazy-responsive-image-with-automatic-webp-format-selection-using-the-picture-tag) where the example code uses `data-sizes="100w"` rather than a valid unit such as `vw`.

**Comment by verlok** [comment]
Thanks for pointing out @davemccrea, would you be able to open a pull request to fix the readme?
