### ISSUE TITLE
Problem to hide and show display block after loading with lazyload.js

### ISSUE THREAD

**Issue by DangerZombie** [verlok/lazyload#391]
I have a problem using lazyload.js. My html can show and hide display block but some item not work correctly and some item work correctly. 
The main problem is when I click the image to show the display block that not working and the web is scrolling to top of page.
Any idea for solve this problem? I very need help with this problem.

**Comment by verlok** [comment]
Hi there,
thank you for opening this. 
It seems that your problem might not be caused by this script. Why do you think lazyload has something to do with it?
Please detail your problem and report the related JS, CSS and HTML code

**Comment by DangerZombie** [comment]
> Hi there,
> thank you for opening this.
> It seems that your problem might not be caused by this script. Why do you think lazyload has something to do with it?
> Please detail your problem and report the related JS, CSS and HTML code

Hi,
Thanks for the response. I was resolving the problem. I have mistake with my JS script, when I append the html to show and hide. I write to many </div> that makes some bugs for the web.
Maybe next time if I have a problem with lazyload.js i will ask again.

Thanks before.
