### ISSUE TITLE
Horizontal Scroll Issue

### ISSUE THREAD

**Issue by ex-jedi** [verlok/lazyload#393]
I have an issue where some images don't appear in a horizontally scrolling container. I've checked on Chrome, and Edge Chromium on Windows 10 (don't @ me) and Android. 

Sorry, I've lost track of what version I'm using, I downloaded it a while ago and only have the minimized file. I'll post code if needed, but wondering if this has occurred before.

Cheers

![ezgif com-optimize](https://user-images.githubusercontent.com/3149496/68504620-491be380-025d-11ea-9e42-f11e29cc2fd4.gif)

**Comment by verlok** [comment]
Hey. It’s very important to know if you’re using version 8.x or newer. 
That
Seems an issue that could happen with version 8. 
Please let me know.

**Comment by ex-jedi** [comment]
No worries actually. Fixed by adding min-height to the images.
