### ISSUE TITLE
lazyload stuck on v12.0.3 on CDNJS

### ISSUE THREAD

**Issue by bridgeport** [verlok/lazyload#394]
I know you switched to jsdelivr in the docs a while ago, but thought it worth mentioning that cdnjs.com has been stuck on v12.0.3 for a long while now:
https://cdnjs.com/libraries/vanilla-lazyload

**Comment by verlok** [comment]
That's exactly why I moved away from cdnjs. 
They stopped working properly and they stopped supporting people, so I stopped using it.
Sorry about that.
