### ISSUE TITLE
Some background images not loading on mobile

### ISSUE THREAD

**Issue by yu-coder** [verlok/lazyload#395]
Hi, I am using this plugin with **Shopify**.
I have tested the site on https://developers.google.com/speed/pagespeed/insights/ but I have noticed that **lazy loading** works on some images but doesn't work on some images on **mobile**.
It seems it works properly on the desktop.

**Javascript**
```js
let myLazyLoad;

// Lazyload images
export function initLazyLoad() {
  myLazyLoad = new LazyLoad({
    elements_selector: '.lazyload',
    callback_loaded: function(el) {}
  });
}

export function updateLazyLoad() {
  myLazyLoad.update();
}

initLazyLoad();

$(document).on('shopify:section:load', function() {
  initLazyLoad();
});

$(window).on('popup-loading', function(event) {
  updateLazyLoad();
});
```

**Liquid**
```liquid
<div class="box-item__image lazyload" data-bg="url({{ _block.image | img_url: '1900x' }})">
...
</div>
```

Did anyone have this issue before?

**Comment by oxcelovel** [comment]
same issue here used default setup, happened at the end of October, desktop OK but default mobile browsers (chrome  android 9.0 safari iPhoneXS) confirm only some images appearing.

<a href="gallery/gallery1.php"><img class="lazy" data-src="path/to/image.jpg"></a>

<script src="js/lazyload-12.3.0.min.js"></script>
<script>var lazyLoadInstance = new LazyLoad({elements_selector: "img.lazy"});</script>

**Comment by verlok** [comment]
Hey @yu-coder ,
thanks for opening this.

Have you checked the demo about loading background images?

Code here: https://github.com/verlok/lazyload/blob/master/demos/background_images.html
Live demo here: https://www.andreaverlicchi.eu/lazyload/demos/background_images.html

I don't happen to notice any malfunctioning there.

I suggest you to check the final HTML generated from Liquid. Are there any spaces or strange characters in the images URLs? If there are spaces, have you wrapped the images urls inside single quotes (`'`)?

**Comment by yu-coder** [comment]
@verlok 
It was an issue on my side not on **lazyload** issue.
I have fixed it so now it works properly.
Sorry for not updating you.
Thank you.

**Comment by verlok** [comment]
Good to know that you solved.
Thanks
