### ISSUE TITLE
Page jumps to iframe and back to top

### ISSUE THREAD

**Issue by VasilchenkoSergei** [verlok/lazyload#396]
Hello! First of all, thank you for your lazyload.

But I got problem with iframe. I try to lazyload them and it looks like 

```html
<iframe allowfullscreen="allowfullscreen" class="lazy" frameborder="0" src="#" data-src="https://www.youtube.com/watch?v=gHLPBlzGRT8987987fwdds"></iframe>
```

1) I have two iframes on the page. And when page is loading, it goes down right to the first iframe and the to the second, and then goes back to the top of the page. I tried to delete all lazy attributes, and then I have no such an effect. Returned them and thought that my script could create a problem, but I deleted it and nothing happened. Jumps were still there with added lazy-attributes.

2) Also when page is loaded finally with all these jumps I see that iframe src has already loaded from the data-src. It happens quite often without any scrolling by myself.

**Comment by verlok** [comment]
Hey @VasilchenkoSergei,
have you looked at the iframes demo?

Code is here: https://github.com/verlok/lazyload/blob/master/demos/iframes.html
See it live here: https://www.andreaverlicchi.eu/lazyload/demos/iframes.html

And have you tried setting a height to the iframes using CSS?

Please let me know how it goes.
Thanks

**Comment by verlok** [comment]
I'm assuming you solved. Feel free to reopen if you still need help.

**Comment by amixel** [comment]
not work
