### ISSUE TITLE
Lazy Load in Slide Down Element

### ISSUE THREAD

**Issue by mturnwall** [verlok/lazyload#40]
I have an element the is off the screen. How can get the images to load once the element slides into view? The element is being slide into view using `translateY()`.

I tried instantiating LazyLoad during the click even that slides the element and setting the `container` property to the element. Some of the images load but ones towards the bottom of the element do not load.

**Comment by verlok** [comment]
Hi @mturnwall,
first of all, this script is only to detect elements that *scrolls* into the window, not elements that *moves* in given a non-scrolling viewport. So it listenes to the browser's `scroll` event to check if elements are inside or not, which is not your case. 
Secondly, I did a quick research to find out whether or not is possible to detect when an element moved with the translateY() 2D transform enters the viewport, but I didn't find anything. I'd suggest you to ask this question to stackoverflow.

**Comment by verlok** [comment]
Psst: have you already starred this repo? All you need to do is to press the Star ★ button on the top right corner of the website. ;)
