### ISSUE TITLE
threshold with percent

### ISSUE THREAD

**Issue by Mater1996** [verlok/lazyload#401]
**Is your feature request related to a problem? Please describe.**
i want to use it like this 
![image](https://user-images.githubusercontent.com/26322213/69601545-6d463580-104f-11ea-92e0-26153fa23b89.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Mater1996** [comment]
threshold is a precent number

**Comment by verlok** [comment]
Hey,
what you ask is already feasible, using the `thresholds` (with an S) option. 
Read the API section of the README for further information. 
Thanks

**Comment by Mater1996** [comment]
and there is a bug 
![image](https://user-images.githubusercontent.com/26322213/69603499-de88e700-1055-11ea-93d6-e482833c686a.png)

because entry.isIntersecting == false  to  entry.isIntersecting ==true  is enter
and entry.isIntersecting == true to  entry.isIntersecting == false is exit 

the intersectionRatio can not effect the enter or exist because when exit the intersectionRatio > 0

**Comment by Mater1996** [comment]
you are right
