### ISSUE TITLE
`callback_loaded` not called for background-image implementations

### ISSUE THREAD

**Issue by pau1brad1ey** [verlok/lazyload#405]
`callback_loaded` is not called for `background-image` lazyload implementations however does get called for `image` implementations in my codebase. After some digging, Ive noticed the demo file doesnt work either so will use this as an example

**To Reproduce**
see demo file here -> https://github.com/verlok/lazyload/blob/6565859812421223ecd8acea1f2908396c28689d/demos/background_images.html

and  live example here -> https://www.andreaverlicchi.eu/lazyload/demos/background_images.html

**Expected behavior**
Expected to see `logElementEvent("👍 LOADED", element)` in the console of the live demo

**Comment by hummal** [comment]
Can confirm

**Comment by verlok** [comment]
That’s ok. It’s not supposed to happen. JavaScript doesn’t fire any callback for loaded background images. Please search in the closed issues for further explanation.

**Comment by verlok** [comment]
Hey @pau1brad1ey, @hummal, 
things changed on version 15. 

I found a way to manage background images's load/error event, so now background images are now getting the `loaded` or `error` class and calling `callback_loaded` and `callback_error`.

Take a look at the [changelog](https://github.com/verlok/lazyload/blob/master/CHANGELOG.md) and to the [upgrading guide](https://github.com/verlok/lazyload/blob/master/UPGRADE.md) if you're interested.

Have a nice day.
