### ISSUE TITLE
image is not showing up in ie11

### ISSUE THREAD

**Issue by vinaygarg502** [verlok/lazyload#406]
image is showing up in chrome but not in ie when i am using lazy load, while showing data-was-processed as true, and can see image being loaded in network call, but not changing src attribute value and not showing up the image.

**Comment by Sunxinqiang** [comment]
so dose me in IE11

**Comment by rickvian** [comment]
IMHO IE user should be deprecated

**Comment by verlok** [comment]
IE11 is still used and supported as of January 5th 2020. An it will be for long I guess. 

LazyLoad is currently working on IE11, it loads all your images with or without the IntersectionObserver polyfill. 

@vinaygarg502 could you please add more information of what is happening to you? Maybe add some cod or even better create a pen on Codepen?

**Comment by verlok** [comment]
Hey @vinaygarg502,
issue #414 helped me find and solve the problem.

IE11 is now working again, from 12.5.1 up.
