### ISSUE TITLE
Images not loading in Safari 13.0.4 when using srcset

### ISSUE THREAD

**Issue by richgcook** [verlok/lazyload#409]
**Describe the bug**
On Safari 13.0.4 (but this also happens on iOS Safari too) images seem to be processed `data-was-processed="true"` and the src tag shows the correct image, however the loading class isn't removed (and thus with my setup it doesn't fade in). 

This works fine on Chrome. I am using data-srcset with the sizes set to auto. However, this does work  on Safari so I'm getting a bit confused. Dropping data-srcset and the images load no problem at all.

```
<img src="/pitman-tozer/site/assets/files/1265/pitman-tozer-team-irfam-alam-associate-director.jpg" data-srcset="/pitman-tozer/site/assets/files/1265/pitman-tozer-team-irfam-alam-associate-director.jpg 450w" sizes="auto" class="--lazy --loading" srcset="/pitman-tozer/site/assets/files/1265/pitman-tozer-team-irfam-alam-associate-director.jpg 450w" data-was-processed="true">
```

**To Reproduce**
https://rd-ck.dev/pitman-tozer/studio/about/

**Expected behavior**
The loading class should changed to loaded.

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version 12.3.0

**Desktop/phone (please complete the following information):**
 - OS: macOS and iOS
 - Browser Safari
 - Version 13.0.4

**Comment by marcelaerts** [comment]
I got the same thing? Why is this closed? Did it get fixed?

**Comment by verlok** [comment]
I don't know why @richgcook closed this, but I'm not aware of any problems on Safari.

**Comment by richgcook** [comment]
> I don't know why @richgcook closed this, but I'm not aware of any problems on Safari.

It was my own mistake, sorry.
