### ISSUE TITLE
Add support for force loading some image classes

### ISSUE THREAD

**Issue by Niresh12495** [verlok/lazyload#41]
For example lazy loading mega menu images in wordpress works only scrolling a bit
that is where force loading may be come handy, also help web devs who want to load some images without lazy loading

**Comment by verlok** [comment]
LazyLoad's job is to check whether images are inside the viewport, then load them automatically. 
For what I understand, you need something to load some images when your menu is shown. So in the code that manages your menu, you want to do something like `new LazyLoad('.megaMenuImage', {immediateLoad: true})`, right?

**Comment by Niresh12495** [comment]
Yes :)

**Comment by verlok** [comment]
Good,
then you don't need LazyLoad for the menu. 
LazyLoad'a main job is to check whether or not images are in the viewport, or close to it, then load it in the positive case. 
What you need to do is just to copy the `data-src` attribute value to the `src` attribute and eventually the `data-srcset` attribute value to the `srcset` one. 
This can be easily done with a couple of lines of code that you can put in your menu component / manager / handler.

**Comment by verlok** [comment]
@Niresh12495 can we close this issue?

**Comment by Niresh12495** [comment]
Hi, sorry for very late reply so do you want me to add a code to the code that manages megamenu? that is not possible in most cases, is there anything that i can do with lazyload js options itself

**Comment by verlok** [comment]
Look, I don't know megamenu but you need to write some code to do what I wrote some comments before. Not necessarily editing megamenu's code, but Listening to the events it fires maybe.
