### ISSUE TITLE
Lazy Load image height issue

### ISSUE THREAD

**Issue by sgurin** [verlok/lazyload#411]
**Describe the bug**
The bug happens when the images or a parent block do not have height https://prnt.sc/qv2j7p

**To Reproduce**
1. Go to http://sgurin.staging.s4.justcoded.com/
2. Open Console and clean cache https://prnt.sc/qv2822 or open incognito window
3. Scroll down to the end of the page
4. Last/Middle row of the images do not load https://prnt.sc/qv28h9 if you hover on the image it starts loading.

**Expected behavior**
All image should be loaded

**LazyLoad version**
- Version [12.4.0]

**Desktop (please complete the following information):**
 - OS: [macOS Catalina Version 10.15.3]
 - Browser [Chrome]
 - Version [79.0.3945.130 (Official Build) (64-bit)]

**Additional context**
It happens because the image and the parent block does not have heigh. If you set the min-height on image https://prnt.sc/qv2dk9 the bug goes away.

**Comment by verlok** [comment]
This is not a bug. If the image is not originally visible, it's not supposed to be loaded. That's how the [IntersectionObserver API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) works.
