### ISSUE TITLE
Not working div bg-image class_loaded: "loaded"

### ISSUE THREAD

**Issue by cvaize** [verlok/lazyload#412]
![image](https://user-images.githubusercontent.com/26907947/73656653-6f152080-46b2-11ea-98e6-dd404a7a7f9b.png)

**Comment by verlok** [comment]
It's not a bug, it's like that by design.

**Comment by cvaize** [comment]
OK

**Comment by verlok** [comment]
Sorry about the brevity of my latest reply, I was in a hurry.
If you search in the closed issues you can find plenty of answers and explanations of the reasons why it's designed like that. 
Thank you for your patience.

**Comment by cvaize** [comment]
Thanks for the explanation!
