### ISSUE TITLE
IE 11 "'Symbol' is undefined" exception

### ISSUE THREAD

**Issue by ninosaurus** [verlok/lazyload#414]
**Describe the bug**
After started using this library in production our error tracking system started reporting JS error that "_'Symbol' is undefined_".

**To Reproduce**
I tried loading IE11 on BrowserStack but the error cannot be reproduced that way.

**Expected behavior**
Since the documentation says that this lib is supposed to work on IE 11 and no errors reported.

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version [12.4.0]

**Desktop (please complete the following information):**
 - OS: Window
 - Browser IE
 - Version 11

**Smartphone (please complete the following information):**

**Screenshots**
![image](https://user-images.githubusercontent.com/17122401/75141146-a47cbf00-56f0-11ea-990b-2933e52fbb4f.png)

**Additional context**
Do you know what may have been issue here, since I don't know what happens with users with this exception?

**Comment by verlok** [comment]
Hey @ninosaurus,
thank you for reporting. 

We are using LazyLoad in production and we support IE 11, but no errors are thrown neither in the browser nor in our error reporting tools.

What do you use? Kibana, Raygun, others?

**Comment by ninosaurus** [comment]
> Hey @ninosaurus,
> thank you for reporting.
> 
> We are using LazyLoad in production and we support IE 11, but no errors are thrown neither in the browser nor in our error reporting tools.
> 
> What do you use? Kibana, Raygun, others?

We're using NewRelic for browser error reports (screenshot above is from NewRelic).
When I take a look at lazyload.min.js I see there is the use of Symbol which as u can check on [HERE](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) and [HERE](https://caniuse.com/#feat=mdn-javascript_builtins_symbol) is not supported on IE11. 
![image](https://user-images.githubusercontent.com/17122401/75227942-73af8f00-57af-11ea-97ed-deca88487188.png)
Thanks for the fast response :)

**Comment by verlok** [comment]
Hey @ninosaurus ,
you're right... this must be an addition coming from the bundler I'm using.
I'll definitely look into that.
Thanks

**Comment by verlok** [comment]
I've found a reference in the babel documentation
https://github.com/babel/babel/issues/7597

**Comment by verlok** [comment]
I should've solved that.
No more `Symbol` in the dist folder.
Please check 12.5.1.
Thanks!

**Comment by ninosaurus** [comment]
Thanks @verlok! 🙌

**Comment by verlok** [comment]
You're welcome.

(or update to 13.0.0 (just released) which is another little improvement)
