### ISSUE TITLE
Loading X images or x pages in advance 

### ISSUE THREAD

**Issue by yanivhyped** [verlok/lazyload#417]
Hi,
Is there a parameter to set in order to load x images or x pages in advance? On slow network it takes time for image to load and therefor the image is not loaded when the user gets to the viewable position of the image

**Comment by verlok** [comment]
Hey @yanivhyped ,

the answer is YES, you can use either the `threshold` or the `thresholds` options. Check the reference in the [API section](https://github.com/verlok/lazyload#-api) of the documentation.

If you want to load a page in advance and your scroll direction is vertical, you could set `thresholds: "100vw 0"` in the options object.
