### ISSUE TITLE
Lazy load is loading some images that haven't entered viewport yet. Why?

### ISSUE THREAD

**Issue by omarel1** [verlok/lazyload#419]
This is a great script and works, but every time I implement it seems like it loads several images that have not entered the viewport yet. I'm not sure why. When I inspect the page with developer tools and check several images below the viewport, it shows lazy load has already loaded about 3 images I know have not entered the viewport yet.

Is there a way to stop that from happening. I'd like it to not load anything that hasn't entered the viewport yet.

**Comment by verlok** [comment]
Hi @omarel1 ,
thank you for opening this.

I suggest you to slow down the network speed using the browser's developer tools, disable cache, and see what happens before loading.

This usually happens when the images don't have an height before they are loaded. If all the images are 0 height, they actually are inside the viewport before loading, so LazyLoad starts loading them all. If this is the case, there are a few techniques to solve this. I wrote a section in the readme: https://github.com/verlok/lazyload#occupy-space-and-avoid-content-reflow

Let me know if this helps!

**Comment by verlok** [comment]
The other reason for this could happen is that LazyLoad watches 300 pixels below (and above) the viewport to preload the images that are likely to enter the viewport. 
So if you have 6 image inside the viewport and 3 more images 200 pixels below the viewport, it would load 9 images.

This is a courtesy to the users that would have to wait less time to see the images. However you can disable this passing `0` to the `threshold` option.

**Comment by omarel1** [comment]
I'm going to look at this right now. I added a height previously to test but same thing. 

The images are coming from Json so I'm using the update method. 

I'm going to test now and see if the threshold option works

**Comment by omarel1** [comment]
The threshold option worked and I definitely need to add a minimum height to images, but this definitely poses some issues when you want to keep the aspect ratio on images and need to use a height of auto. I'm working around it by changing the height to auto after the image has loaded...

but I'm wondering is there a way to add the .lazy class to the div container of an img so I can control the height of the container instead of on the img itself?

**Comment by verlok** [comment]
Hey, thank you for replying back. If you look at the tips and tricks section in the README you will find the way to make your images occupy some vertical space using CSS only or using an SVG in-line image.

**Comment by omarel1** [comment]
The Vertical padding trick seems to have solved the default height I wanted to create on the outer div before the image loads. Thank you.

**Comment by verlok** [comment]
I’m glad you solved.

**Comment by nbaleli-w** [comment]
I couldn't quite understand the vertical padding example, any chance to get some more explanation?

```
.image-wrapper {
    width: 100%;
    height: 0;
    padding-bottom: 150%; /* You define this doing image height / width * 100% */
    position: relative;
}
.image {
    width: 100%;
    height: auto;
    position: absolute;
}
```
