### ISSUE TITLE
Can't implement threshold

### ISSUE THREAD

**Issue by ad31mar** [verlok/lazyload#420]
I can't get the threshold option to work in [my implementation](https://binnedart.com).

```
...
<script src="https://cdn.jsdelivr.net/npm/vanilla-lazyload@13.0.1/dist/lazyload.min.js"></script>
<script>var lazyLoadInstance = new LazyLoad({
    threshold: 900
});
</script>
</head>
```

It doesn't matter what threshold I set, it still lazy loads images only when they hit the viewport. What am I doing wrong? Tried both with and without ` elements_selector`.

**Comment by ad31mar** [comment]
Solved it by specifying the container. Took me a while!

`container: document.getElementById("still")`

**Comment by verlok** [comment]
I’m glad you’ve solved, if you had told me that the scrolling container was different than the main window, I would’ve pointed the right configuration option to you.

**Comment by verlok** [comment]
I know it’s late now, but if you look at the demos folder and the demos descriptions In the README, there is a demo with a single scrolling container and another with multiple scrolling containers, each one with its `threshold` or `thresholds` configuration.
