### ISSUE TITLE
Add support for data-bg-2x

### ISSUE THREAD

**Issue by allaire** [verlok/lazyload#425]
Supporting `data-bg-2x` would allow to use inline backgrounds with hi-dpi support. My workaround is done in javascript on my side currently:

```js
    if (window.devicePixelRatio > 1) {
      const backgroundElements = document.querySelectorAll("[data-bg-2x]");
      backgroundElements.forEach(backgroundElement => {
        backgroundElement.dataset.bg = backgroundElement.dataset["bg-2x"];
      });
    }
```

**Comment by verlok** [comment]
Hey @allaire,

Thanks for opening this. 
Your solution seems to work quite well!

The thing is... what is your use case? Are your images real background images, or are them part of the content of your website? 

If you don’t know how to answer that question, ask yourself: should they be printed if the user printed the page? Should they be read by a screen reader to a blind user? If the answer is yes to both questions, then your images are content images. 

The usage of background images should be discouraged for content images, and you should use “responsive images” instead. 

I’m looking forward to receiving your reply.

**Comment by allaire** [comment]
Hi @verlok, first thanks for the quick reply and the great work on this lib!

You can see how we use inline backgrounds here: https://www.agendrix.com/fr. We use it mostly for `background-size: cover` so we can have a different ratio on mobile (rectangle). using `object-fit` was causing us difficulties in IE (as usual), even with a polyfill.

You can see Docker is using a similar technique on there about page (first fold): https://www.docker.com/company, with the absolute positioning so it can go outside the viewport.

**Comment by verlok** [comment]
Hey @allaire,
thank you for the explanation. I visited the link. It's all clear to me.

I would call the attribute `data-bg-hidpi` and I'd use it for every devicePixelRatio greater than 1.
Why don't you create a pull request to this open source lazyload script?

**Comment by allaire** [comment]
Hi @verlok,

Will do my best. I'm running a business of 26 employees, and with COVID-19, things are pretty hectic at the moment.

Thanks for your time,

Mathieu

**Comment by verlok** [comment]
I can understand. I live in Italy :)
If you don't have time I can do that myself when I find some time.
I'm currently working at a major refactoring that would probably produce v. 14.

**Comment by verlok** [comment]
Done in 15.1.0.

See the [changelog](https://github.com/verlok/lazyload/blob/master/CHANGELOG.md) for 15.1.0 and 15.0.0.

How does it work for you? I'm open to feedback.
And if you like it, you can always say thanks [with a coffee](https://www.buymeacoffee.com/verlok) 😉

**Comment by allaire** [comment]
Thank you! and ✅ for the ☕️

**Comment by verlok** [comment]
Thank you, Mathieu :)

**Comment by allaire** [comment]
@verlok Found a little bug. Currently, if I'm on a hidpi screen, and if I don't specify `data-bg-hidpi`, it does not fallback on `data-bg`

**Comment by verlok** [comment]
That's a good point. So if there isn't a `data-bg-hidpi` but there is a `data-bg` it should use that. Fair enough. Will fix.
