### ISSUE TITLE
error TS1036: Statements are not allowed in ambient contexts.

### ISSUE THREAD

**Issue by hectorccmx** [verlok/lazyload#427]
After upgrading to Angular 9.1.0 and using Typescript 3.8.3, I keep getting these errors when compiling with ng build --watch command:

node_modules/vanilla-lazyload/typings/lazyload.d.ts:36:1 - error TS1036: Statements are not allowed in ambient contexts.

36 if (this._observer) {
   ~~
node_modules/vanilla-lazyload/typings/lazyload.d.ts:37:5 - error TS1036: Statements are not allowed in ambient contexts.

37     this._observer.disconnect();
       ~~~~

**Comment by verlok** [comment]
Hey there thank you for reporting this. 
To which version of LazyLoad are you referring to?

**Comment by hectorccmx** [comment]
Hello @verlok , this version:

"vanilla-lazyload": "^14.0.0"

**Comment by verlok** [comment]
I added the "Help Wanted" label because I don't have the foggiest of what can cause that error on Typescript. I'll ask around and I'll let you know if I found a cause.

In the meantime, can you tell me if you get the same error using version 13.0.1 and with 12.5.1?

Thanks

**Comment by verlok** [comment]
Friends helped. Thanks @cant89. You're the heart of the open-source. 😻🤟

**Comment by verlok** [comment]
Fixed in 14.0.1
