### ISSUE TITLE
Fade in technique not working on Safari iOS

### ISSUE THREAD

**Issue by vvo** [verlok/lazyload#428]
**Is your support request related to a problem? Please describe.**

Hi there,

The Fade in example works great on Chrome desktop but fails on iOS safari, here's a demo video: https://www.webpagetest.org/video/view.php?id=200330_ZT_fd59f387a640e2b66ff913fc0eb3b273.1.0 and I was able to test it also on my own iPhone 8 ios 13.

I did some searching but was not able to make it work. Maybe you or someone else have some idea on why this is not working? Thanks!

**To Reproduce**
1. Use an iPhone or https://www.webpagetest.org/
2. Go to https://www.andreaverlicchi.eu/lazyload/demos/fade_in.html
3. The page displays images without a fade-in effect

**Expected behavior**
The page should display images in a fade-in effect

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version: 14.0

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 13
 - Browser Safari
 - Version 13

**Screenshots**
![2020-03-30 12 04 29](https://user-images.githubusercontent.com/123822/77900644-a3562900-727e-11ea-89e7-407d61b9f6e6.gif)

PS:
I want to thank you for this library, I am using it on https://coronamaison.now.sh/ with great success! Your README is perfect and full of interesting documentation, like the padding ratio trick. I have used MANY lazy loading libraries, I tried them all and ended up with yours. Working with React and React hooks works perfectly too, thanks!

**Comment by verlok** [comment]
Hey man,
thank you for the congratulations, I’m glad you are enjoying it :)
I will check the demo on my Mac or using Browserstack and I’ll let you know.

**Comment by verlok** [comment]
Tested both on Safari for Mac and Safari for iOS, it works perfectly. Maybe it’s a problem of how Webpagetest renders it.

**Comment by vvo** [comment]
true, I guess my iPhone was.. lazy yesterday. works now
