### ISSUE TITLE
Lazyload loading gif until all images are loaded

### ISSUE THREAD

**Issue by udisklorenz** [verlok/lazyload#429]
Hello
I need the code below to display images from a folder on the website. I use lazyload to ensure that the images are not loaded until the user opens the modal. After the user has opened the modal, is it possible to display a loading.gif until all images are loaded? I have already set the delay of lazyload to 2 seconds, but it does not look good if the user opens the modal and nothing appears for 2 seconds. Is it bossible, that the whole `<ul class="ul-li">` shows one laoding gif until all images are loaded?

Thanks

```html
<!-- Modal 1 -->
<div
    class="portfolio-modal modal fade"
    id="portfolioModal1"
    tabindex="-1"
    role="dialog"
    aria-hidden="true"
>
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="close-modal" data-dismiss="modal">
                <div class="lr">
                    <div class="rl"></div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 mx-auto">
                        <div class="modal-body">
                            <!-- Project Details Go Here -->
                            <h2 class="">AugenBlick</h2>
                            <ul class="ul-li">
                                <li data-src="'.$numT.'">
                                    <img class="imggallery lazy" data-src="'.$numT.'" alt="" />
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
```

And here my lazyload settings

```js
var lazyLoadInstance = new LazyLoad({ elements_selector: ".lazy", load_delay: 1000 });
```

**Comment by verlok** [comment]
Hey there,

yes, it is possible by using the public `loadAll()` method on the instance, then waiting for the `callback_finish` to delete the loading gif.

So something like:

```js
var lazyLoadInstance = new LazyLoad({ 
  elements_selector: ".lazy", 
  callback_finish: function() { /* remove the loading gif here */ }
});

// When the modal is open...
lazyLoadInstance.loadAll();
```

THAT SAID, I think this is a bad idea. 
You should just open the modal and let the images be loaded lazily, as the user scrolls down.

The best thing to do in my opinion would be to do:

```js
var lazyLoadInstance = new LazyLoad({ 
  elements_selector: ".lazy", 
  container: ".modal-dialog .container"
});

You can also take a look at the "popup layer" demo

Code here: https://github.com/verlok/lazyload/blob/master/demos/popup_layer.html
Live demo here: https://www.andreaverlicchi.eu/lazyload/demos/popup_layer.html

[Click here](https://www.buymeacoffee.com/verlok) if you liked this reply ☕️

**Comment by udisklorenz** [comment]
The thing is, that the user can not scroll down because there are only 5 to 10 images. 
But with your first code, where can I insert the "loading.gif"?
I'm going to try that version...

**Comment by udisklorenz** [comment]
if you want to you can visit the page:
http://riederhslu.bplaced.net/arart
under "LichtArt" you can see where I use lazyload and there is my problem
Thank you!

**Comment by verlok** [comment]
In addition, I could give you precious advices in order to improve the speed and the display of the images on your website, I you just [bought me a coffee](https://ko-fi.com/verlok) 😅

**Comment by verlok** [comment]
@udisklorenz do you still need help or advice?

**Comment by udisklorenz** [comment]
yes i had an other idea...
Is it possible, that the images are going to load when the user scrolls on "LichtArt". so the images are going to load before the user cklicks on a modal but but only when he's on "LichtArt".
