### ISSUE TITLE
From cdnjs, about library request.

### ISSUE THREAD

**Issue by Piicksarn** [verlok/lazyload#43]
Hi @verlok ~
This is  **[cdnjs](https://github.com/cdnjs/cdnjs)**, and we desire to contain **vanilla-lazyload.**:smiley: 
However, I must to make a check for the files that we need to added.

The files I would like to add are **all the files under dist folder.**

Is that complete for the user? Or other files required?

Thanks for your great work ✨

Piicksarn

**Comment by verlok** [comment]
Hi there,
thanks for publishing my script.
Yes, all that is inside the dist folder is good.
Now I cleaned it up :)

**Comment by verlok** [comment]
Closed issue by mistake.
Fell free to close it when you're done :)
Thanks

**Comment by verlok** [comment]
Thank you!
