### ISSUE TITLE
Option to set failed image placeholder URL

### ISSUE THREAD

**Issue by nikolay-borzov** [verlok/lazyload#431]
**Is your feature request related to a problem? Please describe.**
When an image is failed to load for some reason (invalid URL, proxy problems etc.) it is usually replaced by "no image" placeholder

**Describe the solution you'd like**
Add a setting `failed_src` (and probably `failed_srcset`) that will be used to set `img.src` when image is failed to load 

**Describe alternatives you've considered**
This logic can be handled inside `callback_error`
```
callback_error(imageElement) {
  if (imageElement.src) {
   imageElement.src = NO_IMAGE_URL;
  }

  if (imageElement.srcset) {
    imageElement.srcset = NO_IMAGE_URL;
  }
}
```
But it should include the same checks `lazyload` already has in `lazyload.setSources.js`.
Alternatively, an image with "error" class can have a background set through CSS

**Additional context**
Not sure how it should be handled for `video` and `iframe` elements

**Comment by verlok** [comment]
Hey man,
thank you for the proposal. 

Although what you wrote is perfectly right, you probably want to set the same image for all elements in case of error? If that’s the case, you would have to repeat the same information in the `data-error` of all DOM elements. And it should be an inline image because if the error occurred because of a network failure, the error image could fail too. 

In addition, I don’t want to add logic to make LazyLoad decide is to treat that as a background image or a content image, the HiDPI or jot information, etc. 

I think the error case should be really manage by your (the script users) logic.

**Comment by nikolay-borzov** [comment]
I meant adding `failed_src`  to  LazyLoad settings:
```
new LazyLoad({
  elements_selector: ".js-lazy-product",
  failed_src: "/static/img/default-product-image.svg"
})
```
This way we can enable lazy loading for a group of images with specific "no image" image.

Let me describe my use case in detail. There is an e-commerce site that sells some products. Information about products (including images) is delivered by content provider service. The site has its own static resources (js/css/images) that guaranteed to be available. Sometimes content provider service fails to deliver images (while other data is available). 

I agree that adding support for setting error media for image/video/iframe can be difficult and can be handled better on the user side. I just thought it'd be possible to reuse functions like `setSourcesImg` (passing src instead of data attribute names).

Thanks

**Comment by verlok** [comment]
My fault, sorry, I read the text of your issue in a hurry and I totally misunderstood.
About the logic to make LazyLoad decide if to treat that as a background image or a content image, let me think again and I'll reply back to you.

**Comment by verlok** [comment]
Here I am, so... let's suppose I add some new options like the following:

```
error_src
error_srcset
error_bg //for bg images
error_bg_hidpi //for bg images in hidpi
```

## Case 1:

The script user knows it will loading images with the `img` tag, like:

```html
<img data-srcset="https://hell.to/666.jif 1x, https://hell.to/121212.jif 2x" data-src="https://hell.to/666.jif" alt="666">
```

So it does:

```js
new LazyLoad({
    error_src: "https://hell.to/error.jpg",
    error_srcset: "https://hell.to/error.jpg 1x, "https://hell.to/error@2x.jpg 2x"
}) 
```

When error event occurs, lazyload assigns those to the `src` and `srcset` attributes, that's it.

## Case 2

The script user knows it will loading responsive images with the `picture` tag, like:

```html
<picture>
  <source media="(max-width: 666px)" data-srcset="...">
  <source media="(max-width: 1332px)" data-srcset="...">
  <img data-srcset="https://hell.to/666.jif 1x, https://hell.to/121212.jif 2x" data-src="https://hell.to/666.jif" alt="666">
</picture>
```

And it does:

```js
new LazyLoad({
    error_src: "https://hell.to/error.jpg",
    error_srcset: "https://hell.to/error.jpg 1x, "https://hell.to/error@2x.jpg 2x"
}) 
```

What is lazyload supposed to do? If it just sets the error's `src` and `srcset` to the `img` element, I'm not sure it wouldn't be overridden by the `source`s element on top of it. I'm pretty sure it would be overridden. So probably `lazyload` would have to change them all. But it would be too invasive on the website's DOM.

## Case 3 and 4

Those were reserved for the background and the HiDPI background images, but I think that "case 2" is enough for now.

What do you think?

**Comment by verlok** [comment]
In addition, we need to consider that LazyLoad also manages `iframe`s and `video`s. 
The case with `iframe` would be easy, but `video` is another case where the `source` tag plays a role, and it's a [different role](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source) from the one inside the `picture` element.

**Comment by verlok** [comment]
I think if the script user managed it in their own code, given that it knows what it's loading, it would be much easier and much less JS code would be required in the error handling.

**Comment by nikolay-borzov** [comment]
Apparently, we cannot go with `error_src`, `error_srcset`, `error_bg` and `error_bg_hidpi` only and have to provide options for all possible sources:
```javascript
new LazyLoad({
  error_src: {
    img: {
      src: "https://hell.to/error.jpg",
      srcset: "https://hell.to/error.jpg 1x, https://hell.to/error@2x.jpg 2x",
    },
    picture: {
      // For <img> inside <picture>
      src: "...",
      srcset: "...",
      // For <source> inside <picture>.
      // Mapped by media/type attributes on DOM element
      source: [
        {
          media: "(max-width: 666px)",
          srcset: "...",
        },
        {
          media: "(max-width: 1332px)",
          srcset: "...",
        },
      ],
    },
  },
  video: {
    // src attribute on <video>
    src: "...",
    // Mapped by type. If type isn't set - mapped by <source> element order
    source: [
      {
        type: "video/mp4",
        src: "...",
      },
      {
        type: "video/webm",
        src: "...",
      },
    ],
  },
});
```
Yeah, it's ridiculously complicated).

> I think if the script user managed it in their own code, given that it knows what it's loading, it would be much easier and much less JS code would be required in the error handling.

Agree. Feel free to close the issue.

**Comment by verlok** [comment]
Thank you for your time!
