### ISSUE TITLE
<video> data-poster not loaded if preload="none" is present

### ISSUE THREAD

**Issue by arthabus** [verlok/lazyload#432]
**Describe the bug**

<video> data-poster not loaded if preload="none" is present

**To Reproduce**
1. Add `<video preload="none" data-poster="..." data-src="..." class="lazyload">` tag
2. see error: poster is not loaded

**Expected behavior**
Poster is loaded when `preload="none"` is set or the documentation mention to remove the `preload` attribute

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version 5.2.0

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.5
 - Browser chrome
 - Version 80

**Comment by verlok** [comment]
Hey @arthabus,
support for the `video` element was introduced from version 8.8.0.
I suggest you to update the version of LazyLoad to the latest.
Read the changes in the CHANGELOG.md file.

**Comment by verlok** [comment]
I've added 3 videos in the `video.html` demo, check the source here
https://github.com/verlok/lazyload/blob/master/demos/video.html

And the live demo here
https://www.andreaverlicchi.eu/lazyload/demos/video.html

The demo runs on the latest version of LazyLoad and in all 3 videos, the poster is shown while loading.
