### ISSUE TITLE
background-size: cover / object-fit: cover?

### ISSUE THREAD

**Issue by strarsis** [verlok/lazyload#433]
@verlok: Is it possible to use `lazyload` to cover an element completely with a background image,
what `background-size: cover` or `object-fit` (with an `<img>`) would do?
The height of the element is determined by its content and not known in advance, 
hence JavaScript is needed because `sizes` is static.

**Comment by verlok** [comment]
Hey @strarsis, 
thank you for asking. 
I'm not sure I understood your question, but I'll try and answer anyway.
When this script lazy loads a background image, it will set a new `background-image` option inline in the `style` of an element. You can still set `background-size: cover` in the CSS of your page.
Same thing wit `object-fit`, you can set it in the CSS of your page, and this script would just set the `src`, `srcset` and `sizes` attributes on your lazy images.
I have the feeling that I didn't answer your question, if it's so please ask again with more details.
Thanks

**Comment by strarsis** [comment]
@verlok: Yes, so some `div` got an `<picture>` element inside (with `<img>` that is actually the placeholder), so `webp` and `jpg` are both supported.
Additionally `object-fit: cover` is set for that `<img>` element.
Using `sizes` for each `<source>` inside the `<picture>` element, the browser should be able to load the right image.

However, the height of the `div` can vary wildly because its contents are edited from CMS,
hence it is not possible to specify `sizes` in advance. The text inside may break differently, pushing the div further down and increase the height - and the required width of the image to cover the element.
I need a loader that determined the actual required width of the `<img>`, then sets the right attributes of it so the browser can download the appropriate image file.

**Comment by verlok** [comment]
That's way too much complicated for what this tiny script manages. 
The way you put it, you might be interested in using https://github.com/aFarkas/lazysizes

**Comment by strarsis** [comment]
@verlok: Indeed, sadly that repository isn't maintained anymore.
Issues crop up and indeed it doesn't seem to work in iOS Safari browser for example.

Are you using a browser test service for your project? Could I use that browser test service (for free and fully), too, when I make that tool/lib opensource on GitHub?

**Comment by verlok** [comment]
I didn’t have the same feeling when I looked to it a few days ago. Good to know. 

I use browserstack, they give it to you for free if you manage an open source project.

**Comment by verlok** [comment]
I’m going to close this issue for now, feel free to reopen if you need any more help.

**Comment by strarsis** [comment]
@verlok: Concerning browserstack: Where can I find these tests in your repo? Is this similar to a config file for the other CIs like travis.yml?
Do I have to contact browserstack or do they add support for all public GItHub repos?

**Comment by verlok** [comment]
Hey man, sorry I didn’t understand quite well. 

I have unit tests in code but they are not end to end tests so they are not run on the browser, but on Node. 

I use browserstack to manually perform the tests on the main demos, especially on IE when I develop on Mac, and on Safari when I develop on Windows.

**Comment by strarsis** [comment]
@verlok: Ah! I see. Well, I thought there are tests that run automatically and on all kinds of browsers (by browserstack). It would be nice if these tests check the network connection tab in dev tools or something equivalent for the image file(s) that are downloaded for different window sizes and density.
