### ISSUE TITLE
Delay for showing every next loaded element

### ISSUE THREAD

**Issue by piotrbox** [verlok/lazyload#434]
Hello,

is there any way to add small delay in applying 'loaded' class for every next element. 
So lets say after sroll Lazyload finds 5 elements to load and it adds 'loaded' to every element at the same time. I want a smal delay afert first, than second, than third and so on. So i can display a gracefull loading of multiple elements in the viewport. 

This could be probably be done in some callback function, but I'm not that good at JS to execute it.

side note - obviously I am not talking about "load_delay"  option. 

any help or ideas??
thanx

**Comment by verlok** [comment]
Hey @piotrbox, good question!

First of all, let me ask WHY you would want to "display a graceful loading of multiple elements in the viewport". I agree that the effect would be nice, but put yourself in the shoes of your users, they would have to wait more to see the content they want to see, but the quicker you show the content, the happier they will be. There's plenty of [facts](https://wpostats.com/) about this point. Even a "fade in" effect like the one I showed in the demos is something to be discouraged in my opinion.

For that reason, LazyLoad doesn't provide any "out of the box" way of doing what you ask, but you could figure something out listening to the "loaded" callbacks.

Then secondly, things can get more complicated if you'd like to obtain a something like a linear "show of cards" effect (e.g. showing each image 50ms later than the previous one), because you need to consider that the "loaded" events don't necessarily arrive in the order the lazy elements are in the DOM (e.g: there could be a heavier image in 4th position that takes more to load than the one in 5th position). 

So you would need to keep track of every image in the DOM, check if the previous ones were loaded, chack that 50ms have passed since the last "loaded" event, then throw your own "show" event. 

If you really want to go down that path let us know, there could be someone in the “watchers" of this repo with the solution in their pocket, or willing to help you, or maybe I could help you if you [get me](http://ko-fi.com/verlok) enough caffeine.

**Comment by piotrbox** [comment]
Hey @verlok, thanks for fast replay.

I want this effect on a highly specialized website with low traffic, where general impression and eye catching design and feel is most important.  It's not a conversion monster, that sees improvments in 'ms' gains :) It will probbably convert(if we can even call it conversion there) exactly the same with or without this effect. I just want to polish it well.  

The images that we load are preatty small and of simmilar weight, so should load in qiute a linear matter. 

If there is any bored JS freak out there that is willing to help I would apreciate (lets face it probably 1/2 of mankind is now bored at home).

Will consider the caffe also :)  buona notte ! :)

**Comment by verlok** [comment]
You convinced me. I could help creating a solution and a demo for you. 
It will depend on how good my breakfast will be tomorrow morning ;)
Buona notte Piotr!

**Comment by Jonatan-r** [comment]
Hi @verlok ! Just bought you a ko-fi coffee for your breakfast! ☕️😄And in my message I requested just the same as @piotrbox is asking 😊

+ As well as this:
https://github.com/verlok/lazyload/issues/94#issuecomment-609193346
(making already faded-in (loaded) items not fade in once shown again (and cached) on another page)

Enjoy your breakfast!

**Comment by verlok** [comment]
Hey guys!
I had an excellent breakfast with enough caffeine, I’ve already started thinking about how to make this possible.

**Comment by verlok** [comment]
I’ve come up with a brilliant idea to make this work very simply. I’ll try and translate it to code as soon as I find some free time.

**Comment by verlok** [comment]
It's done!

```js
var toAnimate = [];

function addToAnimate(element) {
    toAnimate.push(element);
    console.log("Pushing", element, toAnimate);
}

var interval = setInterval(() => {
    var element = toAnimate.shift();
    if (!element) return;
    console.log("Shifting", element, toAnimate);
    element.classList.add("visible");
}, 50);

new LazyLoad({
    callback_loaded: addToAnimate,
    callback_error: addToAnimate,
    callback_finish: function() {
        clearInterval(interval);
    }
});
```

And it works like a charm!
I'm pushing it now in a branch named `feature/pocShowDelay`.

@piotrbox please tell me what you think about it!

**Comment by piotrbox** [comment]
Hi @verlok 

Firstly big thanx for the code.

I tryed the demo and it worked well. 
tryed in my project and results were mixed — when scrolling slowly it was ok, but wen going fast, 'visible' wasnt added to all elements, even thoug it was processed (data-ll-status="loaded").

with Chrome it happens when scrolling fast. 
in Safar also elements in different blocks have sometimes proeblems with loading even scrolling slow.
tested on mac only as i have no windows machine at home. 

this is the project i tested it on:

https://magnavisum.co.uk/gallery/  (its live website but gallery is not publicli linked and contains sample data)

Safari and FIREFOX has problems with processig down the botom in "Projects gallery:" section.

I have no idea why this happens.  :/

**Comment by piotrbox** [comment]
OK, I added 
setTimeout 5s to callback_finish -> clearInterval.  its ok now. but maby it should be somethnk else, like chceck if anything in arry of toAnimate.

**Comment by verlok** [comment]
Hey @piotrbox,

> Firstly big thanx for the code.

You're [welcome](https://ko-fi.com/verlok). ☕️ 

> Safari and FIREFOX has problems with processig down the botom in "Projects gallery:" section.
> I added setTimeout 5s to callback_finish -> clearInterval. its ok now. but maby it should be somethnk else, like chceck if anything in array of toAnimate.

I'm not sure I understand what is the problem you're currently having with this solution.
Could you please clarify?

**Comment by Jonatan-r** [comment]
@verlok Awesome quick fix! Thanks a bunch!! :D 
@piotrbox Really nice website design btw :)

**Comment by Jonatan-r** [comment]
Hi @verlok. So I implemented it now. But it's not quite what I expected 
I've showed here what I imagined:
https://www.youtube.com/watch?v=exfpKp5_DU0&feature=youtu.be
The images do load delayed now, but what I thought was that they would load sequentially, according to placement in DOM. Do you think that'd somehow be possible? 😄 

All the best,
Jonatan

**Comment by verlok** [comment]
Hey Jonathan,
this is what I initially wrote to Piotr in this very thread. 

> things can get more complicated if you'd like to obtain a something like a linear "show of cards" effect (e.g. showing each image 50ms later than the previous one), because you need to consider that the "loaded" events don't necessarily arrive in the order the lazy elements are in the DOM (e.g: there could be a heavier image in 4th position that takes more to load than the one in 5th position).

But Piotr replied that he didn’t care about the order, so I’ve created a queue to show the loaded elements every interval. 

To obtain something like what you’re asking is a different problem, because you need to consider both the order of the elements and the fact they were loaded or not. 

So we can’t keep the solution like it’s now, we need to keep a reference to the DOM elements yet to load in an array, then every 50ms check it the first in the queue has loaded, and if it hasn’t check again in another 50ms. 

Do you want to try to implement it yourself? Because now I’m feeling very [sleepy](https://ko-fi.com/verlok)… buona notte guys!

**Comment by piotrbox** [comment]
Hi guys,

sorry for no responce for few days.
Had no time at all.

I took a momen to analize what @verlok did and it was almos perfect.

unfrtunately ther was a bug (also in demo):

if you scrolled to bottom of page fast, before all images loaded nad got the "visible" class the callback_finish fired and stopped the intervl resulting in some images without "visible" class even thoug the files were loaded.

i changed it at the beggingn adding som setTimeout  but that looked like dirty trick.

today I took another turn at it edn set up slightly different aproach for the set interval function.
it runs only when needed and doesnt start on pages without things to lazyload.

the code is pobably choppy and in ancient manner but it works for me.

`    var toAnimate = [];
    var onLook = 0;

    function addToAnimate(el) {
        toAnimate.push(el);
        //console.log("Pushing", el, toAnimate);
    }

    function theLook() {
        if (onLook == 0) {
            onLook = 1;
            interval = setInterval(function() {
                console.log('interval');
                var el = toAnimate.shift();
                if (!el) {
                    clearInterval(interval);
                    onLook = 0;
                    return;
                };
                el.classList.add("visible");
            }, 100)
        }
    }

    function Run(el) {
        addToAnimate(el);
        theLook();
    }

    var lazyLoadInstance = new LazyLoad({
        elements_selector: ".lazy",
        callback_loaded: Run,
        callback_error: Run,
        threshold: tresh //differnet for mobile
    });`

@Jonatan-r unfortunately it does not fix your need for sequential load. 
I have an idea with some kiind of index/sort... but no time for that at the moment. Maby later :)
Also thanx for you appreciation on the website.

Hope it will work for someone.

**Comment by piotrbox** [comment]
`//start
    var toAnimate = [];
    var onLook = 0;

    function addToAnimate(el) {
        toAnimate.push(el);
    }

    function theLook() {
        if (onLook == 0) {
            onLook = 1;
            interval = setInterval(function() {
                console.log('interval');
                var el = toAnimate.shift();
                if (!el) {
                    clearInterval(interval);
                    onLook = 0;
                    return;
                };
                el.classList.add("visible");
            }, 100)
        }
    }

    function Run(el) {
        addToAnimate(el);
        theLook();
    }

    var lazyLoadInstance = new LazyLoad({
        elements_selector: ".lazy",
        callback_loaded: Run,
        callback_error: Run,
        threshold: tresh
    });`

**Comment by piotrbox** [comment]
HMM. somethink breaks whe pastin code ..
it cuts out the beggining 

`//start
    var toAnimate = [];
    var onLook = 0;

    function addToAnimate(el) {
        toAnimate.push(el);
    }

    function theLook() {
        if (onLook == 0) {
            onLook = 1;
            interval = setInterval(function() {
                console.log('interval');
                var el = toAnimate.shift();
                if (!el) {
                    clearInterval(interval);
                    onLook = 0;
                    return;
                };
                el.classList.add("visible");
            }, 100)
        }
    }

    function Run(el) {
        addToAnimate(el);
        theLook();
    }

    var lazyLoadInstance = new LazyLoad({
        elements_selector: ".lazy",
        callback_loaded: Run,
        callback_error: Run,
        threshold: tresh
    });`

**Comment by verlok** [comment]
@Jonatan-r do you still need help with the sequential loading?

**Comment by Jonatan-r** [comment]
@piotrbox @verlok Thanks a bunch guys! 😊 Well as I'm not really any javascripter myself (only a poor user) I don't wanna waste time trying to do anything clever.. Would just be sad haha.. 

> @Jonatan-r do you still need help with the sequential loading?

Well only if you'd have any freetime @verlok it'd be nice. Maybe if you felt like it'd be a nice feature addition for the plugin. I'm sure you could live up to the challenge 😉

But it's not in any way necessary.. not at all "need to have" just "kinda could be nice to have" as this current implementation is just for my [personal portfolio](https://jonatanronsholdt.dk). And I think it looks pretty nice as it is now.  But I can totally see the paradoxical in the 'img loaded?' versus 'dom order' as you described.

**Comment by verlok** [comment]
Your personal portfolio looks gorgeous now, @Jonatan-r !

I don't think you need a perfect DOM order loading because the images already appear in the right order  and in many sections you have full width images. And if - in some odd case - they don't... it wouldn't be a big deal I think.

**Comment by Jonatan-r** [comment]
Thank you @verlok! 😀 You're too kind! 😊
