### ISSUE TITLE
Data status not change on IE11

### ISSUE THREAD

**Issue by pfasang** [verlok/lazyload#435]
**Describe the bug**
Hi, I have a problem with `data-ll-status` attribute in divs with lazy loading bg image. After image is loaded, `data-ll-status` stills keep "loading" value and not change to "observed". 

**LazyLoad version**
- Version: 15.1.1

**Desktop:**
 - OS: macOS
 - Browser: IE
 - Version: 11

**Additional context**

**Comment by verlok** [comment]
Hey,
could you please report the HTML you’re using and the JS code you’re using?
Secondly, could you please specify how you could use IE11 on Mac OS?

**Comment by pfasang** [comment]
I use Browserstack for testing on Mac, sorry for misunderstanding. 
```
const lazyLoadPlugin = new LazyLoad({
    class_loading: 'lazy-loading',
    class_loaded: 'lazy-loaded',
    elements_selector: "[lazy]"
});

<div lazy data-bg="image.jpg" class="ce-image-break-content" ></div>
```
I use Vue.js and in mounted method, I call `lazyLoadPlugin.update()`. Works fine on other browsers, except IE11.

**Comment by verlok** [comment]
Sorry, I forgot to ask the last information: what version of LazyLoad are you using?

**Comment by pfasang** [comment]
Newest version 15.1.1

**Comment by verlok** [comment]
Right, 
so I've tested it on my local IE11 now and it seems to be working fine.

![image](https://user-images.githubusercontent.com/1127721/78561433-0401da80-7818-11ea-848e-4b0121b59f6d.png)

Therefore, I must keep asking.
Are you using some kind of polyfills, e.g. the IntersectionObserver polyfill?

**Comment by verlok** [comment]
By the way, can I ask you why you are loading background images instead of content images? 
I'm asking because it's usually an anti-pattern. Are you images REALLY background images? 
To understand if they are content or background images, ask yourself: would my website user like to see those images when printing the page?
If they are content images, you should go for the `img` tag. It also has advantages for SEO and Accessibility.

**Comment by pfasang** [comment]
I'm using Webpack with core.js plugin. This plugin contains all kind polyfills. Also I don't have any error in IE console. I will check, if this plugin contains IntersectionObserver polyfill as well.

Most of images are loaded by `img` tag, but in some cases I need use bg-image. Google PageSpeed is in green numbers, I'm not worry about that. When you use background images correctly, it has no effect on SEO or Accesibility.

**Comment by pfasang** [comment]
OK, I found solution. `core-js` doesn't have polyfill similar to IntersectionObserver. I installed `intersection-observer`, now is working fine. Thank you for help.

**Comment by verlok** [comment]
I'm glad you solved!
