### ISSUE TITLE
Three Cheers for LazyLoad!

### ISSUE THREAD

**Issue by Blake-LeBlanc** [verlok/lazyload#436]
@verlok , LazyLoad is AWESOME! 

Thanks for all the work you guys put into its EXCELLENT documentation. Your "Upgrade Notes" make it ridiculously easy to stay in touch with everything that's going on with the plugin.

Keep rocking on Andrea and Co!

*fist bump with explosion + raindown*

-Blake

**Comment by verlok** [comment]
Thanks very much @Blake-LeBlanc!
The congratulations like yours keeps te open source developers motivated, those... and [☕️ coffee](https://ko-fi.com/verlok). 
Cheers!

**Comment by verlok** [comment]
Thanks again @Blake-LeBlanc, I'm gonna close this now.
Feel free to [send coffee](https://ko-fi.com/verlok) anytime.
