### ISSUE TITLE
[Newbie] Initializing in Angular - AppComponent

### ISSUE THREAD

**Issue by sid-dob** [verlok/lazyload#440]
**Is your support request related to a problem? Please describe.**
I am trying to initialize LazyLoad in an angular project with no success.

Using this
```typescript
import { Component, Inject, OnInit } from '@angular/core';
import LazyLoad from 'vanilla-lazyload';
import { DOCUMENT } from '@angular/common';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
    title = 'DailyObjects';
    lazyload;

    constructor(@Inject(DOCUMENT) private document: Document) {
        console.info('Loaded');
    }

    ngOnInit(): void {
        this.lazyload = new LazyLoad({
            elements_selector: '.lazy',
        });
        console.log(this.document);
        this.lazyload.update(this.document);
    }
}
```

**Expected behavior**
I do not want to include script in index.html. I want to initiate  this service from typescript in angular itself.

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version 15.1.1

**Comment by verlok** [comment]
Hey @sid-dob thanks for asking. 
Could you please specify why are you failing in what you are trying to achieve?

**Comment by sid-dob** [comment]
I wanted to ask if my implementation is correct. The images from `data-src` aren't loading yet. Is there a way to debug this issue ? Are there any params to debug DOM directives for lazyload or a debug mode.

**Comment by verlok** [comment]
For sure it's not necessary to call the `this.lazyload.update(this.document);` after `this.lazyload = new LazyLoad({`, since the `update` method is called in the costructor.

To understand why this is not working, you probably need to post the related HTML code together with your Angular code.

If you still need help please do so.

**Comment by sid-dob** [comment]
Yes, so I have it figured out. I am writing this in-case anybody needs it in the future.

# Integration in Angular
1. Install dependency via `npm install vanilla-lazyload --save`
2. Add the following import to `AppComponent` : 
```typescript 
import LazyLoad from 'vanilla-lazyload';
```
3. Add the following snippet to `AppComponent` constructor : 
```typescript
constructor(@Inject(DOCUMENT) private document: Document) {
        document.onreadystatechange = () => {
            if (document.readyState === 'complete') {
                this.lazyload = new LazyLoad();
            }
        };
    }
```

Note: You do not need to add anything in `angular.json` or in the `index.html`

Useful things I found while debugging : 
1. Easy way to check if library is working is to check if the data-src is being converted to src at runtime.

**Comment by verlok** [comment]
Thank you @sid-dob
