### ISSUE TITLE
Unable to lazy load videos with use_native: true

### ISSUE THREAD

**Issue by Booligoosh** [verlok/lazyload#441]
**Describe the bug**
When setting `use_native` to `true`, it is unable to lazy load videos.

**To Reproduce**
Here is a basic reproduction:
https://codepen.io/Booligoosh/pen/ExVyVgb
Comment out the line in the JS saying `use_native: true` and it will work.

**Expected behavior**
It should proceed without native lazy loading for video elements, since there _is_ no native lazy loading for video elements

**LazyLoad version**
15.1.1

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 81.0.4044.92

**Comment by Booligoosh** [comment]
Actually, I just found the solution you posted [here](https://github.com/verlok/lazyload/issues/439#issuecomment-613107856). I'm using that for now. However, it might be worth mentioning something about it in the docs, as it probably causes confusion for some people.

**Comment by verlok** [comment]
Thanks for your feedback. 
Yes native lazy loading only works on images and iframes, for now. 
Will update the docs.
