### ISSUE TITLE
trying to use on nextjs framework

### ISSUE THREAD

**Issue by zbiwi** [verlok/lazyload#443]
Hello,

I'm trying to use vanilla-lazyload on my nextjs projet.
I used yarn to install locally lazyload ^15.1.1.
I followed everything in the sandbox project, but when I use it in my project, I have this error : 

./components/utils/lazy-image.js
Module not found: Can't resolve 'vanilla-lazyload' in '/usr/src/app/components/utils'

I checked in my package.json and my node_modules folder and I have the module.
I don't understand why, I have this error :(

thank you for helping me

**Comment by verlok** [comment]
Hey @zbiwi ,
thank you for opening this.

If you still need help, posting the portion of Javascript code that generates the error might be useful to solve your issue.

**Comment by verlok** [comment]
I'm assuming you solved somehow. If you still need help, feel free to reopen.
