### ISSUE TITLE
src and data-src

### ISSUE THREAD

**Issue by evandiamond** [verlok/lazyload#445]
Hi @verlok 

First, wanted to thank you on your plugin, it's made my life a lot easier!

Secondly, I may have found a bug...

In your first example, you have code that looks like this:

```html
<img
   alt="Sneakers &amp; Tennis"
   class="lazy"
   data-src="https://via.placeholder.com/440x560?text=Img+03"
   width="220"
   height="280"
/>
```

However, for w3c validation, it requires a src. So, if I make the code look like this:

```html
<img
   alt="Sneakers &amp; Tennis"
   class="lazy"
   src="https://via.placeholder.com/220x280?text=Img+03"
   data-src="https://via.placeholder.com/440x560?text=Img+03"
   width="220"
   height="280"
/>
```

The src does not load lazily. It loads on page load. Unless I'm doing something wrong?

**Comment by verlok** [comment]
Hey @evandiamond 
thank you for reporting. 

Not having the `src` attribute at landing and applying it later is the whole point of this library. 

If you apply the `src` directly, and _you should do that_ on the first 1-4 images of you page, your images will me loaded as soon as possible. It’s how html and browsers work. 

I wouldn’t worry too much about the w3c validation of your static html code, the code must be valid after JavaScript did its magic. 

I’m glad you love this library. See #437
