### ISSUE TITLE
Scrolling up threshold not working?

### ISSUE THREAD

**Issue by alvarotrigo** [verlok/lazyload#449]
Reproduction online:
https://jsfiddle.net/va36s1dw/1/

Steps:
Scroll up.

Video:
![aa](https://user-images.githubusercontent.com/1706326/80707096-b5c7ba80-8ae9-11ea-9070-aea539b80967.gif)

**Comment by verlok** [comment]
Ola @alvarotrigo ,
you are using a scrolling container and you forgot to set the container option.
There goes [the fix](https://jsfiddle.net/m65v7rb9/).
De nada.

**Comment by alvarotrigo** [comment]
Uh! I missed that!

Thanks for pointing it out @verlok ! ;)
