### ISSUE TITLE
iframe lazy loading not working as expected. 

### ISSUE THREAD

**Issue by oma0256** [verlok/lazyload#450]
I have followed the docs as well as the demo example you have stated on using `lazyload` with `iframes`, however I have issues performing lazy loading with multiple iframes I have rendering on my page. I have an array of links from which I'm dynamically creating iframes for using JavaScript. However when I setup `lazyload`, all the iframes are being rendered regardless of whether they can be seen on the viewport or not. Also when I scroll down the iframes above the viewport will disappear and re render after when I scroll back up same happens when I scroll back up after viewing certain items below the viewport. Example of the code I'm using is below. Any help will be much appreciated thanks.

```html
<script src="https://cdn.jsdelivr.net/npm/vanilla-lazyload@15.1.1/dist/lazyload.min.js"></script>
<script type="text/javascript">
            const get = async (url)  => {
                const res = await fetch(url, {
                  method: "GET"
                });
                const resData = await res.json();
                return resData;
            }
        const url = '<endpoint to retrieve links to be used in iframes>';
        get(url).then(data => {
            const lti_launch_urls = data['lti_launch_urls'];
            const loadNextIframe = index => {
                if (index >= lti_launch_urls.length) {
                    // After all iframes have been created initiate lazy load 
                    var lazyLoadInstance = new LazyLoad({
                        elements_selector: ".lazy"
                        // ... more custom settings?
                    });
                    return;
                }

                const iframe = document.createElement('iframe');
                iframe.sandbox = "allow-same-origin allow-scripts allow-popups allow-forms";
                iframe.width = "100%";
                iframe.frameBorder = "0";
                iframeId = "iframe-" + index;
                iframe.id = iframeId;
                let launch_url = lti_launch_urls[index];
                iframe.setAttribute("class", "lazy");
                iframe.setAttribute("data-src", launch_url);

                iframe.addEventListener('load', () => loadNextIframe(++index));

                console.log(iframe);
                document.body.appendChild(iframe);
            };

            loadNextIframe(0);
       })
</script>
```

**Comment by verlok** [comment]
I can't see anything that shouldn't be working on your code. I mean, it should be working that way.
The only thing you can optimize is that you can create your lazyload intance out of the `loadNextIframe` function, then call its `update` method inside `loadNextIframe` after appending the `iframe` to the body.

**Comment by oma0256** [comment]
Hey @verlok to add more context these iframes are rendering content from a different domain, please let me know if there's more information I can provide to help debug the issue.

**Comment by oma0256** [comment]
@verlok just to add all the iframes are being loaded immediately I visit the page rather than only loading those in the viewport, then loading the rest as I scroll down.

**Comment by verlok** [comment]
Did you set a minimum height for the iframes? Otherwise all of them will be injected inside the viewport and loaded immediately

**Comment by verlok** [comment]
Do you have a scrolling container (overflow: scroll or auto)? If you have it, you need to specify it in the LazyLoad options

**Comment by oma0256** [comment]
@verlok  Thank you very much you are a life saver height on the iframe was the missing puzzle.

**Comment by oma0256** [comment]
Hey @verlok thanks the `min-height` was part of the problem. However there's the issue of iframes reloading again when I scroll any idea why that would happen and how I can prevent that, see screenshot below thanks.  
![Screenshot 2020-05-04 at 00 58 05](https://user-images.githubusercontent.com/14260655/80926886-a2934400-8da2-11ea-8a04-be67271ed847.png)

**Comment by oma0256** [comment]
Thank you @verlok `min-height` was the missing piece. And btw great work you are doing right here really appreciate it.

**Comment by verlok** [comment]
You’re welcome
