### ISSUE TITLE
Lazy load gallery/carousel/slider elements and pause play until next is loaded

### ISSUE THREAD

**Issue by wzol** [verlok/lazyload#453]
This is a bit mixed thing: so, there are many autoplay gallery/carousel/slider solutions, some try to implement lazy loading too. When the next item partly gets into the viewport or reach the threshold, it is easy to handle with the current toolset. 

It becomes tricky when there is only 1 image visible (like a hero slider) and you can skip/autoplay to the next (or on mouseover). What I think about as ideal UX and also in terms of data saving:

- don't load all items at once - probably overkill, they might not even needed
- if there is autoplay, respect that, but only jump to next if and when it is loaded - avoiding empty, partly loaded image: so if autoplay is 3s but the next image is still not loaded, wait for it and then skip to next when it is loaded
- always preload next 2-3 items but cancel pending loadings if play is stopped (example on mouseleave)

I couldn't yet find an out of the box for this, some loads all images, some only care about the timer (showing empty/partly loaded slides on slow connections) so I'd appreciate any ideas.

**Comment by verlok** [comment]
I find [swiper Js](https://swiperjs.com/) very useful for that purpose. Not only it works veeery well on mobile, but it also has a LazyLoad option and options to preload the next and/or the previous slide to prevent having a missing image on slide. 

I also know that some libraries work well in conjunction with my LazyLoad script, being it based on IntersectionObserver, while others don’t. If I’m not mistaken, swiper JS should be amongst the working ones.

**Comment by wzol** [comment]
It is really nice - I'm btw using [Slick](https://kenwheeler.github.io/slick/) - but it seems the same problem exists: while lazy load is possible, it doesn't take into account during autoplay if and when an image is loaded - so it simply jumps to next even if the image is not yet loaded.

But it is not really about a JS library, I'm fine doing a simple mouseover slideshow with just a timer and
```
fader_elem.children().first().hide()
.next().show()
.end().appendTo(fader_elem);
```
The problem is that I can only do this step when the next image is fully loaded - which can be checked, but if it takes more time than the timer I'll have to wait for it. So if I want to show the next image in 3s, but it takes 5s to load it - how will I know when it is loaded? Doing a `while(!nextimagehasClass('loaded')) {sleep()}` before stepping would work in theory but really looks like (and is) an ugly hack.

**Comment by verlok** [comment]
This really seems an issue you should file under the [Slick repo](https://github.com/kenwheeler/slick).

**Comment by wzol** [comment]
I rephrase myself, currently I don't need a slider library. I'm just looking for a best use case on how can I use example Lazy's image loaded callback as an event to trigger a "move to next" to my gallery.

**Comment by verlok** [comment]
I’m still not understanding, sorry. 
Could you please explain what you’re trying to achieve, from the beginning?

**Comment by wzol** [comment]
Ok, a specific example:

- the first image of a gallery is visible
- on mouseover the loading of all the remaining images start
- after 700ms the next image is displayed in the place of the first but only if it is fully loaded
- if the next one is not loaded in 700ms then wait until it is done loading then immediately show it
- repeat with all images, then jump back to the first one
- on mouseleave cancel pending loadings and show the first image

The main difficulty is bringing the two async tasks to sync, the loading queue and the timer:
- if the next image is loaded: wait for the timer
- if the timeout done: wait for the next image to load

**Comment by verlok** [comment]
Hey @wzol 
long story short, you want to create a carousel with lazy loading and auto play.  
What you ask is doable with some custom JavaScript but it has more to do with a carousel script than with a LazyLoad script. 
Again, https://swiperjs.com/ does that and a lot more. Please check that library and especially in its LazyLoad feature.
