### ISSUE TITLE
Lazyload and smooth scroll not playing well together (edit:) with responsive images

### ISSUE THREAD

**Issue by welling11** [verlok/lazyload#456]
This might be more of an enhancement request, (or I'm likely missing a work-around).

**Function:** I'm currently using a smooth scrolling script. A click on a button in the top nav causes the page to automatically scroll directly to the anchor set in the footer. 

**Problem:** With Lazyload in use, not all of the images have loaded between the navigation and the set anchor at the bottom of the page. So the scroll stops short of where the actual anchor is, mistaking the end location for an image that was successfully loaded.

**Attempted Solution:** All my images have width and height values set in the HTML, but smooth scroll still refuses to scroll past anything that lazyload hasn't yet loaded.

**Comment by verlok** [comment]
The solution you’ve attempted should work, meaning reserving space by setting the width and height of images. 

Could you post an example on Codepen, so I can check what is wrong?

**Comment by verlok** [comment]
Hey @welling11 ,
I created [a working example on Codepen](https://codepen.io/verlok/pen/xxwQxEW?editors=0100) so you can see how you could implement it, and it seems to me it's working fine.
I hope you [enjoy ☕ it](https://ko-fi.com/verlok)!

**Comment by welling11** [comment]
Thanks so much for setting this up!  I played around and think my issue could be from using responsive images. I set width/height in the HTML on images to maintain an aspect ratio. But depending upon the browser window size the set image height value isn't the exact image size of what the viewport shows -- possibly causing the scroll to fall short of the destination. The reserved space isn't equaling what is actually needed.
I've been trying a few workarounds (thus far unsuccessfully) and I'll try and get a pen up with the initial issue. But I'm guessing the initial .js just wasn't built with this flexibility in mind.

thx again!

**Comment by verlok** [comment]
You need to occupy vertical space using responsive images so. If you read the readme, there are a couple of ways to do so. One is the percent padding hack, the other one is to use a placeholder SVG. 

You’re [welcome](https://ko-fi.com/verlok)!

**Comment by verlok** [comment]
@welling11 I'm closing this now. If you still need help, feel free to reopen.
