### ISSUE TITLE
Lazyload with Nuxt as a Vue-Directive

### ISSUE THREAD

**Issue by rylanharper** [verlok/lazyload#458]
Hi there!👋 First off thank you for this library I have used this in the past and it is great! I have a question/am looking for help about using Lazyload as a custom Vue-Directive within Nuxt... 

**Describe the Issue**
Currently I have a small blog setup with Nuxt and Prismic.. I am creating a small plugin that uses Lazyload as a custom Vue-Directive which becomes `v-lazy` and then attaching it to an image. I am running into an issue with the data-status attribute on my images that seems to switch back and forth between `data-status=loaded` and `data-status=loading` upon page refresh. Here is what my code briefly looks like:

lazyloader.js 
```
import Vue from 'vue'
import LazyLoad from 'vanilla-lazyload'

/*
** Here we are creating a custom
** Vue directive with lazyload `v-lazy`
*/
Vue.directive('lazy', {
  // When the bound element is inserted into the DOM...
  inserted (el) {},
  bind (el) {
    // Array/nodelist
    el.item = []
    el.item.push(el)
    el.instance = new LazyLoad(
      {
        thresholds: `${window.innerHeight * 2}px 0%`
      },
      el.item
    )
  },

  unbind (el) {
    el.instance.destroy()
  }
})
```
Image.Vue (with `v-lazy`) 
```
<template>
...
	<div class="block-img" :class="size">
		<div class="image-cover">
	     	<prismic-image v-lazy :field="img" :alt="img.alt" />
	  	</div>
	</div>
...
</template>
```
I am also creating a plugin within my nuxt.config.js file: 
```
export default {
...
  /*
  ** Plugins to load before mounting the App
  */
  plugins: [
    {
      src: '~/plugins/lazyloader.js', mode: 'client'
    }
  ],
...
}
```
**The Problem**
Within my development environment, the images seem to get randomly suck with `data-status=loaded` or `data-status=loading` (seems to be random upon page refresh) and I cannot figure out why despite looking into the issue over the past three days or so. I feel it may be an issue with how I have my Vue-Directive set up. However I have thought it may also be an issue within development mode and I have not generated the app yet using Nuxt Generate. Lazyload does seem to be working at least, but I need some addition help for experienced Vue/Nuxt users

**Expected behavior**
Images have a consistent data-status of loaded instead of being randomly stuck suck with `data-status=loaded` or `data-status=loading`    

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version ["vanilla-lazyload": "^16.0.0"]

**Desktop (please complete the following information):**
 - Browser [Chrome]
 - Version [81]

**Additional context**
Any help or advice from experienced Vue/Nuxt users would really help me out! Perhaps someone has already done something similar to this and I just haven't been able to find it 🤔

**Comment by rylanharper** [comment]
**UPDATE**

I solved the issue with using the `use_native` option (from the Lazyload docs) within my custom Vue-Directive.. I am still not entirely certain as to why (possibly since I am using Prismic).

Here is the code to anyone working within Nuxt for a simple plugin with Lazyload:
```
import Vue from 'vue'
import LazyLoad from 'vanilla-lazyload'

/*
** Here we are creating a custom
** Vue directive with lazyload `v-lazy`
*/
Vue.directive('lazy', {
  // When the bound element is inserted into the DOM...
  bind (el) {
    // Array/nodelist
    el.item = []
    el.item.push(el)
    el.instance = new LazyLoad(
      {
        // Distance off the scrolling area from which to start loading the elements
        thresholds: `${window.innerHeight}px 0%`,
        // Hybrid lazyload which delegates loading to browsers that support it
        use_native: true
      },
      el.item
    )
  },
  unbind (el) {
    el.instance.destroy()
  }
})
```
Your image with `v-lazy`: 
```
<template>
...
	<div class="block-img" :class="size">
		<div class="image-cover">
	     	<prismic-image v-lazy :field="img" :alt="img.alt" />
	  	</div>
	</div>
...
</template>
```
Your plugin within your nuxt.config.js:
```
export default {
...
  /*
  ** Plugins to load before mounting the App
  */
  plugins: [
    {
      src: '~/plugins/lazyloader.js', mode: 'client'
    }
  ],
...
}
```

Hope this helps someone out! 😄

**Comment by slav-weber** [comment]
Hey this helped me adapt vanilla-lazyload for Nuxt3 RC13 with Composition API
To start use vanilla lazyload with Nuxt 3 we only need to add 2 files into the /plugins folder:
`vanillalazyload.client.js`
```
import LazyLoad from 'vanilla-lazyload'

/*
** Custom Vue directive with vanilla-lazyload 'v-lazy'
*/
export default defineNuxtPlugin(nuxtApp => {
    nuxtApp.vueApp.directive('lazy', {
        // When the bound element is inserted into the DOM...
        mounted(el) {
            // Array/nodelist
            el.item = []
            el.item.push(el)
            el.instance = new LazyLoad(
                {
                    // Distance off the scrolling area from which to start loading the elements
                    threshold: 50,
                    // Hybrid lazyload which delegates loading to browsers that support it
                    // use_native: true
                },
                el.item
            )
        },

        unmounted(el) {
            el.instance.destroy()
        }
    })
})
```
`vanillalazyload.server.js`
```
/**
 * Fix SSR error when 'lazy' not defined
 */
export default defineNuxtPlugin(nuxtApp => {
    nuxtApp.vueApp.directive('lazy', {})
})
```
Maybe somebody will have some ideas how to do it without `vanillalazyload.server.js` file
I also want to explain why we should use v-lazy directive with SSR.
Without using v-lazy in ssr, you will have to transfer the html file without img tags, which in turn entails the problem of zero image size in height and width. When they do start rendering on the client side, due to the fact that they cannot push each other (height 0 and width 0), the lazy load may think that these images are in the viewport.
When the SSR can see v-lazy without any error, it can prepare <img> tag and send to the client, the client has an html <img> tag that can have a height and can push other images out off the screen.
Unfortunately this is not a short explanation, but I hope it is understandable.
