### ISSUE TITLE
Option to use `src` rather than `data-src` (if can't control that)

### ISSUE THREAD

**Issue by brycewray** [verlok/lazyload#461]
## The problem

When using an SSG and referencing images in Markdown with the `![Alt text here](image_url_here)` syntax, this doesn't make it possible to give the image the `data-src` attribute needed for LazyLoad. Furthermore, if using a plugin with the SSG that turns the image into a responsive image with the `<picture>` element, the plugin may also not give the SSG user the ability to specify that `srcset` should be `data-srcset` as LazyLoad needs.

## Requested/suggested solution

If possible, there should be an option to let LazyLoad recognize `src` rather than `data-src` and, similarly, `srcset` instead of `data-srcset`. This could be similar to the current options `data-src` and `data-srcset` **except** that there **wouldn't** be `data-` understood in them (e.g., the instructions for `data-src` imply that `data-` is passed automatically with whatever one enters for `data-src`, since `src` is this option's default).

## Alternatives considered

Since neither the Markdown image syntax nor the specific responsive-images plugin gives me any options, and since LazyLoad requires `data-`-prefixed attributes, there are no alternatives of which I'm aware under this scenario.

**Comment by verlok** [comment]
Hey @brycewray 

if you use the `src` and `srcset` attributes, the browser will start downloading your images as soon as it finds them in your markup code, unless there's a `load=lazy` attribute in the `img` tag, but I'm afraid you can't add it either using Markdown. 

You should use regular HTML image tags in your markdown. Did you know that you can do that? Markdown accepts HTML code in it.

#### An example from my blog

```markdown
In the latest years, both at my job and as maintainer of a 
[LazyLoad script](https://github.com/verlok/lazyload), I've specialized in **lazy loading** 
of **responsive images**. Today I'm going to show you what HTML, CSS and JavaScript 
code you need to write _in 2019_ in order to serve responsive images _and_ load them 
lazily. In the second part of the post, I'm also showing how to make the browser 
**natively pick the WebP image** when it supports it.

<figure>
    <img 
       alt="Lazy loading responsive images (2019)" 
       src="/assets/post-images/lazy-load-responsive-images-2019__ph.jpg" 
       data-src="/assets/post-images/lazy-load-responsive-images-2019__1x.jpg"
       data-srcset="/assets/post-images/lazy-load-responsive-images-2019__1x.jpg 1x, 
           /assets/post-images/lazy-load-responsive-images-2019__2x.jpg 2x"
       class="lazy post-image">
    <figcaption>
        Photo by <a href="https://unsplash.com/@bugsster">Taras Shypka</a> 
        on <a href="https://unsplash.com/search/photos/responsive">Unsplash</a>
    </figcaption>
</figure>

## Responsive lazy what?

**Responsive images** are the images that adapt to the user's screen _while_ keeping 
our websites fast by downloading just the right image source for the right **viewport 
witdh** (from small devices to large desktop computers), also considering the user's
**screen density** (retina display, hiDpi, etc.). 
```

In this way you can use whichever tag you prefer, like the `figure` and `figcaption` tags to improve A11Y and SEO, or the `picture` tag when you need it.
What do you think?

**Comment by brycewray** [comment]
@verlok Yes, I use HTML in my Markdown at times, but was attempting to use a Markdown-only writing workflow for a variety of reasons. Fortunately, it won’t take me long to convert those image references back to HTML and, thus, control the attributes for compatibility with LazyLoad, so I’ll do that. Thanks!

**Comment by brycewray** [comment]
Just will add, for the sake of other [Eleventy](https://11ty.dev) users who may view this later, that my tests with certain plugins for creating responsive images and lazy-loading images, at least in their current state as I write, suggest you may be better off creating responsive images at build time with your **own**  code (and/or using various utilities to create them on your local setup and send them on, perhaps using Eleventy's [Passthrough File Copy](https://www.11ty.dev/docs/copy/) functionality) and then inserting them in your pages with Eleventy [shortcodes](https://11ty.dev/docs/shortcodes) &mdash; whereupon you can **freely** configure the `picture` and `img` elements for full compatibility with LazyLoad.

Spaghetti-ish but working examples are my run-at-build [`imgxfm.js` script](https://github.com/brycewray/eleventy_solo/blob/master/imgxfm.js) and [`lazy-picture.js` shortcode](https://github.com/brycewray/eleventy_solo/blob/master/src/assets/utils/lazy-picture.js) &mdash; on each of which you obviously can improve greatly! 😄 🤷‍♂️  But at least they point you in the right directions, I hope.

**Comment by c0derabbit** [comment]
coming from eleventy, what you can also do is replace all images’ `src` with `data-src` in your templates (using .11ty.js here):
```js
const lazy = content => content.replace(/<img src/g, '<img data-src')
```
and then in the html:
```html
<article>
  ${lazy(content)}
</article>
```
