### ISSUE TITLE
Callback not fired until images in a batch are loaded.

### ISSUE THREAD

**Issue by JackDandy** [verlok/lazyload#47]
Hello,

I can scroll down to trigger images in a viewport while observing their class change to "loaded" in the inspector view of Firefox.  However, the src= of say one image can complete but the callback_load isn't fired until all currently requested elements of the viewport batch are loaded. The images affected seem to be browser cached images.

This is a subtle feature that affects normal use in this way... I have an indicator display for each image while loading. A requested image in a batch can display but the indicator doesn't go away until all the batched images are loaded.  I expected each image src= to be set when the actual load event is fired, which seems to not be the case, instead it is fired on `scroll` or `update()` (which is called on init which is outside a load event).

I set no other config options apart from the one callback, like so...
```
new LazyLoad({callback_load:function(element){
    $(element).parent().find('.lazy-indicator').hide();
}});
```
and the CSS sections including...
```
/* Fixes Firefox anomaly during image load */
@-moz-document url-prefix(){
	img:-moz-loading{visibility:hidden}
}
```

[edit]
jquery is used here with lazy load, however, the issue persists when the jquery requirement is removed. 

**[edit 2]**
maybe call `_setSources()` in the encapsulated function `loadCallback()` inside of `_showOnAppear()` ?
the callee to _showOnAppear() would need to be considered with this change. Hmm, tests show this change is not a complete solution.

[edit]
On another note, this work can be improved by not firing fetch events for every scroll, but instead when scrolling stops, this way, if a page is scrolled from top to bottom, only images at a final resting place are loaded instead of many of the images in between. The effect here is noticeable when using page refresh then ctrl-end with a page of 100 images, the `throttle` config seems to have no effect here, the bottom images take time to load as many (not all) images above are being loaded first - this is further brought into light as the images on the page are coming from an endpoint that first has to cache the images locally and then return that image to your lazy-load.

Hope this makes sense.

Other than these points, nice work, and thanks.

JD

**Comment by JackDandy** [comment]
Nevermind, i figured a way.

**Comment by verlok** [comment]
Sorry about that. 

Psst: have you already starred this repo? All you need to do is to press the Star ★ button on the top right corner of the website. ;)
