### ISSUE TITLE
Lazy loading of <video> tag?

### ISSUE THREAD

**Issue by si14** [verlok/lazyload#52]
If I understand sources correctly, it is now impossible to use the library for `<video>` tags. Do you think this is a bad idea?

**Comment by verlok** [comment]
I confirm it won't work on videos. The script only considers `source` tags that are siblings of an `img` tag inside a picture.

**Comment by banago** [comment]
This script is perfect for what it does and I suggest you keep it that way.

**Comment by verlok** [comment]
Thanks @banago.
I'm closing this.
