### ISSUE TITLE
Advanced performance optimizations (passive listener, intersection observer)

### ISSUE THREAD

**Issue by si14** [verlok/lazyload#53]
Looks like there is a couple of ways to further improve performance of the library in modern browsers.

1. [Passive event listeners](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md) ([caniuse](http://caniuse.com/#feat=passive-event-listener))
2. [Intersection observer](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) ([caniuse](http://caniuse.com/#feat=intersectionobserver))

Do you think they can be useful for the library? The former is better supported, and the latter is even more efficient.

**Comment by verlok** [comment]
Hey @si14, thanks for your suggestions
Intersection observer is still a draft, but passive event listeners are a thing on most browsers... I'll give it a try and if it degrades gracefully I'll implement it.

**Comment by verlok** [comment]
@si14 all examples that I've found about passive event listeners talk about passive listening the `touchStart` event. Even searching more specifically, I didn't found anything about passive listening neither the `scroll` event nor the `resize` events, which are the only ones my script listens to.

Did you find something more specific?
