### ISSUE TITLE
ignore rewriting of null image sources

### ISSUE THREAD

**Issue by Niresh12495** [verlok/lazyload#54]
Why?
Most php plugins rewrite src to data-original-src, they doesn't check if img src has a value or empty in that case rewriting cause a 404 error 
Example check this url

[How to be happy](https://www.guest.blog/post/7043/be-happy/)

**Comment by Niresh12495** [comment]
This issue was related the following issue
https://github.com/verlok/lazyload/issues/48


Make sure to check if data-original-src set has a value

**Comment by Niresh12495** [comment]
You can close this issue
 add this code to src
`if (elementSrc) element.style.backgroundImage = "url(" + elementSrc + ")";`

https://github.com/verlok/lazyload/issues/48

**Comment by verlok** [comment]
Fixed in [version 4.0.4](https://github.com/verlok/lazyload/releases/tag/v4.0.4)
