### ISSUE TITLE
Not working properly on Safari iPhone 6?

### ISSUE THREAD

**Issue by anchev** [verlok/lazyload#55]
One of the visitors of my site reported a screenshot which clearly shows that all images which don't have "src" attribute don't display on Safari iPhone 6.

Has this been tested on all mobile devices?

**Comment by verlok** [comment]
Yes of course

**Comment by verlok** [comment]
Can you report HTML, CSS and JS code that you're using on your website? Maybe I can help you. But yes, LazyLoad it's used in production on many websites, I'm pretty sure it works on all devices

**Comment by anchev** [comment]
Unfortunately I can't report that because I removed lazyload from the site completely after finding out that it is necessary to use invalid HTML (img without src as reported in the other issue). Logically we can't expect any browser to be able to render invalid HTML long term although it may theoretically work, so I don't want to risk the sites I am working on to have content which users may not be able to see. I have tested at least 5 different lazy load solutions and all seem to use this trick to move the img url to another attribute but it doesn't seem correct. I hope you can find a better, browser-, seo- and valid-html- friendly solution.

**Comment by verlok** [comment]
Thanks for the suggestion @anchev, 
but putting the `src` and `srcset` in the `img` tag triggers the immediate download of the linked image. There's no way of lazily loading images that way.

**Comment by anchev** [comment]
You can probably use a placeholder gif pixel which will be replaced with the actual image. Or even better: a downsized version of the image - then search engines will be able to index it without duplicate content issues.

**Comment by verlok** [comment]
But @anchev, this is what you author should do. It's not up to the editor of the script to manage your HTML or downscale your images. 

You could do:

```html
<img src="/your/downscaled/image1.jpg" data-original="/your/image1.jpg" width="100" height="172">
<img src="/your/downscaled/image2.jpg" data-original="/your/image2.jpg" width="100" height="172">
<img src="/your/downscaled/image3.jpg" data-original="/your/image3.jpg" width="100" height="172">
```

...or simply use a placeholder on all your images...

```html
<img src="/your/placeholder.gif" data-original="/your/image1.jpg" width="100" height="172">
<img src="/your/placeholder.gif" data-original="/your/image2.jpg" width="100" height="172">
<img src="/your/placeholder.gif" data-original="/your/image3.jpg" width="100" height="172">
```

**Comment by anchev** [comment]
Sure. I just didn't see src in the demos so I thought it must not be there at all in order your script to work properly. But if it can be there, that's great.

**Comment by verlok** [comment]
Psst: have you already starred this repo? All you need to do is to press the Star ★ button on the top right corner of the website. ;)
