### ISSUE TITLE
<img> without src attribute is invalid HTML

### ISSUE THREAD

**Issue by anchev** [verlok/lazyload#56]
According to https://validator.w3.org

Perhaps the approach of removing the src and placing another attribute needs to be reconsidered.

**Comment by verlok** [comment]
Thanks for pointing it out @anchev, but putting the `src` and `srcset` in the `img` tag triggers the immediate download of the linked image. There's no way of lazily loading images that way.

**Comment by verlok** [comment]
Psst: have you already starred this repo? All you need to do is to press the Star ★ button on the top right corner of the website. ;)
