### ISSUE TITLE
LazyLoad for hidden elements

### ISSUE THREAD

**Issue by tcolonel** [verlok/lazyload#595]
Is it possible to load hidden element (display:none;)?

Thanks.

**Comment by verlok** [comment]
Not if you use display:none. 
See the demo about hidden elements in the demos folder.

**Comment by verlok** [comment]
Demo 

- Code https://github.com/verlok/vanilla-lazyload/blob/master/demos/image_hidden.html
- Live https://www.andreaverlicchi.eu/vanilla-lazyload/demos/image_hidden.html

**Comment by verlok** [comment]
Hey @tcolonel, 
I’m glad you solved!

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!
