### ISSUE TITLE
Support for background image on a div? 

### ISSUE THREAD

**Issue by justinchen** [verlok/lazyload#6]
Will you add support for background-image loading on a div?

**Comment by verlok** [comment]
Hello. It's not on schedule... but you can create a fork and then submit a pull request if you like... In that case we can think about taking it on board.

**Comment by herrbischoff** [comment]
Hey, sorry for necro-posting. Just wanted to add a possible way I hacked together just now. Behold, ugly CoffeeScript ahead:

```coffeescript
  myLazyLoad = new LazyLoad
    threshold: 500
    elements_selector: "div.item"
    throttle: 30
    data_src: "original"
    callback_set: (element) ->
      # Set the background image
      currentStyle = element.getAttribute "style"
      element.setAttribute "style", "background-image: url(" + element.getAttribute("src") + "); " + currentStyle
      # Clean up after ourselves
      element.removeAttribute "src"
      element.removeAttribute "data-original"
```

It's not exactly pretty but the most succinct and to-the-point solution I could come up with.

Remember, you will need to set the dimensions of the `div` elsewhere, for example with the always useful `padding-bottom: n%` (n = integer) technique.

**Comment by verlok** [comment]
Thank you for letting us know!

**Comment by herrbischoff** [comment]
Thank you for this script — and especially for making it Vanilla JS. jQuery is just so 2006... :sunglasses:

**Comment by verlok** [comment]
Now supported natively in [version 2.0.0](https://github.com/verlok/lazyload/releases/tag/v2.0.0)
