### ISSUE TITLE
Lazyloaded Picture tag doesn't work on IE.

### ISSUE THREAD

**Issue by SamuelBourdon** [verlok/lazyload#62]
Hi,

Because the picture tag isn't supported on IE 11, lazyloaded images always fallback to the default img. 

[This demo](http://verlok.github.io/lazyload/demos/with_picture.html) isn't working for me on IE11.

I am trying to make it work with picturefill.js but without success at the moment.

Is there a solution?

**Comment by verlok** [comment]
Hi @SamuelBourdon,
what you're trying to do is correct, since LazyLoad is not a polyfill, Picturefill must be used to have picture supported on IE. 
If you post some code you're using maybe I can help.

**Comment by SamuelBourdon** [comment]
Here is an example on codePen http://codepen.io/samuelbourdon/pen/rywLQW
It works for pictures loaded on page load but not for the lazyloaded ones.

I think I need to callback picturefill() before the image is loaded, callback_set seems to be the right solution but I do not know how to use it.

**Comment by dxit-gg** [comment]
I have the same problem and I would like to find a solution.
I use picture tags and I'm not sure how I can use polyfill and lazyload. Polyfill requires srcset but if I set lazyload with srcset the lazy loading doesn't work.

Thank you in advance.

**Comment by SamuelBourdon** [comment]
@dxit-gg 
I updated my pen with a nearly working example using callback_set method. It seems to be ok on IE on page load but image swap failed sometimes when resizing

`
            (function() {
                var lazyload = new LazyLoad({
                    callback_set: function () {
                        picturefill({ reevaluate: true });
                    }
                });
            }());
`

**Comment by verlok** [comment]
Sorry guys I've been very busy with my actual job and beyond that preparing the talk for CSS Day 2017. I look forward to be back starting next Monday.

**Comment by verlok** [comment]
> Maybe we just need another event on source change

The event on source change is the one that you're using, `callback_set`  

I'm closing this, if you need further help please reopen.

**Comment by verlok** [comment]
Psst: have you already starred this repo? All you need to do is to press the Star ★ button on the top right corner of the website. ;)
