### ISSUE TITLE
div with style=background

### ISSUE THREAD

**Issue by bigretromike** [verlok/lazyload#64]
I tried few times and had mixed results.
I read in some old issue that `div` is supported.

I'm using
```
<div class="square-base ratio col-center shadow-box zoom-box" style="background-image: url('img.jpg' }}');"></div>
```
Page is using bootstrap (version 3.3.7)
When adding your js in `head` and adding class to div, adding data-original with img.jpg and replacing backgroud-image to blank.gif I end up with all divs being white and there is no request to server for img.jpg

Am I'm missing something ?

I checked if its something with not loading your js, but its not as when im using `<img>` it works fine

**Comment by bigretromike** [comment]
OK first. 
I needed to move script to bottom.
Second when I added 
```
<script>
    (function() {
        new LazyLoad({
            elements_selector: ".lazy"
        });
    }());
</script>
```
And changed class to 'lazy' it started to working;
Kudos for js !

**Comment by verlok** [comment]
Kudos for self solving this! 
Yes the script needs to be at the bottom OR to be executed ad DOM ready, because otherwise it won't find anything in your DOM when searching for it. 
This is also a best practice for performance optimization, so keep it that way!

**Comment by verlok** [comment]
Psst: have you already starred this repo? All you need to do is to press the Star ★ button on the top right corner of the website. ;)

**Comment by bigretromike** [comment]
hahaha. So you type that on each issue. I did star it - thanks for nagging

**Comment by verlok** [comment]
More or less. Only on the solved ones ;)
