### ISSUE TITLE
Not work with require js config.

### ISSUE THREAD

**Issue by pranaysonisoft** [verlok/lazyload#65]
```js
require.config({
        'backbone' : 'lib/backbone-1.1.2.min',
        'lazyload':'lib/plugin/lazyload/lazyload.min'
});

define([
  'backbone',
  'lazyload',
], function(Backbone, LazyLoad) {
  // not working
});


define([
  'backbone',
  'lib/plugin/lazyload/lazyload.min'
], function(Backbone, LazyLoad) {
   var myLazyLoad = new LazyLoad();
 // working fine
});
```

i don't understand why require config not work with lazyload.min.js
my other plugin is work require config.

**Comment by verlok** [comment]
Hi there,
what you're doing now is correct, you could have multiple instances of lazyload in the page so you gotta define each one with `new LazyLoad()` and eventually pass some options in or assign it to a local variable.

**Comment by G100g** [comment]
Hi @pranaysonisoft ,
 did you try using paths config option to setup lazyload

```js
require.config({
    paths: {
        'backbone' : 'lib/backbone-1.1.2.min',
        'lazyload':'lib/plugin/lazyload/lazyload.min'
   }
});

```

I created a working codepen as example
https://codepen.io/G100g/pen/gmowqd

**Comment by pranaysonisoft** [comment]
thank you from replay  @verlok 
thank you @G100g . thank you for codepen example . my problem is solve.

**Comment by pranaysonisoft** [comment]
thank you for replying me @verlok 
thank you @G100g . thank you for codepen example . my problem is solve.
