### ISSUE TITLE
Cached images onLoad callback

### ISSUE THREAD

**Issue by lucavolta** [verlok/lazyload#66]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The script doesn't trigger the callback function when loading cached images.

**If the current behavior is a bug, please provide the steps to reproduce**
If you load this page at https://www.balenciaga.com/gb/women/collections/lookbook-resort-17_section with Safari, you can see images without the "loaded" class, even if that image is actually loaded.
This happens because the onLoad callback isn't triggered.

**Comment by verlok** [comment]
Loaded class on loaded images sounds correct. Did you mean "loading class"?

**Comment by verlok** [comment]
@lucavolta plus, the link you provided it's a "500 - Internal server error - There is a problem with the resource you are looking for and it cannot be displayed." can you provide another?

**Comment by verlok** [comment]
I've been trying with https://www.balenciaga.com/gb/women/handbags but I found a strange behaviour: initially we have the .loaded class only on 7 images, even if all images are downloaded at page landing time - scrolling down, no further network requests are done, but the `loaded` class is applied.

**Comment by verlok** [comment]
Also, I tried with Safari on the [demos](http://verlok.github.io/lazyload/#user-content-demos), for example [here](http://verlok.github.io/lazyload/demos/simple.html), and I get the loaded class also when the image is loaded from the cache.

**Comment by lucavolta** [comment]
@verlok there was a typo in the initial lookbook url, this is the correct one
https://www.balenciaga.com/gb/women/collections/lookbook-resort-17_section

**Comment by verlok** [comment]
I've created a specific demo where you can see that all the callbacks are working correctly. [See it in action](http://localhost:8000/demos/callbacks.html) || [view source](https://github.com/verlok/lazyload/blob/master/demos/callbacks.html). 

I tried that on Safari 10.0.3 on Mac and everything is working, let me know if it works for you too.
