### ISSUE TITLE
Support for Horizontal Scrolls?

### ISSUE THREAD

**Issue by mendelk** [verlok/lazyload#7]
It appears that the scroll event is only triggered for a vertical scroll.

Any way to get it to work for horizontal scroll areas?

**Comment by verlok** [comment]
The script listens to a generic scroll event on scrollable areas, both horizontal and vertical scroll should be covered. Can you share the code on gist or codepen / jsbin?

**Comment by mendelk** [comment]
Thanks for responding @verlok 

Here's an example: http://codepen.io/mendel/pen/wamYyO

At least when I test, it stops loading images after the first couple.

Thanks!

**Comment by verlok** [comment]
It's an error on your side. You just didn't specify the container of the scroll. 

You can fix it like that:
```javascript
var myLazyLoad = new LazyLoad({
    data_src: 'src',
    container: document.getElementById('container')
});
```

See the [fork of your example, fixed](http://codepen.io/verlok/pen/waExWX).

Cheers!
