### ISSUE TITLE
I've got a slick slider which fails to load images when it's their turn in the carousel, only on scroll 1px

### ISSUE THREAD

**Issue by lopugit** [verlok/lazyload#71]
You can see the slider at www.myleisure.com.au

But the issue is that you have to scroll just 1px to get the images to load when the slider reaches that image in it's carousel order.

I've tried a few things like

        var myLazyLoad = new LazyLoad({
		callback_processed: function(){
			$(window).trigger('scroll');
		},
		container: document.getElementById('slick-slider')
	});

**Comment by verlok** [comment]
Two things:
0) which version of my script are you using?
1) why don't you use slick's native lazy load feature?

**Comment by lopugit** [comment]
I did not know it had one :') 

Is it the lazyLoad: 'ondemand' or 'progressive' option they feature? I thought that was a tie in to your script. I'm using 5.1.1 of your script :) 

Thanks for the reply, you're a beautiful dev <3

**Comment by verlok** [comment]
About slick lazy, see the demos here
http://kenwheeler.github.io/slick/

**Comment by verlok** [comment]
If you have the "only shows images when scrolling 1px" problem on other images, please let me know. 
The script is now under automated test and I know that the `update` function is called upon initialization, but maybe there's something else that goes wrong.

**Comment by verlok** [comment]
PS: you might find other scripts that do the same, obviously. Mine is a lightweight and very fast one, continuously evolving along with browsers technologies, but you're free to choose something else. After all, this is github (and te web).
