### ISSUE TITLE
Support IntersectionObserver

### ISSUE THREAD

**Issue by verlok** [verlok/lazyload#72]
Note to self, try playing around with IntersectionObserver, even if browser support is not quite [there]( http://caniuse.com/#feat=intersectionobserver). 

/cc @ricardobrandao @si14 re: #53 and comments on #36

**Comment by verlok** [comment]
Re: #53 and #36

**Comment by verlok** [comment]
Hey @ricardobrandao and @si14!

I've just opened a [new feature branch supporting IntersectionObserver](https://github.com/verlok/lazyload/tree/feature/intersectionObserverSupport).
And it works! 👍 

The only thing that I can't figure out for now is how to manage the fallback for browsers where IntersectionObserver is not supported. I didn't want to include the whole IntersectionObserver polyfill, because it's huge!

At the moment, if the new `observer_fallback` option is set to `1` (default value), LazyLoad loads all the images at once. But I realize it's not a best practice...

Maybe I should code a fallback based on the current version of LazyLoad (listen to scroll and check if the elements are inside the viewport). But it's a shame, because trimming all that code out made the script weigh 1.5kb less (from 5 to 3.5).

Any advice?

/cc @G100g :)

**Comment by verlok** [comment]
As a reference: https://github.com/GoogleChrome/sample-media-pwa/blob/master/src/client/scripts/helpers/lazy-load-images.js

**Comment by G100g** [comment]
Split legacy code and load only if necessary could be a solution
But mean a complicated setup by the user.

This will left the weight low.

We hope to see soon the 

```html
<script type="module">
```

In all browsers

**Comment by verlok** [comment]
Done

**Comment by ricardobrandao** [comment]
@verlok sorry for the late reply but I was abroad on vacations (actually I've visited your country for the first time :)). Thanks for supporting IntersectionObserver!! I'll take a look to what you've done.

**Comment by verlok** [comment]
Cool, I hope you enjoyed Italy!

I just wrote a blog post about the work I've done, find it [here](http://www.andreaverlicchi.eu/using-intersection-observers-to-create-vanilla-lazyload/), and you're mentioned with a link!

Share it on Twitter / whatever if you like ;)

**Comment by ricardobrandao** [comment]
It was awesome, thanks :)

Nice article, I've shared it on twitter.

**Comment by verlok** [comment]
<3

**Comment by si14** [comment]
@verlok it's the latest reply ever, but I missed the ping in the torrent of github notifications years ago and didn't say thank you. I really want to fix the mistake, so: thanks a lot :)

**Comment by verlok** [comment]
Hey @si14, 
Thank you for the closure! :)

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!

**Comment by si14** [comment]
Haha fair enough! Enjoy your coffee ;)
