### ISSUE TITLE
Transpiled version returns an error

### ISSUE THREAD

**Issue by verlok** [verlok/lazyload#73]
Hi @ricardobrandao,
can you help me understand why the transpiled version returns an error and the non-transpiled version doesn't?
See the code under the `development` branch.

**Comment by verlok** [comment]
[Here we might find the answer](http://stackoverflow.com/questions/34973442/how-to-stop-babel-from-transpiling-this-to-undefined) (I'm pretty sure we will)

**Comment by verlok** [comment]
Solved

**Comment by ricardobrandao** [comment]
Sorry for the late reply but yesterday I had a busy day. Glad you've figured it out. I remember [fixing this earlier](https://github.com/verlok/lazyload/pull/45/files#diff-6cac1e8e285dab83b1bdb05d82488d35R330) but we've lost it in the meantime.
