### ISSUE TITLE
Seo friendly?

### ISSUE THREAD

**Issue by MDSilviu** [verlok/lazyload#74]
Is this plugin seo friendly? 
Did anyone check if the lazy loaded images get indexed by google?

**Comment by verlok** [comment]
Hi @MDSilvu,
since Google executes JavaScript, the images should be indexed by Google correctly.
We use it production on many of our websites nowadays. 
Anyway I have a small change in my backlog that will make SEO even better. Stay tuned ;)

**Comment by verlok** [comment]
@MDSilviu version 6.1.0 is out, and it's 100% SEO friendly :)
