### ISSUE TITLE
Srcset for background image.

### ISSUE THREAD

**Issue by MDSilviu** [verlok/lazyload#77]
Would be great if the srcset option could be extended to background images.
Depending on the screen size there isn't always the need to get the full image and serving a smaller image for the background would help.

**Comment by verlok** [comment]
Browsers don't have the technology to understand a srcset in a background image... yet. 
There's a working draft named [image-set](https://drafts.csswg.org/css-images-3/#image-set-notation) but it's currently just a draft.

**Comment by MDSilviu** [comment]
I was referring at a feature that will allow a similar functionality, for example setting multiple images (srcset like) and depending on screen size (width or height) lazy loading the one that fits the best.

**Comment by verlok** [comment]
That wouldn't be a lazy load, but a totally different thing. My script has only the purpose to load images (or iframes) as they enter the viewport. Maybe you should look for something else.
