### ISSUE TITLE
Chrome Double Downloading Image resources. 

### ISSUE THREAD

**Issue by hagcin** [verlok/lazyload#8]
When comparing the network tab in chrome(v44)  vs firefox (v3.9), when using this the late load script, I notice chrome almost double downloads each resource.  29 requests in firefox becomes, 56 requests in chrome...

**Comment by verlok** [comment]
Hi @hagcin,
sometimes the Chrome inspector shows a double download if the cache is not disabled. Have you disabled Chrome's cache from its inspector first?
Otherwise, can you post a jsfiddle, jsbin, codepen example of what you are doing, so I can take a look at it?
Thank you

**Comment by verlok** [comment]
No reply.

**Comment by williambout** [comment]
Same issue. Happening only in Chrome with cache disabled.

**Comment by verlok** [comment]
Thank you, @williambout.
Can you post a jsfiddle, jsbin, codepen example of what you are doing, so I can take a look at it?
Thank you

**Comment by williambout** [comment]
After some tests, I find out the problem disappear on pre-production server, but persist on local server.

**Comment by verlok** [comment]
Good. So it's not a problem of the script I guess. Could you figure out why?

**Comment by williambout** [comment]
I think it's a bug in Chrome since I had no issue in Safari/Firefox.
It could be related to srcset : https://code.google.com/p/chromium/issues/detail?id=526630
