### ISSUE TITLE
Is it possible to Execute a Command  When An Element becomes visible

### ISSUE THREAD

**Issue by Niresh12495** [verlok/lazyload#86]
This might be a feature request.
may be a stupid question 

Is it possible to execute a command when an element becomes visible
`<div id="test1">`
`</div>`
`<script>
if (test1 visible) {
run_a_command;
}
</script>
`
This is not about call back functions, because they execute in batch for all elements detected this is about specific element.
Im asking this question because i would like to execute separate javascript function to different elements as they become visible. 

Thank you.

**Comment by Niresh12495** [comment]
Any how i found out a method in which i could execute it, im closing this myself .

**Comment by verlok** [comment]
The answer is to use a callback, the callback_processed callback, which passes the element as an argument
