### ISSUE TITLE
Code for sizes without srcset is W3C-invalid

### ISSUE THREAD

**Issue by fspeckmaier** [verlok/lazyload#89]
If you are validating the following code, as shown in your docs,

`<img data-original="/your/image1.jpg"
    data-original-set="/your/image1.jpg 200w, /your/image1@2x.jpg 400w"
    sizes="(min-width: 20em) 35vw, 100vw">`

the W3C-Validation fails, because if you are using the `sizes`-attributes you have to provide also a `srcset` attribute to be valid.

So, one possible fix would be to prefix the sizes attribute also with `data-` because then the validation would only see a normal `<img`>`with some data-attributes.

**Comment by verlok** [comment]
Isn't the `img` invalid also because it lacks of the `src` attribute?

**Comment by fspeckmaier** [comment]
Well yes. I supplied a src anyway as a fallback using a base64 transparent
png ... So when the lazyload script runs, it replaces it with the correct
src. So for the validator it would be just a normal `img`.

... But maybe this a bit to specific or more kind of an edge case, because
I need to have the site completely valid.

2017-04-28 15:07 GMT+02:00 Andrea Verlicchi <notifications@github.com>:

**Comment by verlok** [comment]
@fspeckmaier can you report where you took the information from? I coudn't find it online.

[Here](https://developer.mozilla.org/it/docs/Web/HTML/Element/img) the MDN states the following:

> The selected source size affects the intrinsic size of the image (the image’s display size if no CSS styling is applied). If the srcset attribute is absent, or contains no values with a width (w) descriptor, then the sizes attribute has no effect.

So I guessed we could leave the `sizes` in the HTML and when the `srcset` is not present, it is just ignored.

**Comment by verlok** [comment]
I also looked in the entirety of the [W3C document](http://w3c.github.io/html/semantics-embedded-content.html#element-attrdef-img-srcset), but I didn't find anything about what you reported.

**Comment by Tabrisrp** [comment]
Hi,

In fact the W3C validator will trigger a warning `The sizes attribute may be specified only if the srcset attribute is also present.` if sizes is set but srcset is not.

I think ideally, we could set a `data-lazy-sizes` attributes, that would be used to set `sizes` when the image loading is triggered by the script.

That would not change any behaviour of the script, but would prevent the validator warning.

**Comment by Tabrisrp** [comment]
@verlok do you think what I stated in my previous comment could be implemented?

**Comment by verlok** [comment]
It could be, but I think that the HTML should be validated against the W3C in its final state, meaning after JavaScript manipulated it, instead of before. What is the purpose of analyzing HTML code that won’t be used as is it?

**Comment by verlok** [comment]
Because of course implementing it in the script would mean less speed in downloading, parsing and executing it. So every modification should be evaluated carfully.

**Comment by Tabrisrp** [comment]
While I agree with the idea and understand the impact, when you pass an URL to the w3c validator, it's not the final state that is tested, but the initial one, thus returning the error related to sizes and srcset.

Customers don't know about the difference between initial and final states when testing for the validation.

**Comment by verlok** [comment]
Customers will break the internet! 🙃.

I see your point of view. I will implement this it as soon as I’ll be back from my annual leave, which means not before mid July. 

If you feel like collaborating, you could fork my repo, code the change, then open a pull request. This is open source, after all. 

Thanks.

**Comment by verlok** [comment]
All this to fix a W3C validator **warning**? :-/

**Comment by verlok** [comment]
OK, now it's an **error**. Will fix.

**Comment by verlok** [comment]
Versions 10.9.0 and 8.10.0 added the ability to lazily set the `sizes` attribute via a `data-sizes` attribute. See the [README](README.md) file for more information.

**Comment by SunilT420** [comment]
Error: The sizes attribute may be specified only if the srcset attribute is also present.  Help me ....?

**Comment by verlok** [comment]
See #342
