### ISSUE TITLE
Check for Bootstrap 3 Modal is within viewport

### ISSUE THREAD

**Issue by vuongdothanhhuy** [verlok/lazyload#9]
Hello,

LazyLoad script seems to always return `true` when checking for Bootstrap 3 Modal dialog is within viewport or not. This leads to images within modals are always lazyloaded immediatedly after page load.

The expected behaviour is to lazyload image only when the modal display (i.e is within viewport, visually).

Here is a little jsfiddle to play with: https://jsfiddle.net/ac1d9oq2/embedded/result/

I think the checking function might need a bit more work to check for modal visual within viewport, I suppose?

Thanks.

**Comment by verloox** [comment]
Hi @vuongdothanhhuy and thanks for reporting this issue.
I took a look at your example, what is the code that you are executing when clicking the "Check" red button?
Can I see how you are instancing lazyload? Did you instance it passing the modal scrolling container in the "container" option?

**Comment by verlok** [comment]
Hi @vuongdothanhhuy and thanks for reporting this issue.
I took a look at your example, what is the code that you are executing when clicking the "Check" red button?
Can I see how you are instancing lazyload? Did you instance it passing the modal scrolling container in the "container" option?

**Comment by verlok** [comment]
No reply.
