### ISSUE TITLE
Image loading bug

### ISSUE THREAD

**Issue by Niresh12495** [verlok/lazyload#90]
This is a bug report recently switched to 7.2.2 from 6.3.2
Lazyload not rewriting URL for one image
[Dangerous Animals](https://www.guest.blog/9267/top-10-dangerous-killer-animals/)

`<img id="site-logo" ` Look for this line in the source, `data-was-processed="true"` but not writing `lazysrc` to `src` lazyload_vlock.js contain configuration

Strange issues Im getting `data-was-processed="true"` in every element why ?

**Comment by Niresh12495** [comment]
After digging around i found out what is the issue
`clas="animated fadeIn imageloading"` These are the classes assigned to the image listed above
`class_loading: 'imageloading',` This is the class loading, it is not being unset
i have added a style
`<style>. imageloading  {visibility: hidden}</style>`
 to hide images until fully loaded

**Comment by Niresh12495** [comment]
Update, Some images are loading in some instances but some times not even loading
Everything cleared browser cache, cloudflare cache, wordpress cache everything

**Comment by verlok** [comment]
Hi @Niresh12495,
can you report the Javascript and HTML code you're using?
Otherwise it's very hard for me to help you.

**Comment by Niresh12495** [comment]
This is the HTML after loading the page
`class_loading: 'imageloading',` is not being removed
Try to view few pages of this website to check the issue yourself
https://www.guest.blog/5671/10-inspirational-robin-williams-quotes/


```
<div class="container initial" data-was-processed="true">
					<div id="site-branding" class="site-branding initial" data-was-processed="true">
	<h2 id="site-title" class="logo img-logo">
	<a href="https://www.guest.blog/" itemprop="url" rel="home" class="initial" data-was-processed="true">
					<img id="site-logo" data-lazysrc="https://cdn.guest.blog/wp-content/uploads/2017/02/guest-blog-logo.png" alt="Guest Blog" data-bsrjs="https://cdn.guest.blog/wp-content/uploads/2017/02/guest-blog-logo@2x.png" class="animated fadeIn imageloading" src="https://cdn.guest.blog/wp-content/uploads/2017/02/guest-blog-logo.png" data-was-processed="true">
				</a>
</h2>
</div><!-- .site-branding -->
				</div>
```



This is the option im using


  ```
 var myLazyLoad = new LazyLoad({
        throttle: 0,
        threshold: '0',
        //threshold: lazyloadviewportheight,
        data_src: 'lazysrc',
        data_srcset: 'lazyset',
        class_initial: 'animated',
        class_loading: 'imageloading',
        class_loaded: 'fadeIn',
        //callback_load: removeclasslazyloading(),
        skip_invisible: false
    });

    var myLazyLoadx = new LazyLoad({
        skip_invisible: false,
        throttle: 0,
        threshold: lazyloadviewportheight,
        data_src: 'lazybackground',
        //  class_loading: 'lazyloading',
        //  callback_load: removeclasslazyloading(),
        elements_selector: "a"
    });

    var myLazyLoady = new LazyLoad({
        skip_invisible: false,
        throttle: 0,
        threshold: lazyloadviewportheight,
        data_src: 'lazybackground',
        //  class_loading: 'lazyloading',
        //  callback_load: removeclasslazyloading(),
        elements_selector: "div"
    });
```

i tried combining div and a tag into single  `elements_selector: "a div"` it doesn't work that way, this is another bug in lazyload

**Comment by verlok** [comment]
Oh, I can see the problem now. 
In Javascript, there aren't "loaded" events fired wen setting background images. Therefore, LazyLoad can't neither call the `callback_load` nor remove the `loading` class.
Since you're using background images instead of regular images, there's no way to fix this. I'd suggest to use the good old `img` tag instead.
Please note that this has always been like that, it's not a regression bug, it's simply a Javascript limitation.

**Comment by Niresh12495** [comment]
`<img id="site-logo" data-lazysrc="https://cdn.guest.blog/wp-content/uploads/2017/02/guest-blog-logo.png" alt="Guest Blog" data-bsrjs="https://cdn.guest.blog/wp-content/uploads/2017/02/guest-blog-logo@2x.png" class="animated fadeIn imageloading" src="https://cdn.guest.blog/wp-content/uploads/2017/02/guest-blog-logo.png" data-was-processed="true">`

Does it looks like background image? my header logo is having problem and it worked perfectly with 6.3.2

**Comment by Niresh12495** [comment]
This the exact problem im having just view the video
https://www.youtube.com/watch?v=PsoYIJm6Z9I

**Comment by StefansArya** [comment]
Actually I also have this issue a few hours ago and found that "there's no way to fix this"?

So I came up to share the solution with jQuery:

```
var lazyload = new LazyLoad({
	elements_selector: ".lazy"
});
lazyload2('.lazy');

function lazyload2(selector){
	$(selector).each(function(){
		var ref = $(this);
		var src = ref.attr('data-src');
		if(!src) return;
		ref.addClass('loading');

		$('<img/>').attr('src', src).on('load', function(){
			$(this).remove();
			ref.removeClass('loading');
			ref.addClass('loaded');
		});
	});
}
```
