### ISSUE TITLE
Ignore rewriting 

### ISSUE THREAD

**Issue by Niresh12495** [verlok/lazyload#91]
Feature Request
Ignore rewriting data-src to src, if data-srcset exist

Here i have modified your `lazyload.setSources.js`
It will check if browser support srcset first, if yes it will rewrite data-srcset to srcset else it will process data-src

I don't want this to be included into main source, just asking if possible add as an Option in API `data_skipsrc`

```
export default function(element, srcsetDataAttribute, srcDataAttribute) {
    const tagName = element.tagName;
    const elementSrc = element.dataset[srcDataAttribute];
    if (tagName === "IMG") {
        setSourcesForPicture(element, srcsetDataAttribute);
        const imgSrcset = element.dataset[srcsetDataAttribute];


var srcimagetest = document.createElement('img');
var isSRCSETSupported = ('srcset' in srcimagetest);
if (isSRCSETSupported && imgSrcset) {
element.setAttribute("srcset", imgSrcset); 
}  else {
if (elementSrc) { element.setAttribute("src", elementSrc); }
}


        return;
    }
};
```

**Comment by verlok** [comment]
It's OK to me to include it in the main code, but I fail to see why. 
If `srcset` is not supported, why care if it goes in the `img`'s `srcset` attribute?

**Comment by Niresh12495** [comment]
In some instances browser will ignore and load `src` instead of `srcset`,
but when `src` is not defined `srcset` will be forced to load.

Here are some related issues
http://stackoverflow.com/questions/29715791/browser-is-loading-two-images-one-for-srcset-one-for-src-chrome-41-et-al

**Comment by Niresh12495** [comment]
So did you made any decision ?

**Comment by verlok** [comment]
The script does the right thing setting the `srcset` before the `src` so if `srcset` is not supported it will be ignored, whereas where it's supported it will be considered. 
The browser bugs you mentioned are browser bugs, related to a very old version of Chrome and to a polyfill. They are not my script bugs.
So I won't change anything.
