### ISSUE TITLE
 lazyload call back functions not working properly after switching to element.dataset

### ISSUE THREAD

**Issue by Niresh12495** [verlok/lazyload#93]
Bug report, 
This issue is related to
https://github.com/verlok/lazyload/issues/90

I have tested 7.1.0 version of verlok lazyload it is working perfectly but now
7.2.0 == 7.2.1 && 7.2.2 the issue exist in these versions

with element.getAttribute it was working good but now with element.dataset causing the issue check out the video listed below
https://www.youtube.com/watch?v=PsoYIJm6Z9I

```
var myLazyLoad = new LazyLoad({
      throttle: 0,
      threshold: '0',
      //threshold: lazyloadviewportheight,
      data_src: 'lazysrc',
      data_srcset: 'lazyset',
      class_initial: 'animated',
      class_loading: 'imageloading',
      class_loaded: 'fadeIn',
      //callback_load: removeclasslazyloading(),
      skip_invisible: false
  });
```

the following CSS hides image until it fully loads, previous versions of lazyload successfully removed `imageloading` class but after switching to `element.dataset` those functions are not working correctly

`.imageloading {visibility: hidden}`

**Comment by verlok** [comment]
Thanks for the video, but in order to understand what's happening I need to see your HTML, JS and CSS code. 
Can you provide it in a Codepen or a Codepen project?
Otherwise I can't help you.

**Comment by Niresh12495** [comment]
What about a live site
https://www.guest.blog
https://www.guest.blog/8314/101-relationship-tips/

This is the JS code being used, HTML
```
var lazyloadviewportheight = Math.max(document.documentElement.clientHeight, window.innerHeight || 0);
    var myLazyLoad = new LazyLoad({
        throttle: '0',
        threshold: '0',
        //threshold: lazyloadviewportheight,
        data_src: 'lazysrc',
        data_srcset: 'lazyset',
        class_initial: 'animated',
        class_loading: 'imageloading',
        class_loaded: 'fadeIn',
        skip_invisible: false,
callback_set: function (el) {
//console.log(el.currentSrc);
}
    });
```


HTML is normal
Here is an example 
Example 1: Data SRC issue

`<img id="site-logo" data-lazysrc="https://cdn.guest.blog/wp-content/uploads/2017/02/guest-blog-logo.png" alt="Guest Blog" data-bsrjs="https://cdn.guest.blog/wp-content/uploads/2017/02/guest-blog-logo@2x.png" class="animated fadeIn imageloading" src="https://cdn.guest.blog/wp-content/uploads/2017/02/guest-blog-logo.png" data-was-processed="true">`

This html is processed but image class `imageloading` is not remove 

because of the CSS `.imageloading {visibility: hidden}` image is hidden


Example 2: Background Image issue
In another instance for background image, they are not being added into style

`<a alt="Dangerous Animals" title="Top 10 Most Dangerous Killer Animals In The World" data-lazybackground="https://cdn.guest.blog/wp-content/uploads/2017/04/Dangerous-Animals-750x430.jpg" style="" class="img-cont initial" href="https://www.guest.blog/9267/top-10-dangerous-killer-animals/" data-was-processed="true"></a>`

This is the JS being used for background images

```
  var myLazyLoadx = new LazyLoad({
        skip_invisible: false,
        throttle: '0',
        threshold: lazyloadviewportheight,
        data_src: 'lazybackground',
        //  class_loading: 'lazyloading',
        //  callback_load: removeclasslazyloading(),
        elements_selector: "a"
    });
```

**Comment by verlok** [comment]
Hi @Niresh12495,
I'd be very happy to solve this issue, if I only could replicate it. It would be very use you could replicate the problem in an _isolated environment_ such as [Codepen](https://www.codepen.io). 

I did some tests, using v7.2.2 and it all worked fine. See the following:

* Background images lazy loading --> https://codepen.io/verlok/pen/NjMgBX
* Regular Images lazy loading --> https://codepen.io/verlok/pen/qmYjgd

You can fork my pens to reproduce your errors if you want.

**Comment by Niresh12495** [comment]
I cant replicate it 
i just dont understand why cant you just check the website link i have given above?

**Comment by verlok** [comment]
Because in the links you provided all seems to be working...

**Comment by verlok** [comment]
...and if you can't replicate it in an isolated environment, it's not a LazyLoad bug.

**Comment by Niresh12495** [comment]
Ok im sorry, I'm little hot tempered
as you said safari webkit `element.getAttribute` is not playing good
but you have to consider this because most of the users have iPhone and all iPhone browsers are using safari webkit [iPhone, iPad, iPod & Macs]

**Comment by verlok** [comment]
`getAttribute` was used in the old version of LazyLoad. The newer uses `dataset`, which is widely supported in every current browser version and previous version too. [Check here](http://caniuse.com/#feat=dataset).

I tested my previous pens on Safari on MacOS Sierra and everything is working perfectly.

**Comment by verlok** [comment]
Psst: have you already starred this repo? All you need to do is to press the Star ★ button on the top right corner of the website. ;)
