### ISSUE TITLE
Fade in effect

### ISSUE THREAD

**Issue by briwg** [verlok/lazyload#94]
Would it be possible to add a fade in effect and make it available via the api? The Tuupola plug-in uses:

effect : "fadeIn"

Alternatively is there a way of achieving this via the current api?

**Comment by verlok** [comment]
Yes. There is a demo and a recipe. Just read the readme file or the website. You can find the demo under the demos folder.

**Comment by verlok** [comment]
Sorry I just realized there's no recipe and no link to the demos folder in the README file. 
Here you go: https://github.com/verlok/lazyload/blob/master/demos/fade_in.html

The fade in here is delegated to CSS so it's much faster than a JS animation (which is what Mika's jQuery LazyLoad does). 

You could change the fade-in to anything else just changing the CSS. :)

**Comment by briwg** [comment]
Great! Works well. Many thanks.

**Comment by verlok** [comment]
You're welcome 😊

**Comment by perfilev** [comment]
Is it possible to fade background image in?

**Comment by verlok** [comment]
Psst: have you already starred this repo? All you need to do is to press the Star ★ button on the top right corner of the website. ;)

**Comment by cfxd** [comment]
Just for the heck of it I created a pen out of the fade in demo: https://codepen.io/cfxd/pen/Germma

**Comment by Jonatan-r** [comment]
Hi! Thx for a nice lazy load plugin!
Is it possible though to somehow prevent the images already lazy loaded from fading in once again, once shown once again on another page? fx the logo, I'd like it to fade it once initially loaded upon visiting the site the first time, but once it's cached I don't want it to fade in on a new page that the user clicks on 😃
