### ISSUE TITLE
Two issues

### ISSUE THREAD

**Issue by Niresh12495** [verlok/lazyload#96]
Why lazyload is not working
https://codepen.io/Niresh12495/pen/jmxgeo

How can i .update() .destroy() multiple events in the following example

```
<script>
window.lazyLoadOptions = [{
    /* your instance 1 options */
}, {
    /* your instance 2 options */
}];
</script>
```

**Comment by verlok** [comment]
Because in the way you did it, codepen injects the LazyLoad script before you declare the options for it. The correct way to do it on codepen is this: https://codepen.io/verlok/pen/GmGgJE

**Comment by verlok** [comment]
It's complex to use it async and with multiple instances. You need to save the instances as they are created using the event listener of the event `LazyLoad::Initialized`. Each time the event is fired, it passes an instance of LazyLoad in its callback (`e.detail.instance` in the codepen example). You then need to distinguish between the instances and know when to use which.

For a simpler use case, I'd suggest using the synchronous multiple instances creation, like in the demo here https://github.com/verlok/lazyload/blob/master/demos/multiple_container.html

**Comment by verlok** [comment]
Psst: have you already starred this repo? All you need to do is to press the Star ★ button on the top right corner of the website. ;)
