### ISSUE TITLE
ie10, ie9 not work. error message "Unable to get the 'wasProcessed' property, which is not defined or a null reference."

### ISSUE THREAD

**Issue by nina514** [verlok/lazyload#98]
Report a bug.

I am using version 7.2.2.

Ie10, ie9, an error stating that there was no wasProcessed value.
You have selected a div element.

This is an error because the dataset is not initialized and there is no logic to check for members.

Please fix.

This is my modified code.

```
_purgeElements: function _purgeElements () {
            Var elements = this._elements,
                ElementsLength = elements.length;
            Var i = void 0,
                ElementsToPurge = [];

            For (i = 0; i <elementsLength; i ++) {
                Var element = elements [i];
                if(typeof element.dataset == 'undefined') {
                    element.dataset = {}; // init object
                }
                
                / * If the element has already been processed, skip it * /
                If (element.dataset.hasOwnProperty ('wasProcessed') && element.dataset.wasProcessed) {
                    ElementsToPurge.push (i);
                }
            }
            / * Removing elements to purge from this._elements. * /
            While (elementsToPurge.length> 0) {
                Elements.splice (elementsToPurge.pop (), 1);
            }
        },
```

**Comment by verlok** [comment]
Thanks for letting me know. 
IE less then 11 are not supported, though. 
Does this fix only make the script compatible for IE9? I didn't know that.

**Comment by nina514** [comment]
The features I want work fine.
There's nothing wrong with delay loading the div.
Let's test it to see if it works with other features.

Thanks for making a good plugin.

**Comment by davthu** [comment]
> IE less then 11 are not supported, though.

I can't see that browser support is mentioned anywhere in the documentation.

**Comment by verlok** [comment]
Psst: have you already starred this repo? All you need to do is to press the Star ★ button on the top right corner of the website. ;)
