### ISSUE TITLE
How can we improve Lazyload with DIV tag?

### ISSUE THREAD

**Issue by reportingforduty** [verlok/lazyload#99]
* **What is happening?**
When I open a hidden DIV(triggered by showme() js), lazyload didn't load any images until I scroll down a bit.
Also, when I can't scroll down(didn't open anything except one DIV block = everything in 1 screen), lazyload couldn't load these images.
So, **how can I trigger Lazyload to load the image when the user open DIV block**?
(all images are inside `<div> ~ </div>`.)

* **What is the expected behaviour?**
When the DIV is opened, and the img tags are visible onscreen, load the image without scrolling.

* **Which version of LazyLoad are you using?**
Latest (downloaded from here)

* **In which browser(s) and browser version(s) are you experiencing the problem?**
Firefox latest

* **Could you provide the HTML, CSS and JS code you use for your images?**

Something like this:

```
showme() --- change ID style.display to 'block'.
<a onclick="showme('01');">+</a><div id="contents01" style="display:none">......</div>
<a onclick="showme('02');">+</a><div id="contents02" style="display:none">......</div>
<a onclick="showme('03');">+</a><div id="contents03" style="display:none">......</div>
<a onclick="showme('04');">+</a><div id="contents04" style="display:none">......</div>
......
<a onclick="showme('57');">+</a><div id="contents57" style="display:none">......</div>
<script src="lazyload-git.js"></script><script>new LazyLoad();</script></html>
```

```
div example
<div ...>
<img data-original="medium-size-image-01.jpg">
<img data-original="medium-size-image-02.jpg">
</div>
```

**Comment by reportingforduty** [comment]
YEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSS! I figured it out!
Please include this to your toppage so other people can understand it!!
`
<a onclick="showme('57');lazyman.update();">+</a>`

`<script src="lazyload-git.js"></script><script>lazyman=new LazyLoad();</script></html>`

Calling .update() after DIV open FIXED THIS!

**Comment by verlok** [comment]
Sorry about the delay. 
Yes, the solution you found is correct!
The update method is meant to be used right for that purpose.

**Comment by verlok** [comment]
Psst: have you already starred this repo? All you need to do is to press the Star ★ button on the top right corner of the website. ;)
